### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by FilipQL** [UniSharp/laravel-filemanager#100]
Hi,

After following the instructions for installation, when I try to open **localhost/laravel-filemanager** in browser, I get three 404 errors:

![file manager - mozilla firefox 2016-08-01 18 06 57](https://cloud.githubusercontent.com/assets/18264428/17300550/32f9d49c-5813-11e6-89c4-50ab3366d262.png)

BUT, when I copy the entire contents of **vendor/unisharp/laravel-filemanager/src/routes.php** to my **routes.php** (located in app/Http/routes.php) - everything is working fine, there are no errors. 

My question is - do we need to do this in order to make the _fliemanager_ working, or maybe I am missing something?

**Comment by g0110280** [comment]
LaravelFilemanagerServiceProvider.php will load the route of this package.
Maybe this [doc](https://github.com/UniSharp/laravel-filemanager/blob/master/doc/installation.md) can help you?

**Comment by jayked** [comment]
have you put the LaravelFilemanagerServiceProvider above the `App\Providers\RouteServiceProvider::class` in your `providers`?

**Comment by FilipQL** [comment]
@jayked No, these are my service providers:

```
        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
        Collective\Html\HtmlServiceProvider::class,

        Intervention\Image\ImageServiceProvider::class,
        Unisharp\Ckeditor\ServiceProvider::class,
        Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class,
```

Also, I followed your instructions: 

1. Installed unisharp/laravel-filemanager (v, 1.5.2)
2. Added service providers (I've already had _Intervention Image_ installed)
3. Published the package's config and assets:

    ```
     php artisan vendor:publish --tag=lfm_config
     php artisan vendor:publish --tag=lfm_public
    ```

4. Since I am using Laravel 5.2, I set: `'middlewares'           => ['web', 'auth'],`

But I also need to copy the entire contents of **vendor/unisharp/laravel-filemanager/src/routes.php to** my **routes.php** or I will get 404 errors (see my first comment here, above... ).

**Comment by jayked** [comment]
@FilipQL Try to put the `Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class` above the `App\Providers\RouteServiceProvider::class`. This way, on a request, it will first check the routes from the filemanager and if there is no hit it will go to your `routes.php`. Now it will go through your `routes.php` and if it has a catchall route (to catch remaining request that do not have an absolute path or do not match any of your routes) it will end up in the cathcall route en won't be able to even reach the routes of the filemanager.

**Comment by FilipQL** [comment]
Yes, that was the problem.

**Comment by kintela** [comment]
Hi
I have put the Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class above the App\Providers\RouteServiceProvider::class : And I have copied the entire contents of vendor/unisharp/laravel-filemanager/src/routes.php to my routes.php

But nothing works: I get an error 404

regards

**Comment by michalskinder** [comment]
What worked for me for combination of Laravel 5.4 & FileManager 1.7 was to set 'auth' & 'web' middlewares in `config/lfm.php`. Without 'auth' FileManager is public, but without 'web' it yields 404 even with routes present in artisan route:list.

**Comment by Maulik-Vamja** [comment]
I Have Same problem while Uploading Image in file manager. It will return 404 Not found 
![image](https://user-images.githubusercontent.com/60999063/77032360-32835700-69ca-11ea-8fb3-e122aba49038.png)

**Comment by dinhvanit92** [comment]
> r

Please edit .env
APP_URL=http://localhost:8000 or your port

**Comment by shotatchelidze** [comment]
try in TinyMCE configuration  
var editor_config = {
      path_absolute :http://localhost/laravel/blogbook/public/
}

**Comment by shotatchelidze** [comment]
> > I Have Same problem while Uploading Image in file manager. It will return 404 Not found
> > ![image](https://user-images.githubusercontent.com/60999063/77032360-32835700-69ca-11ea-8fb3-e122aba49038.png)
> > my page url is this
> > http://localhost/laravel/blogbook/admin/post/create
> > many times i pasted this url in my TinyMCE configuration but i will everytime return same error.
> > Can someone help me to solve this error..?
> 
> Please edit .env
> APP_URL=http://localhost:8000 or your port

try in TinyMCE configuration
var editor_config = {
path_absolute :http://localhost/laravel/blogbook/public/
}

**Comment by shotatchelidze** [comment]
try in TinyMCE configuration

path_absolute : "http://localhost/laravel/blogbook/public/",

**Comment by shotatchelidze** [comment]
@dinhvanit92  
try in TinyMCE configuration

path_absolute : "http://localhost/laravel/blogbook/public/",
