### ISSUE TITLE
Problem with update project to Laravel 8

### ISSUE THREAD

**Issue by lukaszevo** [UniSharp/laravel-filemanager#1002]
Hi,
I have problem with update my project from Laravel 7 to 8. When I run composer update I have error:

`Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v8.11.2, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.11.1, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.11.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.10.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.9.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.8.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.7.1, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.7.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.6.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.5.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.4.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.3.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.2.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.1.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.0.4, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.0.3, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.0.2, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.0.1, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - Conclusion: don't install laravel/framework v8.0.0, learned rules:
        - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
        - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
        - Root composer.json requires unisharp/laravel-filemanager ^2.1 -> satisfiable by unisharp/laravel-filemanager[v2.1.0].
    - unisharp/laravel-filemanager v2.1.0 requires illuminate/support 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev].
    - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^8.0 -> satisfiable by laravel/framework[v8.0.0, ..., 8.x-dev].`

Can you repair it?

**Comment by fbc** [comment]
They haven't published a Laravel 8 compatible version of the package. I'm waiting on one too. :-(

**Comment by GiTsu** [comment]
try `composer require unisharp/laravel-filemanager:dev-master` as a temporary solution. That command installs latest commit version, not a latest release. As far as a new version emerges, update composer.json to a normal requirement

**Comment by ziyakh542** [comment]
try https://github.com/mafftor/laravel-file-manager  as a temporary solution. That command installs latest commit version, not a latest release. As far as a new version emerges, update composer.json to a normal requirement

**Comment by ziyakh542** [comment]
try this package https://github.com/mafftor/laravel-file-manager

**Comment by streamtw** [comment]
Fixed in `v2.2.0`, thanks for reporting this.
