### ISSUE TITLE
Vulnerability in file upload 

### ISSUE THREAD

**Issue by abublihi** [UniSharp/laravel-filemanager#1005]
And provide the followings :
 * Operating system : linux
 * Laravel version : 5.3
 * Package version : 1.8 to latest version
 * Steps to reproduce your issue : 
1. modify the request form the in the network section in the browser
for example this request payload
```
-----------------------------252986963535943764032024309375
Content-Disposition: form-data; name="working_dir"

/shares
-----------------------------252986963535943764032024309375
Content-Disposition: form-data; name="type"

Files
-----------------------------252986963535943764032024309375
Content-Disposition: form-data; name="_token"

omLBl5pOBvRwqhkcI683kFRD7hlMGdH631iFYOLa
-----------------------------252986963535943764032024309375
Content-Disposition: form-data; name="upload[]"; filename="index.php.php"
Content-Type: image/png

<?php

echo 'hi';
echo ' help!!';

?>
-----------------------------252986963535943764032024309375--
```
2. submit this request to the server the file will be uploaded

 * Screenshots of browser console :
1. if you select the .php file from the input it prevent uploading the file.
![image](https://user-images.githubusercontent.com/10172039/98641979-b2857500-233d-11eb-8262-b52548b306e7.png)

2. but if you modify the request form the network console in the browser it is possible to upload .php files 
![image](https://user-images.githubusercontent.com/10172039/98642442-8b7b7300-233e-11eb-8bb1-eda72e168932.png)

* Proposed solution 
Use laravel validation in the function https://github.com/UniSharp/laravel-filemanager/blob/582b6ee5db851a1ddeff8085dcb56e17218dbf10/src/LfmPath.php#L235

**Comment by streamtw** [comment]
Fixed in `v2.2.0`, thanks for reporting this.
