### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by arbabi2010** [UniSharp/laravel-filemanager#1008]
Hi
I get htmlspecialchars() expects parameter 1 to be string, object given error in ckeditor version
laravel 8.11 and file manager version is 2.2

**Comment by vitalik-v** [comment]
> Hi
> I get htmlspecialchars() expects parameter 1 to be string, object given error in ckeditor version
> laravel 8.11 and file manager version is 2.2

I have the same problem. How did you decide?
