### ISSUE TITLE
alphabetic image sort order is odd

### ISSUE THREAD

**Issue by 7ammer** [UniSharp/laravel-filemanager#1011]
* Operating system : mac 10.15
 * Laravel version : 8
 * Package version : 2.2
----

Images seem to be sorting by capital letter first and then alphabetically. This results in odd looking lists such as the below. When there are a few pages of images this gets really confusing.

<img width="1253" alt="Screenshot 2020-11-27 at 18 29 23" src="https://user-images.githubusercontent.com/3194029/100476853-9542fb80-30de-11eb-9e1f-c948b45d5a97.png">

**Comment by vicheanath** [comment]
@7ammer  I using laravel v8 but it not working. can you help me

**Comment by streamtw** [comment]
Pull request was merged, thanks @7ammer .
