### ISSUE TITLE
Issue with uploaded image url

### ISSUE THREAD

**Issue by bbryan0904** [UniSharp/laravel-filemanager#102]
The image was uploaded successfully into 'public/photos/1/57a8f5aaaf2b3.jpg' through the 'browse server' button , but when I clicked the uploaded image to insert it into ckeditor, the returned url was http://localhost/photos1/57a8f5aaaf2b3.jpg. Looks like a '/' is missing between the 'photos' directory and the user_id directory. Consequently, I cannot insert the image into ckeditor. It works well if I upload the image through the ckeditor "upload" button.
Hopefully someone can help fix the issue. Thanks!

**Comment by bbryan0904** [comment]
It worked after I removed the following from vendor/unisharp/laravel-filemanager/src/views/script.blade.php

if (path.indexOf(ds) === 0) {
      path = path.substring(1);
 }

**Comment by placidrod** [comment]
Thanks @bbryan0904. I was facing the same issue and your solution just solved it.

**Comment by amindeist** [comment]
i have same issue...thank you very much @bbryan0904

**Comment by rifqifurqan** [comment]
nice one already fix it, i hope the the developers fix this soon [URGENT]

**Comment by g0110280** [comment]
Thanks @bbryan0904 , this will be fixed in three days.

**Comment by g0110280** [comment]
Updating to 1.6.1 would solve this.

**Comment by askmhs** [comment]
This also worked for me by replacing the code at line 350 (_vendor/unisharp/laravel-filemanager/src/views/script.blade.php_).

`if (path !== ds) {
    item_url = item_url + path + ds;
} else {
    item_url = item_url + ds;
}`

**Comment by haidang** [comment]
I doesn't see file _"vendor/unisharp/laravel-filemanager/src/views/script.blade.php"_ in v2.1. How to fix this on v2.1?
