### ISSUE TITLE
Can't use route:cache on laravel 8 after created route group to wrap package routes

### ISSUE THREAD

**Issue by caophihung94** [UniSharp/laravel-filemanager#1020]
Can't use route:cache on laravel 8 after create route group to wrap package routes.
 * Operating system : Windows 10 Pro
 * Laravel version : 8.0
 * Package version : dev
 * Steps to reproduce your issue :
 * Screenshots of browser console :  https://imgur.com/zP0mnr6

**Comment by vicheanath** [comment]
for laravel 8 you can use like this
`Route::prefix('laravel-filemanager')->group(function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});`

**Comment by caophihung94** [comment]
> for laravel 8 you can use like this
> `Route::prefix('laravel-filemanager')->group(function () { \UniSharp\LaravelFilemanager\Lfm::routes(); });`

Cannot solve my problem.
