### ISSUE TITLE
when resize image i got error Image source not readable disk s3

### ISSUE THREAD

**Issue by adinata-id** [UniSharp/laravel-filemanager#1031]
when i am change disk to s3 amazon i got error when resize image or crop image 

eror message :  Image source not readable

here details error message :  [https://imgur.com/a/CqCrQ1V](url)

but when i am upload and delete image or folder it's work fine , i got error only when resize or crop image..

Thanks

**Comment by DJZT** [comment]
Same issue!
@streamtw will you fix it?

**Comment by adinata-id** [comment]
problem Solved..
update to version 2.30

follow this update instruction : 

composer update unisharp/laravel-filemanager

 php artisan vendor:publish --tag=lfm_view --force
 php artisan vendor:publish --tag=lfm_public --force
 php artisan vendor:publish --tag=lfm_config --force

 php artisan route:clear
 php artisan config:clear

**Comment by aarreedd** [comment]
This is still a problem on version 2.5.

Resizing, Cropping, and Downloading all don't work because this does not work with s3: `$file->path('absolute')`

**Comment by faizan-zahid-arhamsoft** [comment]
@aarreedd what should be the solution to that $file->path('absolute') when using S3 bucket
