### ISSUE TITLE
Laravel file manager doesn't show uploaded images in file manager

### ISSUE THREAD

**Issue by bantawa04** [UniSharp/laravel-filemanager#1051]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Ubuntu 18.08
 * Laravel version : 6.0
 * Package version :2.2.0
 * Steps to reproduce your issue :

- Install laravel
- Install package
- Config with Tinymce
- Upload image from tinymce image button

 * Screenshots of browser console :
![Screenshot from 2021-03-03 12-22-58](https://user-images.githubusercontent.com/22129795/109764729-02a18380-7c1c-11eb-929d-08e59f7dccb2.png)
![Screenshot from 2021-03-03 12-23-09](https://user-images.githubusercontent.com/22129795/109764734-046b4700-7c1c-11eb-81f5-38a083bbd3e0.png)
![Screenshot from 2021-03-03 12-23-24](https://user-images.githubusercontent.com/22129795/109764740-059c7400-7c1c-11eb-9ef2-0e32465c26bc.png)
![Screenshot from 2021-03-03 12-23-34](https://user-images.githubusercontent.com/22129795/109764742-06350a80-7c1c-11eb-88d5-e084df0ebd2a.png)
![Screenshot from 2021-03-03 12-23-47](https://user-images.githubusercontent.com/22129795/109764743-06cda100-7c1c-11eb-9a80-fd7d4da7d7f4.png)
![Screenshot from 2021-03-03 12-24-03](https://user-images.githubusercontent.com/22129795/109764748-07663780-7c1c-11eb-8242-2c4e12264b3a.png)

**Comment by GrytsenkoAndrey** [comment]
I have the same issue
Ubuntu 20.04
PHP8
Laravel 8
Package 2.2.0

**Comment by streamtw** [comment]
Try running `php artisan storage:link`.

**Comment by bantawa04** [comment]
> Try running `php artisan storage:link`.

Yes, I did it while installation didn't solved the proble,

**Comment by Steve-sy** [comment]
same issue, on shared hosting namecheap

**Comment by Steve-sy** [comment]
fixed it by just deleting the storage folder in public, and rerun : ` php artisan storage:link `

**Comment by AntistressStore** [comment]
if UniSharp laravel-filemanager adding '/storage' to you files, and its dont preview because path to file incorrect, use in filesystems.php config 
 'mediafiles' => [
            'driver' => 'local',
            'root' => public_path(),
            'visibility' => 'public',
            **'url' => ''**, // url without any path
        ],

my files in public/mediafiles path, and this config help

**Comment by tatpongpro4** [comment]
how fix?

**Comment by GrytsenkoAndrey** [comment]
> 
> 
> how fix?

Check routes; be sure that you have storage:link

it works for me

**Comment by trimor** [comment]
> fixed it by just deleting the storage folder in public, and rerun : `php artisan storage:link`

thank you so much....the problem "Invalid Proses Upload" is SOLVED...

**Comment by sajidosman15** [comment]
> fixed it by just deleting the storage folder in public, and rerun : `php artisan storage:link`

Thank you so much. It was really helpful

**Comment by hoantv1107** [comment]
> Thank you so much. It was really helpful

Thank you so much. It was really helpful

**Comment by hoantv1107** [comment]
> 

Thank you so much. It was really helpful

**Comment by thilaju** [comment]
it says links already created.
it was showing until recently but after the last delete image, the new image uploads stop showing

**Comment by Arif-X** [comment]
Change your env `APP_URL` configuration with same port of serve or your own domain.
Add `storage:link` too
I Solve my issues in my TinyMCE

**Comment by engsaiful0** [comment]
> fixed it by just deleting the storage folder in public, and rerun : `php artisan storage:link`

This is working fine. Thanks

**Comment by farzanehlbf** [comment]
thanks

**Comment by GrytsenkoAndrey** [comment]
> if UniSharp laravel-filemanager adding '/storage' to you files, and its dont preview because path to file incorrect, use in filesystems.php config 'mediafiles' => [ 'driver' => 'local', 'root' => public_path(), 'visibility' => 'public', **'url' => ''**, // url without any path ],
> 
> my files in public/mediafiles path, and this config help

👍

**Comment by shahin-AG** [comment]
same issue on host, any suggestion?

**Comment by rezajalilian** [comment]
> Thank you so much

**Comment by rezajalilian** [comment]
> fixed it by just deleting the storage folder in public, and rerun : `php artisan storage:link`

Thank you so much man

**Comment by DieuPC** [comment]
> > nếu UniSharp laravel-filemanager thêm '/storage' vào tệp của bạn và nó không xem trước vì đường dẫn đến tệp không chính xác, hãy sử dụng trong filesystems.php config 'mediafiles' => [ 'driver' => 'local', 'root' => public_path(), 'visibility' => 'public', **'url' => ''** , // url không có đường dẫn ],
> > các tệp của tôi trong đường dẫn tệp công khai/tệp đa phương tiện và trợ giúp về cấu hình này
> 
> 👍

**Comment by DieuPC** [comment]
> > nếu UniSharp laravel-filemanager thêm '/storage' vào tệp của bạn và nó không xem trước vì đường dẫn đến tệp không chính xác, hãy sử dụng trong filesystems.php config 'mediafiles' => [ 'driver' => 'local', 'root' => public_path(), 'visibility' => 'public', **'url' => ''** , // url không có đường dẫn ],
> > các tệp của tôi trong đường dẫn tệp công khai/tệp đa phương tiện và trợ giúp về cấu hình này
> 
> 👍

**Comment by DieuPC** [comment]
> > if UniSharp laravel-filemanager adding '/storage' to you files, and its dont preview because path to file incorrect, use in filesystems.php config 'mediafiles' => [ 'driver' => 'local', 'root' => public_path(), 'visibility' => 'public', **'url' => ''**, // url without any path ],
> > my files in public/mediafiles path, and this config help
> 
> 👍

In laravel 7 how to fix the above error?

**Comment by ArfeelHaroon** [comment]
**Issue: Uploaded Images Not Showing Preview in Laravel File Manager**
If you're facing the problem of uploaded images not showing a preview or thumbnail in Laravel File Manager, it might be due to an incorrect image URL being generated. This can often be resolved by making a simple adjustment in your application's configuration.

**Solution: Update the Filesystems Configuration**

1. Locate the `filesystems.php` configuration file in your Laravel project. You can find it in the `config` directory.
2. Inside the `filesystems.php` file, look for an entry named `'public'`.
3. In the `'public'` entry, you'll find a `'url'` setting that might look something like this:
  
![Screenshot 2023-08-11 043955](https://github.com/UniSharp/laravel-filemanager/assets/129212947/96f87750-c661-4101-8216-e4803396de8b)
`'url' => env('APP_URL') . '/storage',
`
4. To fix the image preview issue, you can modify this setting as follows:
`'url' => '/storage',
`
You're essentially removing env('APP_URL') . from the URL.
**Final Steps: Clear Cache and Routes (If require)**
After making this configuration change, it's a good idea to perform these two commands to ensure that your changes take effect:
1. Clear the cache:
`php artisan cache:clear
`
2. Clear the routes:
`php artisan route:clear
`
These steps should resolve the issue of uploaded images not showing previews in Laravel File Manager. Your images should now be displayed correctly.

Please note that modifying configuration files should be done with caution, and it's always a good practice to back up your files before making changes. This solution should help you improve the image preview experience within Laravel File Manager.

**Comment by hondaman900** [comment]
> Change your env `APP_URL` configuration with same port of serve or your own domain. Add `storage:link` too I Solve my issues in my TinyMCE

I already had the `storage:link` set but `APP_URL` in my `.ENV` was wrong, as suggested above. Changing that to what was actually my site URL fixed the issue for me.

**Comment by dayan2222** [comment]
> fixed it by just deleting the storage folder in public, and rerun : `php artisan storage:link`

This works for me. 
Thanks :)

**Comment by stevensu123** [comment]
Can Unisharp handle logic like this? For example, I have 2 file choose options: one for choosing a background file and the other for choosing an author file. When the background file is selected, the file manager opens, and the user is directed to the background folder
![image](https://github.com/user-attachments/assets/d6dde70e-8a97-4bf3-b3d3-7b81b6b69588)

**Comment by avakar782-netizen** [comment]
a
