### ISSUE TITLE
wrong image path with tinymce integration

### ISSUE THREAD

**Issue by harimayco** [UniSharp/laravel-filemanager#106]
Hi,

I found this after selecting image with tinymce integration.
![wrong path](http://image.prntscr.com/image/d10e26bf9ff74c6d9df866572e69b028.png)
as you can see it returns `http://localhost:8000/photosshares/blabla.jpg` the right path is `http://localhost:8000/photos/shares/blabla.jpg`

I'm using Laravel 5.2
this is my config  : 
`// If true, the uploaded file will be renamed to uniqid() + file extension.
    'rename_file'           => true,

    // If rename_file set to false and this set to true, then filter filename characters which are not alphanumeric.
    'alphanumeric_filename' => true,

    'use_package_routes'    => true,

    // For laravel 5.2, please set to ['web', 'auth']
    'middlewares'           => ['web', 'backend'],

    // Add prefix for routes
    'prefix'           => 'filemanager',

    // Allow multi_user mode or not.
    // If true, laravel-filemanager create private folders for each signed-in user.
    'allow_multi_user'      => false,

    // The database field to identify a user.
    // When set to 'id', the private folder will be named as the user id.
    // NOTE: make sure to use an unique field.
    'user_field'            => 'id',

    'shared_folder_name'    => 'shares',
    'thumb_folder_name'     => 'thumbs',

    'images_dir'            => 'public/photos/',
    'images_url'            => '/photos/',

    'files_dir'             => 'public/files/',
    'files_url'             => '/files/',`

I think something is wrong with useFile function .
because it's working when i changed shared_folder_name with /
 'shared_folder_name'    => '/shares',

btw thank you for the awesome package, it really helps me alot.  :bowtie:

**Comment by ognjenm** [comment]
it works when comment out line 351 
    if (path.indexOf(ds) === 0) {
      //path = path.substring(1);
    }
in .../vendor/unisharp/laravel-filemanager/src/views/script.blade.php

**Comment by Neanrakyr** [comment]
i try the @ognjenm and work well, thanks you :) any patch inc for that?

**Comment by Grald** [comment]
@Neanrakyr i had also that kind of error but still can't i fixed i changed this line:
if (path.indexOf(ds) === 0) {
//path = path.substring(1);
}
but error nothing's happen

**Comment by moeinrahimi** [comment]
same here like @Grald

**Comment by Grald** [comment]
@moeinrahimi in your public/vendor folder find the script.blade.php you need to comment out that line and it works fine

**Comment by moeinrahimi** [comment]
@Grald thank you

**Comment by Grald** [comment]
@moeinrahimi  welcome

**Comment by g0110280** [comment]
Updating to 1.6.1 would solve this.

**Comment by rajeswaridevi** [comment]
I am using filemanager of 1.8 version functionality wise it is working good as my project is a news related it has more images .file manager is taking more time to load.how to overcome this issue.Please help me on this.
