### ISSUE TITLE
Request URL was not found with localhost public

### ISSUE THREAD

**Issue by yc-public** [UniSharp/laravel-filemanager#107]
Sorry im new to laravel, i just look the #77 issue but i still not able to solve my problem here.
I was follow the installation guide, installed composer require file, updated config/app, and publish the package's config and assets, and updated 'middlewares' => ['web', 'auth'],

Then i add the independent use text field as guide,
`<div class="input-group">
      <span class="input-group-btn">
        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
          <i class="fa fa-picture-o"></i> Choose
        </a>
      </span>
      <input id="thumbnail" class="form-control" type="text" name="filepath">
    </div>
    <img id="holder" style="margin-top:15px;max-height:100px;">`

When click upload the button show up
![image](https://cloud.githubusercontent.com/assets/8948755/17638041/2611e7dc-611a-11e6-8f2f-32dc7c30f89d.png)

i had no idea whats the problem but i think that maybe cause of route issue, this my php artisan route:list 

![image](https://cloud.githubusercontent.com/assets/8948755/17638117/97c20862-611a-11e6-8f24-fa2baf3b5079.png)

![image](https://cloud.githubusercontent.com/assets/8948755/17638135/adf38d68-611a-11e6-9bf4-a55bd073511f.png)

my root path was localhost/asoap/public, and i tried to hit up with localhost/asoap/public/laravel-filemanager?type=Images and this the output...

![image](https://cloud.githubusercontent.com/assets/8948755/17638200/1002bfba-611b-11e6-81e9-37e368bda818.png)

Well, hope i can get help with whats problem to my project here, and sorry for the time.
And a question, in installation part no.4, Ensure that the files & images directories (in config/lfm.php) are writable by your web server. What does this means ?

**Comment by chebaby** [comment]
try to follow the steps on [documantation](https://github.com/UniSharp/laravel-filemanager/blob/master/doc/installation.md)

I had the same problem, all I did was to clear the cache
`php artisan route:clear`
