### ISSUE TITLE
Ftp loding takes too much time to fetch files and directories from server

### ISSUE THREAD

**Issue by dactanit** [UniSharp/laravel-filemanager#1084]
Ftp loding takes too much time to fetch files and directories from server

Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system :
 * Laravel version :8.12
 * Package version :2.2
 * Steps to reproduce your issue :
 * Screenshots of browser console :

**Comment by eugenefvdm** [comment]
Hi there @streamtw and @tsawler , CC @youchenlee ,

Would you guys please consider closing this issue, as it's nonsensical.

**Comment by streamtw** [comment]
Information provided is not enough to trouble shoot the actual issue. Please reopen this if this is still a issue to you.
