### ISSUE TITLE
how to set path format untuk stand alone button ?

### ISSUE THREAD

**Issue by hilmihidyt** [UniSharp/laravel-filemanager#1089]
![stand alone button](https://imgur.com/5WRVC8X)

for stand alone button, how to set the path format from http://127.0.0.1:8000/storage/photos/1/Brand/logo.png to be like this photo/1/Brand/logo.png ? so, http://127.0.0.1:8000/storage is not entered into the database table.

For now, I can change the value in the input field manually, but I want it to automatically exclude http://127.0.0.1:8000/storage.

**Comment by abbasfisal** [comment]
> ![stand alone button](https://camo.githubusercontent.com/aff400183f873e0e1e0ec62747c42b0bb0970aebb28fc6e7c2bba5bab071422f/68747470733a2f2f696d6775722e636f6d2f35575256433858)
> 
> for stand alone button, how to set the path format from http://127.0.0.1:8000/storage/photos/1/Brand/logo.png to be like this photo/1/Brand/logo.png ? so, http://127.0.0.1:8000/storage is not entered into the database table.
> 
> For now, I can change the value in the input field manually, but I want it to automatically exclude http://127.0.0.1:8000/storage.

in the **.env** file APP_URL set it to null
`APP_URL=`
