### ISSUE TITLE
Create New Folder Locale Issue

### ISSUE THREAD

**Issue by yc-public** [UniSharp/laravel-filemanager#109]
Im using the zh-cn locales to create a new folder, but the folder name went something wrong after created like..

Folder name : 产品
![image](https://cloud.githubusercontent.com/assets/8948755/17647555/bfee5bc0-6227-11e6-8493-18579e8dad5c.png)

Folder created:
![image](https://cloud.githubusercontent.com/assets/8948755/17647559/df38aa9e-6227-11e6-8e6e-5375490b78d5.png)

When i create a new images, the images actually created in the folder, however the naming went wrong so unable to display as shown as pic1. Is it a bug or any solution on this ?

And also, every single folder i created it exist a backslash infront of folder name, i think this is not usual and i cant delete the folder with start with \t or \x like \thumb or \xx, thought it hit the javascript string objects type.
![image](https://cloud.githubusercontent.com/assets/8948755/17648442/496ea1b4-6248-11e6-8026-9ca1c7dc9dfc.png)

Besides, when my config/app set the locale to zh, i cannot use the resource/lang/vendor/laravel-manager/en/lfm.php file, would be suggest to allow user set the locale in config/lfm.php file.

**Comment by g0110280** [comment]
This might be the issue with directory seperator of the backslash on Windows.
Will check this soon.

**Comment by g0110280** [comment]
Solved in `v1.7.0`.
