### ISSUE TITLE
cURL 60 error

### ISSUE THREAD

**Issue by Silent2000** [UniSharp/laravel-filemanager#1090]
Hi. We use S3 as filesystem disk and faced with error:
`production.ERROR: Error executing "ListObjects" on "https://coursebook.test-namespace-6xsx.s3pd01.sbercloud.ru/?prefix=admin%2F&max-keys=1&encoding-type=url"; AWS HTTP error: cURL error 60: Unable to communicate securely with peer: requested domain name does not match the server's certificate. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"userId":3,"exception":"[object] (Aws\\S3\\Exception\\S3Exception(code: 0): Error executing \"ListObjects\" on \"https://coursebook.test-namespace-6xsx.s3pd01.sbercloud.ru/?prefix=admin%2F&max-keys=1&encoding-type=url\"; AWS HTTP error: cURL error 60: Unable to communicate securely with peer: requested domain name does not match the server's certificate. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /var/www/isaukov/data/www/coursebook.ru/laravel/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)`

How can we disable ssl verify or make url path style (not host style like it's now)? We need url like https://test-namespace-6xsx.s3pd01.sbercloud.ru/coursebook

**Comment by streamtw** [comment]
Sorry for late reply. If you mean you want relative urls other than full urls, example code can be found in https://github.com/UniSharp/laravel-filemanager/issues/1233 .
