### ISSUE TITLE
How can I remove the domain name from the path of image?

### ISSUE THREAD

**Issue by DevYSM** [UniSharp/laravel-filemanager#1107]
Hello devs, Please how can I remove the domain name from the Image path for example:
http://127.0.0.1:8000/storage/photos/1/61a4d686d98b9.jpeg
I just need the : 
/storage/photos/1/61a4d686d98b9.jpeg

the package handle this or I will do it manually.

**Comment by sorryjack** [comment]
same with me. keep using http://127.0.0.1:8000/ even I set relative_url to true. caused image nt found cz calling http://127.0.0.1:8000/ twice

**Comment by sorryjack** [comment]
find this and its solved
[https://github.com/UniSharp/laravel-filemanager/issues/1089](https://github.com/UniSharp/laravel-filemanager/issues/1089)

**Comment by DevYSM** [comment]
I find the same ticket issue but why remove the App Domain !!!

**Comment by ORN-Fox** [comment]
Salut voici comment résoudre ce problème car je l'ai déjà eu :
`'public' => [
             'driver' => 'local',
             'root' => storage_path('app/public'),
-            'url' => env('APP_URL').'/storage',
+            'url' => '/storage',
             'visibility' => 'public',
         ],`

dans le fichier `config/filesystems.php`

**Comment by nqlinh2205** [comment]
why images are stored in folder name "1" ?? who can explain to me? pls

**Comment by eugenefvdm** [comment]
User ID 1, or 2, or 3 etc.

@@streamtw
@tsawler
@youchenlee

Please close this?

**Comment by tsawler** [comment]
I don’t have permission to close this, since this is a fork.

--
Trevor

**Comment by streamtw** [comment]
Solution can be found in #1233 .
