### ISSUE TITLE
File size exceeds server limit (2M)

### ISSUE THREAD

**Issue by MatthiasScreed** [UniSharp/laravel-filemanager#1108]
hello i devellop a blog on laravel laravel 8 and i use file-manager last version everything was working until i put my app on digital server ocean that run on unbuntu now i can't upload images because apparently file size exceeds server limit(2M)

i change the php ini config :
 
post_max_size = 30M
 upload_max_filesize = 30M

i change the nginx.conf : 

client_max_body_Size 2000M;
client_body_buffer_size 128k;

i restart both but i still have the same error  the file size exceed server limit and i don't understands how to fix it

**Comment by fsociety** [comment]
Have you looked at the config file?
![image](https://user-images.githubusercontent.com/13049077/155168225-8c564aa4-958f-4d13-830c-44495e34c647.png)

**Comment by yogaoga7** [comment]
@fsociety 
/*
    |--------------------------------------------------------------------------
    | Folder Names
    |--------------------------------------------------------------------------
     */

    'folder_categories'        => [
        'file'  => [
            'folder_name'  => 'files',
            'startup_view' => 'list',
            'max_size'     => 50000, // size in KB
            'thumb' => true,
            'thumb_width' => 80,
            'thumb_height' => 80,
            'valid_mime'   => [
                'image/jpeg',
                'image/pjpeg',
                'image/png',
                'image/gif',
                'application/pdf',
                'text/plain',
            ],
        ],
        'image' => [
            'folder_name'  => 'assets',
            'startup_view' => 'grid',
            'max_size'     => 50000, // size in KB
            'thumb' => true,
            'thumb_width' => 80,
            'thumb_height' => 80,
            'valid_mime'   => [
                'image/jpeg',
                'image/pjpeg',
                'image/png',
                'image/gif',
            ],
        ],
    ],

**Comment by tanjilahmed7** [comment]
I'm encountering the same problem and need assistance in resolving it as soon as possible. Additionally, I have a file named 'valid_mime' that is not compatible with the upload process. How can I address these issues?

Need to answer ASAP. 

![image](https://github.com/UniSharp/laravel-filemanager/assets/8897830/e3e927f0-82d8-49fc-907e-04636c176639)
![image](https://github.com/UniSharp/laravel-filemanager/assets/8897830/f70ef580-f448-48c7-a06c-8de8598ec7b4)
![image](https://github.com/UniSharp/laravel-filemanager/assets/8897830/70710437-e4b0-4e83-bed4-e4db207fce26)

**Comment by streamtw** [comment]
For anyone encountered this issue: 

If you see the exact error message "File size exceeds server limit (2M)", this is usually related to `php.ini` configuration. The `2M` is the default value for `post_max_size` and `upload_max_filesize`.

To debug if `php.ini` is set properly, you can use the following line somewhere in your view or controller:
```
dd(ini_get('post_max_size'), ini_get('upload_max_filesize'));
```

If both values are `2M`, please check if `php.ini` configuration is in the right place.
