### ISSUE TITLE
How can I make the pictures visible and accessible to everyone?

### ISSUE THREAD

**Issue by akbarali1** [UniSharp/laravel-filemanager#1112]
When I upload photos and files, the user's self-uploaded photos appear. How can all users view and use each other's photos?

**Comment by DilmurodQurbonboyev** [comment]
the same issue

**Comment by akbarali1** [comment]
So I found the answer myself


/app/Servies/FileManagerService.php
write

```

<?php

namespace App\Services;

class FileManagerService
{
    public function userField()
    {
        return 'all_users';
    }
}

```

edit `config/lfm.php` 36 line

` 'private_folder_name'      => \App\Services\FileManagerService::class,`

![image](https://user-images.githubusercontent.com/39323182/151573168-41e47445-b917-41a7-b7df-1b5139f5f202.png)

![image](https://user-images.githubusercontent.com/39323182/151573188-2d1f90cb-3ba6-448f-91af-564cfba3d3d8.png)
