### ISSUE TITLE
Call to undefined method League\\Flysystem\\Filesystem::getAdapter()

### ISSUE THREAD

**Issue by FauziAris** [UniSharp/laravel-filemanager#1118]
I've tried to install this package in Laravel 9. Then I tried to create a folder or upload an image, but the result is an error **Call to undefined method League\\Flysystem\\Filesystem::getAdapter()**. How to fix the error?

 * Operating system : Windows 11
 * Laravel version : ^9.0
 * Package version : ^2.4
 Screenshots of browser console :
![image](https://user-images.githubusercontent.com/46512994/154889559-652ba438-9fb3-461e-9122-e83ddec756c7.png)

**Comment by truongbo17** [comment]
same

**Comment by raminr63** [comment]
same

**Comment by alnefely** [comment]
same

**Comment by baruchyan** [comment]
same

**Comment by mnjadidi** [comment]
same

**Comment by SHSharkar** [comment]
Hey There,

I am facing the same error. I guess its because of Filesystem upgraded to ^3

Here is the error information I got.

```
Call to undefined method League\Flysystem\Filesystem::getAdapter()
```

```
UniSharp\LaravelFilemanager\LfmStorageRepository::rootPath
PROJECT_PATH\vendor\unisharp\laravel-filemanager\src\LfmStorageRepository.php
:29
```

```
public function rootPath()
    {
        $adapter = $this->disk->getDriver()->getAdapter();

        if ($adapter instanceof CachedAdapter) {
            $adapter = $adapter->getAdapter();
        }

        return $adapter->getPathPrefix();
    }
```

```
Extra info
+-------------------------+----------------+
| Platform                | WINNT          |
| PHP                     | 8.0.16         |
| Laravel                 | 9.2.0          |
+-------------------------+----------------+
```

**Comment by JohnyPutraPetir** [comment]
I just try to change function rootPath() at LfmStorageRepository.php
```
public function rootPath()
  {
    // $adapter = $this->disk->getDriver()->getAdapter();

    // if ($adapter instanceof CachedAdapter) {
    //   $adapter = $adapter->getAdapter();
    // }

    // return $adapter->getPathPrefix();
    return $this->path();
  }
```
it's working, hope that not make code messed up

**Comment by maryam-farahani** [comment]
Hello
I also had this problem, my problem was solved with your solution
Thank you

**Comment by FauziAris** [comment]
> I just try to change function rootPath() at LfmStorageRepository.php
> 
> ```
> public function rootPath()
>   {
>     // $adapter = $this->disk->getDriver()->getAdapter();
> 
>     // if ($adapter instanceof CachedAdapter) {
>     //   $adapter = $adapter->getAdapter();
>     // }
> 
>     // return $adapter->getPathPrefix();
>     return $this->path();
>   }
> ```
> 
> it's working, hope that not make code messed up

**Comment by FauziAris** [comment]
> Saya baru saja mencoba mengubah fungsi rootPath() di LfmStorageRepository.php
> 
> ```
> public function rootPath()
>   {
>     // $adapter = $this->disk->getDriver()->getAdapter();
> 
>     // if ($adapter instanceof CachedAdapter) {
>     //   $adapter = $adapter->getAdapter();
>     // }
> 
>     // return $adapter->getPathPrefix();
>     return $this->path();
>   }
> ```
> 
> itu berfungsi, semoga tidak membuat kode kacau

While waiting for a fix from the UniSharp/laravel-filemanager team, I'll be following your code for a while.

**Comment by JohnyPutraPetir** [comment]
> I just try to change function rootPath() at LfmStorageRepository.php
> 
> ```
> public function rootPath()
>   {
>     // $adapter = $this->disk->getDriver()->getAdapter();
> 
>     // if ($adapter instanceof CachedAdapter) {
>     //   $adapter = $adapter->getAdapter();
>     // }
> 
>     // return $adapter->getPathPrefix();
>     return $this->path();
>   }
> ```
> 
> it's working, hope that not make code messed up

and if after doing that you can't resize or crop the image, try to edit function path($type = 'storage') at vendor\unisharp\laravel-filemanager\src\LfmPath.php like this

```
 public function path($type = 'storage')
  {
........
........
    } else {
      // absolute: /var/www/html/project/storage/app/files/{user_slug}
      // absolute on windows: C:\project\storage\app\files\{user_slug}
      // return $this->storage->rootPath() . $this->path('storage');
      return $this->storage->rootPath();
    }
  }
```
I don't know what i'm doing is right or not, but it's work for a while

**Comment by wsdnathan** [comment]
Hello @jcsoriano @streamtw could you please look into a resolve for this? v2.4.0 broke uploads.

**Comment by dev8loper** [comment]
when will the solution come?

**Comment by urakozz** [comment]
It's because of underlying league/flysystem has been changed from v1 to v3. This dependency is not listed in the composer.json and not tested even though library relies on the details of implementation such as import of the League\Flysystem\Cached\CachedAdapter (which is not there as well in the v3)

**Comment by bugrabozkurtt** [comment]
Does anyone have a solution?
I've the same problem when i create folder, upload file

**Comment by mziraki** [comment]
@streamtw ping!

**Comment by timvanuum** [comment]
For the time being while this isn't fixed.
I use this patch

`diff --git a/src/LfmStorageRepository.php b/src/LfmStorageRepository.php
index d57e63d4..c396a042 100644
--- a/src/LfmStorageRepository.php
+++ b/src/LfmStorageRepository.php
@@ -26,13 +26,7 @@ public function __call($function_name, $arguments)

     public function rootPath()
     {
-        $adapter = $this->disk->getDriver()->getAdapter();
-
-        if ($adapter instanceof CachedAdapter) {
-            $adapter = $adapter->getAdapter();
-        }
-
-        return $adapter->getPathPrefix();
+        return $this->disk->path('/');
     }

     public function move($new_lfm_path)
`

Can be used with this package: https://github.com/cweagans/composer-patches

**Comment by FauziAris** [comment]
I have tried this package in Laravel 9 with version v2.4.1 and it works fine. I will close this issue. Thank you.

**Comment by a21ns1g4ts** [comment]
Do not use laravel 9 with league filesystem 2.4

**Comment by climbcoder** [comment]
It doesn't let install v2.4.1 with Laravel 9

**Comment by zlanich** [comment]
This also worked for me too after upgrading to Laravel 9, AWS v3, etc. Thank you!
