### ISSUE TITLE
lg is not defined

### ISSUE THREAD

**Issue by Palvaneh** [UniSharp/laravel-filemanager#112]
click on images causes:
laravel-filemanager:528 Uncaught ReferenceError: lg is not defined

**Comment by g0110280** [comment]
Please post your screenshots here, thanks.

**Comment by Palvaneh** [comment]
script.blade.php line 389: `$.prompt(lg.fck_select_integration);`

**Comment by bbryan0904** [comment]
Are you using the standalone button? I have encountered this error in that situation. In my scenario, after I initialized the button with $('#lfm').filemanager('image'); the error disappeared.

Here's what I had in my view:
<a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">Browse</a>
<script src="/vendor/laravel-filemanager/js/lfm.js"></script>  
$('#lfm').filemanager('image');

**Comment by creaz35** [comment]
Hello,
I have exactly the same issue, i cannot view the file.

ReferenceError: lg is not defined when i click on the file name.

Tested on Firefox and Chrome.

**Comment by creaz35** [comment]
How to fix it ?

**Comment by Palvaneh** [comment]
I don't know how to fix problem, I decided to use laravel built in file manager :(

**Comment by g0110280** [comment]
@bbryan0904 Did you integrate the standalone button successfully?
I want to know if the error still happens.

**Comment by g0110280** [comment]
Updated : I figured this out!
This error happens when no WYSIWYG editor is found.
For example, open a new tap and type in the route of file manager will then show the error.
I will solve this in v1.6.2 .

**Comment by g0110280** [comment]
v1.6.2 were release today.
Close issue for now.
