### ISSUE TITLE
Use of Laravel asset function in script.blade.php cause getFileUrl to return bad path

### ISSUE THREAD

**Issue by cbernard73** [UniSharp/laravel-filemanager#114]
On Jun 28 a change was made to line 5 of script.blade.php so that it now reads:

var image_url     = "{{ asset(Config::get('lfm.images_url')) }}";

The asset function was added. The use of the asset function causes the trailing / of images_url to be removed. 

Then getFileUrl remove the leading / here:

 if (path.indexOf(ds) === 0) {
      path = path.substring(1);
    }

The result is a path like http:://localhost/images1/23423423.png

**Comment by g0110280** [comment]
Thank you!
Will check this later.

**Comment by Perpleex** [comment]
Same problem with Ck-editor integration
Exemple :
http://localhost:8000/imagesshares/drap_oc1.gif

A similar problem occur when you try to delete a folder.

C:\Users\Perpleex\Documents\Project/public/files/shares/sharesexemple not found!
Shares is bound two times  and one without /

Some strange things too if you are in images mode and you create a new folder you comeback in file mode.

**Comment by g0110280** [comment]
basename() function is buggy with Chinese characters.
We have to find out another solution.

**Comment by wallauschek** [comment]
script.blade.php

> function getFileUrl(file) {
> ...
>    if (path != ds) {
>          item_url = item_url **+ ds** + path + ds;
>     }

**Comment by g0110280** [comment]
Root cause for #102, #103, #106

**Comment by g0110280** [comment]
Update to 1.6.1 would solve this.

**Comment by FerchoCarcho** [comment]
that asset thing isnt good when you want to customize your files into a Database field. I removed it but now Im getting double `/photos//rNd2zDCdanpj/sliders/57d86ded98d53.jpg` slash after photos.
Can you explain why did you include asset?
