### ISSUE TITLE
cant delete folder when there is contents

### ISSUE THREAD

**Issue by azizikri** [UniSharp/laravel-filemanager#1142]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Windows 10
 * Laravel version : 8
 * Package version : v2.5.1
 * Steps to reproduce your issue : create folder and fill it with image, and delete it
 * Error : Method UniSharp\LaravelFilemanager\Controllers\DeleteController::error does not exist.

**Comment by adityadees** [comment]
> Please check the following instructions before submitting a bug :
> 
> * Make sure you are using the latest version.
> * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.
> 
> And provide the followings :
> 
> * Operating system : Windows 10
> * Laravel version : 8
> * Package version : v2.5.1
> * Steps to reproduce your issue : create folder and fill it with image, and delete it
> * Error : Method UniSharp\LaravelFilemanager\Controllers\DeleteController::error does not exist.

you can upload the images?

**Comment by azizikri** [comment]
update here, I think this happened because the error function is deleted in src/Controllers/LfmController.php, this was deleted in commit "b115dca3c1b089aa08c8b0b0107683668ad17279" I don't know what the purpose the code was deleted, maybe @streamtw can elaborate?

**Comment by tanero** [comment]
Same error still exist, at version 2.7.0.    It looks like this package development is not in progress, otherwise I think someone would have taken care of this problem until now.

**Comment by streamtw** [comment]
Sorry for late reply. I have reproduced this issue on my end.
The `error` function may be deleted because I falsely thought it was a redundant function.
I will release a fixed version today.

**Comment by streamtw** [comment]
`v2.7.1` has been released to fix this issue. Please run `php artisan vendor:publish --force --tag=lfm_public` and `php artisan vendor:publish --force --tag=lfm_view` after upgrading to `v2.7.1`.

**Comment by streamtw** [comment]
`v2.7.1` has been released to fix this issue. Please run `php artisan vendor:publish --force --tag=lfm_public` and `php artisan vendor:publish --force --tag=lfm_view` after upgrading to `v2.7.1`.

**Comment by jayson-velasquez** [comment]
in public/vendor/laravel-filemanager/js/lfm.js  the file_path in window.SetUrl is empty. causing an error

<img width="1162" alt="Screen Shot 2024-02-28 at 2 33 14 PM" src="https://github.com/UniSharp/laravel-filemanager/assets/13635502/7ad0e405-f5a9-4092-9318-9fa6a3080e09">
