### ISSUE TITLE
Upload images to /resources folder instead of /public folder

### ISSUE THREAD

**Issue by binwangdev** [UniSharp/laravel-filemanager#115]
Hi,
For better security, I want to upload images to /resources folder instead of /public folder. I changed the configuration and the images were uploaded successfully. However, the images cannot be displayed in the file manager window and I cannot insert them into ckeditor. I understand it's because they are not in web root folder and we need other functions to serve them. Is there any way to add that functionality? Without that the configuration doesn't really work. Correct me if I'm wrong. Appreciate your help! Thanks.

**Comment by g0110280** [comment]
Hello @bbryan0904 , this is our 2.0 milestone!
We are going to integrate [this package](https://github.com/UniSharp/laravel-fileapi) to handle file uploading.
When it's is done, we will be able to upload files to /public, /storage, and of course /resources directories.

**Comment by arisschlingmann** [comment]
Hi @g0110280 ,
Great to hear this is going to be implemented. We really need this feature! Do you know when 2.0 will be available?
Thanks!

**Comment by claytongf** [comment]
Hi @g0110280 ,
Do you have any date for this release coming out?

**Comment by g0110280** [comment]
Hello @bwang0904 @arisschl @claytongf ,
This feature is already supported. Simply change `images_dir` in `config/lfm.php` can do the trick.
```
'images_dir' => 'resources/photos/', // default value : public/photos
```
And since apache and nginx don't server files directly from `resources`, you will need to adjust them to fit this feature.

**Comment by g0110280** [comment]
No release date for v2.0 for now, since too many features are required to be done.
But a feature branch might be released within this month to support this feature.

**Comment by bonucci** [comment]
hello @g0110280  i already used your example but for some reason is uploading to 'photos' folder when i already change the path on 'images_dir'

**Comment by EngHazem** [comment]
@g0110280 

I tried using `images_dir` but didn't work, still unable to view thumbnails in file browser.

My configs:

```php
  'base_directory' => 'storage/app/public',

    'images_folder_name' => 'finder_images',
    'files_folder_name'  => 'finder_files',

    'shared_folder_name' => 'finder_shares',
    'thumb_folder_name'  => 'finder_thumbs',

    'images_dir' => 'storage/finder_images/', // default value : public/photos
```

**Comment by g0110280** [comment]
This feature is available now in `v1.7.2`.

**Comment by AnimalInstinct** [comment]
Hi! How can i upload to folder that levels up from root folder? For example my public folder in /../../httpdocs/images , ive changed it in config file, but it doesnt works :(

**Comment by AnimalInstinct** [comment]
Security issue is saving files to framework dirs, sad, it means this file manager useless, i am just lost my time to install and configure it

**Comment by jayenne** [comment]
Ok. I think you may need to understand more about servers and security.

You can use a controller to move the files after upload.


On 4 Jul 2018, at 17:19, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Security issue is saving files to framework dirs, sad, it means this file manager useless, i am just lost my time to install and configure it

**Comment by gwleuverink** [comment]
I’m not sure this is what you’re looking for, but you could try saving to storage directory and create a symbolic link in the directory you want to access the files from.
