### ISSUE TITLE
Question - how to specify route for standalone upload button

### ISSUE THREAD

**Issue by bwang0904** [UniSharp/laravel-filemanager#116]
I'm trying to specify a route url for the standalone upload button instead of specifying an 'id' and loading the javascript:

```
<script src="/vendor/laravel-filemanager/js/lfm.js"></script>  
$('#lfm').filemanager('image');
```

This is because I cannot click the button on iphone/ios with the javascript method window.open(). Can someone please help provide the code and route for this scenario? Thanks!

**Comment by g0110280** [comment]
@bbryan0904 
It is really strange that this issue only happens on Chrome for iOS.
Testing on Safari and Chrome for Android was fine.
Figuring this out...

**Comment by g0110280** [comment]
Tested on v1.6.2, work fine with Chrome for iOS v43 and Safari. Close issue now.
