### ISSUE TITLE
Standalone button path to images sometime full URL sometime relative

### ISSUE THREAD

**Issue by fencer-md** [UniSharp/laravel-filemanager#117]
i have used twice this package for my sites, and cant figure out, first time I have used this it have returned me relative path to image I have uploaded **/photos/shares/Clients/57c4324a23d0f.png** and it was exactly what I wanted. Second time this plugin returns me full path to resource **http://localhost:8000/photos/shares/Clients/57c4324a23d0f.png** why this is happening and how can i control this?

**Comment by jayked** [comment]
Check your `lfm.php` in your `config` folder (the configuration of the plugin off course) and check the following : 
```php
<?php
'images_dir' => 'public/photos/',
'images_url' => env('SITE_URL') . '/photos/',

'files_dir'             => 'public/files/',
'files_url'             => env('SITE_URL') . '/files/',
```

**Comment by fencer-md** [comment]
'shared_folder_name'    => '/shares',
    'thumb_folder_name'     => 'thumbs',

    'images_dir'            => 'public/photos/',
    'images_url'            => '/photos/',

    'files_dir'             => 'public/files/',
    'files_url'             => '/files/',

Those are my confings and although in input I get **http://localhost:8002/photos/shares/Clients/57c4324a23d0f.png** but I nee just **/photos/shares/Clients/57c4324a23d0f.png**

Can you advice me how to get this result? in my another project I have the same configs and I get the result without full path

**Comment by jayked** [comment]
Check wether you use the same version of the package on both servers. If you don't, try installing the older version (since I think there are a lot of bugs in the most recent version).

**Comment by fencer-md** [comment]
In js file I have subtracted the base path from url variable, and I got my result.
 
It's just weird thing that the same package just gave me the different result, and I suppose that logic would be to add the path to the file and not full URL.

**Comment by nasirkhan** [comment]
facing the same issue. Previously it was showing the relative path, but now it is showing the complete file path including the domain. It might be happening after updating the version.

**Comment by 7ammer** [comment]
Same here

**Comment by fencer-md** [comment]
Not sure if this is the best solution although it works for me:

replace last function in lfm.js with this one

```
function SetUrl(url){
    //set the value of the desired input to image url
    //  alert(window.location.protocol + "//" + window.location.host)
    url = url.replace(window.location.protocol + "//" + window.location.host+"/","/");
    let target_input = $('#' + localStorage.getItem('target_input'));
    target_input.val(url);
    //set or change the preview image src
    let target_preview = $('#' + localStorage.getItem('target_preview'));
    target_preview.attr('src',url);

}
```

**Comment by fencer-md** [comment]
Also if someone needs this I have created button for deleting the selected image from input and preview

HTML

```
<div class="form-group">
                        <div class="input-group col-md-10 col-md-offset-2">
                                            <span class="input-group-btn">
                                                <a id="lfm" data-input="image" data-preview="holder" class="btn btn-primary">
                                                    <i class="fa fa-picture-o"></i> Choose
                                                </a>
                                          </span>
                            <input name="image" id="image" class="form-control" type="text" readonly>
                                          <span class="input-group-btn">
                                            <a id="delete" data-input="thumbnail" data-preview="holder" class="btn btn-danger">
                                                <i class="glyphicon glyphicon-remove"></i>
                                            </a>
                                      </span>
                        </div>
                        <div class="col-md-10 col-md-offset-2"><span class="help-block">Image of the product, Sugested dimesion is 600 x 600</span></div>

                        <img id="holder" class="col-md-offset-2" style="margin-top:15px;max-height:100px;">
                    </div>
```

JS

```
 $('#delete').click(function(){
                $('input#image').val('')
                $('img#holder').attr('src','')
            })
```

**Comment by leanweb** [comment]
File Manager gets the path by calling the asset() helper in Blade... which is supposed to return the full path... 

**See script.blade.php...**
```
var image_url     = "{{ asset(Config::get('lfm.images_url')) }}";
var file_url      = "{{ asset(Config::get('lfm.files_url')) }}";
```
So the expected behaviour is to return the full path and not a relative path...

If you want a relative path, remove the call to asset, that will return only the configuration value for images_url or files_url as per your lfm.php configuration file...

**Comment by nasirkhan** [comment]
any update on this issue?

**Comment by g0110280** [comment]
Solved in 01e64d6, `script.blade.php` as @leanweb suggested.

**Comment by 7ammer** [comment]
I'm having this issue again: v1.7.1

```
[
...
    'base_directory' => 'public',

    'images_folder_name' => 'storage/general-photos',
    'files_folder_name'  => 'storage/general-files',

    'shared_folder_name' => 'shares',
    'thumb_folder_name'  => 'thumbs',
...
]

```

**Comment by rahmat2222** [comment]
same issue at v1.7.1

**Comment by g0110280** [comment]
Done in `v2.0.0-alpha`.

**Comment by frnaky-op** [comment]
To get the full path:
**from**  /photos/shares/Clients/57c4324a23d0f.png
**to** http://localhost:8000/photos/shares/Clients/57c4324a23d0f.png
you need to change **file_path** in your **lfm.js**  inside **vendor/laravel-filemanager/js/lfm.js** 
**from** => target_input.val(**file_path**).trigger('change');
**to** => target_input.val(**url**).trigger('change');

**Comment by utsavDave97** [comment]
> To get the full path:
> **from** /photos/shares/Clients/57c4324a23d0f.png
> **to** http://localhost:8000/photos/shares/Clients/57c4324a23d0f.png
> you need to change **file_path** in your **lfm.js** inside **vendor/laravel-filemanager/js/lfm.js**
> **from** => target_input.val(**file_path**).trigger('change');
> **to** => target_input.val(**url**).trigger('change');

cannot find **lfm.js**

**Comment by hasanibrahim2** [comment]
Hi, I have made a simple JS*modify for this. Can see in: [https://github.com/UniSharp/laravel-filemanager/issues/288#issuecomment-770242910](url)

> copy **unisharp/laravel-filemanager/public/** to the project's vendor directory._This will help to protect from composer update._
> Change the setUrl function from "laravel-filemanager/js/stand-alone-button.js" as below:
> ..
> ..
> ```
>  window.SetUrl = function (items) {
>                 var file_path = items.map(function (item) {
>                     return "/storage/" + item.url.split("storage/")[1];
>                 }).join(','); 
> ```
> ..
> ..
