### ISSUE TITLE
Dynamic Folder Name Change for Multi Tenancy

### ISSUE THREAD

**Issue by mrtsglk** [UniSharp/laravel-filemanager#1188]
I can change the folder names via the lfm.php file. But how can I dynamically change this folder name?

What I want to do:

folder_name = tenant('id').'/photos';

But when I call the tenant id in the config file, it is empty. The package I am using is tenancyforlaravel.com

**Comment by mrtsglk** [comment]
I added TenancyInitialized in listener.

**Comment by BechirAhmed** [comment]
How? Can you explain your approach?
