### ISSUE TITLE
Not compatible with intervention/image 3

### ISSUE THREAD

**Issue by mshahrestani** [UniSharp/laravel-filemanager#1210]
Laravel version : 10.41
Intervention/Image version: 3.3

 Problem 1
    - unisharp/laravel-filemanager[0.5.1, ..., 0.5.3, 1.0.0, ..., v1.9.2, v2.0.0, ..., v2.6.4] require intervention/image 2.* -> found intervention/image[2.0.0, ..., 2.7.2] but it conflicts with your root composer.json require (^3.3).
    - Root composer.json requires unisharp/laravel-filemanager * -> satisfiable by unisharp/laravel-filemanager[0.1.0, ..., 0.5.3, 1.0.0, ..., v1.9.2, v2.0.0, ..., v2.6.4].

**Comment by 4nd114** [comment]
I have the same problem

**Comment by streamtw** [comment]
For anyone encounter this issue, please update `unisharp/laravel-filemanager` to `v2.7.0`.

**Comment by streamtw** [comment]
Update: `v2.9.0` has been released to fully support `v3.*` versions of `intervention/image`.
