### ISSUE TITLE
Undefined method Error

### ISSUE THREAD

**Issue by Samvdg** [UniSharp/laravel-filemanager#1212]
* Operating system : Debian 11
 * Laravel version : 9
 * Package version : 2.7.0
 * Steps to reproduce your issue : Get an error (rename a file to the same name for example)

I feel like my version of the package is missing something after an update?
Suddenly parent::error doesn't work anymore in for example the renameController at line 43.

The static error function is gone? And since there are no other tickets opened with this issue i wonder if i did something wrong?

**Comment by Samvdg** [comment]
I havent messed around inside of the package locally. The only thing i have done is override the demo route in my web.php but even if i use the package routes or reinstall the package from scratch, it doesn't seem to work.

**Comment by tanero** [comment]
parent:error function comes from LfmController.php, and seems been removed by package maintainer.  But no fix yet.

related issue, [#1142](https://github.com/UniSharp/laravel-filemanager/issues/1142)

**Comment by Samvdg** [comment]
I'm sorry to tag you @streamtw but i believe you're the main person left working on this project and i was wondering about your opinion about this issue

**Comment by streamtw** [comment]
Sorry for late reply. I have reproduced this issue on my end.
The `error` function may be deleted because I falsely thought it was a redundant function.
I will release a fixed version today.

**Comment by Samvdg** [comment]
All good! Glad it's getting fixed!

**Comment by streamtw** [comment]
`v2.7.1` has been released to fix this issue. Please run `php artisan vendor:publish --force --tag=lfm_public` and `php artisan vendor:publish --force --tag=lfm_view` after upgrading to `v2.7.1`.
