### ISSUE TITLE
Missing parent::error method at LfmController

### ISSUE THREAD

**Issue by tanero** [UniSharp/laravel-filemanager#1214]
Some of the controllers calls parent:error() (UniSharp\LaravelFilemanager\Controllers\DeleteController or RenameController) method but parent (LfmController) has no error method.

And provide the followings :
 * Operating system : Linux 
 * Laravel version : 10
 * Package version : 2.7.0
 * Steps to reproduce your issue : delete a folder with images, then error occur.
 * Screenshots of browser console :

**Comment by Samvdg** [comment]
This is a pretty critical bug. It throws a very easily fixable exception for a function that doesn't exist anymore for some reason. Litteraly when you rename something and then don't change the name, this exception pops up.

**Comment by streamtw** [comment]
Related to #1142 .

**Comment by streamtw** [comment]
`v2.7.1` has been released to fix this issue. Please run `php artisan vendor:publish --force --tag=lfm_public` and `php artisan vendor:publish --force --tag=lfm_view` after upgrading to `v2.7.1`.
