### ISSUE TITLE
Larave File Manager version 2.6.4 does not support .gif files

### ISSUE THREAD

**Issue by daktaritech** [UniSharp/laravel-filemanager#1218]
Laravel file manager does not support .gif files for versions 2.6> 

![Screenshot 2024-02-26 101135](https://github.com/UniSharp/laravel-filemanager/assets/154595623/6b71a62d-1bb5-4a17-851f-c7e39ce0bd44)
![Screenshot 2024-02-26 101147](https://github.com/UniSharp/laravel-filemanager/assets/154595623/f2dd543c-74ca-4e8f-85e8-fdc5973f3aa5)

 * Operating system : Windows 11 Home 22H2, BUILD: 22621.3085
 * Laravel version :^9.19
 * Package version : 2.6.4
 * Steps to reproduce your issue : Upload a new gif file on laravel file manager
 * Screenshots of browser console :
 
![Screenshot 2024-02-26 101553](https://github.com/UniSharp/laravel-filemanager/assets/154595623/da477da1-e9e8-4633-ad81-7da9a1807598)

**Comment by Samvdg** [comment]
Gotta change this in your config settings my friend. By default it doesn't but you can allow it to

**Comment by streamtw** [comment]
Here is the related [document](https://unisharp.github.io/laravel-filemanager/config#folder_categories), by configuring `valid_mime`, you can customize what types of file can be uploaded. You can also see this [mime type list](https://docs.w3cub.com/http/basics_of_http/mime_types/complete_list_of_mime_types) to find out the corresponding values to fill in.

**Comment by daktaritech** [comment]
i added:  
![Screenshot 2024-02-28 141016](https://github.com/UniSharp/laravel-filemanager/assets/154595623/f8984407-a15b-4d16-92b5-c58425d372c8)
in both image and folder_categories, ran
php artisan cache:clear 
php artisan config:clear

now it works fine!  Thanks.
