### ISSUE TITLE
Class \"Intervention\\Image\\Facades\\Image\" not found

### ISSUE THREAD

**Issue by alnefely** [UniSharp/laravel-filemanager#1220]
On uplade Any Images show this error 
Class \"Intervention\\Image\\Facades\\Image\" not found
![Screenshot 2024-02-28 191924](https://github.com/UniSharp/laravel-filemanager/assets/68406210/0a937b5f-ec64-4420-9ca7-ff31b1313a3b)
![Screenshot 2024-02-28 192015](https://github.com/UniSharp/laravel-filemanager/assets/68406210/aa55f138-3901-4722-b4b0-7ea65d7c4747)

**Comment by dreigningking** [comment]
I am experiencing this issue too.. just today

**Comment by streamtw** [comment]
Looks like there is some API changes in `v3.x` versions of `intervention/image`. I will take some time updating the integration with `intervention/image`.

**Comment by MeeDNite** [comment]
Hi,
If we use intervention/image-laravel instead of intervention/image, we can upgrade this easily with some simple changes.
@streamtw

**Comment by streamtw** [comment]
Update: `v2.9.0` has been released to fully support `v3.*` versions of `intervention/image`.
