### ISSUE TITLE
Not compatible with Laravel 11

### ISSUE THREAD

**Issue by aarreedd** [UniSharp/laravel-filemanager#1222]

**Comment by streamtw** [comment]
I noticed that Laravel 11 introduces a lot of changes in directory structure. I am going to take some time trying a fresh install on Laravel 11 before releasing a new version of this package.

**Comment by streamtw** [comment]
`v2.8.0` has been released to support Laravel 11. All installation steps stay the same. Please let me know if there is any compatibility issue.
