### ISSUE TITLE
"Class \"Intervention\\Image\\Facades\\Image\" not found" on Laravel 11 and laravel-filemanager 2.8

### ISSUE THREAD

**Issue by alfikridotname** [UniSharp/laravel-filemanager#1224]
On upload Any Images show this error
Class \"Intervention\\Image\\Facades\\Image\" not found

![image](https://github.com/UniSharp/laravel-filemanager/assets/5585020/97c04b7d-4ac3-4830-8fee-139823a69c1b)
![image](https://github.com/UniSharp/laravel-filemanager/assets/5585020/282181e9-8be8-4ecb-a6f8-98df652b70b4)

thanks

**Comment by streamtw** [comment]
This is related to #1211 , while installing `intervention/image:v3` is possible, it contains breaking changes that make it not backward compatible. Please use `v2.x` of `intervention/image` for now.

**Comment by alfikridotname** [comment]
Thank You
After I tried downgrading to version intervention/image 2.7, it finally worked

**Comment by MeeDNite** [comment]
I have created a PR for this. hope @streamtw reviews it.
#1226

**Comment by streamtw** [comment]
Update: `v2.9.0` has been released to fully support `v3.*` versions of `intervention/image`.

**Comment by nasirkhan** [comment]
> Update: `v2.9.0` has been released to fully support `v3.*` versions of `intervention/image`.

Please mark the v2.9.0 as the latest release, it still shows 2.8.1 as the latest. 

![image](https://github.com/UniSharp/laravel-filemanager/assets/396987/9f43d421-d304-4210-8066-2f6d2078edcd)

**Comment by streamtw** [comment]
@nasirkhan it is done now. Thanks for the notice.
