### ISSUE TITLE
Logs left in code

### ISSUE THREAD

**Issue by Samvdg** [UniSharp/laravel-filemanager#1229]
So there is 2 places where 'Log::' gets used

In UploadController : 38
and LfmPath : 235

In uploadcontroller we log an error. This messes with my bugreporting tool. Is this still necessery here? We throw exceptions everywhere else. In case this is intended, i will look for a different workaround but it doesn't immediately seem like this piece of code should be here.

**Comment by streamtw** [comment]
These two logs are left intentionally, to avoid the anti-pattern: "Error should never pass silently".

But if it troubles you, I think maybe using another logging channel setting in `config/logging.php` may solve it. How do you think?

**Comment by Samvdg** [comment]
Good to know, thank you!
This makes sense. I will check out `logging.php`, thank you for the suggestion!
