### ISSUE TITLE
get full url

### ISSUE THREAD

**Issue by dickyeka** [UniSharp/laravel-filemanager#123]
this my output wen im save data 
`<img src="/photos/5/246-1440032744.png" alt="" width="223" height="262" />`
I want`<img src="http://localhost:8000/photos/5/246-1440032744.png" alt="" width="223" height="262" />`

becasue whe im show in view broken link

**Comment by g0110280** [comment]
This is related to #117,  and this package should always return relative path.
However, you can modify `resources/vendor/laravel-filemanager/script.blade.php` to change this behavior.

**Comment by Pashaster12** [comment]
I can't find the file `resources/vendor/laravel-filemanager/script.blade.php` after installation 1.8.4 version of the laravel-filemanager. What should I do to make absolute url after image upload instead of the relative?

**Comment by hlaingbhwar** [comment]
yes im show in view broken link ????

**Comment by hlaingbhwar** [comment]
this my output wen im save data
<img src="/photos/5/246-1440032744.png" alt="" width="223" height="262" />
I want<img src="http://localhost:8000/photos/5/246-1440032744.png" alt="" width="223" height="262" />

becasue whe im show in view broken link

source code img full url borken
