### ISSUE TITLE
Class "Intervention\Image\Laravel\Facades\Image" not found

### ISSUE THREAD

**Issue by nasirkhan** [UniSharp/laravel-filemanager#1230]
Installed the latest version (v2.9). when I tried to update any file it showed the following error. 

```php
Class "Intervention\Image\Laravel\Facades\Image" not found {"file":"C:\\wamp64\\www\\laravel\\laravel-starter-2024\\vendor\\unisharp\\laravel-filemanager\\src\\LfmPath.php","line":332,
```

And provide the followings :
 * Operating system : Windows 11
 * Laravel version : 11
 * Package version : 2.9
 * Steps to reproduce your issue : 
 * Screenshots of browser console :

**Comment by streamtw** [comment]
Sorry for your trouble. I have updated [installation document](https://unisharp.github.io/laravel-filemanager/installation) and added instructions for installing with `v3.*` of `intervention/image`.

**Comment by webservice96** [comment]
> Sorry for your trouble. I have updated [installation document](https://unisharp.github.io/laravel-filemanager/installation) and added instructions for installing with `v3.*` of `intervention/image`.

Yes now is working.

**Comment by nasirkhan** [comment]
new doc solves the issue. thanks.
