### ISSUE TITLE
not https if im embed youtube 

### ISSUE THREAD

**Issue by dickyeka** [UniSharp/laravel-filemanager#124]
`<iframe width="560" height="315" src="www.youtube.com/embed/vBzg0Us5MDk" frameborder="0" allowfullscreen></iframe>`

**Comment by g0110280** [comment]
@dickyeka What did you mean?
This package does not contain any features about embed videos.

**Comment by g0110280** [comment]
Feel free to re-open this issue if you need further discuss.

**Comment by hlaingbhwar** [comment]
<iframe width="560" height="315" src="www.youtube.com/embed/vBzg0Us5MDk" frameborder="0" allowfullscreen></iframe>

yes i not working
