### ISSUE TITLE
Upload Works, but not list files in file manager

### ISSUE THREAD

**Issue by rafalau** [UniSharp/laravel-filemanager#126]
Hello, follow the installation steps but the files are not listed in the file manager. I am using Laravel 5.1 + laravelcollective / html 5.1 + intervention / image 2.3.8.
![captura de tela 2016-09-30 as 09 56 32](https://cloud.githubusercontent.com/assets/15903589/18992508/0ec522c8-86f5-11e6-89cd-ed8d9f2b9a31.png)

**Comment by leanweb** [comment]
Difficult to help with so little info... How did you integrate it to your view?

**Comment by g0110280** [comment]
@rafalau Please post the errors in your chrome console here, thanks.

**Comment by Shahaan143** [comment]
Same error for me and whenever i tried to create new folder i go the attach error in console but file upload works fine
<img width="1280" alt="screen shot 2016-11-07 at 4 25 40 am" src="https://cloud.githubusercontent.com/assets/9671584/20042811/463eb2ee-a4a2-11e6-865f-fefb152a5f9b.png">

**Comment by Shahaan143** [comment]
@g0110280 @leanweb please help me with this issue ASAP please

**Comment by g0110280** [comment]
@Shahaan143 the error you see was due to code [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/script.blade.php#L34), please check the lang file for your locale.
