### ISSUE TITLE
Add ability to select multiple images

### ISSUE THREAD

**Issue by 7ammer** [UniSharp/laravel-filemanager#128]
It would be great if we could have the ability to select multiple images which would then output as an array.

**Comment by g0110280** [comment]
Done in #97, will be released in v1.6.3 .

**Comment by g0110280** [comment]
Apologies, #97 deals with uploading multiple files. This feature will be in v1.6.4 or v1.7 .

**Comment by g0110280** [comment]
Done in fbe9689.
