### ISSUE TITLE
Integrate with AWS S3

### ISSUE THREAD

**Issue by alvaropeso97** [UniSharp/laravel-filemanager#134]
Hello,
i need to integrate the laravel-filemanager with my AWS S3 server.
Thanks

**Comment by g0110280** [comment]
Hello @alvaropeso97 , you can try integrate this pkg with [fileapi](https://github.com/UniSharp/laravel-fileapi), another UniSharp pkg which supports S3. This is also included in our v2.0 milestone.

**Comment by g0110280** [comment]
Related to #80 .
