### ISSUE TITLE
How to upload both images and files?

### ISSUE THREAD

**Issue by angusho223** [UniSharp/laravel-filemanager#135]
According to the setting, I can upload image successfully but cannot upload pdf file. It will show "Unexpected mime type error". I also check the $this->file_type inside LfmController, it always equals 'iamge'. I am not understand the part in CKEditor. How to change the url among the 4 urls?

Thank you very much.

**Comment by jayked** [comment]
What are the exact steps you make that give you this error? Please give some screenshots.

**Comment by angusho223** [comment]
Thank you for your reply.

I just click upload and upload a pdf file, it gives the error.
![screen1](https://cloud.githubusercontent.com/assets/19291295/19643818/ede3a9a2-9a1e-11e6-8453-63b50dc523e1.JPG)
![screen2](https://cloud.githubusercontent.com/assets/19291295/19643823/f274d0e0-9a1e-11e6-95d1-947947ed1cc0.JPG)

**Comment by g0110280** [comment]
Be sure to set mime types you want in config. See [here](https://github.com/UniSharp/laravel-filemanager/blob/master/doc/config.md).

**Comment by angusho223** [comment]
Thank you for your help. I understand much more about my problem.
Furthermore, how can I change the upload request url from '/laravel-filemanager?type=Images' to '/laravel-filemanager?type=Files' ?

**Comment by g0110280** [comment]
[Doc](https://github.com/UniSharp/laravel-filemanager/blob/master/doc/integration.md#option-1-ckeditor) here, you can see the urls as you described and change all 'Images' to 'Files'.

**Comment by angusho223** [comment]
Thank you for your reply.

I can upload pdf files without error message by hard code the type with 'Files'
![screen4](https://cloud.githubusercontent.com/assets/19291295/19672887/1462856a-9aad-11e6-9d56-a7dacd47297f.JPG)

However, the image features which are resize, crop and thumbnail preview had gone.
![screen6jpg](https://cloud.githubusercontent.com/assets/19291295/19672933/7ac95126-9aad-11e6-8a0c-b679d8ec5d33.JPG)

This is the screen shot for the original which is the type equals image
![screen5](https://cloud.githubusercontent.com/assets/19291295/19672947/9bf044c2-9aad-11e6-8721-ddbb71fd2762.JPG)

Are there any solutions to keep the image features such as thumbnail and crop, at the same time to upload pdf files?

Thank you for your attention.

**Comment by g0110280** [comment]
You can modify this [blade](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/item.blade.php) in `resources/views/vendor/laravel-filemanager`, to fix the broken file icon in image view.

**Comment by drakakisgeo** [comment]
It would be great to have a global array with supporting Mime types. In my case I would like to have thumbnails (and preview) for images  and a generic one for any other type ( zip, doc, txt, pdf etc.)

**Comment by g0110280** [comment]
v1.7-alpha has been released. The solution will be to simply use "File mode".

**Comment by hermawanheri66** [comment]
"File mode" where location folder?  @g0110280

**Comment by g0110280** [comment]
@hermawanheri66 See configs [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/config/lfm.php#L35).
