### ISSUE TITLE
Delete folders !

### ISSUE THREAD

**Issue by smartdeath** [UniSharp/laravel-filemanager#137]
I have problem with delete folder . This is my delete url " uploads/files/shares/sharesa not found! " .
But that's not true because added "shares" before my folder name .

**Comment by smartdeath** [comment]
I fix that . How ? 
Create a new method for getFolderName in LfmController.
    private function getFolderName($folder)
    {
        $lfm_dir_start = strpos($folder, $this->file_location);
        $working_dir_start = $lfm_dir_start + strlen($this->file_location);
        $lfm_file_path = substr($folder, $working_dir_start);
        $arr_dir = explode('\\', $lfm_file_path);
        $arr_foldername['short'] = end($arr_dir);
        $arr_foldername['long'] = '/' . $lfm_file_path;
        return $arr_foldername;
    }

**Comment by smartdeath** [comment]
Oh god this problem is windows . 👎

**Comment by g0110280** [comment]
Fixed in 0fa6cc4.
