### ISSUE TITLE
Error 500 on last release

### ISSUE THREAD

**Issue by welcoMattic** [UniSharp/laravel-filemanager#14]
I caught error 500 on `/laravel-filemanager` route since last release.
No more information, sorry. 

Investigate on last PR ;)

**Comment by welcoMattic** [comment]
Not sure is a package issue.

**Comment by welcoMattic** [comment]
Ref #15

**Comment by g0110280** [comment]
I just merged #15.
Please let me know whether it solves your issue.

**Comment by welcoMattic** [comment]
It works, but only with `dev-master#5a8e244` on my composer.json
May be we have to tag a minot release (bugfix) `1.0.1`?

**Comment by youchenlee** [comment]
@welcoMattic 
Thanks! Bump to [1.1.0](https://github.com/UniSharp/laravel-filemanager/releases/tag/1.1.0)

**Comment by welcoMattic** [comment]
Perfect timing for my last preprod deploy of the week!
Thanks :wink:

**Comment by youchenlee** [comment]
You are welcome, have a nice weekend!
