### ISSUE TITLE
How to upload files

### ISSUE THREAD

**Issue by steven-v** [UniSharp/laravel-filemanager#140]
I'm obviously missing something here... I can upload images, but how do I upload files?
If I click the img icon and -> browse server it automatically adds type=Images, so I assumed if I would click the img icon -> upload tab -> send to server it would use the type=Files but apparently not since it returns Unexpected MimeType: application/pdf.

Can anyone point me in the right direction?

**Comment by g0110280** [comment]
In both CKEditor and TinyMCE, click the link button(hyper link icon), and then click "Browse server" button.
The error you receive was due to the settings of `valid_file_mimetypes` in `config/lfm.php` .
Feel free to create new issues if you encounter new ones.
