### ISSUE TITLE
How to create folders according to database

### ISSUE THREAD

**Issue by taishi06** [UniSharp/laravel-filemanager#144]
Hi,

I am trying to develop a CMS that will work with more than one database. I would like to know if there's a way I can use a specific folder for a specific database connection, based from a session data?

I know that there is an option for multi user, but I would like to know if its possible for multi database connections?

Thanks!

**Comment by g0110280** [comment]
This package only deals with files in the server, does not contain any code related to database for now.

**Comment by g0110280** [comment]
@taishi06 I get your point now. This is related to #19. Can you see if what you think matches @youchenlee 's idea?

**Comment by g0110280** [comment]
In `v1.7.2`, edit config : `user_field`. It can now accept a closure.
