### ISSUE TITLE
class unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider not found

### ISSUE THREAD

**Issue by mh-jamil** [UniSharp/laravel-filemanager#145]
Hi,

I'm using L 5.2, and while installing this package when I did: 

`php artisan vendor:publish --tag=lfm_config`

I've got following error:

![screenshot_1](https://cloud.githubusercontent.com/assets/10434700/20593636/39e3daba-b244-11e6-9447-0acd6362edb3.png)

Any help?

**Comment by mh-jamil** [comment]
I've figured out the issue, thanks

**Comment by ahmedalmulki** [comment]
Please can I know how you solved this problem ?
