### ISSUE TITLE
Display FileManager inside a page (without Editor)

### ISSUE THREAD

**Issue by mh-jamil** [UniSharp/laravel-filemanager#146]
Hi, I want to create a Media page which will show the File Manager. Admin will be able to view, upload, delete or rename images on this page using File Manager.

I have integrated your filemanager successfully, but cannot find a way to display File Manager inside a page. I want to do something like Wordpress's Media page, a dedicated page for File Manager / Media.

Any help please?

**Comment by mh-jamil** [comment]
Just to show an example, this is what I'm trying to do:

![untitled-1](https://cloud.githubusercontent.com/assets/10434700/20646707/aec4d196-b491-11e6-8aa8-4d231e427607.jpg)

**Comment by g0110280** [comment]
Since the apis in filemanager will return HTML of folder tree(left side) and images(right side), you can copy the HTML in `vendor/unisharp/laravel-filemanager/src/views/index.blade.php`, paste it to your page and modify it to fit you site.

**Comment by gwleuverink** [comment]
The approach I tend to take most of the time is to include the file manager as a partial like so:

`@include('admin.partials.file-manager', array('working_dir'=> $working_dir, 'file_type' => $file_type, 'extension_not_found' => $extension_not_found))`

Please note that the partial in the example above is a copy of `vendor/unisharp/laravel-filemanager/src/views/index.blade.php` with a couple of edits to make it fit the styling of my admin view.

Just be sure the parent view can pass the necessary variables to the partial. To do this those variables ($working_dir,  $file_type & $extension_not_found) must be passed from your controller to the parent view. You can find how these variables are fetched and passed to the filemanager in `vendor/unisharp/laravel-filemanager/src/controllers/LfmController.php`

Copy the code inside the constructor in your own controller's constructor and pass the variables to the parent view just like the show() method in the LfmController.php


Another approach is not to copy the code from LfmController but to make a new instance of the LfmController class, access it's public properties and send those to the view in your own controller.

Please note that i'm not sure this is the best way. It's just how I have done it in the past.
@g0110280 What do you think of this method?

**Comment by g0110280** [comment]
@gwleuverink Thanks for your advice. I think the first approach will be easier to fit in @mh-jamil's project.

**Comment by mh-jamil** [comment]
Thanks, I've used @g0110280's method and its working now.

**Comment by blu94** [comment]
can i know how to do this exactly? i don't know how to get these three parameters 'working_dir', 'file_type', 'extension_not_found' although the view are shown normally, but the filemanager display another directory, not the photos directory that i want to show, and the upload lightbox also not shown normally, the lightbox show the upload form and immediately hide it

**Comment by g0110280** [comment]
We should add this to our document.

**Comment by g0110280** [comment]
The document is [here](http://unisharp.github.io/laravel-filemanager/integration#embed-file-manager).
