### ISSUE TITLE
Default view: grid

### ISSUE THREAD

**Issue by maig81** [UniSharp/laravel-filemanager#147]
Hello,
Can I set default view to be grid/list instead of thumbnails? 
I did not see in documentation any mention of this...
Thanks

**Comment by g0110280** [comment]
Add below codes in `resources/views/vendor/laravel-filemanager/script.blade.php` : 
```javascript
$(document).ready(function () {
    $('#thumbnail-display').click();
});
```

**Comment by maig81** [comment]
Worked like a charm! Thanks so much for the quick answer! :)

**Comment by g0110280** [comment]
You are welcome!

**Comment by gwleuverink** [comment]
For a slightly cleaner solution please check out my PR. You can set the preferred view type to load for the file and image manager from the configuration file.

https://github.com/UniSharp/laravel-filemanager/pull/148

**Comment by disney1993** [comment]
i dont have the file script.blade.php
![Captura](https://user-images.githubusercontent.com/26549202/89701967-d5009000-d901-11ea-9c8a-adf81ee89e62.PNG)
how can i do that? sorry by my english

**Comment by maig81** [comment]
I think you are about 4 years too late :) 
The issue was for a far earlier release.
