### ISSUE TITLE
Safe deleting/renaming

### ISSUE THREAD

**Issue by gwleuverink** [UniSharp/laravel-filemanager#149]
Hi,

I was wondering what the best approach is to check if a file path is used in a particular table/column or collection before deleting or renaming them within the filemanager. In the case of renaming it should preg_replace the path in the database field and when deleting it should raise an alert of some kind.

I understand that interacting with the database is not the goal of this package as stated in this question: https://github.com/UniSharp/laravel-filemanager/issues/144

Maybe you have some thoughts on how I can accomplish this. Any input is greatly appreciated.

Thanks!

**Comment by g0110280** [comment]
My idea was to move all current codes from controllers to event listeners. Controllers only fire events. For example, when deleting a file, three events will be fired : pre-delete, deleting, post-delete(event names are just for example too). So developers can abort or throw exceptions before the file was deleted.

Haven't done this before in a package. @gwleuverink How do you think ?

**Comment by gwleuverink** [comment]
I don't have any experience with that either. I have been pondering this feature for a while. As I understand the implementation of listeners in Laravel this might be a great approach. 

I'm wondering tough if a simple middleware might be easier to implement. Breaking backwards compatibility might be less likely to occur since rewriting of the controllers isn't necessary. 

For example:

- The delete and rename controller in their constructor check if a custom middleware was filled in the config/lfm.php file and apply the middleware if specified.
- In the middleware a developer can do whatever check he likes using the get parameters already provided by the request and return an error.
- The error is caught in the response success callback on the frontend and fires a function that displays the error message in a popup of some kind.

Maybe the assigning of the middleware makes more sense in the routes.php file in your package to prevent breaking convention with the existing codebase.


What do you think? Do listeners give more flexibility than this approach? I'm new to the eventing in Laravel and I don't know all the benefits it could give compared to middleware. Also it might be easier for new adopters of the package to get in to since the controllers stay as readable as they are now. (Which is no small feat by the way, nice work on that)

@g0110280 I'm planning on forking the repo and implementing the feature if I have the time but like to know what you think before I start out.

**Comment by youchenlee** [comment]
@gwleuverink, I think it's not about flexibility. It's about its responsibilities. Taking actions before user deleting / updating / renaming a file sounds like a business-level job. It's proper in controllers or event listeners, not middlewares. Middlewares are more likely to handling HTTP requests and responses only.

**Comment by g0110280** [comment]
@gwleuverink Events are now fired before rename/delete actions are performed. An example implementation will be show in [this repo](https://github.com/UniSharp/laravel-filemanager-example-5.3) soon.

**Comment by gwleuverink** [comment]
@g0110280 That's great! I believe this feature greatly improves the value of this package. Looking forward to trying it out soon. Thanks again for the amazing work!
