### ISSUE TITLE
Allow all files types to upload ( No needs validation )

### ISSUE THREAD

**Issue by yubitib** [UniSharp/laravel-filemanager#151]
Hi,

i need to remove validate file mime type, allow all files to upload, how can i do it with UniSharp/laravel-filemanager please help me

thanks

**Comment by g0110280** [comment]
Config should be modified to allow all files to upload. This will be done in v1.6.4 .

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.
