### ISSUE TITLE
Please remove the demo route.

### ISSUE THREAD

**Issue by RushabhJoshi** [UniSharp/laravel-filemanager#152]
Latest laravel 5.3 (though I am also using laravel annotation service) is not supporting routes with closure function.

Thank you

**Comment by pderiy** [comment]
Remove this route, or convert it to class. We can't cache our routes, because closure based routes cannot be cached

**Comment by RushabhJoshi** [comment]
Can you provide me the working example of custom routes in laravel v5.3

It would be nice

**Comment by g0110280** [comment]
Will do this in v1.6.3 .

**Comment by pderiy** [comment]
#157 This PR should fix route caching problem

**Comment by g0110280** [comment]
@pderiy Thank you for this PR.
