### ISSUE TITLE
Can't view /laravel-filemanager

### ISSUE THREAD

**Issue by kfulk14** [UniSharp/laravel-filemanager#154]
When I type in my url mywebsite.com/laravel-filemanager I get redirected to mywebsite.com/auth/login in NotFoundHTTPException in RouteController.php line 161. 
I am using laravel 5.1 any ideas on why this occurring? Thanks

**Comment by gwleuverink** [comment]
Are you logged in tou rour application using the 'auth' guard?

If you want to use the package without authenticating yourself first remove the 'auth' guard from the middlwares in config/lfm.php

Does it work after changing that?

**Comment by kfulk14** [comment]
@gwleuverink thank you for the quick response I commented out the middleware line in the config/lfm.php I am now receiving an error array_merge(): Argument #1 is not an array in routes.php line 2

**Comment by kfulk14** [comment]
@gwleuverink I just created went with using the middleware and creating a new user. Thanks for all the help.
