### ISSUE TITLE
It creates the labels but it doesn't upload the files (in live server)

### ISSUE THREAD

**Issue by cakesforfree** [UniSharp/laravel-filemanager#156]
I am  using laravel 5.3 and I managed to get it working perfectly in the localhost, but when i upload it to a live server (GoDaddy) it works, it creates the labesl but it doesn't upload the images or files.

![fielamanger_no](https://cloud.githubusercontent.com/assets/13759233/21172759/7082b83e-c199-11e6-991e-89d29ec99d49.PNG)

So far, my server is using the PHP 5.6 version
The fileinfo, GD and imagick modules are enabled, 

When I upload the files manually they show up and you can actually use the image:
Example 1:
![image](https://cloud.githubusercontent.com/assets/13759233/21172886/3785e69a-c19a-11e6-8955-4c904c91d890.png)
Example 2:
![image](https://cloud.githubusercontent.com/assets/13759233/21172909/604cb7ca-c19a-11e6-9171-650df5df2d5c.png)

So i don't think that it is about a path problem, but instead an uploading problem, I own the server and the permission in those folders ('photos/shares/thumbs') are all 755

**Comment by cakesforfree** [comment]
![image](https://cloud.githubusercontent.com/assets/13759233/21184243/2c297e38-c1d1-11e6-8d35-4200959e50e5.png)
OMG... that was it.

**Comment by cakesforfree** [comment]
Since in your localhost your main folder is the App folder,the filemanager starts looking and uploading as soon as it findes the "public" folder, but in live server, your main is the folder created in the html_public, so you need to change the 

![image](https://cloud.githubusercontent.com/assets/13759233/21184442/274ebb66-c1d2-11e6-814d-d6259f8f68e4.png)

to whatever it is yours: 
(in my case) 
![image](https://cloud.githubusercontent.com/assets/13759233/21184427/1345b84a-c1d2-11e6-8237-07edff2a38f4.png)

It is that simple, thank you to all of you do

@taswler the original author.
@olivervogel for the awesome image library
@welcoMattic providing fr translations and lots of bugfixes.
@fraterblack TinyMCE 4 support and pt-BR translations.
@1dot44mb tr translations.
@Nikita240 fixing controller extending errors.
@amin101 guide for independent use and fixes for url/directory error on Windows
@nasirkhan bug fixes and alphanumeric filename check
@petyots Bulgarian translation
All @UniSharp members

It works b-e-a-u-t-i-f-u-l

**Comment by cakesforfree** [comment]
For those whiling to upload the project to a live server, in the lfm.php config file you are going to have to use something like this
![image](https://cloud.githubusercontent.com/assets/13759233/21189526/9b0931dc-c1e4-11e6-8d51-822d31eb3cce.png)

becase if you leave only public/photos or public/files it is going to upload the files into the root folder, not the one that is in the public_html server

**Comment by johnef** [comment]
found the solution [here](https://unisharp.github.io/laravel-filemanager/config#working-directory)
