### ISSUE TITLE
Customize view templates

### ISSUE THREAD

**Issue by RushabhJoshi** [UniSharp/laravel-filemanager#158]
is there any way to style laravel file manager views according to my themes?

**Comment by gwleuverink** [comment]
Did you publish the assets? You can go wild as long as you leave all the important parts intact. Just don't edit anything in the root/vendor/Unisharp directory or you'll have trouble with future updates.

**Comment by RushabhJoshi** [comment]
Thank you,

Sometimes I forgot RTFM
