### ISSUE TITLE
Unable to read image from file

### ISSUE THREAD

**Issue by RushabhJoshi** [UniSharp/laravel-filemanager#161]
Whenever I upload pdf it shows this error

![screen shot 2016-12-28 at 11 27 00 am](https://cloud.githubusercontent.com/assets/5484018/21514940/ecdd71aa-ccf0-11e6-84de-b44d5f56a753.png)

**Comment by g0110280** [comment]
PDF files should not be uploaded when parameter `type` is set to `Images`. However, error page like this should not be seen, neither. Thanks for reporting this.

**Comment by RushabhJoshi** [comment]
FYI this error occurs when type is Files. May be it easy for you to track down

**Comment by g0110280** [comment]
@RushabhJoshi This is fixed in e73f389. Please update and check it.
