### ISSUE TITLE
Folder name is not correct in Windows

### ISSUE THREAD

**Issue by Wayne-Wen** [UniSharp/laravel-filemanager#163]
The folder list in Windows is different from Linux.  For example, I got "shares\thumbs" when I open "http://localhost:27007/laravel-filemanager?type=Images". In Linux ,this folder should be hidden. 

After I created a folder called "test-folder", it will show "shares\test-folder", and I cannot deleted this folder in Windows.  While in Linux, it shows "test-folder" without "shares\" and can be deleted.

I have checked the code and found out that Linux directory separator "/" is used in "getFileName" function, which will cause problem in Windows.

Are you going to add support for Windows??

**Comment by g0110280** [comment]
This is related to #137 .

**Comment by g0110280** [comment]
Plenty of functions need to apply `realpath()` function to handle directory separator issue. This will be done in v1.6.4 .

**Comment by g0110280** [comment]
Fixed in 0fa6cc4. Please update and check it.

**Comment by g0110280** [comment]
v1.7-alpha has been released, closing issue now.
