### ISSUE TITLE
page content is not updated

### ISSUE THREAD

**Issue by Wayne-Wen** [UniSharp/laravel-filemanager#164]
1. When you upload a file with success, the modal will close, but when you click the "Upload" button again, the modal will open, and last uploaded file is still there. I think you need to clear that file input's value after user have upload successfully.

2. After cropping an image, the thumbnails view is not updated. Even you click the "Crop" button again, the view showing is still an old one,  which looks like your cropping is failed, in fact it isn't. I know it is about browser's cache, but I think this should be fixed, cause you cannot let user keep using "Ctrl+F5" to refresh the file-manager's view after cropping.

**Comment by g0110280** [comment]
The first issue is fixed in `dev-master`. The second issue will be fixed in v1.6.4 .

**Comment by g0110280** [comment]
The second issue is fixed in #183 .
