### ISSUE TITLE
S3 file system as disk support?

### ISSUE THREAD

**Issue by maorkavod** [UniSharp/laravel-filemanager#165]
Hello,
i am using AWS S3 as my file system with **League\Flysystem\Filesystem**
so AWS S3 is my "disk" actually.
how can i use the file manager with s3 directory? 
is this possible with this package?

**Comment by g0110280** [comment]
Related to #80 , cloud storage support is in our v2.0 milestone.

**Comment by mitjarobic** [comment]
Do you know when is the v2.0 milestone planned?

**Comment by drfenixion** [comment]
> Do you know when is the v2.0 milestone planned?
I interesting too.

**Comment by maorkavod** [comment]
no, 
but i build it from scretch in my project, preaty easy.. 
just download some open source php file manager and developed the upload,delete,update function to use with s3 with class League\Flysystem\Filesystem;

**Comment by pepijnolivier** [comment]
@maorkavod Would you care to PR ? :)

**Comment by imlunek** [comment]
I have tried v2.0 alpha version but I don't feel like s3 is working. Does anyone here know how to setup s3 with v2.0?
