### ISSUE TITLE
Upload images doesn't appear in list and filesystem

### ISSUE THREAD

**Issue by GertTimmerman** [UniSharp/laravel-filemanager#166]
I have installed a new site for my client on his server. Uploading images does work locally, but on the server uploading images does not work. I can select an file, i can make a new directory and can upload a file, i see the loading image, the upload endpoint returns a 200 statuscode, but the file was not uploaded, i can't see the file in the filesystem and not in the media library. I also don't get any error in my errorlog.

Anyone suggestions?

**Comment by g0110280** [comment]
This doesn't look like permission error, neither. Please provide the version you are using.

**Comment by g0110280** [comment]
Get it now. This is a Windows issue. Figuring this out.

**Comment by g0110280** [comment]
Fixed in 0fa6cc4. Please update and check it.

**Comment by GertTimmerman** [comment]
I get now a new error: ReflectionException·Class Unisharp\Laravelfilemanager\middleware\MultiUser does not exist

**Comment by GertTimmerman** [comment]
Solved, i have a own routes file with old/wrong namespace ..
