### ISSUE TITLE
Unknown mimitype on mac

### ISSUE THREAD

**Issue by fencermd** [UniSharp/laravel-filemanager#169]
Hi, I can't upload anything besides images, all other PDF...... on upload generates the same issue unexpected **Mimetype:aplication/pdf.....**
can you help me with that?
![screen shot 2017-01-16 at 11 13 31](https://cloud.githubusercontent.com/assets/25147971/21976997/019dcaae-dbdd-11e6-81ef-6a55931c6fe3.png)

**Comment by g0110280** [comment]
Please check you config : `lfm.valid_file_mimetypes`, make sure `'application/pdf'` is in the array.

**Comment by fencermd** [comment]
yes it is:

'max_image_size' => 20000000,
    'max_file_size' => 10000000,

    // available since v1.3.0
    'valid_image_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif'
    ],

    // available since v1.3.0
    // only when '/laravel-filemanager?type=Files'
    'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'application/pdf',
        'text/plain',
    ],

    // file extensions array, only for showing file information, it won't affect the upload process.
    'file_type_array'         => [
        'pdf'  => 'Adobe Acrobat',
        'doc'  => 'Microsoft Word',
        'docx' => 'Microsoft Word',
        'xls'  => 'Microsoft Excel',
        'xlsx' => 'Microsoft Excel',
        'zip'  => 'Archive',
        'gif'  => 'GIF Image',
        'jpg'  => 'JPEG Image',
        'jpeg' => 'JPEG Image',
        'png'  => 'PNG Image',
        'ppt'  => 'Microsoft PowerPoint',
        'pptx' => 'Microsoft PowerPoint',
    ],

    // file extensions array, only for showing icons, it won't affect the upload process.
    'file_icon_array'         => [
        'pdf'  => 'fa-file-pdf-o',
        'doc'  => 'fa-file-word-o',
        'docx' => 'fa-file-word-o',
        'xls'  => 'fa-file-excel-o',
        'xlsx' => 'fa-file-excel-o',
        'zip'  => 'fa-file-archive-o',
        'gif'  => 'fa-file-image-o',
        'jpg'  => 'fa-file-image-o',
        'jpeg' => 'fa-file-image-o',
        'png'  => 'fa-file-image-o',
        'ppt'  => 'fa-file-powerpoint-o',
        'pptx' => 'fa-file-powerpoint-o',
    ],

**Comment by gwleuverink** [comment]
Are you using the image manager or the file manager mode?

**Comment by fencermd** [comment]
On file mode, and also on simple mod "/laravel-filamanager" I get this error

**Comment by g0110280** [comment]
v1.7-alpha has been released, please update and check this issue again.

**Comment by fencermd** [comment]
Yes in 1,7 it's OK, hope we will get stable ASAP, thanks!
