### ISSUE TITLE
Error on File upload, Images behaviour executed

### ISSUE THREAD

**Issue by welcoMattic** [UniSharp/laravel-filemanager#17]
I'm trying to upload a .pdf file via the Filemanager popup, but Images behaviour is executed.

It looks like input[name=type] is missing on files view, then `lfm_type` is never set to `Files`.

I'll give more info during my debugging work.

**Comment by youchenlee** [comment]
Thank you @welcoMattic, will check it later.

**Comment by youchenlee** [comment]
Fixed by @g0110280 at fc396b0
Plan for a new release

**Comment by youchenlee** [comment]
Included in https://github.com/UniSharp/laravel-filemanager/releases/tag/1.1.1
