### ISSUE TITLE
pt_PT language support

### ISSUE THREAD

**Issue by anaisabel19886** [UniSharp/laravel-filemanager#170]
translation file: [https://github.com/anaisabel19886/laravel-filemanager-pt_PT](link)

author: @https://github.com/youchenlee

I just adapted it to pt_PT

**Comment by g0110280** [comment]
Please fork our project, create lfm.php for locale, and send a pull request here.

**Comment by g0110280** [comment]
Merged #171.

**Comment by anaisabel19886** [comment]
Here is the pull request link [https://github.com/UniSharp/laravel-filemanager/pull/171](pull request)

(I hope this is what you wanted, I'm a newbie to this..)

**Comment by g0110280** [comment]
Already merge into dev-master, thank you @anaisabel19886 .
