### ISSUE TITLE
Cant upload PDF

### ISSUE THREAD

**Issue by luisbecerra** [UniSharp/laravel-filemanager#173]
Before an update, i can upload pdf correctly, but now is imposible, only is posible to upload images

**Comment by TnCoders** [comment]
Same here
An error has occured: Internal Server Error

And Laravel Exception
1/1
NotReadableException in Decoder.php line 20:
Unable to read image from file

**Comment by g0110280** [comment]
v1.7-alpha has been released, please update and check this issue again.

**Comment by g0110280** [comment]
Working fine in `v1.7-alpha`, closing issue now.
