### ISSUE TITLE
Standalone button 404 error

### ISSUE THREAD

**Issue by dolphintr** [UniSharp/laravel-filemanager#174]
Hi
Click on the  
 Standalone button and I get 404 error.

Create a button, input, and image preview holder if you are going to choose images.

Specify the id to the input and image preview by data-input and data-preview.

    <div class="input-group">
      <span class="input-group-btn">
        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
          <i class="fa fa-picture-o"></i> Choose
        </a>
      </span>
      <input id="thumbnail" class="form-control" type="text" name="filepath">
    </div>
    <img id="holder" style="margin-top:15px;max-height:100px;">

Import lfm.js(run php artisan vendor:publish if you need).
    <script src="/vendor/laravel-filemanager/js/lfm.js"></script>

Init filemanager with type. (requires jQuery)
    $('#lfm').filemanager('image');

<a href='https://postimg.org/image/rzxm7y6xt/' target='_blank'><img src='https://s24.postimg.org/rzxm7y6xt/image.png' border='0' alt='postimage'/></a>
Thanks

**Comment by g0110280** [comment]
v1.7-alpha has been released, please update and do the following :
```
$('#lfm').filemanager('image', {prefix: "localhost/blog/public"});
```

**Comment by g0110280** [comment]
`v1.7.0` has released. Closing issue now.
