### ISSUE TITLE
how to change permisan in localhost ? Xampp server ?

### ISSUE THREAD

**Issue by Pravinslk** [UniSharp/laravel-filemanager#175]
can anyone explain this
4.Ensure that the files & images directories (in config/lfm.php) are writable by your web server.?

still im getting this error https://drive.google.com/open?id=0B79G7jjMOBkmM0xyc3lEMHZmQnM

**Comment by TnCoders** [comment]
Where is the Error ?

**Comment by TnCoders** [comment]
To make the parent directory as well as all other sub-directories writable, just add -R
chmod -R a+w <directory> in your Command line
