### ISSUE TITLE
Thumbs folder issue on MS Windows

### ISSUE THREAD

**Issue by Pejic88** [UniSharp/laravel-filemanager#18]
I have a problem with thumbs folder since it's listed along with images.
I saw in the code that this folder shouldn't be listed, but it's.
```php
public function getDirectories($path)
    {
        $thumb_folder_name = Config::get('lfm.thumb_folder_name');
        $all_directories = File::directories(base_path($path));

        $arr_dir = [];

        foreach ($all_directories as $directory) {
            $dir_name = $this->getFileName($directory);

            if ($dir_name !== $thumb_folder_name) {
                $arr_dir[] = $dir_name;
            }
        }

        return $arr_dir;
    }
```
![screenshot_2](https://cloud.githubusercontent.com/assets/2436669/12027695/9ef5f1b0-adca-11e5-9bff-c98b43a96533.png)

**Comment by Pejic88** [comment]
When I go to the thumbs dir, I can't see thubmnail images.
![screenshot_22](https://cloud.githubusercontent.com/assets/2436669/12027700/bd5e6182-adca-11e5-8949-b28969b95a27.png)

**Comment by g0110280** [comment]
Did you set "thumb_folder_name" to "\thumbs" in config/lfm.php?

**Comment by Pejic88** [comment]
No, I didn't. It's "thumbs", as by default setup.

**Comment by youchenlee** [comment]
@Pejic88 Is your server under Microsoft Windows? If so, we haven't tested it on Windows. This might be a bug, I will check it later.

**Comment by Pejic88** [comment]
Yes, I'm using WAMP server under Microsoft Windows. Tnx and please, let me know if you find a fix for this :smiley:

**Comment by Pejic88** [comment]
Since this was on my local machine, I test this on my dev server, which is on Linux and there's no problem with thumbs

**Comment by youchenlee** [comment]
@Pejic88 Would you please check if version [1.4.0-alpha](https://github.com/UniSharp/laravel-filemanager/releases/tag/1.4.0-alpha) has this issue fixed on Windows?

**Comment by g0110280** [comment]
Tested today.
[1.5.2](https://github.com/UniSharp/laravel-filemanager/releases/tag/1.5.2) works fine on Windows 10.

**Comment by Pejic88** [comment]
@youchenlee it's working now, tnx :+1:

**Comment by youchenlee** [comment]
@pejic88 no problem
