### ISSUE TITLE
NotReadableException in Decoder.php On PDF Upload

### ISSUE THREAD

**Issue by TnCoders** [UniSharp/laravel-filemanager#180]
Hi,

I have this issue When i try to Upload PDF

**This is the laravel Exception:**
NotReadableException in Decoder.php line 20:
Unable to read image from file (C:\Users\***\AppData\Local\Temp\php78C1.tmp).

Im testing in Local and there is no problem when uploading Picture.

`------WebKitFormBoundaryd0dlQ8jpfIkLCGwL
Content-Disposition: form-data; name="upload[]"; filename="1.pdf"
Content-Type: application/pdf

------WebKitFormBoundaryd0dlQ8jpfIkLCGwL
Content-Disposition: form-data; name="working_dir"

------WebKitFormBoundaryd0dlQ8jpfIkLCGwL
Content-Disposition: form-data; name="show_list"

0
------WebKitFormBoundaryd0dlQ8jpfIkLCGwL
Content-Disposition: form-data; name="type"

Files
------WebKitFormBoundaryd0dlQ8jpfIkLCGwL
Content-Disposition: form-data; name="_token"

6TG8cEBIaJc9wpApJm05Qa0UQsZRHV1iNdF1y2F3
------WebKitFormBoundaryd0dlQ8jpfIkLCGwL--`

**Comment by g0110280** [comment]
v1.7-alpha has been released, please update and check this issue again.

**Comment by MatthiasHertel** [comment]
i had tested in `1.7-alpha` works good ...

**Comment by TnCoders** [comment]
Problem 1
    - The requested package unisharp/laravel-filemanager ^1.7 is satisfiable by unisharp/laravel-filemanager[v1.7-alpha] but these conflict with your requirements or minimum-stability.


"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "laravelcollective/html": "^5.3",
        "intervention/image": "^2.3",
        "doctrine/dbal": "^2.5",
        "dimsav/laravel-translatable": "^6.0",
        "cviebrock/eloquent-sluggable": "4.1",
        "unisharp/laravel-filemanager": "^1.7",
        "mcamara/laravel-localization": "^1.1",
        "spatie/laravel-glide": "^3.0"
    },


what im doing wrong ?

**Comment by MatthiasHertel** [comment]
try this in your composer.json:

`"unisharp/laravel-filemanager": "^1.7-alpha",`

**Comment by TnCoders** [comment]
Thank you :)

**Comment by TnCoders** [comment]
Big Problem over here :+1: 

![filemanager](https://cloud.githubusercontent.com/assets/24681177/22289562/935be46e-e2fc-11e6-92a9-4490cff0da77.PNG)

I have this now nothing is displayed, i just composer updated it and i didint touch anything else.

I have Picture and folder inside my public directory and nothing is displayed.

**Comment by TnCoders** [comment]
Of corse i did this : 
php artisan vendor:publish --tag=lfm_view --force
php artisan vendor:publish --tag=lfm_config --force

**Comment by g0110280** [comment]
Please run `php artisan vendor:publish --tag=lfm_public --force` to update all assets, including lfm.js.
An upgrate note will be added to readme.

**Comment by TnCoders** [comment]
Thank you every thing is good
