### ISSUE TITLE
File manager content not shown!

### ISSUE THREAD

**Issue by rtanzifi** [UniSharp/laravel-filemanager#182]
Hi guys. When i click to open file manager, the file manager window appear but there is no content in it. I'm using it with tinymce editor. Does anybody know what's wrong? My tinymce version is 4.5.2.
![capture](https://cloud.githubusercontent.com/assets/16733912/22210520/5ac04b44-e19f-11e6-98cd-5d57820d12b0.PNG)

**Comment by g0110280** [comment]
Please post errors from your console here.

**Comment by rtanzifi** [comment]
There is no error in console. I change the editor to Ckeditor and now it just works fine!

**Comment by MatthiasHertel** [comment]
maybe the renaming of script.js was the issue ... i had the same and in the browser console was 404 ... `php artisan vendor:publish` fixed it for me
