### ISSUE TITLE
Undefined method Illuminate\Foundation\Application::share() when upgrading to Laravel 5.4

### ISSUE THREAD

**Issue by smuzammilali** [UniSharp/laravel-filemanager#186]
Any updates coming for Laravel 5.4?

**Comment by smuzammilali** [comment]
![2017-01-26_1607](https://cloud.githubusercontent.com/assets/24757934/22351130/8c43dd60-e3e4-11e6-9274-657de1e0aec3.png)

**Comment by youchenlee** [comment]
should be fixed by #187
Thanks for the info.

**Comment by g0110280** [comment]
`V1.7.0` has released. Closing issue now.
