### ISSUE TITLE
this.on error for standalone option laravel 5.4

### ISSUE THREAD

**Issue by sbcman74** [UniSharp/laravel-filemanager#189]
I am getting the following error in the console when trying to load laravel-filemanager.

`
lfm.js:12 Uncaught TypeError: this.on is not a function
    at init.$.fn.filemanager (lfm.js:12)
    at create:103
`

**Comment by sbcman74** [comment]
Was able to get it to work by changing from `this.on` to `this.live`.  I am not sure this is the best solution however.

**Comment by g0110280** [comment]
This should be an error with jQuery version.
