### ISSUE TITLE
Need a more flexible way to customize folders accessibility.

### ISSUE THREAD

**Issue by IgnitedCoder** [UniSharp/laravel-filemanager#19]
First: Thanks for a great lib. Can you give me a hint as to how I use it with multiple clients? For example users belong to a client and they should all have access to that clients folder of images and files. I see the allow_multi_user config var and the user_field which would've worked great if I had the client_id in the users table but its in a pivot table and my admin users will never have a client_id set. 

Any suggestions on what I can change would be most appreciated.

Thanks

**Comment by IgnitedCoder** [comment]
Changed it in your middleware for now... But I would definitely consider adding a config item for perhaps a session var as opposed to user_field or both. :)

**Comment by youchenlee** [comment]
@IgnitedCoder Would you mind showing us your `git diff` of that fix in middleware? It may help for us to provide a better way to customize this package.
I will reopen this issue to keep tracking.

**Comment by IgnitedCoder** [comment]
Note*: This is a hack and given time I would probably do it better, but here it is

$workingDir = session()->hasKey('client_id') ? session()->get('client_id') : \Auth::user()->user_field;
if ($base == null) {
    $request->merge(['working_dir' => $workingDir]);
} elseif ($this->wrongDir($base)) {
       $request->replace(['working_dir' => $workingDir]);
}

**Comment by youchenlee** [comment]
Thank you @IgnitedCoder 

Instead of the simple user_field config:
```
'user_field'         => 'id',
```

We should have something like:
```
'can_access' => function($user, $folder) { ... };
```
I will modify the subject of this issue for tracking this feature.

**Comment by stront90** [comment]
Maybe just possibility to set config values (images|files)_(dir|url) in middleware? And possibility to add more directories (eg. images_dir = ['shared', 'user_1', 'group_43'])?

**Comment by g0110280** [comment]
Config : `user_field` can now accept a closure, in `v1.7.2`.
