### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by hxor** [UniSharp/laravel-filemanager#190]
Hi, i just install this package to my laravel. But, when I try to upload some file some error got me:
the server responded with a status of 500 (Internal Server Error) on */laravel-manager/upload. Sure, permission was enable 777.

Sorry for my english.

**Comment by g0110280** [comment]
If you are using `v1.6.3`, please upgrade to `v1.7-alpha` to check if this issue exists.

**Comment by hxor** [comment]
Thanks for fast response. Yes, I installed that v1.6* version. Let me try to v1.7*.

**Comment by hxor** [comment]
Hi, after update to 1.7. I got this error:
vendor/laravel-filemanager/js/script.js 404 (Not Found)

and the filemanager is not work

**Comment by g0110280** [comment]
Please run `php artisan vendor:publish`

**Comment by hxor** [comment]
Oh, sorry I forgot to do that. But I just place the script.js from unisharp dir and it's done. Thank you. 😆
