### ISSUE TITLE
Make a Great docs

### ISSUE THREAD

**Issue by wedus98** [UniSharp/laravel-filemanager#197]
Can anyone make  a detail docs ? i think its important for usage. :D

**Comment by youchenlee** [comment]
@wedus98 thank you for the suggestion.
It takes some time to create a perfect doc, but we can start from some most important parts.

What topics do you like?

**Comment by g0110280** [comment]
Working on GitHub Pages.

**Comment by g0110280** [comment]
Document is available at [unisharp.github.io/laravel-filemanager](https://unisharp.github.io/laravel-filemanager) now.
