### ISSUE TITLE
Right configuration 

### ISSUE THREAD

**Issue by fencermd** [UniSharp/laravel-filemanager#199]
Who can share with me his configuration file where in standalone usage it will return correct link and thumbnails will show OK.

in my case I have 

> 'user_field'            => 'id',
> 
>     'shared_folder_name'    => 'shares',
>     'thumb_folder_name'     => 'thumb',
> 
>     'images_dir'            => 'public/photos/',
>     'images_url'            => '/photos',
> 
>     'files_dir'             => 'public/files/',
>     'files_url'             => '/files',

I have returned link is http://sandra.dev/photos/shares/Events/58836aa9c5018.jpg
but in filemanager I have
![screen shot 2017-02-07 at 12 33 55](https://cloud.githubusercontent.com/assets/25147971/22687772/0c2be814-ed32-11e6-8a5e-7d46d4e77148.png)
![screen shot 2017-02-07 at 12 34 09](https://cloud.githubusercontent.com/assets/25147971/22687777/1157350a-ed32-11e6-87bd-f157c8b87b46.png)

======================
if I add '/shares' thumbnails are OK, but the link to image will be http://sandra.dev/photo**s//s**hares/Events/58836aa9c5018.jpg

**Comment by g0110280** [comment]
`config/lfm.php` has been refactored. Please run `php artisan vendor:publish --tag=lfm-config --force`. Upgrade guide will be noted in readme, and then stable version of v1.7 will be released.

**Comment by fencermd** [comment]
OK, forgot to mention, I have made some settings in scripts.blade
var image_url     = "{{ Config::get('lfm.images_url') }}";
var file_url      = "{{ Config::get('lfm.files_url') }}";

and because of this I get this double slashes.

**CAN WE have configuration in lfm.php that will help us to configure use url or path to files.
SHOW FULL PATH = FALSE**

**Comment by g0110280** [comment]
Sorry I forgot to mention that, `script.blade.php` is also refactored and replaced with with `script.js`, run `php artisan vendor:publish --tag=lfm_public` to get that.

**Comment by fencermd** [comment]
Great looking foreword for 1.7 and action there :)

**Comment by Jonybang** [comment]
after upgrade double slashes problem still exists for 'allow_multi_user' => false

**Comment by g0110280** [comment]
`v1.7.0` has released. Closing issue now.
