### ISSUE TITLE
Browse buttons not shown

### ISSUE THREAD

**Issue by PENDOnl** [UniSharp/laravel-filemanager#20]
Hi,

for some reason the buttons don't show up. I installed the package UniSharp/laravel-ckeditor first and then this package. The editor works, also the URLs to the different browsers work (including the uploads). However... the buttons don't seem to show up!

I published everything, configured it to my liking.. just those buttons. I tripple checked the configuration of the jquery adapter. This is the code I'm using:

```php
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
    $( 'textarea.editor' ).ckeditor({
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });
</script>
```

**Comment by youchenlee** [comment]
@PENDOnl Did you get any errors on the browser console?

**Comment by PENDOnl** [comment]
Nope, unfortunately not. The filemanager links are all working correctly and the javascript isn't throwning any errors either. It's just the buttons that don't show up.

**Comment by youchenlee** [comment]
Did you mean the CKEditor buttons?
<img width="719" alt="screen shot 2016-01-10 at 18 51 12" src="https://cloud.githubusercontent.com/assets/181350/12221209/42ee7486-b7cb-11e5-977d-8fb3dc61e9c2.png">

**Comment by PENDOnl** [comment]
No, those are working fine. It's the button inside the popup that is missing. Having the browsers enabled should give me a [Browse server] button besides the input field, right?

![Browse Button](http://s21.postimg.org/negyzh3br/Rumbold_Bijeenkomst_2016_01_10_11_59_13.png)

**Comment by youchenlee** [comment]
Does it happens on both firefox and google chrome?

**Comment by PENDOnl** [comment]
All browser act the same

**Comment by youchenlee** [comment]
@PENDOnl I have no idea now. 
Would you please:
1. list your laravel-ckeditor and laravel-filemanager versions.
2. try out kcfinder or other file-uploading extension of CKEditor. That may help to figure out if the problem is in CKEditor or laravel-filemanager.

Very appreciate!

**Comment by PENDOnl** [comment]
I'll go after this anytime soon! Just a few things to solve in this project first.

**Comment by PENDOnl** [comment]
Not sure of this is related, but (even with your laravel-filemanger plugin disabled) I'm not able to input anything in this popup:

![What is clickable](http://s17.postimg.org/k49vzrrpr/editor.png)

The tab bar is clickable, but anything inside the tab bar is not clickable. I cannot input a web address or change the target. I disabled the filemanager plugin to test, but this popup was still not working.

Versions:
```
        "laravel/framework": "5.1.*",
        "unisharp/laravel-ckeditor": "^4.5",
        "unisharp/laravel-filemanager": "^1.1",
```

Thanks for your time!

**Comment by PENDOnl** [comment]
The popups have been fixed, apparently due to the jquery setup they failed.. this my code right now:

```javascript
<script>
    CKEDITOR.replace('ckeditor', {
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });
</script>
```

But still,.. no "Browse" buttons in the link/image popup.

**Comment by PENDOnl** [comment]
I noticed adding the URLs right into the config.js file is working:

```
CKEDITOR.editorConfig = function( config ) {
    config.filebrowserImageBrowseUrl = '/laravel-filemanager?type=Images';
    config.filebrowserBrowseUrl = '/laravel-filemanager?type=Files';
    // other config
};
```

So, am I missing something here? Because the code below does not add anything.

```
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('ckeditor', {
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });
</script>
```

**Comment by PENDOnl** [comment]
Issue found!

Apparently, you cannot give your textarea field the class '.ckeditor', this causes the script to automatically bind a CKEditor instance to the textarea before you've set the configuration. My working solution is:

```
<div class="form-group ">
    <label for="body" class="control-label">Bericht:</label>
    <textarea class="form-control" id="body" name="body" cols="50" rows="10"></textarea>
</div>
```

With this javascript:

```
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
    $('#body').ckeditor({
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });
</script>
```

So, using the class 'ckeditor' will bypass these codes:

```
CKEDITOR.replace('ckeditor', {options});
$('.ckeditor').ckeditor({options});
```

My last issue remains (disabled inputs) but this is unrelated to this issue and I think it's even completely unrelated to your plugin. You can close this issue if you want. I'll leave it open for you to comment.

**Comment by youchenlee** [comment]
@PENDOnl

You are right,  the `<textarea>` elements with a class named `ckeditor` will be automatically replaced by a CKEditor instance. This feature can be customized with the `replaceClass` attribute.
http://docs.ckeditor.com/#!/api/CKEDITOR-cfg-replaceClass


You might still want to use class as the selector, just avoid `ckeditor`.
```
<div class="form-group ">
    <label for="body" class="control-label">Bericht:</label>
    <textarea class="form-control my-editor" id="body" name="body" cols="50" rows="10"></textarea>
</div>
```
```
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
    $( 'textarea.my-editor' ).ckeditor({
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });
</script>
```

I have no idea about the "disabled input" issue either. 
The latest stable version of CKEditor is 4.5.6, worth giving it a try.
I added an issue to the laravel-ckeditor fork for the upgrade.  ( unisharp/laravel-ckeditor#3 )

**Comment by PENDOnl** [comment]
Thanks, I knew about the other classes. Just didn't know that the ckeditor class was used by default. You might want to add that to your documentation in the plugin. You know, just in case anyone runs into the same problem. It was a pain in the ass finding this since it was caused by such a little thing.

The disabled input was caused by the CKEditor being put inside a Bootstrap Modal, it was fixed by this answer (http://stackoverflow.com/questions/22637455/how-to-use-ckeditor-in-a-bootstrap-modal).

In the end, all little things. But fixed. Thanks for the quick replies. Afterall a great plugin which I surely are going to use more often!

**Comment by youchenlee** [comment]
@PENDOnl Thanks, I will update the doc later. Glad to know you solved those problems. Happy hacking!
