### ISSUE TITLE
Back button dont working

### ISSUE THREAD

**Issue by Jonybang** [UniSharp/laravel-filemanager#200]
Was return from click handler on `if (previous_dir == '') return;`
Debugger screenshot: https://i.imgur.com/PxYzK2M.png

**Comment by g0110280** [comment]
It was written to prevent user from accessing parent folder of user folder.

**Comment by Jonybang** [comment]
This problem occurred when configured: `'allow_multi_user'      => false,`
Please fix this.

**Comment by g0110280** [comment]
Please follow [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to v1.7.6.
