### ISSUE TITLE
Laravel 5.4: Uncaught ReferenceError: success_response is not defined

### ISSUE THREAD

**Issue by smuzammilali** [UniSharp/laravel-filemanager#202]
Getting this error:
![2017-02-10_1524](https://cloud.githubusercontent.com/assets/24757934/22842925/29728c8c-efa5-11e6-9291-65d3b6dcd0b1.png)

using: dev-master

**Comment by smuzammilali** [comment]
![2017-02-10_1530](https://cloud.githubusercontent.com/assets/24757934/22843092/e9b4c24e-efa5-11e6-86d6-217db4d08c74.png)


![2017-02-10_1530_001](https://cloud.githubusercontent.com/assets/24757934/22843095/eccc7b3e-efa5-11e6-8207-11b93b5ea06e.png)

**Comment by smuzammilali** [comment]
Not showing any errors on the console when checking from the text editor:
![2017-02-10_1618](https://cloud.githubusercontent.com/assets/24757934/22844529/bc7f87c6-efac-11e6-9126-9ad50995fca2.png)

But it's not rendering html

**Comment by smuzammilali** [comment]
It only happenings in TinyMCE editor CKEditor works fine!

**Comment by g0110280** [comment]
See [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/index.blade.php#L119).

**Comment by g0110280** [comment]
`v1.7.0` has released. Please follow the instructions in readme.

**Comment by BirdyUK** [comment]
@smuzammilali - Did you get this working? i have the same issue with unexpected type parameter, ive checked the source and its coming from isProcessingImages() method.
