### ISSUE TITLE
Audio/mpeg

### ISSUE THREAD

**Issue by blackmamb41** [UniSharp/laravel-filemanager#203]
It's not support on mime types audio/mpeg??

**Comment by blackmamb41** [comment]
![image](https://cloud.githubusercontent.com/assets/11955657/22885865/d24038de-f22d-11e6-89d9-3fa0ba9d9c32.png)

![image](https://cloud.githubusercontent.com/assets/11955657/22885878/e1215edc-f22d-11e6-9998-226c1c5215d5.png)

**Comment by g0110280** [comment]
@blackmamb41 You filled in the mime type to `valid_file_mimetypes`, you should go to `http://localhost:8000/laravel-filemanager?type=Files` and upload your file.

**Comment by Ariunbold13** [comment]
mp3 mimetypes is 'application/octet-stream'. Then ????

**Comment by g0110280** [comment]
@Ariunbold13 fill it into `valid_file_mimetypes`.

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.
