### ISSUE TITLE
Failure when uploading a file. (version 1.6)

### ISSUE THREAD

**Issue by fmarkos** [UniSharp/laravel-filemanager#204]
Uploading was working 2-3 months ago. It seems composer update doesn't update this library.

In version 1.6 of /vendor/unisharp/laravel-filemanager/src/controllers/UploadController.php
$files = Input::file('upload');
didn't return an array. The following foreach($files as $file) was never run.
I changed it to:
$files[] = Input::file('upload');
and now it works.

**Comment by g0110280** [comment]
`v1.7.0` has released. Please follow the instructions in readme. This should not happen in `v1.7.0`.
