### ISSUE TITLE
How to add further file types 

### ISSUE THREAD

**Issue by danielthomascarr** [UniSharp/laravel-filemanager#205]
Is there a way to add a new file type, in particular Adobe Illustrator files to the config file?

**Comment by g0110280** [comment]
Please visit the [configuration document](https://github.com/UniSharp/laravel-filemanager/blob/master/docs/config.md) and find out which mime type to fill in from [here](https://www.sitepoint.com/web-foundations/mime-types-complete-list/).

**Comment by g0110280** [comment]
`v1.7.0` has released. Please follow the instructions in readme.
