### ISSUE TITLE
Deploy laravel-filemanager to DirectAdmin host , can not upload image and no error display

### ISSUE THREAD

**Issue by hungelc** [UniSharp/laravel-filemanager#206]
Hi,
I'm using laravel-filemanager version 1.7 and laravel version 5.4.I upload my image (size 25KB) successful in my local Apache webserver but i can not upload it in DirectAdmin host.No error in console.
I deploy project by follow :
- Upload all file and folder to public_html folder.
- Cut all file and folder in public folder and paste them to public_html.
- Edit file index.html : 
require __DIR__.'/../bootstrap/autoload.php'; =>  require __DIR__.'/bootstrap/autoload.php';
$app = require_once __DIR__.'/../bootstrap/app.php'; => $app = require_once __DIR__.'/bootstrap/app.php';

Please help me ! Thank you very much.

http://www.upsieutoc.com/image/YpV94N

**Comment by dedydantry** [comment]
apload all folders and files except the public folder, to the root directory. All files contained in the folder folder public move to folder public_html.
here is example 
![larapus](https://cloud.githubusercontent.com/assets/20817716/23096708/7255d9de-f650-11e6-8c02-2848d796aaba.JPG)

**Comment by g0110280** [comment]
@hungelc did you run commands like `chown` or `chmod`?

**Comment by hungelc** [comment]
@g0110280 I set chmod recursively for public_html folder but the issue is not fixed

**Comment by g0110280** [comment]
Will it work if you rename public_html to public?

**Comment by g0110280** [comment]
If you need to upload files to public_html, remember to set `base_directory` from [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/config/lfm.php#L41).

**Comment by hungelc** [comment]
@g0110280  i always set 'base_directory' => 'public_html'. If i rename public_html to public, my website is error "The requested URL / was not found on this server.".
Do you check my host ? I can send you information about my host via e-mail

**Comment by hungelc** [comment]
Hi @g0110280 sorry for my issues.I add logging to UploadController.php file and get an error "Reading Exif data is not supported by this PHP installation."
The error means my host is not install exif extension.I will contact the administrator to install it tomorrow.
Thank you very much.
