### ISSUE TITLE
Over limit size:image/jpeg with ckeditor

### ISSUE THREAD

**Issue by manoj-infrasssist** [UniSharp/laravel-filemanager#208]
When I tried to upload greater than 2 mb image it says the Over limit size:image/jpeg
Please let me know where to set the max file upload settings for ckeditor/laravel-filemanager.
My upload_max_filesize in php.ini is 1000M

**Comment by g0110280** [comment]
Try to modify apache/nginx settings.

**Comment by manoj-infrasssist** [comment]
When I try to upload file from other module using basic fileupload ($file->storeAs('job_docs/',$filename);) , It is getting successfully uploaded. And also other projects in the same server can upload larger file.
I think there should be some setting in ckeditory or laravel-filemanager for max file upload.

**Comment by g0110280** [comment]
Got it. Check settings [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/config/lfm.php#L75).

**Comment by manoj-infrasssist** [comment]
Thanks very much for you support.
I have made change in config/lfm.php max_image_size and it's worked.
