### ISSUE TITLE
Preview image is not correct when i change base_directory 

### ISSUE THREAD

**Issue by diz123** [UniSharp/laravel-filemanager#209]
I changed base_directory and image in review is not correct.
```
base_directory='media/'.date('Y-m-d');
```

Image uploaded  correct  to folder  '/media/'.date('Y-m-d').'/photos/{id}'/filename.jpg
But url image in review just '/photos/{id}'/filename.jpg. it look like missing 'base_directory' in url image.
What i 'm doing wrong or missing something?

Thanks so much.

**Comment by g0110280** [comment]
Sorry to say that preview image would only work if `base_directory` is set to `public`, for now.

**Comment by g0110280** [comment]
Related to #115 .

**Comment by g0110280** [comment]
Please upgrade to `v1.7.2`.
