### ISSUE TITLE
How can I custom the button add some or remove 

### ISSUE THREAD

**Issue by johnef** [UniSharp/laravel-filemanager#215]
How can I custom the button add some or remove buttons I try the config.js but noting is changing
please help
thanks

**Comment by g0110280** [comment]
If you mean to custom the buttons of CKEditor or TinyMCE, you should check their documents. If you want to integrate this package with them, you can see "Integration document" of this package.

**Comment by johnef** [comment]
Yes I did checked the CKEditor documentation and got the customization needed which will be put in the header  `CKEDITOR.editorConfig = function( config ) {}` and I found this under `public/vendor/unisharp/laravel-ckeditor/config.js` and I changed it already but nothing has been changed

what I am doing wrong here

**Comment by johnef** [comment]
I got rid of the installed package CKEditor and I installed the original from CKEditor
