### ISSUE TITLE
404 not found in chrome

### ISSUE THREAD

**Issue by gifary** [UniSharp/laravel-filemanager#217]
Hello, 

Please help me,
I am getting error 404 not found in chrome browser when integration with ckeditor, but in local work properly and another browser fine. Thank you very much

**Comment by g0110280** [comment]
Please upgrade to `v1.7.2`.

**Comment by g0110280** [comment]
Tested and worked just fine. Maybe you should clear the cache of you Chrome.

**Comment by gifary** [comment]
thanks a lot
