### ISSUE TITLE
After Upload content will be not updated

### ISSUE THREAD

**Issue by bypit** [UniSharp/laravel-filemanager#218]
When I upload a File or Image, the List of files will not be updated. I must close the file manager and open it again to see new Files. The same Issue occurs on delete

**Comment by fdioni** [comment]
+1

**Comment by g0110280** [comment]
@bypit @fdioni Can you provide your OS and browers?

**Comment by fdioni** [comment]
@g0110280 windows 7, google chrome

**Comment by g0110280** [comment]
Please upgrade to `v1.7.2`.
