### ISSUE TITLE
ErrorException in RouteCollection.php line 89: Illegal offset type

### ISSUE THREAD

**Issue by danjswade** [UniSharp/laravel-filemanager#219]
Updated composer, no issues. I'm running laravel 5.0.x so have my service providers:

`'Intervention\Image\ImageServiceProvider',`
`'Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider',`

and my class alias:

`'Image'     => 'Intervention\Image\Facades\Image',`

I get no errors when I code out the Unisharp service provider so I can only assume this line is the issue. The error I get is:

> ErrorException in RouteCollection.php line 89:
> Illegal offset type
> in RouteCollection.php line 89
> at HandleExceptions->handleError('2', 'Illegal offset type', '/opt/lampp/htdocs/mrfc2016/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php', '89', array('route' => object(Route), 'action' => array('middleware' => array('auth', '\Unisharp\Laravelfilemanager\middlewares\MultiUser', '\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder'), 'as' => array('unisharp.lfm.', 'show'), 'uses' => '\Unisharp\Laravelfilemanager\controllers\LfmController@show', 'controller' => '\Unisharp\Laravelfilemanager\controllers\LfmController@show', 'namespace' => '\Unisharp\Laravelfilemanager\controllers', 'prefix' => 'laravel-filemanager', 'where' => array()))) in RouteCollection.php line 89
> at RouteCollection->addLookups(object(Route)) in RouteCollection.php line 51
> at RouteCollection->add(object(Route)) in Router.php line 469
> at Router->addRoute(array('GET', 'HEAD'), '/', array('uses' => 'LfmController@show', 'as' => 'show')) in Router.php line 126
> at Router->get('/', array('uses' => 'LfmController@show', 'as' => 'show')) in Facade.php line 213
> at Facade::__callStatic('get', array('/', array('uses' => 'LfmController@show', 'as' => 'show'))) in routes.php line 15
> at LaravelFilemanagerServiceProvider->{closure}(object(Router))
> at call_user_func(object(Closure), object(Router)) in Router.php line 352
> at Router->group(array('middleware' => array('auth', '\Unisharp\Laravelfilemanager\middlewares\MultiUser', '\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder'), 'prefix' => 'laravel-filemanager', 'as' => 'unisharp.lfm.', 'namespace' => '\Unisharp\Laravelfilemanager\controllers'), object(Closure)) in Facade.php line 213
> at Facade::__callStatic('group', array(array('middleware' => array('auth', '\Unisharp\Laravelfilemanager\middlewares\MultiUser', '\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder'), 'prefix' => 'laravel-filemanager', 'as' => 'unisharp.lfm.', 'namespace' => '\Unisharp\Laravelfilemanager\controllers'), object(Closure))) in routes.php line 90
> at include('/opt/lampp/htdocs/mrfc2016/vendor/unisharp/laravel-filemanager/src/routes.php') in LaravelFilemanagerServiceProvider.php line 21
> at LaravelFilemanagerServiceProvider->boot()
> at call_user_func_array(array(object(LaravelFilemanagerServiceProvider), 'boot'), array()) in Container.php line 526
> at Container->call(array(object(LaravelFilemanagerServiceProvider), 'boot')) in Application.php line 703
> at Application->bootProvider(object(LaravelFilemanagerServiceProvider)) in Application.php line 685
> at Application->Illuminate\Foundation\{closure}(object(LaravelFilemanagerServiceProvider), '16')
> at array_walk(array(object(EventServiceProvider), object(RoutingServiceProvider), object(AuthServiceProvider), object(ControllerServiceProvider), object(CookieServiceProvider), object(DatabaseServiceProvider), object(EncryptionServiceProvider), object(FilesystemServiceProvider), object(FormRequestServiceProvider), object(FoundationServiceProvider), object(PaginationServiceProvider), object(SessionServiceProvider), object(ValidationServiceProvider), object(ViewServiceProvider), object(SluggableServiceProvider), object(ImageServiceProvider), object(LaravelFilemanagerServiceProvider), object(AppServiceProvider), object(BusServiceProvider), object(ConfigServiceProvider), object(EventServiceProvider), object(RouteServiceProvider)), object(Closure)) in Application.php line 686
> at Application->boot() in BootProviders.php line 15
> at BootProviders->bootstrap(object(Application)) in Application.php line 183
> at Application->bootstrapWith(array('Illuminate\Foundation\Bootstrap\DetectEnvironment', 'Illuminate\Foundation\Bootstrap\LoadConfiguration', 'Illuminate\Foundation\Bootstrap\ConfigureLogging', 'Illuminate\Foundation\Bootstrap\HandleExceptions', 'Illuminate\Foundation\Bootstrap\RegisterFacades', 'Illuminate\Foundation\Bootstrap\RegisterProviders', 'Illuminate\Foundation\Bootstrap\BootProviders')) in Kernel.php line 199
> at Kernel->bootstrap() in Kernel.php line 110
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 84
> at Kernel->handle(object(Request)) in index.php line 52
> at require_once('/opt/lampp/htdocs/mrfc2016/public/index.php') in server.php line 21

Anyone tell me where I'm going wrong?

**Comment by johnef** [comment]
This is a route issue run `php artisan route:list` and check if you have the right routes listed there
and make sure that this `lfm.php` has `'use_package_routes' => true,` and try again

**Comment by danjswade** [comment]
I've found that the problem is the:

`'Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider',`

If I comment this out, I don't get the error message. If I leave it in, then try to do `php artisan vendor:publish --tag=lfm_config` I get the message:

> [ErrorException]
>Illegal offset type

Any ideas?

**Comment by g0110280** [comment]
Please upgrade to `v1.7.2`.
