### ISSUE TITLE
can create folders but can't upload files

### ISSUE THREAD

**Issue by ehsand** [UniSharp/laravel-filemanager#222]
hi
laravel-filemanager in my project can create folders but can't upload files
there is no error when i try to upload file but still doesn't upload files

**Comment by PendoNL** [comment]
+1, I'm having the same issue. Lokal enviroment is working like it should by the way (same code as far as I know right now). Creating folders works, uploading "pretends" to work, but no files are being uploaded.

**Comment by gfd6th** [comment]
+1, same isuue , even in demo example

**Comment by g0110280** [comment]
Thank you @gfd6th .

**Comment by g0110280** [comment]
Solved in 699de19.

**Comment by PendoNL** [comment]
I cannot confirm that this solution works.. also the views seem to be misformed (scroll bars, too large icons, etc.)

**Comment by g0110280** [comment]
@PendoNL Solutions to misformed views, see the [upgrade doc](http://unisharp.github.io/laravel-filemanager/upgrade). And your problems with uploading seem like an issue with permission, since it  works fine in your local machine. See if `chmod` to 777 helps.

**Comment by PendoNL** [comment]
Strange enough 777 doesn't work either, first thing I tried and checked were the folder permissions and diskspace of the account..

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`, which disables upload validation by default.

**Comment by PendoNL** [comment]
I'm going to try this later today, thanks for the help so far.

**Comment by ismailcaakir** [comment]
+1

Everything works fine but it does not upload any files at all. On the local server

**Comment by progsmile** [comment]
@ismailcaakir Thanks, Works for me!

**Comment by rregister87** [comment]
Experiencing the same issue on an Ubuntu 16.04 VPS. The file permissions are set correctly to 775, and the group and owner are set to www-data (for nginx). I was originally getting the 'action failed due to server error' message, but after changing permissions the error has gone away. I can now create folders, but am unable to upload any files. I can confirm that both mbstring.so and exif.so are installed.

**Comment by g0110280** [comment]
@rregister87 Please post the errors in your console here.

**Comment by g0110280** [comment]
Please upgrade to v1.7.2.

**Comment by balinux** [comment]
thanks it's solved with move size to   'max_image_size' => 5000,
and enable extension=php_exif.dll   at php.ini
thanks

**Comment by armannadim** [comment]
I'm having this same issue in a shared hosting...
can create folder but not uploading files. folder permission is 777.
I've enabled exif, max_image_size is 50000... updated the library with the current version.
In local host working correctly.
Any other issue that might be the reason of this problem??

**Comment by rtanzifi** [comment]
Same issue here. I did every thing on this thread nothing work! whats wrong?

**Comment by rregister87** [comment]
Make sure you have Intervention Image installed (http://image.intervention.io/getting_started/installation) and one of the two required image libraries (GD Library >=2.0 or Imagick PHP extension >=6.5.7). Also, there is a config file published by Intervention Magic, in which you need to set which of the two libraries you are using (I think the default is 'gd'). Having the config file set improperly or not having the library installed would cause a silent failure when you try to upload images, but would allow folder creation.

**Comment by roswatafak** [comment]
I fixed this problem by enable extension name "php_exif"

**Comment by rtanzifi** [comment]
Hi guys. you should enable these two extension on your php.ini file:
extension=php_gd2.dll
extension=php_exif.dll
my problem is the exif module. enable it and your file should be appear after uploading.
