### ISSUE TITLE
How to get the Thumbnail url in blade file

### ISSUE THREAD

**Issue by mavinothkumar** [UniSharp/laravel-filemanager#223]
Hi,

I have configured everything and its working good. Thanks for that. But I don't know how to get the image file as well as its thumbnail image path to show thumbnail image and onclick to show the actual image.

**Comment by g0110280** [comment]
@mavinothkumar See [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/item.blade.php#L5).

**Comment by MikeDynamic** [comment]
@g0110280  The see here gives a 404 error. 
I am also trying to find out how to get the thumbnail, I can get the fullsize image easily.

**Comment by g0110280** [comment]
@MikeDynamic I have updated the link, you can also see it [here](https://github.com/UniSharp/laravel-filemanager/blob/v1.7.1/src/views/item.blade.php#L2) (version 1.7.1)

**Comment by MikeDynamic** [comment]
Thank you very much @g0110280
