### ISSUE TITLE
Unable to upload file until GD library is missing

### ISSUE THREAD

**Issue by enstain** [UniSharp/laravel-filemanager#224]
Very similar to #222 

Server environment: Ubuntu 16.04 / PHP 7.1

So, same thing. Uploading file popup dies in silence without any error. It's so much like that filemanager just doesn't correspond about upload limit, but increasing upload max size in lfm config doesn't help.

Local environment works fine with create new folders and upload files. Production side allows only create folders. It's also not a Windows issue, since there is Ubuntu. It seems that I have to finetune production server somehow, but it isn't obvious what to do exactly. One thing I did at the server is that lfm asked me to install gd or imagick package and I install imagick package.

**Comment by enstain** [comment]
That's fun, but issue really belongs to gd and imagick package choose issue. Deep logging into UploadController shows following exception (it's thrown at UploadController:67 and by the way, doesn't anybody think it's weird that this exception catch dies silently?):

`Intervention\Image\Exception\NotSupportedException: GD Library extension not available with this PHP installation.`

So, I install GD package also and that's it! File uploads fine.

I guess it definitely should be mentioned at the documentation that we have to install GD package, not image magick.

**Comment by rtanzifi** [comment]
Hi guys. you should enable these two extension on your php.ini file:
extension=php_gd2.dll
extension=php_exif.dll
my problem is the exif module. enable it and your file should be appear after uploading.
