### ISSUE TITLE
Problem with image/svg+xml

### ISSUE THREAD

**Issue by mikkpokk** [UniSharp/laravel-filemanager#226]
Hello

At the moment there is impossible to add SVG images via image file manager.

On image below you can see hacky fix for that.

![image](https://cloud.githubusercontent.com/assets/14272312/24103109/eb43c96c-0d86-11e7-8bde-590fb9c1e150.png)

UploadController.php

Line 58:
` && $file->getMimeType() != 'image/svg+xml'`

Line 65-72:

`// Extra hacky part - otherwise user cannot see image preview`
`$move = File::move($file->path(), str_replace($new_filename, '', $new_file_path).'thumbs/'.$new_filename);`
`// Copy file from thumbs directory to main directory`
`if ($move) {`
`    File::copy(str_replace($new_filename, '', $new_file_path).'thumbs/'.$new_filename, $new_file_path);`
`}`

Is there any hope to fix SVG problem ASAP?

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.

**Comment by mikkpokk** [comment]
Unfortunately problem is still up on that release.

The problem is: SVG file gets passed on method "fileIsImage", but class "Image" and method "makeThumb" are unable to work with the SVG file. So SVG files never show up on image manager (works only with file manager).

**Comment by g0110280** [comment]
Please upgrade to `v1.7.2`.
