### ISSUE TITLE
get the image

### ISSUE THREAD

**Issue by ahmedalmulki** [UniSharp/laravel-filemanager#227]
I follow the whole of document , but when I upload the image I get nothing , I can create folder I can see the photos folder in my public folder but when I upload the image no error no image , what I missed .

**Comment by g0110280** [comment]
Related to #222 .

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.

**Comment by ahmedalmulki** [comment]
Thanks .
