### ISSUE TITLE
How to sorter file upload DESC

### ISSUE THREAD

**Issue by daolvcntt** [UniSharp/laravel-filemanager#228]
How do I sorter the new upload logs to the top of the newest creation date.

Sorry for my bad english!!!

**Comment by g0110280** [comment]
@daolvcntt Use `usort()` from [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/traits/LfmHelpers.php#L295).

**Comment by daolvcntt** [comment]
@g0110280 thank you
