### ISSUE TITLE
Problem with all mimetype file

### ISSUE THREAD

**Issue by laypassmail** [UniSharp/laravel-filemanager#229]
Hi!
At the moment there is impossible to add xml, xlsx, zip, bla bla via image file manager.
Please fix it, thanks

**Comment by g0110280** [comment]
@laypassmail Did you mean that you cannot upload those files even after setting `valid_image_types` in `config/lfm.php`?

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.
