### ISSUE TITLE
Problem cropping and resizing: 500 error

### ISSUE THREAD

**Issue by vivekpadhye** [UniSharp/laravel-filemanager#230]
I configured everything according to the documentation and Integration. I can upload files now, but unable to crop and resize the same uploaded image. 
I get following error in console 

`Failed to load resource: the server responded with a status of 500 (Internal Server Error) - http://127.0.0.1:8000/laravel-filemanager/doresize?img=http%3A%2F%2F127.0.0.1%3A8000%2Fphotos%2F1%2F835e871b8f5105255b1ead21947b6799.jpeg&working_dir=%2F1&dataHeight=&dataWidth=&=1490245875358 `

And if I go to the link above it throws an error 

```
NotReadableException in AbstractDecoder.php line 335:
Image source not readable
```

How to resolve this 500 Internal Server Error error?

**Comment by g0110280** [comment]
Related to #213 .

**Comment by vivekpadhye** [comment]
@g0110280 thanks. It worked for crop but does not work for resize. I did the same in `doResize()` function in `resize.blade.php` img: `img: '{{ parse_url($img, PHP_URL_PATH) }}'`. Can you guide me here. What should I change for it to resize

**Comment by fmarkos** [comment]
@vivekpadhye 

  function doResize() {
    $.ajax({
      type: "GET",
      dataType: "text",
      url: "{{ route('unisharp.lfm.performResize') }}",
      data: {
        img: '{{ parse_url($img, PHP_URL_PATH) }}',
        // img: '{{ $img }}',
        working_dir: $("#working_dir").val(),
        dataX: $("#dataX").val(),
        dataY: $("#dataY").val(),
        dataHeight: $("#height").val(),
        dataWidth: $("#width").val()
      },
      cache: false
    }).done(function (data) {
      if (data == "OK") {
        loadItems();
      } else {
        notify(data);
      }
    });
  }

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.
