### ISSUE TITLE
HTTPS Filemanager

### ISSUE THREAD

**Issue by Jurhillebrink** [UniSharp/laravel-filemanager#236]
For HTTPS I set behind all asset url's , true. That works. But I get two errors and I don't understand it:

http://www.site.com/folders?working_dir=&type=Images&_=1490370299854 , mixed content. 
http://www.site.com/laravel-filemanager/errors?working_dir=&type=Images&_=1490370299855, mixed content
I don't know which URL it is in which file. Can someone help me?

**Comment by g0110280** [comment]
Please upgrade to v1.7.2.
