### ISSUE TITLE
Standalone button

### ISSUE THREAD

**Issue by abumafrim** [UniSharp/laravel-filemanager#237]
I have tried to use the standalone button, but I couldnt. Can anyone help please. The steps provided are not clear to me

**Comment by g0110280** [comment]
There are already-integrated [codes](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/demo.blade.php) in `vendor/unisharp/laravel-filemanager/src/views/demo.blade.php`. See if it helps.
