### ISSUE TITLE
Routes don't work on a production server (DigitalOcean)

### ISSUE THREAD

**Issue by euryrodriguez** [UniSharp/laravel-filemanager#238]
**Hello
Sorry for bothering you and for my English, becuase is not that good, but, I need your help.**

I'm trying to use **laravel-filemanager** with Ckeditor on my production server and I'm getting a 404 error. I'm using **laravel 5.2**  on ubuntu 16.04 , but it's not working. I have tried many things , such as copy the content of \Unisharp\Laravelfilemanager\route.php to the App/http/routes.php file, but when I do this, I get this error **error array_merge(): Argument 2 is not an array** . I set the **use_package_routes** to false but I still have the same problem.

if I execute **php artisan route:list** on my **local** server, I get the rotes of the package:

`|        | GET|HEAD                       | laravel-filemanager                                                                 | unisharp.lfm.show                 | \Unisharp\Laravelfile
manager\controllers\LfmController@show               | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/crop                                                            | unisharp.lfm.getCrop              | \Unisharp\Laravelfile
manager\controllers\CropController@getCrop           | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/cropimage                                                       | unisharp.lfm.getCropimage         | \Unisharp\Laravelfile
manager\controllers\CropController@getCropimage      | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/delete                                                          | unisharp.lfm.getDelete            | \Unisharp\Laravelfile
manager\controllers\DeleteController@getDelete       | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/deletefolder                                                    | unisharp.lfm.getDeletefolder      | \Unisharp\Laravelfile
manager\controllers\FolderController@getDeletefolder | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/demo                                                            | unisharp.lfm.                     | \Unisharp\Laravelfile
manager\controllers\DemoController@index             | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/doresize                                                        | unisharp.lfm.performResize        | \Unisharp\Laravelfile
manager\controllers\ResizeController@performResize   | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/download                                                        | unisharp.lfm.getDownload          | \Unisharp\Laravelfile
manager\controllers\DownloadController@getDownload   | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/errors                                                          | unisharp.lfm.getErrors            | \Unisharp\Laravelfile
manager\controllers\LfmController@getErrors          | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/folders                                                         | unisharp.lfm.getFolders           | \Unisharp\Laravelfile
manager\controllers\FolderController@getFolders      | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/jsonitems                                                       | unisharp.lfm.getItems             | \Unisharp\Laravelfile
manager\controllers\ItemsController@getItems         | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/newfolder                                                       | unisharp.lfm.getAddfolder         | \Unisharp\Laravelfile
manager\controllers\FolderController@getAddfolder    | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/rename                                                          | unisharp.lfm.getRename            | \Unisharp\Laravelfile
manager\controllers\RenameController@getRename       | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD                       | laravel-filemanager/resize                                                          | unisharp.lfm.getResize            | \Unisharp\Laravelfile
manager\controllers\ResizeController@getResize       | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |
|        | GET|HEAD|POST|PUT|PATCH|DELETE | laravel-filemanager/upload                                                          | unisharp.lfm.upload               | \Unisharp\Laravelfile
manager\controllers\UploadController@upload          | web,\Unisharp\Laravelfilemanager\middlewares\MultiUser,\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder |`

But when I run this command on  digitalocean, I don't see  the routes of the package and I followed this guide to the letter [http://unisharp.github.io/laravel-filemanager/installation](url).

I got this inside my **blade** file:

  var options = {
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
        };

        CKEDITOR.replace( 'content',options);

I would appreciate your thoughts on this.

best regards **elfuerte36**

**Comment by euryrodriguez** [comment]
I realized that this method return null, I don't know why

$middleware = array_merge(\Config::get('lfm.middlewares'), [
    '\Unisharp\Laravelfilemanager\middlewares\MultiUser',
    '\Unisharp\Laravelfilemanager\middlewares\CreateDefaultFolder'
]);

can someone explain me what does this method?

**Comment by youchenlee** [comment]
@euryrodriguez Thank you for providing us the details.
For now I only think of two reasons:
1. Make sure you have the configs published by `php artisan vendor:publish --tag=lfm_config`
2. Try cleaning the route cache by `php artisan route:clear` [ref](https://laravel.com/docs/5.4/controllers#route-caching)

Please me know if got any updates.

**Comment by euryrodriguez** [comment]
Thanks for your help, I'll try that out and I'll let you know what happened.

**Comment by euryrodriguez** [comment]
The issue is resolved. 

I cleared the route cache and I change permissions of the file (in config/lfm.php) to writable 

Thanks for your help.
