### ISSUE TITLE
Can't access subfolders.

### ISSUE THREAD

**Issue by 1dot44mb** [UniSharp/laravel-filemanager#24]
I can not navigate into subfolders. The package always asks for folders from the server appended to "files_url" as if it is a root folder in "files_dir". 

Thanks.

**Comment by 1dot44mb** [comment]
This happens when "allow_multi_user" is set to false.

**Comment by youchenlee** [comment]
Hi @1dot44mb
What operation system is your server on? And what are your files_url and files_dir settings?
Thanks.

**Comment by 1dot44mb** [comment]
Hi,
Ubuntu vagrant box. Laravel 5.2
The absolute path to files_dir is '/vagrant/public/files/'  

    'allow_multi_user'   => false,
    'user_field'         => 'id',
    'shared_folder_name' => 'shares',
    'thumb_folder_name'  => 'thumbs',
    'images_dir'         => 'public/files/',
    'images_url'         => '/files/',
    'files_dir'          => 'public/files/',
    'files_url'          => '/files/',

**Comment by youchenlee** [comment]
@1dot44mb Thank you. I will check this tomorrow.

**Comment by youchenlee** [comment]
Sorry for late reply.
It looks like filemanager currently only support 1 level folder.
Issue relates to #26 and #34
We are working on it.

**Comment by youchenlee** [comment]
Fixed by @g0110280 in https://github.com/UniSharp/laravel-filemanager/releases/tag/1.4.0-alpha
Allow creating unlimited, multi-level folders.
