### ISSUE TITLE
You should create routes to serve images if it is not set to public.

### ISSUE THREAD

**Issue by hermawanheri66** [UniSharp/laravel-filemanager#241]
how to make routes if it is not set to public ? give examples?

**Comment by g0110280** [comment]
@hermawanheri66 See [this comment](https://github.com/UniSharp/laravel-filemanager/issues/211#issuecomment-289145866) from #211 .

**Comment by hermawanheri66** [comment]
"Folder name cannot be empty!" if delete file why? @g0110280

**Comment by g0110280** [comment]
It might be a bug. Please open a new issue.

**Comment by hermawanheri66** [comment]
sorry will iam create new issue
