### ISSUE TITLE
"Folder name cannot be empty!" if delete file why?

### ISSUE THREAD

**Issue by hermawanheri66** [UniSharp/laravel-filemanager#242]
please give me solution

**Comment by g0110280** [comment]
Related to #241 , might due to setting `base_directory` other than `public`. Will check this soon.

**Comment by traoredbrm** [comment]
have the same probleme (Laravel 5.4)

**Comment by g0110280** [comment]
Please upgrade to `v1.7.6`.

**Comment by gabuladze** [comment]
I'm having the same problem. Laravel 5.4, file manager 1.7.6; base_directory is public

**Comment by albertcht** [comment]
Please upgrade your package to `v1.8.0` to see if this issue still exists.

**Comment by DenimaMab** [comment]
Same problem with v1.8.

**Comment by DenimaMab** [comment]
Problem resolved.
The problem is that the
` 'base_directory' => 'public/uploads/'`
 were having a slash at the end.
delete that last slash and all will work perfectly.   @g0110280

**Comment by g0110280** [comment]
@DenimaMab thank you, we should add that to our document.

**Comment by g0110280** [comment]
This issue is solved in `v1.8.2-alpha`.

**Comment by g0110280** [comment]
Done in `v2.0.0-alpha`.
