### ISSUE TITLE
Problem with crop and resize in AWS

### ISSUE THREAD

**Issue by cevv13** [UniSharp/laravel-filemanager#245]
I have problem with crop and resize in amazon web services .. I am using the latest version which has already corrected that problem with the use of:

img: '{{ parse_url($img, PHP_URL_PATH) }}',

I even tried it as it was before and it does not work ... I throw the error:

NotReadableException in AbstractDecoder.php line 335:
Image source not readable

**Comment by g0110280** [comment]
Please upgrade to `v1.7.6`.
