### ISSUE TITLE
URL with double forward slashes, before the actual file

### ISSUE THREAD

**Issue by maquiavel** [UniSharp/laravel-filemanager#246]
Hello, I'm getting the url path like this -> http://localhost:8000/uploads//image.png 
I only change the  images folders to uploads. Can someone help me with this? 

anyway thank's UniSharp for this package

**Comment by g0110280** [comment]
@maquiavel Please paste you config here.

**Comment by johnef** [comment]
I had the same issue before, and this what I did in the config/lfm.php
under working directory

```
'base_directory' => 'public',

    'images_folder_name' => 'images/resources',
    'files_folder_name' => 'images/files',

    'shared_folder_name' => 'shares',
    'thumb_folder_name' => 'thumbs',
```

and this worked fine with me.

**Comment by g0110280** [comment]
Please upgrade to `v1.8.2-alpha`.
