### ISSUE TITLE
I can't upload files (AGAIN)

### ISSUE THREAD

**Issue by waska14** [UniSharp/laravel-filemanager#249]
Hello, can you help me? 
I upgraded to version 1.7

There is my lfm.php
`
    'max_image_size' => 5000,
    'max_file_size' => 100000,

    // available since v1.3.0
    'valid_image_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif'
    ],

    // available since v1.3.0
    // only when '/laravel-filemanager?type=Files'
    'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'application/pdf',
        'text/plain',
    ],`

I Can upload images but if i try to upload any file, it goes on error.

Can anybody help? 

Here is the video / GIF: http://recordit.co/oXrADRkx4c

**Comment by shamilchoudhury** [comment]
Enable `exif` support for PHP.

If you are on Windows, edit your `php.ini` file and uncomment these two lines:
```
extension=php_mbstring.dll
extension=php_exif.dll 
```
make sure the order of the extensions are same as above ( `exif` depends on `mbstring` and hence `mbstring` should be loaded first).

If you are on Ubuntu, run the following command:
```
ls `php -i | grep "^extension_dir" | sed -e 's/.*=> //'`
```
This will display a list of all the installed extensions in your system. Check if `exif.so` and `mbstring.so` are present in the list. If you do not spot these two extensions listed, you can install them easily:
```
sudo apt-get install php7.0-mbstring && sudo apt-get install php7.0-common
```

**Comment by g0110280** [comment]
Please upgrade to `v1.7.2`.
