### ISSUE TITLE
Can't navigate up

### ISSUE THREAD

**Issue by 1dot44mb** [UniSharp/laravel-filemanager#25]
"Back to parent folder" button is missing.

Thanks.

**Comment by youchenlee** [comment]
Thanks. Bug confirmed. Should be fixed in a few days.

**Comment by youchenlee** [comment]
fixed by @g0110280

**Comment by youchenlee** [comment]
Released in https://github.com/UniSharp/laravel-filemanager/releases/tag/1.4.0-alpha
