### ISSUE TITLE
Navbar toggle button in mobile version

### ISSUE THREAD

**Issue by maupasquotto** [UniSharp/laravel-filemanager#251]
Hello :)

I recently found a bug with the toggle navbar button. 
When using the filemanager in mobile version, the button to toggle the navbar doesn't work properly. 

I researched the bug in the file [laravel-filemanager/src/views/index.blade.php](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/index.blade.php) and I found out that the data-target of the button (navbar-toggle) isn't right and the "\<div class="collapse navbar-collapse">" is missing the ID so the button can find it.

**Comment by g0110280** [comment]
Thank you @maupasquotto .

**Comment by g0110280** [comment]
Fixed in `v1.7.2`.
