### ISSUE TITLE
AngularJS get value of text input is undefined when use lrf as 'standalone button'

### ISSUE THREAD

**Issue by hungelc** [UniSharp/laravel-filemanager#257]
Hi all,

I use lrf as below
```
 <div class="input-group">
   <span class="input-group-btn">
     <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
       <i class="fa fa-picture-o"></i> Choose
     </a>
   </span>
   <input id="thumbnail" class="form-control" type="text" name="filepath" value="<% slider.image %>" ng-model="slider.image">
 </div>
 <img id="holder" style="margin-top:15px;max-height:100px;">
```

I use angularjs get value of slider.image model when the button click function. 
```
// Save new slider and upate existing slider
$scope.save = function(modalstate, id) {
$log.log($scope.slider);
$log.log($scope.slider.image);
.....
```

$scope.slider.image value is undefined but another value of slider is valid.I tried edit text in thumbnail input and click button again, $scope.slider.image is valid. Can you please tell me how to fix this ?
![image](https://cloud.githubusercontent.com/assets/21072916/24815834/d301e5b8-1c00-11e7-8ff6-244ebbd68763.png)

**Comment by g0110280** [comment]
Cannot confirm the issue is related to this package.

**Comment by hungelc** [comment]
I found the cause of my issue. ngModal of AngularJS listens for 'input' event. I edited lfm.js file as below and it worked successfully.

function SetUrl(url, file_path){
  //set the value of the desired input to image url
  var target_input = $('#' + localStorage.getItem('target_input'));
  target_input.val(file_path);
  target_input.trigger('input'); // Use for Chrome/Firefox/Edge
  target_input.trigger('change'); // Use for Chrome/Firefox/Edge + IE11

  //set or change the preview image src
  var target_preview = $('#' + localStorage.getItem('target_preview'));
  target_preview.attr('src', url);
}
