### ISSUE TITLE
Bug when creating a folder in subfolder

### ISSUE THREAD

**Issue by 1dot44mb** [UniSharp/laravel-filemanager#26]
When i create a folder in a subfolder; two folders get created; one in subfolder (appropriate place) and another in the same level as the folder i am in (buggy).

Thanks.

**Comment by youchenlee** [comment]
@1dot44mb I'm sorry for these buggy subfolder features.
Bug confirmed. Will check it tomorrow.

**Comment by g0110280** [comment]
Hello, @1dot44mb .
We currently support only two-level folders.
This issue will be a future feature.

**Comment by 1dot44mb** [comment]
Thanks @g0110280

**Comment by youchenlee** [comment]
We should remove the "create folder" button at the second level folder. @g0110280

**Comment by youchenlee** [comment]
Fixed by @g0110280 in https://github.com/UniSharp/laravel-filemanager/releases/tag/1.4.0-alpha
Allow creating unlimited, multi-level folders.
