### ISSUE TITLE
Upload and create multiple copy in different resolution of the image

### ISSUE THREAD

**Issue by nasirkhan** [UniSharp/laravel-filemanager#260]
Is there any option to upload a image and automatically create several copies in different resolution. It could be similar as creating thumbnails. 

Can you please help me to resolve this situation?

**Comment by g0110280** [comment]
https://github.com/UniSharp/laravel-filemanager/blob/master/src/controllers/UploadController.php#L140-L142
Duplicate these lines and fill in the sizes you want.

**Comment by g0110280** [comment]
Another solution might be to listen to `ImageWasUploaded` event, and create more thumbnails in your event listener. The list of events is in [event document](http://unisharp.github.io/laravel-filemanager/events).

**Comment by nasirkhan** [comment]
i think this might be better. I will try to implement that and will inform you the updates.
