### ISSUE TITLE
Action failed, due to server error. 

### ISSUE THREAD

**Issue by traoredbrm** [UniSharp/laravel-filemanager#263]
LOG.error: InvalidArgumentException: The "/home/vagrant/www/laravel/public/storage/photos/4" **directory does not exist**. in /home/vagrant/www/laravel/vendor/symfony/finder/Finder.php:546

Have this probleme when I change  "base_directory" to 'public/storage'. **I use laravel 5.4**
``
![image](https://cloud.githubusercontent.com/assets/19824939/24923055/415d4f7c-1ee8-11e7-8177-57ff011cb409.png)

**Comment by g0110280** [comment]
Duplicate issue of #131 .

**Comment by g0110280** [comment]
Please upgrade to v1.7.2. The message "Action failed, due to server error." occurs when ajax requests fail in any reason. So this issue is ambiguous. Exception messages will be displayed instead of "Action failed, due to server error." in v1.7.2.
