### ISSUE TITLE
File-manager view in existing DOM element(container)

### ISSUE THREAD

**Issue by martins54blue** [UniSharp/laravel-filemanager#264]
Hi. I am building CMS and try to find way, how to implement this plugin in laravel view (not as modal, but as normal view). In my case, I need to use this in both ways - standalone view and in tinymce. I found some questions about this, but no answers. Is there any possibility that this will be supported in future?
![image](https://cloud.githubusercontent.com/assets/17180175/24975035/f2d1b948-1fcc-11e7-9f99-74f99d6742ed.png)

P.S. I can use this plugin in this way only if I rewrite some views. If I do that, then I lose option to update plugin to newer versions.

**Comment by g0110280** [comment]
Use this [line](https://github.com/UniSharp/laravel-filemanager/blob/master/src/controllers/LfmController.php#L29).
