### ISSUE TITLE
Weird Folder list

### ISSUE THREAD

**Issue by annecchini** [UniSharp/laravel-filemanager#265]
Hi! 
I'm using:
ubuntu 14.04
apache2+php7+laravel5.3+TinyMCE4+Filemanager
GD library

I create a following folder list with my user:
1
- Images01
- Images02
- Images03
- Images04
- Teste01
- Teste02
- Teste03
- Teste04

But on the file manager the list show me this:

Files
- Images03
- Images02
- Teste01
- Images01
- Teste03
- Images04
- Teste02
- Teste04 

This is a "bug" or I'm doing something wrong?

**Comment by g0110280** [comment]
Cannot reproduce this in macOS. I should sort the folders by their names.

**Comment by ElioMS** [comment]
Having the same problem and i cant upload images :(

**Comment by g0110280** [comment]
@ElioMS Please check the following instructions  :
 * Make sure you are using the latest version.
 * If you are new to this package, make sure you followed every step from [installation document](http://unisharp.github.io/laravel-filemanager/installation).
 * If you have problem applying this package, please check the [integration document](http://unisharp.github.io/laravel-filemanager/integration).
 * If anything went broken after you upgraded, please check the [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade).

If your problem still remains, please do these steps :
 * run `php ./vendor/unisharp/laravel-filemanager/bin/debug` and paste the results here.
 * (optional) If there are errors in browser console, click on the links and you should see some PHP exceptions. Please capture screenshots and paste them here.

**Comment by ElioMS** [comment]
Hello i got this,
OS System & Version: Linux staffcreativaluhego-desktop 3.19.0-84-generic #92-Ubuntu SMP Fri Mar 24 15:46:19 UTC 2017 x86_64
Laravel Version: v5.4.19
File Manager Version: v1.7.5
imagick Extension: Not Install
gd Extension: Install

**Comment by g0110280** [comment]
@ElioMS Is there any error in console?

**Comment by ElioMS** [comment]
@g0110280 I'm not getting any errors in my console

**Comment by ElioMS** [comment]
![erroflm](https://cloud.githubusercontent.com/assets/25486631/25439781/0b4d9640-2a63-11e7-92f0-3547b3eec76a.png)

Idk what is the first line! My FLM is not working :(

**Comment by g0110280** [comment]
@annecchini @ElioMS Please follow [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.6`.
