### ISSUE TITLE
File are upload but not show Laravel 5.4. Action failed, due to server error.

### ISSUE THREAD

**Issue by Neanrakyr** [UniSharp/laravel-filemanager#266]
Hi so here the error I have

Action failed, due to server error.

Console:
jquery.js:9659 GET http://localhost:8000/laravel-filemanager/jsonitems?working_dir=%2F2%2Fsddsdsds&type=Files&_=1492205804041 500 (Internal Server Error)

I can create folder and see it, I can upload, and it upload but I cannot See the file/Image I upload.

**Comment by g0110280** [comment]
Please see the error in http://localhost:8000/laravel-filemanager/jsonitems?working_dir=%2F2%2Fsddsdsds&type=Files&_=1492205804041 and post the exception here.

**Comment by Neanrakyr** [comment]
@g0110280 ErrorException in LfmHelpers.php line 96:
preg_match(): Unknown modifier 't'

**Comment by pavinthan** [comment]
use https://github.com/jeylabs/vaultbox

**Comment by enjoyvinh** [comment]
I have problem same this issue.
When i upload source onto hosting, i can't upload file although data response is OK.
Laravel 5.4

**Comment by g0110280** [comment]
Please upgrade to v1.7.2. The message "Action failed, due to server error." occurs when ajax requests fail in any reason. So this issue is ambiguous. Exception messages will be displayed instead of "Action failed, due to server error." in v1.7.2.

**Comment by enjoyvinh** [comment]
Thank you so much,It worked normally.

**Comment by Neanrakyr** [comment]
Yeah work for me tooo :) 1.7.2 build ^^
