### ISSUE TITLE
Retrieving url for thumbnail using standalone 

### ISSUE THREAD

**Issue by MikeDynamic** [UniSharp/laravel-filemanager#269]
Hi 

I am trying to retrieve the thumbnail url. 
Currently the standalone is saving the url to my database as /photos/1/filename.jpg but it is also saving a thumbnail as photos/1/thumb/filename.jpg. 

Is there a way for me access the full size image url and the thumbnail url so that I can save both to the DB ? 

Thanks very much

**Comment by g0110280** [comment]
Try if the following works.
```
$lfm_helper = new \Unisharp\Laravelfilemanager\LfmHelper();
$full_file_path = ; // get this from db
$thumb_url = $lfm_helper->getThumbUrl($full_file_path);
```

**Comment by MikeDynamic** [comment]
Thank you very much

**Comment by MikeDynamic** [comment]
I have included the Class but I am getting the error 
```
FatalThrowableError in PostsController.php line 83:
Class 'Unisharp\Laravelfilemanager\LfmHelper' not found
```

**Comment by g0110280** [comment]
Sorry, LfmHelper's'.

**Comment by MikeDynamic** [comment]
np, it is still throwing the Class not found error :( 

I am using the latest version of 5.2 could that be the issue? 

I am also using 1.7 not 1.7.1

**Comment by g0110280** [comment]
Updated : `Unisharp\Laravelfilemanager\traits\LfmHelpers`.

**Comment by g0110280** [comment]
Updating to latest version is also suggested.

**Comment by MikeDynamic** [comment]
Thank you for the help but it still threw the same type of error. 
I am new to using a file manager in Laravel so I am probably doing something wrong :) 
I am still learning Laravel even though I have built a few blogs :) 
I did find a quick fix that will allow me to get the full-size img url that is submited by the create form and append the "thumb" to the url. 
Hopefully, this will help others, I will turn this into a function in a helpers.php file later but currently it will allow me to save it to the database should I need to :) 

Thank you  
`$img = $request['photo_path'];
 $img_thumb = explode('/', $img);
$directory = dirname($img);

 $thumbnail = $directory . '/thumb/' . end($img_thumb);
	    
$input['photo_thumb'] = $thumbnail;`

**Comment by g0110280** [comment]
You are welcome.

**Comment by nmpribeiro** [comment]
The getThumbUrl method from the trait is not accurately updated, as it is grabbing the thumbs from the wrong directory (not the thumb immediately next to the original file).

**Comment by BAKTETE** [comment]
> Unisharp\Laravelfilemanager\traits\LfmHelpers

Class 'Unisharp\Laravelfilemanager\traits\LfmHelpers' not found
