### ISSUE TITLE
bug crop and rezise

### ISSUE THREAD

**Issue by LusenkoSasha** [UniSharp/laravel-filemanager#272]
![image](https://cloud.githubusercontent.com/assets/27783985/25201387/35a5ace2-255a-11e7-88cc-f6c75351e66b.png)
![image](https://cloud.githubusercontent.com/assets/27783985/25201423/5bd69106-255a-11e7-8607-7df9edc87d5c.png)
![image](https://cloud.githubusercontent.com/assets/27783985/25201685/453c5768-255b-11e7-8e28-7120603446b3.png)

**Comment by g0110280** [comment]
Might be an issue with Windows, will check this soon.

**Comment by g0110280** [comment]
Please upgrade to `v1.7.6`.
