### ISSUE TITLE
Coalesce operator is available in PHP 7 only

### ISSUE THREAD

**Issue by johnef** [UniSharp/laravel-filemanager#273]
I have installed the package and everything was fine
now I integrated with `CKEDITOR`
Then I try to use it
Got this Error

`FatalErrorException in a7e5d3702983b3269d9bea975c6460c0ed23f401.php line 9: syntax error, unexpected '?'`

when I checked the file `a7e5d3702983b3269d9bea975c6460c0ed23f401.php` found this lines

```
<?php foreach($items as $item): ?>
  <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 img-row">
    <?php $item_name = $item->name; ?>
    <?php $thumb_src = $item->thumb; ?>
    <?php $folder_path = $item->path ?? ''; ?>
```

the problem is here `<?php $folder_path = $item->path ?? ''; ?>`
Coalesce operator is available in PHP 7 only

The file location [grid-view.blade](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/grid-view.blade.php)

what I did wrong here please

**Comment by johnef** [comment]
I try to edit this to be `<?php $folder_path = $item->path ? $item->path : '' ?>` got `Method Illuminate\View\View::__toString() must not throw an exception` any idea

**Comment by M1hai** [comment]
Well on PHP 5.6.30 had the same issue you're facing mate and I solved it like this:
inside grid-view.blade.php replace
<?php $folder_path = $item->path ?? ''; ?> (line 9 for me)
with this approach
<?php if(isset($item->path)) $folder_path = $item->path; else $folder_path = ''; ?>

**Comment by johnef** [comment]
Really you are wonderful :)

**Comment by michail1982** [comment]
https://github.com/UniSharp/laravel-filemanager/blob/master/src/LfmPath.php#L122
same truble php7-only syntax
