### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by ElioMS** [UniSharp/laravel-filemanager#275]
Hello guys, 

I did a composer update and getting this error.

**Comment by ElioMS** [comment]
I solve the first problem using json_decode but now im getting this error 

`FatalErrorException in ItemsController.php line 0:`
> Method Illuminate\View\View::__toString() must not throw an exception

**Comment by g0110280** [comment]
try `php artisan vendor:publish --tag=lfm_views --force`

**Comment by g0110280** [comment]
Please follow [this document](http://unisharp.github.io/laravel-filemanager/upgrade) from readme, and upgrade to `v1.7.5`.
