### ISSUE TITLE
Can't crop .svg file

### ISSUE THREAD

**Issue by arnbondzinskas** [UniSharp/laravel-filemanager#276]
Hello, when I try to crop .svg file I get 500 server error which says: NotReadableException in Decoder.php line 20: Unable to read image from file. Other formats crops correctly.

**Comment by g0110280** [comment]
Sorry for that, seem like intervention/image doesn't support .svg files.

**Comment by arnbondzinskas** [comment]
Ok, thanks! Atleast we can upload svg files! :)
