### ISSUE TITLE
After installation View [folders] not found

### ISSUE THREAD

**Issue by ahmedonee** [UniSharp/laravel-filemanager#277]
After installation View [folders] not found

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: View [folders] not found. (View: /Applications/MAMP/htdocs/***/vendor/unisharp/laravel-filemanager/src/views/grid-view.blade.php)

**Comment by g0110280** [comment]
Make sure to install the latest veriosn and run `php artisan vendor:publish --tag=lfm_views --force`.
