### ISSUE TITLE
error after installtion

### ISSUE THREAD

**Issue by tunglt1508** [UniSharp/laravel-filemanager#278]
![gggg](https://cloud.githubusercontent.com/assets/10413345/25301949/e959082a-275c-11e7-8c39-9b5739355f3b.PNG)

**Comment by g0110280** [comment]
Please capture screenshots of the exceptions inside the links and paste them here.

**Comment by g0110280** [comment]
Tested and worked fine. Cannot confirm what caused this error. Close issue for now.
