### ISSUE TITLE
How to publish "lang" folder?

### ISSUE THREAD

**Issue by Simpson1993** [UniSharp/laravel-filemanager#280]
How to publish "lang" folder? Translation for 'nav-sort', 'nav-sort-alphabetic',  'nav-sort-time' write only in English language. I need translation for Ukrainian language, but can not publish lang folder. String what I must add to uk/lfm.php file:
```
    'nav-sort'          => 'Сортування',
    'nav-sort-alphabetic' => 'За алфавітом',
    'nav-sort-time'     => 'За часом додавання',
```

**Comment by gwleuverink** [comment]
You can try to fork the repo and create a pull request to get your translation merged with the master branche. I'm sure the devs would appreciate that :)

**Comment by g0110280** [comment]
@Simpson1993 Please see the [customization document](http://unisharp.github.io/laravel-filemanager/customization#translations).
