### ISSUE TITLE
Can not upload images

### ISSUE THREAD

**Issue by amirzarafshani** [UniSharp/laravel-filemanager#282]
Hi.
My laravel based website is under the "src" folder like this: http://mydomain.com/src/
I was following the installation guide carefully and upgrade unisharp filemanager.
File and folder upload is working fine, but image upload dosn't work and upload nothing!
The file manager styles and scripts don't load because of their wrong path.
I think I should change the routs but I don't know how to do...
Please help me.
thnx.

**Comment by ElioMS** [comment]
Are you having these problems? https://github.com/UniSharp/laravel-filemanager/issues/265

**Comment by g0110280** [comment]
@amirzarafshani Please post screenshots of your console.

**Comment by amirzarafshani** [comment]
The root of my site is like this:
![root](https://cloud.githubusercontent.com/assets/28008650/25418777/81e27384-2a63-11e7-9b1d-ab4e7922090a.jpg)
and the laravel project is in the "src" folder of root:
![laravel](https://cloud.githubusercontent.com/assets/28008650/25418810/c36c43ca-2a63-11e7-8bcd-65fc4482012a.jpg)
and the file manager is showen like this:
![file manager](https://cloud.githubusercontent.com/assets/28008650/25418846/097cd73a-2a64-11e7-9363-cf93f7d54a8e.jpg)
the files and folders are uploading and editing successfully but only images dosn'y uploadding.
When I puting the image file with ftp in photo's folder the image in file manager is showen like this:
![file manager and image](https://cloud.githubusercontent.com/assets/28008650/25418977/d7d13ca2-2a64-11e7-8b54-ce59555d7cf3.jpg)

**Comment by amirzarafshani** [comment]
I think if you put an option in config file as "root directory" , this problem will be solved.

**Comment by g0110280** [comment]
@amirzarafshani The 3rd and 4th screenshots indicated that images were uploaded successfully, but thumbnails could not be found. It means that if you upload files through FTP, you should also upload the same files to thumbnail folder. Or you can wait for `v1.7.6` release, which will retrieve original image as thumbnail if the thumbnail is not found.

**Comment by amirzarafshani** [comment]
> The 3rd and 4th screenshots indicated that images were uploaded successfully
No it is not. I put the images with ftp and their dosn't upload with the file manager.
I still can not upload photos with file manager.

**Comment by g0110280** [comment]
Please follow [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.6`.

**Comment by amirzarafshani** [comment]
already tried and doesnt work.
because my project is under the "root/src" folder and Because of this, Even css and js files are not loaded properly. Image upload also does not work.

**Comment by g0110280** [comment]
Please post your console error as well.

**Comment by Nebudev** [comment]
Try this to artisan commands, you can find them on step 3 of installation.
 php artisan vendor:publish --tag=lfm_config
 php artisan vendor:publish --tag=lfm_public

**Comment by alfo1** [comment]
https://github.com/UniSharp/laravel-filemanager/issues/499#issuecomment-395771014
