### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by journeyman73** [UniSharp/laravel-filemanager#285]
with these settings in the config
// If true, private folders will be created for each signed-in user.
    'allow_multi_user' => false,
    // If true, share folder will be created when allow_multi_user is true.
    'allow_share_folder' => false,

you get a an error whilst trying to upload
of 
InvalidArgumentException in Finder.php line 546:
The "/Applications/MAMP/htdocs/cms/public/uploads/user_images/ms/public/uploads/user_images/user_shares" directory does not exist.

**Comment by g0110280** [comment]
Please upgrade to `v1.7.6`.
