### ISSUE TITLE
iconv(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by allaghi** [UniSharp/laravel-filemanager#289]
I am trying to create new folder using arabic name , it gives me this error message .
iconv(): Detected an illegal character in input string

**Comment by waister** [comment]
Same problem here :(

**Comment by vertisan** [comment]
Same here too...

**Comment by talgatbaltasov** [comment]
same problem, any ideas?

**Comment by g0110280** [comment]
Please upgrade to `v1.8.1`.
