### ISSUE TITLE
pdf/docs  support?

### ISSUE THREAD

**Issue by od3n** [UniSharp/laravel-filemanager#29]
```
NotReadableException in Decoder.php line 20:
Unable to read image from file 
```

**Comment by g0110280** [comment]
Thanks for reporting this.
Will fix this issue later.

**Comment by youchenlee** [comment]
@od3n 
This [1.3.0-alpha](https://github.com/UniSharp/laravel-filemanager/releases/tag/1.3.0-alpha) release is now supporting strict MIME type check.  Please set `valid_file_mimetypes` array and make sure you have `type=Files` in the URL. The [README](https://github.com/UniSharp/laravel-filemanager/blob/master/README.md) might have for more detail.

Please give it a try.
