### ISSUE TITLE
Unable to download a file in 'grid display type for items'

### ISSUE THREAD

**Issue by maupasquotto** [UniSharp/laravel-filemanager#290]
Hi,
I've noticed that the package has a slight difference between file options when using 'grid display' and 'list display'. 

![image](https://cloud.githubusercontent.com/assets/9861930/25618556/c8f74ad8-2f1d-11e7-85e2-5cea7c2beea3.png)

![image](https://cloud.githubusercontent.com/assets/9861930/25618612/0c629d5e-2f1e-11e7-9cb4-1dd3113e2c95.png)

The 'grid display type' has fewer options than the 'list display type'. Is there any reason to this difference ?
In my application, I'd use the 'list display' because It's not needed to preview a file however the 'list display' doesn't have the download, preview or rename button.

Thanks :)

**Comment by g0110280** [comment]
Done in `v2.0-dev` branch.
