### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by diz123** [UniSharp/laravel-filemanager#292]
I have this error,cant view image or folder inside .
Upload file still working but cant show. Any ideal for that?
![capture 1](https://cloud.githubusercontent.com/assets/10492139/25697609/d76edf1c-30e5-11e7-8792-74f72686969e.JPG)

![capture](https://cloud.githubusercontent.com/assets/10492139/25697273/8594c838-30e4-11e7-8fc7-35306ed6aad1.JPG)

OS System & Version: Windows NT V 6.3 build 9600 (Windows 8.1 Home Premium Editi
on) i586
Laravel Version: v5.4.19
File Manager Version: v1.7.5
imagick Extension: Install
gd Extension: Install

**Comment by g0110280** [comment]
Please follow the [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade).

**Comment by diz123** [comment]
I fogort publish view. Sorry and thanks you !
