### ISSUE TITLE
add watermark on this package

### ISSUE THREAD

**Issue by webafra** [UniSharp/laravel-filemanager#295]
hello and Thank you, because created this tool :)

Please add watermark feature to upload images and Set watermark path into config file .

i edite UploadController.php and add this Code : 
`
$watermark = public_path().'/watermark.png';
                if(file_exists($watermark))
                {
                    Image::make($file->getRealPath())
                         ->orientate()
                         ->insert(public_path().'/watermark.png', 'bottom-right', 10, 10)
                         ->save($new_file_path, 90);
                }
                else
                {
                    Image::make($file->getRealPath())
                         ->orientate()
                         ->save($new_file_path, 90);
                }
`

but if update your package , my code don't work .

thanks :)

**Comment by g0110280** [comment]
Thank you @m-alinasab . At this moment, you can move you code to a event listener, which listens to `Unisharp\Laravelfilemanager\Events\ImageWasUploaded` event. See available events from the [events document](http://unisharp.github.io/laravel-filemanager/events).
