### ISSUE TITLE
laravel file manager not showing any files

### ISSUE THREAD

**Issue by rtanzifi** [UniSharp/laravel-filemanager#296]
Hi
I'm using laravel file manager in my website to upload images but the explorer window show nothing. Here is my lfm file config:
`  /*
    |--------------------------------------------------------------------------
    | Working Directory
    |--------------------------------------------------------------------------
    */

    // Which folder to store files in project, fill in 'public', 'resources', 'storage' and so on.
    // You should create routes to serve images if it is not set to public.
    'base_directory' => '../public_html',

     'images_folder_name' => 'Images',
     'files_folder_name'  => 'files',
     'shared_folder_name' => 'shares',
     'thumb_folder_name'  => 'thumbs',`

and here is my explorer screenshot
![pic1](https://cloud.githubusercontent.com/assets/16733912/25775304/9a503e7c-32b7-11e7-8382-b33324ace99a.PNG)
and here is my directory structure. All images should be upload in public_html/Images folder:
![pic2](https://cloud.githubusercontent.com/assets/16733912/25775306/ba5c44cc-32b7-11e7-919a-723cc4b2748c.PNG)
The console current work directory poined to : /shares
Whats wrong?

**Comment by rtanzifi** [comment]
Any help would be appreciate

**Comment by rtanzifi** [comment]
It's been 3 days and nobody answer. please help us

**Comment by gwleuverink** [comment]
Does it work if you create a 'shares' directory inside of the Images directory?

**Comment by rtanzifi** [comment]
I already have shares directory inside Images directory

**Comment by g0110280** [comment]
`'base_directory' => 'public_html'`, remove '../'

**Comment by rtanzifi** [comment]
now it gives me 505 internal error: blog/public_html/Images/shares" directory does not exist.
and that is true because public_html is outside of blog(my laravel application folder)

**Comment by rtanzifi** [comment]
It seems there is a problem with php exif module. After re-installing module i can upload image. But the directory problem still exist. I mean why explorer starts from shares directory? I just want to upload all of my files including images,files and...etc in Images directory.

**Comment by g0110280** [comment]
Please upgrade to `v1.8.2-alpha`.

**Comment by g0110280** [comment]
@rtanzifi check you `config/lfm.php` and see if `allow_multi_user` is `true` or not.
