### ISSUE TITLE
UniSharp/laravel-filemanager error (Trying to get property of non-object)

### ISSUE THREAD

**Issue by bantawa04** [UniSharp/laravel-filemanager#299]
I'm using UniSharp/laravel-filemanager with tinyMCE 4. When I click file explorer button. I gives out error in a bootstrap model. And the error is

`Trying to get property of non-object
(View: F:\moonlight\resources\views\public\tour\single.blade.php)`

It is requesting for route`(single.tour) which looks like:

`Route::group(['middleware' => ['web']], function () {
    Route::get('{category}/{slug}','GetPublicController@singleTour')
            ->where('category', '[A-Za-z\d\-\_]+')
            ->where('slug', '[A-Za-z\d\-\_]+')
            ->name('single.tour');
});`
when I comment out or remove the above route file explorer works perfectly. I have used this package in my previous projects but never had this problem and I am not using Sentinal ACL package like previous issue.

**Comment by g0110280** [comment]
@bantawa04 You might need to add `auth` middleware into your routing.

**Comment by bantawa04** [comment]
Gave shot to your suggestion still same error. 
`Route::group(['middleware' => ['auth']], function () { 
     Route::get('{category}/{slug}','GetPublicController@singleTour') ->where('category', '[A-Za-z\d\-\_]+') ->where('slug', '[A-Za-z\d\-\_]+') ->name('single.tour');
 });`

**Comment by g0110280** [comment]
This might not be a routing issue. Please paste the line which throws the exception from your view.
