### ISSUE TITLE
where are the routes?

### ISSUE THREAD

**Issue by AmrAlfoly** [UniSharp/laravel-filemanager#30]
what are the routes to add to my routes.php file so i can access the scaipt?
i tried to point the route to the package folder to LfmController but it says that it can't be accessed

**Comment by youchenlee** [comment]
@AmrAlfoly 
I'm not quite sure about your question, would you explain it more?
The route file: (https://github.com/UniSharp/laravel-filemanager/blob/master/src/routes.php) will be loaded by the ServerProvider (https://github.com/UniSharp/laravel-filemanager/blob/master/src/LaravelFilemanagerServiceProvider.php#L21)

**Comment by g0110280** [comment]
@AmrAlfoly The package generates routes by default, meaning you don't need to set route by yourself.
If you need to customize the routes, see customization document by the link below.
https://github.com/UniSharp/laravel-filemanager/blob/master/doc/customization.md
