### ISSUE TITLE
Uploading a regular file (PDF) causes UploadedFile::path() error

### ISSUE THREAD

**Issue by PendoNL** [UniSharp/laravel-filemanager#301]
![Upload Error](https://preview.ibb.co/kcfSFk/Schermafbeelding_2017_05_08_om_17_58_27.png)

Looks like a method is used that doesn't exists. I tried looking for other issues but the method `$file->path()` is only used when uploading files. When uploading images `$file->getRealPath()` is used. After replacing the first with the second for file uploads, I was able to upload files again.

PR: https://github.com/UniSharp/laravel-filemanager/pull/300

**Comment by g0110280** [comment]
Thanks for your PR @PendoNL .

**Comment by jonjie0317** [comment]
@PendoNL  I updated this package and now, it returns an error :<br> 

> TokenMismatchException in VerifyCsrfToken.php line 53:

<br><br>
Thanks

**Comment by PendoNL** [comment]
That seems unrelated to this package or issue @jonjie0317

**Comment by jonjie0317** [comment]
@PendoNL it's the file size, I tried to upload lower size file, and it worked. do you have any idea for this, so I can set the file size to be uploaded.

**Comment by jonjie0317** [comment]
@PendoNL  I also tried `'max_file_size' => 900000`, but nothings changed.

**Comment by gwleuverink** [comment]
@jonjie0317 If it's the file size please check out [this thread](https://github.com/UniSharp/laravel-filemanager/issues/312)

Setting 'max_file_size' doesn't work because the setting is overwritten in the same request as you are uploading the file in. You have to edit this in your php.ini file.

**Comment by PendoNL** [comment]
The filesize has nothing to do with a tokenMismatchException as far as I know. The GD Library does use a lot of memory so you might want to look at the bottom of config/laravel-filemanager.php to this setting: https://github.com/UniSharp/laravel-filemanager/blob/master/src/config/lfm.php#L167

Try increasing it to 512 or 1024M (but be sure you server can allocate such amount before increasing). I'm also still having some issues here and there with large files and I'm looking to move to Imagick since that should use less memory.

**Comment by gwleuverink** [comment]
I agree that a token mismatch exception doesn't have anything to do with the file size. The csrf token doesn't seem to be valid. The token is sent along with every ajax request. Do you have any errors in your javascript console?

**Comment by jonjie0317** [comment]
@PendoNL  hm, Thank you for that. But, just confused, why is that happening, if I upload a lower file size, it worked, but if I upload a large size (about 24MB), it returns the same error.

**Comment by jonjie0317** [comment]
@gwleuverink hm there's no error out in js console. hmm

**Comment by PendoNL** [comment]
Only thing I can guess is that your server doesn't have enough memory left to persist the CSRF Token in the request. Sounds strange, but there is no other relation to the CSRF token and the filesize but the memory limit it is stored in.

Have you tried increasing the memory limit as I said?

**Comment by jonjie0317** [comment]
@PendoNL yes, but still now working for large files. And... also no validation or message that says "The maximum file size must be 17MB or lower.", so users will know how big the file they can upload.

**Comment by PendoNL** [comment]
That it's not working for large files doesn't mean it doesn't have anything to do with the memory limit. Did you enable debugging and full error logging in Laravel? The maximum filesize *IS NOT* the same as the memory limit. In my tests, GD roughly takes up 10 times the amount of space in memory to handle an image.

If you can't supply more debugging details, I'm afraid I can't help you any further.

**Comment by jonjie0317** [comment]
@PendoNL I apologize for that sir. But one more question, do you have any suggestion on how can I put a message there, that says "The maximum file size must be 17MB" something like that. Thanks a lot men!

**Comment by PendoNL** [comment]
I think this is a different issue, looks like there is a filesize check (https://github.com/UniSharp/laravel-filemanager/blob/master/src/controllers/UploadController.php#L84), I'm unable to help for a few days due to a busy week coming up!
