### ISSUE TITLE
Action failed, due to server error.

### ISSUE THREAD

**Issue by stevemanes** [UniSharp/laravel-filemanager#302]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * If you are new to this package, make sure you followed every step from [installation document](http://unisharp.github.io/laravel-filemanager/installation).
 * If you have problem applying this package, please check the [integration document](http://unisharp.github.io/laravel-filemanager/integration).
 * If anything went broken after you upgraded, please check the [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade).

If your problem still remains, please do these steps :
 * run `php ./vendor/unisharp/laravel-filemanager/bin/debug` and paste the results here.
 * (optional) If there are errors in browser console, click on the links and you should see some PHP exceptions. Please capture screenshots and paste them here.

**Comment by stevemanes** [comment]
I did a "composer update" this evening and now I'm getting this error when I click on the "insert image" icon on TinyMCE.  This appears in a popup over the FileManager.

Action failed, due to server error.

![screen shot 2017-05-08 at 10 18 16 pm](https://cloud.githubusercontent.com/assets/2812783/25832986/4a6eba92-343c-11e7-803e-ea61a97d0d45.png)

I also get this error in the Laravel log:

[2017-05-08 22:11:07] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: View [folders] not found. (View: /web/hrl/vendor/unisharp/laravel-filemanager/src/views/grid-view.blade.php) in /web/hrl/vendor/unisharp/laravel-filemanager/src/controllers/ItemsController.php:0
Stack trace:
#0 {main}  

I get this same error whenever I try to click on one of the image directories. 

The directories and images are owned by the web server owner, www:www.

root@paco:/web/hrl# php ./vendor/unisharp/laravel-filemanager/bin/debug
OS System & Version: Linux paco.alphatest.net 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64
Laravel Version: v5.4.21
File Manager Version: v1.7.6
imagick Extension: Not Install
gd Extension: Install

**Comment by g0110280** [comment]
Please follow the [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade) and run `php artisan vendor:publish`.
