### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'SetUrl' of null

### ISSUE THREAD

**Issue by manozbiswas** [UniSharp/laravel-filemanager#304]
(Hello, I am using this cool package. I am facing a problem when I  clicked on any image item in both list view and grid view
![screenshot_1](https://cloud.githubusercontent.com/assets/6625569/26023697/edcd91ea-37e3-11e7-9ad4-73b8a72741ff.png)

![console](https://cloud.githubusercontent.com/assets/6625569/26023760/43ee12ba-37e5-11e7-9552-efca69356a41.png)

```
console.log(url);
console.log(file_path);
window.opener.SetUrl(url, file_path);
```

I logged the url and file_path arguments of the SetUrl function. Though I noticed that the two argument has some value the SetUrl returns  "Cannot read property 'SetUrl' of null" error as shown in the second screenshot.

I don't understand the problem. SetUrl gets some value so why it indicates the arguments as null
How can I solve  this problem?

Regards
Manoz

**Comment by newpain01** [comment]
I also get the same problem, searching for solution now.

**Comment by orangeShadow** [comment]
I change `function SetUrl to window.SetUrl = function(url, file_path)` in file lfm.js and it help
