### ISSUE TITLE
Clicking the image NOT Working

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#308]
Everything is working until uploading. But when I choose an image, it is not working. its not getting the image. And nothings happen. I also tried .png and .jpg

![imagenothinghappen](https://cloud.githubusercontent.com/assets/16563175/26093919/65c3d80e-3a4a-11e7-81df-25ad686bbb3a.png)

Thanks!

**Comment by PendoNL** [comment]
Have you tried to "force" to overwrite all vendor files? That's just the configuration file and the views I believe. I've ran into similar issues becuase "vendor:publish" didn't overwrite what was already published.

**Comment by jonjie0317** [comment]
Thanks men. Just missed an `=` sign in this part `var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;` :)
