### ISSUE TITLE
Getting Redirected to "/" directory when clicking image icon.

### ISSUE THREAD

**Issue by rebootcode** [UniSharp/laravel-filemanager#31]
Whenever i click on "image" icon for directory view, it redirects document inside popup to home page.

cms_url = 'http://localhost/laravel/blog/public/laravel-filemanager?field_name=' + field_name;'

but when i open , it takes me back to "http://localhost/laravel/blog/public".

Just for Clarification, I am already logged in and middleware '[auth]' is working just fine.

**Comment by gissly** [comment]
add web middleware
'middlewares' => ['web','auth'],

**Comment by rebootcode** [comment]
Got fixed 3 hours ago too :)

**Comment by youchenlee** [comment]
@gissly @rebootcode 
With laravel 5.2, when not adding the `web` middleware, the problem occurs. is that right?
I think we would better mention it in README.

issue reopened.
