### ISSUE TITLE
Error UploadedFile::path() when trying to upload a media/video using TinyMCE

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#311]
I am using laravel5.1, and I included this package. Uploading images is working, but the media is not. Every time I choose a video and click Upload, it returns an error:<br><br>

> FatalErrorException in UploadController.php line 64: Call to undefined method
> Symfony\Component\HttpFoundation\File\UploadedFile::path()

<br><br>
Do you have any idea for this? Thanks .

**Comment by PendoNL** [comment]
Fix this in this PR: https://github.com/UniSharp/laravel-filemanager/pull/300

**Comment by PendoNL** [comment]
You may close this one @jonjie0317, since the PR fixed the issue. We just need to get it merged!

**Comment by jonjie0317** [comment]
Ok @PendoNL  Thanks much again ..
