### ISSUE TITLE
get error NotFoundHttpException in RouteCollection.php line 179

### ISSUE THREAD

**Issue by nekooee** [UniSharp/laravel-filemanager#315]
Hi 
my root not "/public" and only "/"
when I install laravel file-manager I get this error:
NotFoundHttpException in RouteCollection.php line 179

see below image:
![2017-05-19 19_36_55-file manager](https://cloud.githubusercontent.com/assets/6003803/26254097/a9b6c030-3cca-11e7-9e92-a52099096bef.png)

![2017-05-19 19_38_34-sahatoos - f__my work_web site_sahatoos - _vendor_unisharp_laravel-filemana](https://cloud.githubusercontent.com/assets/6003803/26254155/cd210d96-3cca-11e7-9119-ac24cba9caf1.png)
please help me :(

**Comment by nekooee** [comment]
screenshot of my consol:
![2017-05-19 22_14_36-file manager](https://cloud.githubusercontent.com/assets/6003803/26260043/001631ca-3ce1-11e7-99e1-afdb1a6eb092.png)

**Comment by nekooee** [comment]
I find out that conflict with language middleware. how to slove it?
`<?php
// app/Http/Middleware/Language.php
namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class Language
{
    public function handle(Request $request, Closure $next)
    {
// Check if the first segment matches a language code
        if (!array_key_exists($request->segment(1), config('translatable.locales'))) {

// Store segments in array
            $segments = $request->segments();

// Set the default language code as the first segment
            $segments = array_prepend($segments, config('app.fallback_locale'));

// Redirect to the correct url
            return redirect()->to(implode('/', $segments));
        }

        return $next($request);
    }
}

?>`

**Comment by kimpoy010** [comment]
what file did you edit? where is it located? Thanks!

**Comment by RosyStephen** [comment]
hi,
 I git same error how do you fixit
