### ISSUE TITLE
Stand alone button

### ISSUE THREAD

**Issue by journeyman73** [UniSharp/laravel-filemanager#317]
How can I make the image preview be the thumbnail for the standalone button? Currently it is the full size image.

Cheers

**Comment by g0110280** [comment]
Doesn't support this for now. Maybe we should enhance the `.filemanager()` jquery function.

**Comment by g0110280** [comment]
Done in fbe9689. In line 25 of `public/js/lfm.js`, please replace

`$('<img>').attr('src', item.thumb_url)`

with

`$('<img>').attr('src', item.path)`
