### ISSUE TITLE
Trying to upload

### ISSUE THREAD

**Issue by Epistol** [UniSharp/laravel-filemanager#318]
Hey,

I've tried everything to make the filemanager work, and o boi it work.

Well, it ... show off which is nice but I can't upload anything.
I've made a screen capture to show it better : 

https://www.youtube.com/watch?v=wauOX1Foqdw

I really don't know why it won't upload, chmod 777 is set to the folder and subfolders  ...

**Comment by Pashaster12** [comment]
@Epistol The same... any ideas?

**Comment by Pashaster12** [comment]
@Epistol in my case I found, I have this error after multiple uploading images. I created a new issue for this - #330

**Comment by Pashaster12** [comment]
@Epistol I solved my problem - #330 . So, check your .htaccess and other url settings. Hope, it will be helpful for you too.

**Comment by Asonn** [comment]
@Epistol I had the same problem but after enabling the extension `EXIF` it worked like a charm.

**Comment by g0110280** [comment]
If this problem still occurs, please reopen this issue.
