### ISSUE TITLE
Triple slash in path

### ISSUE THREAD

**Issue by vertisan** [UniSharp/laravel-filemanager#320]
Hi,
On images I getting errors 'Not found', maybe because in address have trible slash, eg. 
`http://laravel.dev/file-manager///image.png?timestamp=1495395635`
I config I have setted:
```   
 'base_directory' => 'public/storage/files',
    'images_folder_name' => '',
    'files_folder_name'  => '',

    'shared_folder_name' => '',
    'thumb_folder_name'  => '',
```
How to fix it?

**Comment by g0110280** [comment]
```
 'base_directory' => 'public/storage/files',
    'images_folder_name' => 'photos',
    'files_folder_name'  => 'files',

    'shared_folder_name' => 'shares',
    'thumb_folder_name'  => 'thumbs',
```

**Comment by vertisan** [comment]
That's I know but I need to put all in one directory without subdirs

**Comment by g0110280** [comment]
Got it. You can integrate only the `file` link with your WYSIWYG editor.
