### ISSUE TITLE
Call to undefined method Closure::__set_state()

### ISSUE THREAD

**Issue by pderiy** [UniSharp/laravel-filemanager#323]
Hi, 
after `php artisan config:cache` I have an error:
`[2017-05-25 10:34:01] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Closure::__set_state() in my-project/bootstrap/cache/config.php:773
`

config.php:
![image](https://cloud.githubusercontent.com/assets/9549383/26443082/4b668e40-4137-11e7-8f95-7d61baa7acb1.png)

This error is because you put function into configs. Could you change it, to fix?
` 'user_field'         => function () {
        return auth()->user()->id;
    },`

I see you wrote a comment, that's not possible to use in Laravel 5.2. But what I have to do? Should I remove 'user_field' or what?

When change user_field to 'id' it works good.
Could you change default config user_fild value to 'id' instead of closure?

OS System & Version: Linux skey-Inspiron-5737 4.10.0-21-generic #23-Ubuntu SMP Fri Apr 28 16:14:22 UTC 2017 x86_64
Laravel Version: v5.4.23
File Manager Version: v1.7.7
imagick Extension: Not Install
gd Extension: Install

**Comment by g0110280** [comment]
Hello @pderiy , Laravel suggested not using closures in config files, since they cannot be cached. The reason why we use closure as the value of `'user_field'` is to demonstrate the flexibility of this package.

**Comment by kingofswing** [comment]
I had the same problem , on production server I tried to optimize Laravel ,but stoped here. any solution yet ? thanks!  

Laravel:5.4 
File Manager: unisharp/laravel-filemanager": "^1.7"
TinyMCE: 4.5.7.

**Comment by JohanMa4** [comment]
I think, i found the solution, in the config/lfm.php field, set the key like this 'user_field' => \App\User::class or where you have the User model in laravel 5.4, i hope that help that.

**Comment by g0110280** [comment]
Set value of `'user_field'` to `'id'` can do the same.

**Comment by g0110280** [comment]
Please upgrade to `v1.8.1`.

**Comment by ajoy39** [comment]
Does anyone know how to recover from this? I updated to 1.8.1 but artisan is still broken, I can't run any commands at all

**Comment by kasra-appscore** [comment]
I resolved it by removing this: bootstrap/cache/config.php

**Comment by vc-siddhrajsinh** [comment]
Resolved it by removing  **bootstrap/cache/config.php**

**Comment by inquisitive-stha** [comment]
I have updated it to v1.8.1 and also deleted `bootstrap/cache/config.php` but still getting same error `  Call to undefined method Closure::__set_state()  
` on `php artisan optimize`

Also tried to replace it as: 

```
    'user_field' => \App\User::class,
````

But getting error: 
```
  Unable to prepare route [api/user] for serialization. Uses Closure.  
```

**Comment by timbogdanov** [comment]
Why is this closed? Please reopen

**Comment by Desto1998** [comment]
Remove the **/bootstrap/cache/config.php**  and run _PHP artisan vendor:publish_ instead of PHP artisan optimize, 
This work for me
