### ISSUE TITLE
Store original image before cropping or resizing.

### ISSUE THREAD

**Issue by k4rl1** [UniSharp/laravel-filemanager#324]
Hi,
I would need the ability to crop or rezisze a image while the original image will be preserved (so a new cropped image shell be created and the original don't change, or change the original image and store a duplicate of the original image before cropping).

Are you eager to intergrate this :)? Thanks!

**Comment by matthiaszach** [comment]
This would be a great feature! +1

**Comment by gwleuverink** [comment]
I'll try my hand at this if I have some time. Maybe next week.

**Comment by gwleuverink** [comment]
@k4rl1 @matthiaszach this feature has been merged with master. thanks @g0110280!

**Comment by g0110280** [comment]
You are welcome @gwleuverink . Also, thanks for helping these issues.

**Comment by matthiaszach** [comment]
Thanks :)

**Comment by k4rl1** [comment]
Thx! :)

**Comment by k4rl1** [comment]
Now there's a bug for the config field "user_field"

my old value:
'user_field' => function() {
        return null;
 }

Now this has to be a class or the method getUserSlug from LFmHelpers.php will throw a exception because **config('lfm.user_field')** is no object. 
**Line:   if (class_exists(config('lfm.user_field'))) {**

**Comment by g0110280** [comment]
Please upgrade to `v1.8.1`.

**Comment by rashidul-hasan** [comment]
I created a pull request which add a 'Copy & Resize' that stores the original image & create new image with the new dimensions. link: #1216
