### ISSUE TITLE
Cyrilic file names

### ISSUE THREAD

**Issue by eok8177** [UniSharp/laravel-filemanager#325]
![lfm_bug](https://cloud.githubusercontent.com/assets/8864590/26559840/d73d7bfa-44ba-11e7-8461-12f3d3c3cf73.jpg)

When uploading file with cyrilic name
upload file without name

**Comment by eok8177** [comment]
when add: setlocale(LC_ALL, 'ru_RU.UTF-8');
change all names to "___"

comment line 128 in  /src/controllers/UploadController.php
// $new_filename = preg_replace('/[^A-Za-z0-9\-\']/', '_', $new_filename);

working good

**Comment by g0110280** [comment]
You can simply set `'alphanumeric_filename'` to false in [lfm.php](https://github.com/UniSharp/laravel-filemanager/blob/v1.7.7/src/config/lfm.php#L79).
