### ISSUE TITLE
Hangs on file upload

### ISSUE THREAD

**Issue by nadj** [UniSharp/laravel-filemanager#33]
Hi, I'm using laravel 5.2 on debian.
When I try to upload anything than img file, it hangs. 
But the file gets uploaded to photos folder, when I try to insert it into CKeditor it creates an img tag.

**Comment by youchenlee** [comment]
@nadj 
1. Are you able to upload files directly from the http://your.hostname/laravel-filemanager interface?
2. Would you please provide your ckeditor configurations?

**Comment by gissly** [comment]
Make sure you have installed imagick on your server.

**Comment by youchenlee** [comment]
Thank you @gissly 
Yes that might be the problem too.
laravel-filemanager depends on https://github.com/Intervention/image and required gd or imagick extension.

I opened a new issue for this enhancement #35

**Comment by nadj** [comment]
My ckeditor setup looks like this:
`$('.ckeditor').ckeditor({
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });`

But when I go to the link tab and click on the Browse Server button the link looks like this:

http://homestead.app/laravel-filemanager?type=Images&CKEditor=sr%5Bdescription%5D&CKEditorFuncNum=0&langCode=en

It still puts type=Images in the link. 
Do you have some suggestion? 

Thanks in advance.

**Comment by youchenlee** [comment]
@nadj  Fixed in c9f8c62. An alpha release https://github.com/UniSharp/laravel-filemanager/releases/tag/1.3.0-alpha is now under testing. Would you please give it a try?

**Comment by nadj** [comment]
@youchenlee thanks, now file upload doesn't hang but I receive an error 

> Unexpected MimeType: application/CDFV2-unknown

That's fine but I want to upload a file from the link tab Browse Server button. The link that opens is: 

> http://homestead.app/laravel-filemanager?type=Images&CKEditor=sr%5Bdescription%5D&CKEditorFuncNum=0&langCode=en

But in the config i have this:
`$('.ckeditor').ckeditor({
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });`

Can you tell me what am I doing wrong here? 

The image upload is ok, just the type variable is wrong I think

**Comment by youchenlee** [comment]
Hi @nadj 
The release contains two new configs. if you upgrade the package without running `php artisan vendor:publish --force --tag=lfm_config` (note: the --force argument is important), you won't see these two configs in config/lfm.php

In your case, please add `application/CDFV2-unknown` into the `valid_file_mimetypes` array.
I will add this to FAQ section in README. 

```
    // valid image mimetypes
    'valid_image_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif'
    ],

    // valid file mimetypes (only when '/laravel-filemanager?type=Files')
    'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'application/pdf',
        'text/plain'
    ],
```

**Comment by nadj** [comment]
Thank you @youchenlee 
I have that in my lfm.php config. 
But my problem is when I go like this:
![screenshot-homestead app 2016-03-08 12-14-27](https://cloud.githubusercontent.com/assets/6311444/13600171/73b695c4-e527-11e5-972c-93508aed745e.png)

I receive a file manager window with a link:

> http://homestead.app/laravel-filemanager?type=Images&CKEditor=sr%5Bdescription%5D&CKEditorFuncNum=0&langCode=en

But when I go to this link (http://homestead.app/laravel-filemanager?type=Files) in a new window, the upload works fine after adding application/CDFV2-unknown to valid_file_mimetypes.

**Comment by youchenlee** [comment]
@nadj 
There are two main entries to upload file in CKEditor.
![screen_shot_2016-03-08_at_20_26_31](https://cloud.githubusercontent.com/assets/181350/13601638/6fea473e-e56c-11e5-8d03-db053cdf4a7d.png)

If you click on the image button, it will append a `type=Image` url parameter while opening filemanager window. 

You might try either of the solutions:
1. use the "File (link) button" instead, add your mimetype to `valid_file_mimetypes`
2. keep using the image button, but add your mimetype to `valid_image_mimetypes`. (this is kind of weird but it should work)

**Comment by youchenlee** [comment]
Correction: The second solution won't work because once filemanager expects an image, it will try to create a thumbnail from the image. That causes an error.

https://github.com/UniSharp/laravel-filemanager/blob/master/src/controllers/UploadController.php#L51

**Comment by nadj** [comment]
Thanks a lot, that solves all of my problems :+1:

**Comment by youchenlee** [comment]
@nadj You're welcome!
