### ISSUE TITLE
Can't upload images after multiple upload

### ISSUE THREAD

**Issue by Pashaster12** [UniSharp/laravel-filemanager#330]
I tried to upload several images at once but uploading failed. The filemanager's window closed and files didn't upload.

The most aweful of this situaition is I can't upload anything after this bug at all.

The error is very similar to #318. Upgrading the package's version doesn't help. Re-installing and php artisan vendor:publish --force too.

The most interesting - after I pressed the "Upload" button I've got the empty request in the Unisharp\Laravelfilemanager\controllers\UploadController@upload without any parameter... 

What should I do to have a possibility to upload anything?

**Comment by Pashaster12** [comment]
Sorry for this issue) The reason was pretty easy - the problem was with my .htaccess file and with incorrect routes) For future, if you have the same problem - check your .htaccess and auth for laravel-filemanager's routes (routes should be inside the middleware auth):

Route::group(array('before' => 'auth'), function ()
{
    Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
    // list all lfm routes here...
});

It may be the reason of the problem also.

**Comment by Asonn** [comment]
I had the same problem but after enabling `EXIF` in my php.ini everything worked.
