### ISSUE TITLE
how modify environment filemanager?

### ISSUE THREAD

**Issue by thavoo** [UniSharp/laravel-filemanager#331]
Good afternoon the filemanager can be customized I want to change the name of the titles and modify the environment  #index #question

**Comment by g0110280** [comment]
1. From [customization](http://unisharp.github.io/laravel-filemanager/customization) document : run `php artisan vendor:publish --tag= lfm_view`, and go to `resources/views/vendor/unisharp/laravel-filemanager/index.blade.php`, edit the file as you wish.
2. What do you mean by "the environment"?
