### ISSUE TITLE
Thumbs folder dont exist issue

### ISSUE THREAD

**Issue by k4rl1** [UniSharp/laravel-filemanager#332]
Hi,

I have an issue concerning the thumb folders. We import images into the filemanager/images folder and therefore the thumbs folder for this directory will not be created (we could possibly create the directory by ourself but i think it is a task for the library to check the existance of this folder and create it). If I try to crop one of these images, I get a warning that the thumbnail for this image couldn't be created because the thumbs directory dont exist. Please check if the thumbs folder exists and if not try to create the folder before trying to create the thumb image. Thanks!

**Comment by aboustayyef** [comment]
I'm having the same difficulty with migrating an existing filemanager library (older version). 

In my case the thumbs folder was on the base directory. So it was running a parallel hierarchy to main images (see photo). In this package it seems I can't set a path relative to the base directory for thumbs. I tried '../thumbs', but that's relative to the photo being uploaded, and it will only work if the photo is at the first level after the base directory.

<img width="246" alt="screen shot 2017-06-13 at 5 30 01 am" src="https://user-images.githubusercontent.com/1009406/27067266-8fb171fc-4ff9-11e7-8604-e92a193fd57f.png">

**Comment by aboustayyef** [comment]
@k4rl1 so I dug through the code. The grid and list view are designed not to show you the "crop" and "rename" items in the dropdown if the image in question doesn't have a thumb. The problem is that the code for knowing whether an image has a thumb or not is not working. $item->thumb is returning the original image, not the thumb's location as it's supposed to.

**Comment by k4rl1** [comment]
yeah thats possible, but it should also work to create a new thumb image (for the cropped image) if the original image doesn't have a thumb image and possibly no thumb directory exists ;)

**Comment by g0110280** [comment]
Done in current version of `dev-master`, this issue will be solved after `v2.0-alpha` version releases.
