### ISSUE TITLE
Publish Vendor not Work Laravel 5.4

### ISSUE THREAD

**Issue by hxor** [UniSharp/laravel-filemanager#336]
When I run php vendor publish config and public is not doing something.
Config and Route is not found.

OS System & Version: Darwin Kiddies-MBP 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
Laravel Version: v5.4.24
File Manager Version: v1.7.7
imagick Extension: Not Install
gd Extension: Install

**Comment by g0110280** [comment]
Did you set up the service provider in `config/app.php`?

**Comment by hardiktailored** [comment]
Run below command in terminal: 
`php artisan config:cache`

And, try again publishing vendor files:
`php artisan vendor:publish --tag=lfm_config`
`php artisan vendor:publish --tag=lfm_public`

**Comment by codejam1024** [comment]
It works of my laravel 5.4 system
