### ISSUE TITLE
The problem with Russian names for photos

### ISSUE THREAD

**Issue by LusenkoSasha** [UniSharp/laravel-filemanager#341]
![image](https://user-images.githubusercontent.com/27783985/27045705-727a5b8e-4faa-11e7-960d-fc2e907437c2.png)
There was a problem with downloading files in Russian. Has solved a problem so. Possible to update.
In addition to Russian words, there was a problem with spaces.

**Comment by albertcht** [comment]
In our [v1.8.0 release](https://github.com/UniSharp/laravel-filemanager/releases/tag/v1.8.0), we have fixed an iconv bug while processing non-utf8 folders. Please update your package to this version and see if this bug still exists.
