### ISSUE TITLE
I tell you how to put a watermark and change the size of the photo at boot time(it's not a question)

### ISSUE THREAD

**Issue by LusenkoSasha** [UniSharp/laravel-filemanager#342]
![-1](https://user-images.githubusercontent.com/27783985/27047179-c6c2df22-4faf-11e7-8bba-aeb669f1f938.jpg)
http://image.intervention.io/api/insert

**Comment by g0110280** [comment]
Thanks @LusenkoSasha, we have moved this to our [wiki](https://github.com/UniSharp/laravel-filemanager/wiki/Putting-a-watermark-and-change-the-size-of-the-image-when-uploading-a-image).
