### ISSUE TITLE
Call to undefined method Closure::__set_state() when updating

### ISSUE THREAD

**Issue by unlikenesses** [UniSharp/laravel-filemanager#343]
When I tried to update LFM from 1.7.7 => 1.8 it runs `php artisan optimize` which triggers the error

> Fatal error: Call to undefined method Closure::__set_state() in C:\xampp\htdocs\NAME\app_base\bootstrap\cache\config.php on line 299

OS System & Version: Windows NT NAME 6.3 build 9600 (Windows 8.1 Home Premium Edition) i586
Laravel Version: v5.4.10
File Manager Version: v1.8.0
imagick Extension: Not Install
gd Extension: Install

**Comment by g0110280** [comment]
In `config/lfm.php`, please set `user_field` to `id` and try again.

**Comment by unlikenesses** [comment]
I made that change but the same error is occurring. The error specifies `app_base\bootstrap\cache\config.php` so shouldn't I be changing something there?

**Comment by g0110280** [comment]
Can't know for sure if this is related to this package. Only thing for sure is that if there is a closure in config, you will get an error when running `php aritsan config:cache`.

**Comment by unlikenesses** [comment]
I modified line 299 of `app_base\bootstrap\cache\config.php` to 

`'user_field' => 'id',`

and it removed the error.
