### ISSUE TITLE
v1.8 csrf missmatch when weight of an image exceeds the limit.

### ISSUE THREAD

**Issue by spyrosjevan** [UniSharp/laravel-filemanager#345]
Laravel v5.4
Package: v1.8
wamp 3.0.36 64bit

This was reported before but im getting a csrf missmatch error when im trying to upload files much larger than the alower weight.

Also that error is only show when the window of manager is on fullscreen, if u try upload the same file in a more minimized version the window just close.

Im using a standar alone button.

```
{!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!}
var route_prefix = "{{ url(config('lfm.prefix')) }}";
$('#lfm').filemanager('image', {prefix: route_prefix});
```

![csrf](https://user-images.githubusercontent.com/17203716/27178365-9fc17e0e-51d2-11e7-8895-522db6eca820.png)

**Comment by g0110280** [comment]
@spyrosjevan 
1. What did you mean by "weight"?
2. Can you upload files successfully if size of the files is lower than 2 MB ?

**Comment by spyrosjevan** [comment]
yes

**Comment by spyrosjevan** [comment]
Never mind we removed the whole package and developed our own thanks for your response.
