### ISSUE TITLE
how to disable lfm from non-admin users?

### ISSUE THREAD

**Issue by greatsami** [UniSharp/laravel-filemanager#346]
Hi 

I have v1.7 in my project, and it works fine in administrator side, also images works fine in front-side. but my problem when any registered user (non-admin) or visitor can access laravel-filemanager page by when click on image right-click and open it in new window like:

http://www.domain.com/laravel-filemanager/photos/1/593e3d9f3d8fb.jpg

if remove (photos/1/593e3d9f3d8fb.jpg) he can access file manager.

i tried to change config/lfm.php in middlewares but i failed.... how i can disable LFM from any user not admin?

Note: I've middleware called checkRole that check role_id in users table.
I tried to put it in lfm middlewares but it is not work

any help or suggestion?

Regards
Sami

**Comment by afshine1989** [comment]
go to this path \vendor\unisharp\laravel-filemanager\src\config,  open the lfm.php file and then add your middleware to the line 15 

'middlewares' => ['web','auth','admin']

i added admin as my middleware

**Comment by gwleuverink** [comment]
Alternatively if you set up your authentication with guards you can change the 'auth' middleware definition in lfm.php to 'auth:admin'.

This only works if you defined guards in config/auth.php tough.

**Comment by greatsami** [comment]
@afshine1989 & @gwleuverink 

Thank you for reply, actually i tried both solutions you wrote. 

but i solved this issue by edit (vendor/unisharp/laravel-filemanager/src/routes.php)

put from (// Show LFM) to (// delete ) inside my route group as my web.php cod:

```
Route::group(['middleware' => ['auth', 'roles'], 'roles' => ['admin', 'supervisor']], function() {
	// Show LFM
	Route::get( '/', [
		'uses' => 'LfmController@show',
		'as'   => 'show'
	] );

	...
	...
	...

	// delete
	Route::get( '/delete', [
		'uses' => 'DeleteController@getDelete',
		'as'   => 'getDelete'
	] );
});

```

also in lfm.php 

```
'middlewares' => ['web'],
'allow_multi_user' => false,
'allow_share_folder' => false,
```

and it is solved with me :) 

regards
