### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by syedkhushairy** [UniSharp/laravel-filemanager#347]
hey guys i already overcome the trouble from before but i have this problem now.
i got an error message unauthorized.
then it will display like in the image below

![empty](https://user-images.githubusercontent.com/11833679/27211221-640ec64c-528a-11e7-9029-296a9e3a22d1.png)

**Comment by g0110280** [comment]
Make sure you followed every steps from [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade).
