### ISSUE TITLE
Unisharp doesn't work with xamp or maybe apatch

### ISSUE THREAD

**Issue by afshinizadi** [UniSharp/laravel-filemanager#353]
When I try to use UniSharp after running my project by xamp, the route reply The requested URL was not found....., but when i try to run it by laravel build in web server (php artisan serve) it works well, what's wrong ? will my project works after uploading it to the server?

**Comment by g0110280** [comment]
Make sure you followed every step from the [installation document](http://unisharp.github.io/laravel-filemanager/installation). And try running `php artisan route:clear`.
