### ISSUE TITLE
image path in ckeditor 

### ISSUE THREAD

**Issue by saeed7m** [UniSharp/laravel-filemanager#354]
i have problem with ckeditor integration , every thing is ok , but the path of image is full url , for example : www.mydomain.com/image/test.jpg 
when i use standalone button , the path is ok and it is : /image.test.jpg 
i use ver 1.8 . pls help me , 
thank you ...

**Comment by g0110280** [comment]
Cannot reproduce this issue. Please upgrade to `v1.8.2-alpha`.

**Comment by g0110280** [comment]
Inactive for over six months, closing issue.
