### ISSUE TITLE
Delete photos and lignbox (it's not a question)

### ISSUE THREAD

**Issue by LusenkoSasha** [UniSharp/laravel-filemanager#357]
Understood how to do a photo removal when editing a product for example. And also connected lightbox

![image](https://user-images.githubusercontent.com/27783985/27517586-b5bbe78c-59d7-11e7-85bf-c07a073e7423.png)
The first line is responsible for the appearance of the delete button when adding photos

The second line is for adding  lightbox (http://lokeshdhakar.com/projects/lightbox2/)
`
I'll give an example with two buttons, if you need two photos for the goods
![image](https://user-images.githubusercontent.com/27783985/27517693-2380ddb2-59d9-11e7-9594-82e71bcdbff4.png)

Next, we do a loop in which we check the value input, and if the value is not empty, then we assign our delete button, and also assign the data-lightbox attribute to our lightbox for the href_img class.

![image](https://user-images.githubusercontent.com/27783985/27517708-53291ea8-59d9-11e7-9b81-4916699f24ba.png)

We finished with the code that will show the photo with the ability to delete it when editing the product

Let's start deleting the photo.
![image](https://user-images.githubusercontent.com/27783985/27517804-fb5d107e-59da-11e7-83ff-0b3aa7c6daa3.png)

We add the code in lfm.js
![image](https://user-images.githubusercontent.com/27783985/27517841-724d5c52-59db-11e7-85bf-5e91d9f1246d.png)

![image](https://user-images.githubusercontent.com/27783985/27517869-f41e2afe-59db-11e7-8c71-a9cc1e3c7307.png)

![image](https://user-images.githubusercontent.com/27783985/27517874-107b77b0-59dc-11e7-88e0-9686b5b0dc21.png)
![image](https://user-images.githubusercontent.com/27783985/27517883-2a1ce9ba-59dc-11e7-9c5e-8d3f45090c90.png)

Sorry for my english, wrote through google translate

`

**Comment by g0110280** [comment]
Thank you @LusenkoSasha , we will move this post to the wiki of this package!

**Comment by g0110280** [comment]
Done. Wiki is in [here](https://github.com/UniSharp/laravel-filemanager/wiki/Lightbox-integration-(including-function-of-delete-photos)).
