### ISSUE TITLE
loading chinese images url bug

### ISSUE THREAD

**Issue by chiukovo** [UniSharp/laravel-filemanager#358]
when i upload chinese file

url: /laravel-filemanager/photos/shares/thumbs/test/哈摟.jpg?timestamp=1498720409
resquset url: /laravel-filemanager/photos/shares/thumbs/test/%E5%93%88%E6%91%9F.jpg

so i think need to urldecode this can fix that !

like this:

![6311212088689](https://user-images.githubusercontent.com/11659606/27678670-93cd44ea-5ce8-11e7-9d30-9823f20c4a58.jpg)

**Comment by g0110280** [comment]
#350 can fix this, and it is merge also. Please upgrade to `v1.8.1`.
