### ISSUE TITLE
File not found issue

### ISSUE THREAD

**Issue by jagadishwarballa** [UniSharp/laravel-filemanager#359]
![screen shot 2017-06-30 at 10 29 01 am](https://user-images.githubusercontent.com/29790063/27721634-3841f782-5d7f-11e7-9b7a-e41d773c719a.png)
The latest version of the file gives error as below. Basically it is the issues with the File class in src/index.blade.php
FatalErrorException in 8044fcdde4c6efead703d3f0ac3004c12342d8a8.php line 20:
Class 'File' not found

**Comment by g0110280** [comment]
Please set up `File` facade in your `config/app.php`.
