### ISSUE TITLE
How to use stand alone button ?

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#361]
Hi guys. Im having a trouble when opening the dialog to upload a file. When I click the `Choose file` button that I've created, another new window/dialog opens but it returns an error. 

> **Not Found**
> The requested URL /laravel-filemanager was not found on this server.
> 

Maybe I have the same issue with [this link](https://github.com/UniSharp/laravel-filemanager/issues/309), but Im using the tinyMCE Editor and it works fine. But not in stand alone button. What should I do?

**Comment by gwleuverink** [comment]
is the filemanager available when accessing directly using the prefix in config/lfm.php?

**Comment by jonjie0317** [comment]
How can I check if that is available?

**Comment by gwleuverink** [comment]
visit development-server.dev/laravel-filemanager

where 'development-server.dev' is the domain you are working on and 'laravel-filemanager' is the prefix as defined in config/lfm.php.

what is the response if you visit that url directly?

**Comment by jonjie0317** [comment]
The error is the response. But when I try to visit `my-project/public/laravel-filemanager` it works fine.

**Comment by jonjie0317** [comment]
Should I have to use this part?

> var domain = "";
>  $('#lfm').filemanager('image', {prefix: domain});

**Comment by jonjie0317** [comment]
It worked now sir. Thanks for the effort .
