### ISSUE TITLE
method request() not work

### ISSUE THREAD

**Issue by alisyahbana** [UniSharp/laravel-filemanager#363]
Hello i was using Laravel 5.0.35 and lfm 1.8.0, but i still get this error

![image](https://user-images.githubusercontent.com/16076194/27848650-ead35478-6170-11e7-94c3-14d146ee78ab.png)

but it was fixed by modifying vendor/unisharp/laravel-filemanager/src/routes.php 

and then i got this error

> FatalErrorException in LfmHelpers.php line 335:
> Call to undefined function Unisharp\Laravelfilemanager\traits\request()

**Comment by g0110280** [comment]
Maybe the helper `request()` is absent in Laravel 5.0 . We should replace them with `Request::input`.

**Comment by g0110280** [comment]
@alisyahbana please use [laravel-50 branch](https://github.com/UniSharp/laravel-filemanager/tree/laravel-50) of this package.
