### ISSUE TITLE
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException

### ISSUE THREAD

**Issue by lovnishwis** [UniSharp/laravel-filemanager#364]
When i click on browse server then this happen. And also send it server for ckeditor is also not working

![error](https://user-images.githubusercontent.com/19872593/27860659-20cb0006-619b-11e7-9332-90449f17df91.png)

**Comment by g0110280** [comment]
Make sure you run `php artisan vendor:publish --tag=lfm_view --force`.
