### ISSUE TITLE
redirect to my folder again and again due to this : var cmsURL = editor_config.path_absolute + 'blog?field_name=' + field_name;

### ISSUE THREAD

**Issue by SandeepBanerjee** [UniSharp/laravel-filemanager#366]
I just install the filemanger on the Laravel, as per your docx and when i click on 
![1](https://user-images.githubusercontent.com/8704829/27881678-3b436062-61e7-11e7-8660-aa01623d5d57.png)

it redirects to my folder 
![2](https://user-images.githubusercontent.com/8704829/27881561-c5300b32-61e6-11e7-985e-2f4b80b2d14b.png)
as i just changed 
var cmsURL = editor_config.path_absolute + '**blog**?field_name=' + field_name;

if i did not change the url it will redirect me to your github demo project as i already download your project.

Help will be appreciate.

**Comment by g0110280** [comment]
In `config/lfm.php`, please set `prefix` or `url_prefix` to `blog`.
