### ISSUE TITLE
Route [unisharp.lfm.upload] not defined. (View: D:\xampp\htdocs\laracms\resources\views\vendor\laravel-filemanager\index.blade.php)

### ISSUE THREAD

**Issue by bossby** [UniSharp/laravel-filemanager#369]
Hey. I'm trying to use this package. But i found a problem.  

![ss](https://user-images.githubusercontent.com/21689649/28419409-0daf881c-6d89-11e7-8efb-f7d652bc5b3e.png)

I have read this `https://unisharp.github.io/` . But maybe i miss something.

**Comment by g0110280** [comment]
Did you set up service provider in `config/app.php`.

**Comment by bossby** [comment]
I fix it. I just need to republish it

```
php artisan vendor:publish --tag=lfm_config
 php artisan vendor:publish --tag=lfm_public
```

**Comment by mehrdadshirvan** [comment]
use this 
`composer update unisharp/laravel-filemanager
`
` php artisan vendor:publish --tag=lfm_view --force
 php artisan vendor:publish --tag=lfm_public --force
 php artisan vendor:publish --tag=lfm_config --force
`
 `php artisan route:clear
 php artisan config:clear`
