### ISSUE TITLE
What is the purpose of the prefix config?

### ISSUE THREAD

**Issue by pankajbhaliya** [UniSharp/laravel-filemanager#371]
It is mentioned as following 
`// The url to this package. Change it if necessary.
'prefix' => 'laravel-filemanager',`

But even if we change, it is not getting affected to URL. 
We added following routes in our routes/web.php 

`Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\UploadController@show');
 Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');`

So if we are already registering routes in route file then what is the use of prefix. 
Please explain

**Comment by g0110280** [comment]
If you set `base_directory` other than `public`, then `prefix` is needed to compose url for files and images.
