### ISSUE TITLE
Uncaught ReferenceError: lang is not defined

### ISSUE THREAD

**Issue by smilingsenti** [UniSharp/laravel-filemanager#372]
![lang error](https://user-images.githubusercontent.com/3455321/28492734-2d289512-6f28-11e7-9c25-359bce17fc0c.PNG)

**Comment by g0110280** [comment]
@smilingsenti From which file did you see this error? `demo.blade.php` doesn't have an error like this.

**Comment by smilingsenti** [comment]
I see this error after clicking image icon on TinyMCE editor or when file manager pops out
![captureunisharp](https://user-images.githubusercontent.com/3455321/28604614-a9d14990-71eb-11e7-8c3c-f9e365478638.PNG)

**Comment by g0110280** [comment]
Try running `php artisan vendor:publish --tag=lfm_views --force`, and clear browser cache.

**Comment by palomamtnez** [comment]
After running `php artisan vendor:publish --tag=lfm_views --force`, it says:

>    INFO  No publishable resources for tag [lfm_views].
