### ISSUE TITLE
Security route init error??

### ISSUE THREAD

**Issue by t67132** [UniSharp/laravel-filemanager#376]
hi !! Set up for security for authentication!!
How to deal with it??
![image](https://user-images.githubusercontent.com/20123094/28683418-0d6ba0ac-7333-11e7-8616-4dda8f00411d.png)

route config
![image](https://user-images.githubusercontent.com/20123094/28683637-ed5d39c8-7333-11e7-87ae-e585004662bf.png)

**Comment by g0110280** [comment]
Try adding `'middleware' => 'auth'` to your route group.
