### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by t67132** [UniSharp/laravel-filemanager#377]
I would like to ask how this solution has been through auth, will appear the following error
![image](https://user-images.githubusercontent.com/20123094/28702227-3699f8ba-738e-11e7-8702-48cb48d0261c.png)

**Comment by youchenlee** [comment]
line 9 in ConfigHandler.php is

```
return auth()->user()->id;
```

When multi-user mode enabled, FileManager needs to identify the user to restrict access to the owned folder.
Looks like it has failed to retrieve the user.

**Comment by uresh** [comment]
what was the problem. i am also getting same error . it was work fine, i think after composer update it happen

**Comment by Alirezah19** [comment]
I've got the same error with laravel 5.4,
You should go to app/config/lfm and set the `'allow_multi_user' => false,` .
hope it helps!
