### ISSUE TITLE
Browse server error

### ISSUE THREAD

**Issue by mgolshan** [UniSharp/laravel-filemanager#382]
Hello.
Whenever I try to browse the server in image insertion of CK Editor, I face to this error:
![filemanager-error](https://user-images.githubusercontent.com/10296177/28759718-8e9bd876-756e-11e7-9809-4843bbb81f8f.png)

It seems it's supposed to route to the 'show' action of LfmController. But, I see no variable is defined there.
Not only $extension_not_found, but also $working_dir and a few more variables are unknown.

I have to say I already have both gd and imagick libraries installed.

Does anyone know how to fix this issue?

Thank you in advanced

**Comment by g0110280** [comment]
From [upgrade document](http://unisharp.github.io/laravel-filemanager/upgrade).
`php artisan vendor:publish --tags=lfm_views --force`

**Comment by mgolshan** [comment]
Thanks man. You saved me.
Please edit your answer and replace --tags with --tag

Cheers.
