### ISSUE TITLE
Install with composer not work

### ISSUE THREAD

**Issue by bpGusar** [UniSharp/laravel-filemanager#384]
i use this line in php shtorm terminal
composer require unisharp/laravel-filemanager 

next i add service priveders and add aliases and ublish the package’s config and assets, after paste in view file script for tinymce4, and if i add in web.php middleware routes and try to open file browser i see the error No hint path defined for [laravel-filemanager], if i do not paste routes i see the error NotFoundHttpException 

what i do wrong?

**Comment by noge075** [comment]
Hi!

Did you try to run `php artisan route:clear`?
Some usefull CLI commands:

`#!/bin/bash

php artisan clear-compiled
php artisan config:cache
php artisan route:cache
php artisan optimize --force`
