### ISSUE TITLE
Problem with Directory After Upload Site on shared host

### ISSUE THREAD

**Issue by farshidrezaei** [UniSharp/laravel-filemanager#385]
Hi. 
When i was working on localhost, i don't have any problem. 

but now , i was uploaded my laravel app in a shared host . in sub-domain like `farshid.example.com`.
and i move all folders and files except **public** folder, in to **source** folder.
then , move all in **public** folder in the **root**(`/`). 
then change `index.php` like down:

`require __DIR__.'/source/bootstrap/autoload.php';`
...
`$app = require_once __DIR__.'/source/bootstrap/app.php';`

now everything work correctly. but images and files ....
should i change any thing ? what i do ?
please help me . thanks.

**Comment by FreedomKnight** [comment]
laravel base on some http rewrite mechanism.
I think you should contact your shared host provider to give you a way to set your http rewrite.

**Comment by g0110280** [comment]
Inactive for too long, closing issue.
