### ISSUE TITLE
Authorization and logging out

### ISSUE THREAD

**Issue by nwaughachukwuma** [UniSharp/laravel-filemanager#387]
We have installed Larevel-filemanager as the filemanager of our application, and what a fine addition it is. But there's a challenge. The application has it's own route, and only users with a special role can access the filemanager (registry). The issues are:
* When the page is idle for a while is logs the user off
* The user is momentarily unable to perform any action as he gets a modal that shows authorization error.

How can we solve this problem, as this registry (filemanager) is one core function of the application. Thanks

**Comment by g0110280** [comment]
@nwaughachukwuma you can perform your authorization check in a middleware, and add that middleware to `middlewares` config in `config/lfm.php`.
