### ISSUE TITLE
How to custom images_folder_name ?

### ISSUE THREAD

**Issue by longtd269** [UniSharp/laravel-filemanager#389]
Hi all,
I want to custom value of images_folder_name in view (path will be generate depending on some conditions)
I did set: config(['images_folder_name' => 'myDir\']) but it still keep old value in file config (lfm.php) instead of use new value.
Is there a way to set this value automatically?

Please help me. Many thanks!

**Comment by g0110280** [comment]
Try this :
```
\Config::set('images_folder_name', 'myDir');
```

**Comment by levinhne** [comment]
I encountered the same problem and I have tried:
\Config::set('images_folder_name', 'myDir');
, but it is keep the old value in file config  (lfm .php) instead of use new value.
Is there other way ? Please help me. @g0110280  
Thanks!

**Comment by tuyennt22** [comment]
I encountered the same problem and I have tried:
\Config::set('images_folder_name', 'myDir');
, but it is keep the old value in file config (lfm .php) instead of use new value.
Is there other way ? Please help me. @g0110280
Thanks!

**Comment by g0110280** [comment]
I think setting config value using `\Config::set()` might be reset after the request ended. Maybe we can add this feature to `ConfigHandler` to overwrite the value in config.

**Comment by streamtw** [comment]
Documents for custom folder name had been written in [this section of config document](https://unisharp.github.io/laravel-filemanager/config#multi-user-mode).
