### ISSUE TITLE
Bug : thumb  image url issue

### ISSUE THREAD

**Issue by amin101** [UniSharp/laravel-filemanager#39]
i have noticed thumb urls has an extra redundant  `\thumbs` in its src url : 
also thumb's image `id` seems odd , it has an `/thumbs/` substring , that i think it should be modified too.

         <img id="E:\xampp\htdocs\pnu/public/photos/1/\thumbs//56d2c43764003.jpg"
             onclick="useFile('56d2c43764003.jpg')" style="cursor:pointer;" alt="" 
              src="/photos/1/\thumbs/thumbs/56d2c43764003.jpg">

**Comment by youchenlee** [comment]
@amin101 Thanks for suggestion. 

Related to #18

**Comment by youchenlee** [comment]
@amin101 Would you please check if version [1.4.0-alpha](https://github.com/UniSharp/laravel-filemanager/releases/tag/1.4.0-alpha) has this issue fixed?

**Comment by amin101** [comment]
I upgraded to 1.4.0-alpha and then everything failed.  i couldn't upload image (upload File button didnt work)or even see user /shared folder in the left sidebar(it was empty space).so i downgraded to 1.2 twice

**Comment by g0110280** [comment]
@amin101 Could you paste here the console error messages and config/lfm.php in 1.4.0-alpha?

**Comment by g0110280** [comment]
Merged pull request #43 .

**Comment by g0110280** [comment]
#18
