### ISSUE TITLE
Invalid Upload request 

### ISSUE THREAD

**Issue by flashery** [UniSharp/laravel-filemanager#391]
http://localhost:8000/photos/1/Invalid upload request I tried your Demo file and I got that error..

**Comment by danrovito** [comment]
Enable the exif extension in your php config

**Comment by flashery** [comment]
Thanks man

**Comment by jonjie0317** [comment]
@danrovito Hi. I'm facing this problem now. How can I edit exif? I found them in `php.ini` but what should I do with this? Is there a value I should change?  And what is the effect when I change it? Thanks a lot.

**Comment by flashery** [comment]
In you php.ini. It is commented by default, just uncomment it. Then restart you web server

**Comment by jonjie0317** [comment]
@flashery There are many exif options there, which one should I uncomment?

**Comment by pranayaryal** [comment]
extension=php_mbstring.dll
extension=php_exif.dll

**Comment by jonjie0317** [comment]
@pranayaryal These two options are already enabled.

**Comment by jonjie0317** [comment]
I have already restart my server. Exif is now enabled but still getting the same error. Please see the image below

![image](https://user-images.githubusercontent.com/16563175/37146295-46b91d00-22fe-11e8-87a7-7c80f9e9a633.png)

**Comment by flashery** [comment]
@jonjie0317  Have you tried @pranayaryal instruction? Run this` php ./vendor/unisharp/laravel-filemanager/bin/debug` and paste the output here so we can help.

**Comment by jonjie0317** [comment]
Hi @pranayaryal @flashery  Please see the output below: (Thanks)

![image](https://user-images.githubusercontent.com/16563175/37316715-a406225a-269b-11e8-821c-a88bff47c4b9.png)

**Comment by pranayaryal** [comment]
So looks like imagick php extension is not installed.
You can do a google search and install it for windows. I am not sure what to do for windows. I installed on mac.

**Comment by jonjie0317** [comment]
@pranayaryal  Hi. May I ask one more question?  What is imagick php extension for?

**Comment by dickyeka** [comment]
enable php_fileinfo, imagick,

**Comment by aabraham88** [comment]
same problem here, I have Ubuntu 16.04. PHP 7.2 with exif, imagick and fileinfo enabled.

This is the current output of the filemanager debug:
OS System & Version: Linux localhost 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64
Laravel Version: v5.5.40
File Manager Version: v1.9.2
imagick Extension: Install
gd Extension: Install

Please, I appreciate your help with this.
