### ISSUE TITLE
Fab button ui issues

### ISSUE THREAD

**Issue by 7ammer** [UniSharp/laravel-filemanager#392]
Cannot click on icons behind fab icon where list item is at the bottom or grid item is at the bottom right. See images for example of issue.

**_cannot click on action buttons_**

<img width="398" alt="screen shot 2017-08-15 at 15 16 05" src="https://user-images.githubusercontent.com/3194029/29319711-c8945bb0-81cc-11e7-8af9-f771b715c368.png">

**_cannot click on dropdown button._**

<img width="259" alt="screen shot 2017-08-15 at 15 16 29" src="https://user-images.githubusercontent.com/3194029/29319701-c35d0aa2-81cc-11e7-98ed-957bd5f80dae.png">

**Comment by g0110280** [comment]
Will fix this in `v2.0`.

**Comment by g0110280** [comment]
Done in `350fec7`. If any item is selected, fab button will be hidden.
