### ISSUE TITLE
How can i show data from database using tinymce in laravel

### ISSUE THREAD

**Issue by Hredoy** [UniSharp/laravel-filemanager#393]
Hello. I can't show that data from database.
i submitted data using tinymce which is <p>Hello World <img src='/img/01.jpg'></p>
i saved that data in body column of post tags
when i want to saw my that data in show.blade.php page  the output seeing like  same
 
my code.
{{ $post->body }}

help me how to solve it

**Comment by skamat007** [comment]
use 
{!! $post->body !!}
