### ISSUE TITLE
404 not found, in version 1.8, i was use below that version not have trouble.

### ISSUE THREAD

**Issue by hai-ru** [UniSharp/laravel-filemanager#394]
![image](https://user-images.githubusercontent.com/24634668/29450622-9d2b4e66-8429-11e7-8f8b-30ffc9db8cad.png)

My Route List :
![image](https://user-images.githubusercontent.com/24634668/29451029-4ec75b1e-842b-11e7-8bfc-277a3b45b9b3.png)

Providers :
![image](https://user-images.githubusercontent.com/24634668/29451059-6d7f8d7e-842b-11e7-834f-05f49e3ed4ed.png)

Alliases :
![image](https://user-images.githubusercontent.com/24634668/29451069-7376d12e-842b-11e7-9032-3844d67bc039.png)

I have already follow any instruction in issue
[100](https://github.com/UniSharp/laravel-filemanager/issues/100)
[83](https://github.com/UniSharp/laravel-filemanager/issues/83)
[309](https://github.com/UniSharp/laravel-filemanager/issues/309)
[283](https://github.com/UniSharp/laravel-filemanager/issues/283)

but not resolve my problem,

I was follow the instruction like ussually i used below version in 
[installation](http://unisharp.github.io/laravel-filemanager/installation)
and if i publish the vendor, file can't make automatically to public, views, and config.
I Had make it self by looking file that i used before.

But still NOT WORKING. Pls resolve this problem.
Sorry my english not good.
Thank you.

**Comment by hai-ru** [comment]
I have installed new project and install all library first before i had copied recent project file, it works. I don't know whats wrong with my project before -_-. but me surely all step it same.

**Comment by g0110280** [comment]
@hai-ru which version are you using? If you are using `v1.8.2-alpha`, in `config/lfm.php` there is a `url_prefix`, which defines the url to the filemanager. Check if you have such a config.

**Comment by hai-ru** [comment]
Ok thank you it work
