### ISSUE TITLE
Blank popups and no files showing.

### ISSUE THREAD

**Issue by eqxDev** [UniSharp/laravel-filemanager#396]
Issue 1.
<img width="1440" alt="screen shot 2017-08-23 at 22 17 44" src="https://user-images.githubusercontent.com/14370263/29639083-69e67392-8851-11e7-94d9-0ada77b41621.png">
There are two blank popups that show up when the page loads, there are some errors too.

Issue 2. Items can be created and added except no files are shown if you look in the back of the image attached you only see the white.

Any help will be amazing.

**Comment by eqxDev** [comment]
Solved!

Turned off secure in valet.
Edited the route file as I had a route "{}/{}".

**Comment by youchenlee** [comment]
👍  Thank you for your sharing @eqxDev. We will close this issue now
