### ISSUE TITLE
Optimizing Images

### ISSUE THREAD

**Issue by jeremyhart** [UniSharp/laravel-filemanager#397]
Does anyone know how to make this awesome plugin resize and optimise the images when they are saved?

I want to optimize them like Google suggests here:
https://developers.google.com/speed/docs/insights/OptimizeImages

**Comment by youchenlee** [comment]
Perhaps try image-optimizer https://github.com/spatie/image-optimizer/blob/master/README.md and implement it right after the `file uploading` event
