### ISSUE TITLE
Token mismatch error while uploading BIG video files

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#399]
Hi guys. When I'm trying to upload about 20MB video file, it return a `Token Mismatch` error, but when I upload 17MB or below, it works fine. Why is that?

**Comment by gwleuverink** [comment]
Hi @jonjie0317. I believe this has something to do with PHP. If your `post_max_size` property in your php ini file is exceeded, the $_FILEs and $_POST superglobals will not be filled. Because of this the CSRF token wil also not be posted.

Can you set `post_max_size` a little higher and see if that helps? 

If you want to catch this error you could consider to update the `max_image_size` and `max_file_size` options in lfm.php to a value that is lower than the setting in your .ini file. (I didn't test if this works yet, but sounds plausible)

**Comment by jonjie0317** [comment]
@gwleuverink  Hi, I'll try it later. Thank you for your reply.

**Comment by jonjie0317** [comment]
Hello. Any update about this issue?  After I updated this, I'm now getting the `File is too big` error message. Why is that? I'm just uploading 55MB.

**Comment by jonjie0317** [comment]
I've already changed it.

upload_max_filesize: 128MB
post_max_size: 200MB

**Comment by jonjie0317** [comment]
Still getting the same error. Any updates?

**Comment by gwleuverink** [comment]
Can you post the exact error trace using the network tab inside chrome after a failed upload?

**Comment by jonjie0317** [comment]
Hi @gwleuverink . This is the response:

{"html":"<p>Folder is empty.<\/p>\n","working_dir":"\/3\/Vids\/Myself"}

**Comment by jonjie0317** [comment]
@gwleuverink  What's do I have to do next?

**Comment by jonjie0317** [comment]
I can upload up to 51.9MB. And not greater than that. It shows an error **File is too big**. Please see the image below:


![image](https://user-images.githubusercontent.com/16563175/40461370-a335b478-5f3d-11e8-921f-23e0e62bc22d.png)

**Comment by g0110280** [comment]
Check this comment https://github.com/UniSharp/laravel-filemanager/issues/592#issuecomment-388404299. See if changing `memory_limit ` config helps.

**Comment by jonjie0317** [comment]
I tried to changed it in `lfm.php` and in `php.ini` but still getting the same message.

**Comment by jonjie0317** [comment]
I see the `File is too big` message in `dropzone.min.js` file. But I don't know what its checking. Uhm really confusing.

**Comment by g0110280** [comment]
You might also need to change `max_file_size` and `max_image_size` in `config/lfm.php`.

**Comment by jonjie0317** [comment]
Should I also change `'should_validate_size' => false` to `'should_validate_size' => true` ?

**Comment by jonjie0317** [comment]
I currently have this setup. Is it fine to setup like this:

![image](https://user-images.githubusercontent.com/16563175/40467645-4801cdd8-5f5d-11e8-9ba6-f625a8cbb42a.png)

**Comment by jonjie0317** [comment]
Great! It works now. Thanks a lot @g0110280 .
