### ISSUE TITLE
use filemanager separate from editor

### ISSUE THREAD

**Issue by amin101** [UniSharp/laravel-filemanager#40]
is it possible to use this filemanager apart from tinymce \ckeditor ?
i tried `/laravel-filemanager?field_name=thumbnail&type=Images"` . it does open the image browser but when i try to select an image it doesnt close image browser and nothing happen
[Responsive File Manager](www.responsivefilemanager.com) has a callback (responsive_filemanager_callback) that run when an image is selected in its file browser. 
I dont know if there is a such callback for this filemanager

**Comment by youchenlee** [comment]
@amin101 There is no such function yet, but we are current working on it, hopefully it will be in the next release.

This issue is similar to #37 .

**Comment by tekinerten** [comment]
how can we get an external button for uploading a file?

**Comment by g0110280** [comment]
Implemented today, docs are added, too.
Please update to dev-master and give it a try.

**Comment by nasirkhan** [comment]
can you please update the package version number, the `composer update` does not pull the new code.

**Comment by youchenlee** [comment]
@nasirkhan , Just released 1.5.0 https://packagist.org/packages/unisharp/laravel-filemanager#1.5.0
Thanks for advice.

**Comment by nasirkhan** [comment]
you released the 1.5.1 but the composer update does not fetch the code

**Comment by youchenlee** [comment]
@nasirkhan That doesn't make sense. The release 1.5.1 (https://packagist.org/packages/unisharp/laravel-filemanager#1.5.1) should be available in just few minutes after we pushed the tag.

Are you able to access 1.5.1 now? It's okay to keep using 1.5.0. There's no major changes.

**Comment by g0110280** [comment]
@nasirkhan 
1.5.2 was released today, please follow the upgrade guide in readme, see if you can fetch the new version.
Also thanks for spotting the error in integration document.
