### ISSUE TITLE
I cannot upload pdf/files on live website

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#400]
Hi guys! After I followed the upgrade guide, there's still no changes made. I still have this little bug, because when I'm trying to upload a PDF file in my localhost it works fine, but in live, it is not working, no file appears in the list of files. I can choose a file though, but I can't upload it. Why is that? Thanks!

**Comment by youchenlee** [comment]
Hi @jonjie0317 
There must have some errors in PHP/laravel error logs or browser console.
Would you please paste these logs here?

**Comment by jonjie0317** [comment]
@youchenlee Sorry for the late reply, I will try it now.

**Comment by jonjie0317** [comment]
@youchenlee I got this response,


> html | <table class="table table-resp…tr>       </tbody> </table>
> -- | --
> working_dir | /31

**Comment by g0110280** [comment]
I think this is fixed in `v2.0.0-alpha6`. Please comment here if there is any further problem.
