### ISSUE TITLE
Standalone file manager

### ISSUE THREAD

**Issue by jeremyhart** [UniSharp/laravel-filemanager#401]
Is there a way to make a standalone file editor? I've put one in an iframe but I can only manage files or images, I want to manage both as is renaming and moving sorting etc

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by g0110280** [comment]
Got it. We should add it to our document.

**Comment by g0110280** [comment]
@jeremyhart The document is [here](http://unisharp.github.io/laravel-filemanager/integration#embed-file-manager).

**Comment by jeremyhart** [comment]
@g0110280 thanks for adding it to the doc's, however, I my question above what about how to show both images and files in this view, without the type parameter in the url it doesn't show the images or files.

**Comment by g0110280** [comment]
Without `type` parameter, images and files shows up the same time.
