### ISSUE TITLE
Form appears at the bottom left of the screen, every first time, the page loads.

### ISSUE THREAD

**Issue by cakesforfree** [UniSharp/laravel-filemanager#402]
This happends after the page loads:

![image](https://user-images.githubusercontent.com/13759233/29747870-6bd65d36-8ac5-11e7-8687-8f7beb81d516.png)

But it gets fixed after the window gets closed and you open anyother window, the emoticon window for example:
![image](https://user-images.githubusercontent.com/13759233/29747909-7c504180-8ac6-11e7-9029-1f6f3085d1a5.png)

it then appears at the center:
![image](https://user-images.githubusercontent.com/13759233/29747913-9fa51c78-8ac6-11e7-858c-b59a40acc3b5.png)

Could help me to prevent it keep appearing at the botton left, please? 

![image](https://user-images.githubusercontent.com/13759233/29747917-c5212d2a-8ac6-11e7-912a-a3b40f624d87.png)

Theme that i am using:
https://github.com/creativetimofficial/material-dashboard

**Comment by g0110280** [comment]
@cakesforfree This should be the issue with CKEditor, you might need to paste your screenshots to their GitHub repository as well.

**Comment by cakesforfree** [comment]
@g0110280 The problem is that it started to happend after I installed this filemanager, and it only happends with the "image propeties" window. Without the filemanager the "image propeties" window pops right at the middle of the screen.
