### ISSUE TITLE
laravel-filemanager update on sherehosting and open chmod 777 a 

### ISSUE THREAD

**Issue by jirakit2537** [UniSharp/laravel-filemanager#403]
**laravel-filemanager** update on sherehosting and open chmod 777 but don't upload image and file but can create folder and rename crop edit delete  system show suscess but don have image  and i update version 1.8.1
![255](https://user-images.githubusercontent.com/18676643/29771483-3d471640-8c1e-11e7-91d7-cd5d5c7c26fc.PNG)

my support hosting tell me laravel-filemanager can't support for hosting

**Comment by youchenlee** [comment]
@jirakit2537 
Hi, there should be some errors in browser console or PHP/laravel error logs.
Would you please paste the logs here?

**Comment by g0110280** [comment]
Closing inactive issue.
