### ISSUE TITLE
Stand alone button.

### ISSUE THREAD

**Issue by eqxDev** [UniSharp/laravel-filemanager#404]
Hi,

I am using the stand alone button and only one is working per page. 

Both of them open the iframe except when you select an image they both open in the first button.

<img width="1139" alt="screen shot 2017-08-29 at 23 16 55" src="https://user-images.githubusercontent.com/14370263/29846828-70dedd74-8d10-11e7-99e6-7a56c9e7bf58.png">

Thanks in advance.

**Comment by gwleuverink** [comment]
Initialize each button by a unique id. That should do the trick.

**Comment by gwleuverink** [comment]
Hi @eqxDev. Was this issue resolved?

**Comment by g0110280** [comment]
Please take a look at `src/views/demo.blade.php`.
