### ISSUE TITLE
I get the files uploaded in a different folder, but i can retrieve the url where they are stored

### ISSUE THREAD

**Issue by cakesforfree** [UniSharp/laravel-filemanager#405]
all my project files are stored in the root folder of the server:
root/project/
![image](https://user-images.githubusercontent.com/13759233/29859020-6d9003fc-8d1d-11e7-9b07-2f1b87bc3c93.png)

but all my public files are stored in the "public_html" folder:
public_html/
![image](https://user-images.githubusercontent.com/13759233/29859039-7fd65e44-8d1d-11e7-92e7-63460fb6fdc5.png)

in order to upload the files to the public_html folder i had to use the following paths,
lfm config file:
'base_directory' => 'public',
'images_folder_name' => '../../public_html/public/public/filemanager/photos/',
'files_folder_name'  => '../../public_html/public/filemanager/files/',

this actually works, the images and files get uploaded, but when i want to retrive the image and display them, it keeps getting the same url:

![image](https://user-images.githubusercontent.com/13759233/29858842-942d5628-8d1c-11e7-9eab-b3d281ec1c74.png)

and i wonder if there is a way to work this around, something like this:
![image](https://user-images.githubusercontent.com/13759233/29858864-ab1ff8ea-8d1c-11e7-966c-299c2350d003.png)

where you can define paths  where the files are going to be stored, and the url to get the images and files from the public_html folder.

**Comment by johnef** [comment]
@cakesforfree why did you close this issue dose it improved??

**Comment by johnef** [comment]
@cakesforfree please before you close the issue, please clear how did you solve it
I found it [here](https://unisharp.github.io/laravel-filemanager/config#working-directory)
