### ISSUE TITLE
No errors, but file not uploaded

### ISSUE THREAD

**Issue by derapermana** [UniSharp/laravel-filemanager#409]
Recently i've moved my OS from ubuntu to CentOS 7. 
On Ubuntu everything works perfectly, but in CentOS i can't upload anything.
The response from console is "OK", even the "file uploaded succesfully" notification show up, but file not uploaded. 
What i've done :
- Install and enable gd and exif
- Changing folder permission from
- Changing folder owner
But no luck.
Please help me.

**Comment by FreedomKnight** [comment]
did you open the selinux configurations?
maybe you should open the some options like allow_httpd_anon_write

```
setsebool -P allow_httpd_anon_write 1
```
or other options like this

**Comment by derapermana** [comment]
@FreedomKnight I had set httpd_anon_write and httpd_sys_script_anon_write like you said, but still no luck.

**Comment by derapermana** [comment]
OK, i've found the solution from https://blog.lysender.com/2015/07/centos-7-selinux-php-apache-cannot-writeaccess-file-no-matter-what/. It's there.
