### ISSUE TITLE
Browse Server Button Redirecting to Site Root

### ISSUE THREAD

**Issue by cbuchert** [UniSharp/laravel-filemanager#41]
When attempting to integrate laravel-filemanager into both CKEditor and TinyMCE as per the directions in README.md,  making a get request as an authenticated user to /laravel-filemanager/folders redirects to the site root.

**Comment by youchenlee** [comment]
Hi @cbuchert,
Did you sign-in before opening /laravel-filemanager ?
By default laravel-filemanger set the middleware `auth` on https://github.com/UniSharp/laravel-filemanager/blob/master/src/config/lfm.php#L8, it will redirect any guest requests.

**Comment by youchenlee** [comment]
@cbuchert are you using laravel 5.2? if so, please set `'middlewares' => ['web', 'auth'],` to your config/lfm.php

#31

**Comment by kashifleo55** [comment]
Hi i integrate file manager for admin panel i assign the middleware 'middlewares' => ['auth:admin'], partialy file manager load but it also load  my home page view. how to integrate in admin side with
