### ISSUE TITLE
jpg and png image not upload but show message (File Uploaded Successfully)

### ISSUE THREAD

**Issue by fahadhowlader** [UniSharp/laravel-filemanager#414]
everything is done, file work 100%, not show error

**Comment by FreedomKnight** [comment]
Can you find uploaded file on the server side, or can you provide broken image path?

**Comment by mideal** [comment]
I have the same problem on Ubuntu 16 with php 7 and nginx
On local server(xampp) image upload, but on production(ubuntu) server file manager do not upload image and response uploaded successfully. File upload, problem just with image.
I can not find uploaded file on the server. Also on Linux i have this message  laravel-filemanager::lfm.message-extension_not_found

**Comment by DeehSlash** [comment]
+1 Same thing happening here.

**Comment by FreedomKnight** [comment]
@DeehSlash you may try to install php-gd or php-magick

**Comment by mideal** [comment]
@FreedomKnight Thanks. After install php-gd everything work
