### ISSUE TITLE
How to deploy standalone unisharp Laravel-filemanager?

### ISSUE THREAD

**Issue by yorivor** [UniSharp/laravel-filemanager#415]
Hi just want to ask how to deploy a standalone laravel-filemanager?... I tried it on textarea and it works fine... but when i try it to standalone nothing happen when i click the choose button...
here's my code:
```
@extends('layouts.app')

@section('content')
<div class="container top-space">
    <div class="row" >
        <div class="container weldiv">
            <span class="welcomeh1">Add Slidshow</span>
        </div>
    </div>
    <div class="row top-space">
        <div class="container weldiv">
            <div class="col-md-9 col-md-offset-1">
                <form class="form-horizontal" role="form" method="POST" action="{{ route('add_slideshow.post', $article->article_id) }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="slide_title" class="col-md-4 control-label">Slide Title</label>
                        <div class="col-md-8">
                            {{ $article->article_title }}
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('filepath') ? ' has-error' : '' }}">
                        <label for="filepath" class="col-md-4 control-label">Slide Description</label>
                        <div class="col-md-8">
                            <div class="input-group">
                              <span class="input-group-btn">
                                <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                  <i class="fa fa-picture-o"></i> Choose
                                </a>
                              </span>
                              <input id="thumbnail" class="form-control" type="text" name="filepath">
                            </div>
                            <img id="holder" style="margin-top:15px;max-height:100px;">
                            @if ($errors->has('filepath'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('filepath') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    @if(session()->has('message'))
                        <div class="alert alert-success">
                            {{ session()->get('message') }}
                        </div>
                    @endif
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Submit
                            </button>
                            <a href='{{ URL('/home') }}' class="btn btn-primary">
                                Cancel
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{{ asset('vendor/laravel-filemanager/js/lfm.js') }}"></script>
<script>
     $('#lfm').filemanager('image', {prefix: "{{ URL::to('/') }}/"});
</script>
@endsection
```
hope you can help me.. this is a grate filemanager by the way... thanks

**Comment by gwleuverink** [comment]
Hi @yorivor. Did you publish the public assets with `php artisan vendor:publish`?
If that's not the issue could you please paste your console output here?

**Comment by yorivor** [comment]
Hi @gwleuverink yes i did published the assets using` php artisan vendor:publish` but it still not working...

**Comment by yorivor** [comment]
here's my console output
![image](https://user-images.githubusercontent.com/26926416/30526893-d4f176a2-9c54-11e7-9814-2bba81392cf9.png)

**Comment by gwleuverink** [comment]
Hi @yorivor. Sorry for the mix-up. I meant your browser console.

**Comment by yorivor** [comment]
There's no browser error shows on the console.. that's why it kinda hard to determine what is the problem...

**Comment by gwleuverink** [comment]
That does make it more difficult. What version of the filemanager are you using? I will try to reproduce using your code example.

**Comment by gwleuverink** [comment]
@yorivor Your example works on my end. Make sure you click 'choose' instead of the input field. 

Also, I had to remove the prefix parameter of your javascript initialisation to make it work on a clean install. But this might depend on the machine you are using. (It's necessary on Windows)

Does the file manager window open on your end if you click 'choose'?

**Comment by yorivor** [comment]
@gwleuverink no the file manger window didn't open up every time i click the choose button

**Comment by gwleuverink** [comment]
The fact that no errors are raised makes me suspect that a pop up blocker might be preventing the window.open call. Can you check that? And have you tried different browsers to pinpoint the issue?

**Comment by gwleuverink** [comment]
Hi @yorivor. Did you solve this issue?

**Comment by nalorim** [comment]
Missing url prefix to larval-filemanager:

1. composer update

2. Add url prefix in the script
var route_prefix = "{{ url(config('lfm.url_prefix')) }}";
$('#lfm').filemanager('image', {prefix: route_prefix});

**Comment by yorivor** [comment]
Hi watashi_nalo,

I haven't tried it yet.. but thank you for your reply..

**Comment by g0110280** [comment]
Closing inactive issue.
