### ISSUE TITLE
Bootstrap 4 and Laravel 5.5

### ISSUE THREAD

**Issue by nasirkhan** [UniSharp/laravel-filemanager#416]
Is there any plan or activities going on regarding Bootstrap 4 and Laravel 5.5?

**Comment by gwleuverink** [comment]
5.5 has been tested #407 and package auto discovery has been working since release 1.8.1 as per this PR #352 .

About bootstrap 4 i'm not sure. Bootstrap is still in aplha now. Do you think it will add extra value when it releases?

**Comment by nasirkhan** [comment]
Bootstrap v4 is Beta now and it is the default version at http://getbootstrap.com. So from now on anyone download the library will get this version. But as like the previous version there are links to visit the Bootstrap v3. 

For the next release, Bootstrap v4 should be added. As every one is not ready and not all the the templates are v4 ready, so v3 and v4 select option could be added on the config page.

**Comment by gwleuverink** [comment]
Cool I wasn't aware the beta was out. The filemanager runs in a new window or iframe so there will not be any compatibility issues when people use the Bootstrap 4 beta in their project.

**Comment by g0110280** [comment]
Laravel 5.5 is supported already. It's true that the styles of filemanager does not have compatibility with laravel project. But still we should use Bootstrap v4 instead of v3 for future version. I will add this as a milestone of v2.0 .

**Comment by g0110280** [comment]
Implemented in d3c7aba.
