### ISSUE TITLE
Wrong date format.

### ISSUE THREAD

**Issue by domialex** [UniSharp/laravel-filemanager#417]
In **objectPresenter** in **LfmHelpers.php** line **479** on version **1.8**, the date format should be _"Y-m-d h:i"_ instead of _"Y-m-d h:m"_.

**Comment by gwleuverink** [comment]
Thanks! Good catch! See #418 . If it's merged the next release will fix it.

**Comment by youchenlee** [comment]
Merged. Thank you @domialex
