### ISSUE TITLE
error on view parameter : Trying to get property of non-object Laravel 5.1 Sentinel

### ISSUE THREAD

**Issue by heribertusk** [UniSharp/laravel-filemanager#42]
I'm using laravel 5.1, and Sentinel Package as auth manager. Here is my lfm.php:
`
return [
    'rename_file'        => true,

    'use_package_routes' => true,

    'middlewares'        => ['SentinelAdmin'],

    'allow_multi_user'   => false,

    'user_field'         => 'id',

    'shared_folder_name' => 'shares',
    'thumb_folder_name'  => 'thumbs',

    'images_dir'         => 'public/uploads/images',
    'images_url'         => '/images/',

    'files_dir'          => 'public/uploads/files/',
    'files_url'          => '/files/',
`
While open the image browser from tinyMCE 4, its fire error :

>  Trying to get property of non-object

, My guess every index view parameter like $error, $working_dir doesnt get their value.

Am I missing some steps? TIA

**Comment by g0110280** [comment]
@heribertusk :
I tested with tinyMCE 4 and cannot reproduce this error.
I think there might be some problems with "SentinelAdmin" middleware.
Could you replace it with Laravel "auth" middleware and test it again?
Or you can provide more information about this error so I can fix it.

**Comment by g0110280** [comment]
Close issue for now.
Feel free to reopen this issue if you need further discuss.
