### ISSUE TITLE
Bug in RenameController.php

### ISSUE THREAD

**Issue by domialex** [UniSharp/laravel-filemanager#422]
On **line 47** of **RenameController.php** it seems that there is a regex check using **lfm.alphanumeric_directory** instead of **lfmalphanumeric_filename**. The logic here might need some rethinking.
Also, the regex should be _'/[^\w.-]/i'_ or else it will never be able to be renamed using the dot added to the filename on **line 36**.

**Comment by youchenlee** [comment]
@domialex Thank you.

That is definitely a bug, and it needs a refactoring.
I'll work on it soon.
