### ISSUE TITLE
Event Handling 

### ISSUE THREAD

**Issue by nikhil53** [UniSharp/laravel-filemanager#423]
while handling event I am getting following error ..!

> "message": "Type error: Argument 1 passed to App\\Providers\\UploadListener::onImageWasUploaded() must be an instance of App\\Providers\\ImageWasUploaded, string given", "exception":
![screenshot](https://user-images.githubusercontent.com/19602629/30690535-2a1473a2-9ee2-11e7-94c5-cd710839f145.png)

**Comment by gwleuverink** [comment]
Hi @nikhil53. Can you post your UploadListener class here?

**Comment by nikhil53** [comment]
`<?php

namespace App\Providers;


use App\Providers\ImageWasUploaded;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class UploadListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    public function subscribe($events)
    {
        $events->listen('*', UploadListener::class);
    }


    public function handle($event)
    {
        $method = 'on'.class_basename($event);
        if (method_exists($this, $method)) {
            call_user_func([$this, $method], $event);
        }
    }

    public function onImageWasUploaded(ImageWasUploaded $event)
    {
        \Log::info('Info.', ['msg','Image uploaded']);
        $path = $event->path();
        // your code, for example resizing and cropping
    }
}
`

**Comment by gwleuverink** [comment]
Thanks. I can't find anything that could cause that error here. Can you share your `EventServiceProvider` as well?

ps: I edited your comment so all code is formatted.

**Comment by sandeepts** [comment]
EventServiceProvider  is like this

 protected $listen = [
     ImageWasUploaded::class => [
         UploadListener::class,
     ],
 ];

**Comment by sandeepts** [comment]
I have same issuse
EventServiceProvider :
 protected $listen = [
     ImageWasUploaded::class => [
         UploadListener::class,
     ],
 ];

also generated using
php artisan event:generate

**Comment by FreedomKnight** [comment]
Is use App\Providers\ImageWasUploaded your customized class?
Or try to change the namespace into Unisharp\Laravelfilemanager\Events\ImageWasUploaded

**Comment by g0110280** [comment]
Closing inactive issue.
