### ISSUE TITLE
How to insert image name into database after upload with Tinymce???

### ISSUE THREAD

**Issue by vDiFoung** [UniSharp/laravel-filemanager#425]
Sorry for my English!!!
i have the problem. After upload image with Tinymce successfully, i want insert image name to database. HOw can do it?  
Thank you!!!

**Comment by gwleuverink** [comment]
You can listen to the ImageWasUploaded event and save the path using Eloquent.

Do the same with deleting and renaming and you'll keep everything in sync across the database and filesystem.

You can find implementation examples in the [documentation](https://unisharp.github.io/laravel-filemanager/events).

**Comment by vDiFoung** [comment]
Thank you so much!!! I have managed to solve this problem

**Comment by gwleuverink** [comment]
Great! 😄
