### ISSUE TITLE
Issue upload More file

### ISSUE THREAD

**Issue by gifary** [UniSharp/laravel-filemanager#427]
Hello,
thanks for created amazing package.  I got an issue when upload file more than 20. The success upload file less than 15. It doesn't show error message or anything. I try on local and live server. 
Information
Each file less than 2Mb

**Comment by g0110280** [comment]
@gifary What is the value of your `upload_max_filesize ` & `post_max_size ` in `php.ini`?

**Comment by gifary** [comment]
Sory, I am forgot to increase value on php.ini.
Thanks
