### ISSUE TITLE
How to select multiple photos?

### ISSUE THREAD

**Issue by LusenkoSasha** [UniSharp/laravel-filemanager#428]
How to select multiple photos in one box? I want to make a back gallery

**Comment by youchenlee** [comment]
Hi @LusenkoSasha 
laravel filemanger only supports multiple files selection for upload.
On laravel filemanger gallery view, it is not supported currently.

**Comment by Miri92** [comment]
Hi. I need this, too

**Comment by g0110280** [comment]
Done in `v2.0.0-alpha`.
