### ISSUE TITLE
Multi_user mode but for other model not user

### ISSUE THREAD

**Issue by nfunwigabga** [UniSharp/laravel-filemanager#431]
I would like to integrate this into a Laravel Spark application, so that each "Team" can upload images to a specific private directory for that "Team". So it would be like "multi_user" mode but instead of using the User model, I want to use the "Team" model. Any way to handle this?

**Comment by youchenlee** [comment]
Hi @nfunwigabga 
This is a good question.

I think it can simply be done by setting the `user_field` config.

For example, set `user_field` to your config provider
```
    'user_field' => Your\Own\UserFieldConfigProvider::class,
```

Inside `UserFieldConfigProvider`
```
<?php
namespace Your\Own;

class ConfigHandler
{
    public function userField()
    {
        return auth()->user()->team_id;
    }
}
```

where `unique_team_id` (or any DB field matching your purpose) should be a field represents the user's team identity.

an example table will look like

```
user table:
  id int autoincrease
  username varchar(64)
  team_id varchar(64)
```

with  `'allow_multi_user' => true,`, the team members are sharing their uploads inside their own specific  team_id folder

**Comment by g0110280** [comment]
Closing inactive issue.
