### ISSUE TITLE
Can not select the image from file manager after upload from directory 

### ISSUE THREAD

**Issue by saifuldhaka** [UniSharp/laravel-filemanager#432]
![fireshot screen capture 015 - dashboard - shopavision - 127_0_0_1_8000_client_product](https://user-images.githubusercontent.com/2381203/31110462-e251f4b6-a839-11e7-8b59-ed1f1b4fb281.png)

Hi i am using laravel 5.4 and TinyMCE4 as editor. Here i can create folder and upload images but it not allow me facing an issue, i cant select the image what i just uploaded and popup window not close. I follow your instruction from here https://unisharp.github.io/laravel-filemanager/integration
thanks

**Comment by saifuldhaka** [comment]
hi if i use this link 
https://cloud.tinymce.com/stable/tinymce.min.js
it works but popup notice
![111](https://user-images.githubusercontent.com/2381203/31111164-a94ab5f4-a83e-11e7-9ca0-2d144e747058.png)

**Comment by gwleuverink** [comment]
Hi @saifuldhaka. A bug was introduced in TinyMCE 4.6.7 that breaks the integration. They TinyMCE is working on a fix. See #424 and check if that solution works for you.

**Comment by saifuldhaka** [comment]
i just changed 
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
to 
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.6.6/tinymce.min.js"></script>
it works fine.

**Comment by gwleuverink** [comment]
Good! In that case i'll close this issue :)
