### ISSUE TITLE
laravel-filemanager (Laravel 5.5)  cannot  upload png and jpg

### ISSUE THREAD

**Issue by val08** [UniSharp/laravel-filemanager#433]
All file types are uploaded except png and jpg. Gif and svg are loaded normally. I can not understand why it does not work with png and jpg. OS Archlinux, php-gd installed.
PHP 7.1.10 (cli) (built: Sep 27 2017)

**Comment by netopvh** [comment]
It's happening to me too, I think it's some problem in the source.

Please help!

**Comment by gwleuverink** [comment]
Can you run `php ./vendor/unisharp/laravel-filemanager/bin/debug` and paste the output here?

**Comment by val08** [comment]
└─ $ php ./vendor/unisharp/laravel-filemanager/bin/debug
OS System & Version: Linux vmarch 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64
Laravel Version: v5.5.2
File Manager Version: v1.8.0
imagick Extension: Install
gd Extension: Install

**Comment by eduardduta** [comment]
hi, when i click on a thumbnail open image in new window not put in input in editor. i use it with tinyMCE

**Comment by youchenlee** [comment]
Hi @val08 and @netopvh,
Thank you for the info.
However, for now, I can just guess it's causing by thumbnails, because we don't create thumbnails for svg and gif.

To make sure if we have fixed it before, would you help us to test the bug on `v1.8.2-alpha`? It's on packagist now and it can be installed by `composer`

**Comment by youchenlee** [comment]
Hi @eduardduta,
This sounds like a different issue. Can you please file a new issue for that? And please provide as much information as possible.

**Comment by val08** [comment]
Installed v1.8.2-alpha (without extension php-exif was not installed "extension=exif.so"). Everything works perfectly. I tried it on v.1.8.0, it also works. 
Many thanks. I close the issue.
