### ISSUE TITLE
click on thumbnail open image in new window

### ISSUE THREAD

**Issue by eduardduta** [UniSharp/laravel-filemanager#434]
OS System & Version: Linux dev2 4.4.44-1-pve #1 SMP PVE 4.4.44-84 (Thu, 9 Mar 2017 12:06:34 +0100) x86_64
Laravel Version: v5.5.11
File Manager Version: v1.8.1
imagick Extension: Not Install
gd Extension: Install

I can upload resize, crop but when i try to select image for editor it open in new tab instead to select in editor.

**Comment by g0110280** [comment]
@eduardduta Were you integrating this package with WYSIWYG editor? Or with standalone button?

**Comment by eduardduta** [comment]
i use tinyMCE

**Comment by LenisDaniel** [comment]
@eduardduta Could you solve the problem?

**Comment by eduardduta** [comment]
not yet. the problem still persist.

**Comment by g0110280** [comment]
@eduardduta do you have any error from your console?

**Comment by eduardduta** [comment]
No, that was first thing that i checked.

**Comment by colinbarstow** [comment]
Getting the exact same issue, i've tried with TinyMCE, Summernote, CKE and standalone button. 
File manager opens fine, images upload fine, resize and crop all works nicely but as soon as i click on an image to select it, it just opens a new window "view file" with the image and nothing else. 

No idea what's going on. Tied in multiple projects and same thing each time.

**Comment by sezginriggs** [comment]
@g0110280 I can also confirm same bug, cannot select with CKE, when clicked on image, opens "View File"

**Comment by mohammedfathi92** [comment]
I have the same problem ,I  use tinyMCE

**Comment by webkkopsse** [comment]
to fix when u click on images then open "view file" :  
1. open resources/views/vendor/laravel-filemanager/grid-view.blade.php
2. and change onlick = "viewFile" to onclick = "useFile" 
before
<div class="square clickable {{ $item->is_file ? '' : 'folder-item' }}" data-id="{{ $item_path }}"
           @if($item->is_file && $thumb_src) onclick="viewFile('{{ $item_path }}', '{{ $item->updated }}')"
           @elseif($item->is_file) onclick="download('{{ $item_name }}')" @endif >
      @if($thumb_src)
      <img src="{{ $thumb_src }}">
      @else
      <i class="fa {{ $item->icon }} fa-5x"></i>
      @endif
    </div>
after
<div class="square clickable {{ $item->is_file ? '' : 'folder-item' }}" data-id="{{ $item_path }}"
           @if($item->is_file && $thumb_src) onclick="useFile'{{ $item_path }}', '{{ $item->updated }}')"
           @elseif($item->is_file) onclick="download('{{ $item_name }}')" @endif >
      @if($thumb_src)
      <img src="{{ $thumb_src }}">
      @else
      <i class="fa {{ $item->icon }} fa-5x"></i>
      @endif
    </div>

this work for me

**Comment by mohammedfathi92** [comment]
yes, and work for me too  ... thanks @webkkopsse

**Comment by g0110280** [comment]
Views are refactored in `v2.0.0-alpha`.

**Comment by Lunberg88** [comment]
Have the same issue, but in "vendor/unisharp/....../views/grid-view.blade.php"

`
    <div class="square clickable {{ $item->is_file ? '' : 'folder-item' }}" data-text="testHere" data-id="{{ $item_path }}"
           @if($item->is_file && $thumb_src) onclick="**useFile**('{{ $item_path }}', '{{ $item->updated }}')"
           @elseif($item->is_file) onclick="download('{{ $item_name }}')" @endif >
      @if($thumb_src)
      <img src="{{ $thumb_src }}">
      @else
      <i class="fa {{ $item->icon }} fa-5x"></i>
      @endif
    </div>
`
Allready this function - useFile().

And when i click to insert img link it open a new window with img preview...

Who can help?

**Comment by paulkn** [comment]
@Lunberg88 Do you also have that same file in resources/views/vendor/laravel-filemanager/? If so Laravel will use that one and override any changes you make to this file vendor/unisharp/....../views/grid-view.blade.php for reference see: "Overriding Package Views" https://laravel.com/docs/5.1/packages

**Comment by paulkn** [comment]
@Lunberg88  Also remove those ** around useFile if that is your actual code.

**Comment by Lunberg88** [comment]
> @paulkn 
Thanks, but there is no such dir in resources, only css & js.
Also in vendor dir, in view file the code is clean and without (**).
`onclick="useFile('{{ $item_path }}', '{{ $item->updated }}')"`
So, if u have any idea's, it would be nice :)
