### ISSUE TITLE
Publish vendor not working

### ISSUE THREAD

**Issue by phamtien990819** [UniSharp/laravel-filemanager#435]
in Laravel 5.5
![image](https://user-images.githubusercontent.com/31003927/31377924-e3d99b8c-add3-11e7-8230-b369e754ee99.png)

**Comment by gwleuverink** [comment]
Hi @phamtien990819. Have you tried adding the tags?

```
php artisan vendor:publish --tag=lfm_config
php artisan vendor:publish --tag=lfm_public
```

**Comment by phamtien990819** [comment]
@gwleuverink I tried it, but does not work.

**Comment by gwleuverink** [comment]
It looks like the service provider isn't discovered correctly so the publish commands aren't registered within your app. 
Does the package register after you run `composer dump-autoload`?

**Comment by phamtien990819** [comment]
I tried manually adding the provider and it worked.

**Comment by gwleuverink** [comment]
Thanks for posting back. Glad it works. I’ll close this
