### ISSUE TITLE
Laravel 5.5 - orientate() is not applied to uploaded image

### ISSUE THREAD

**Issue by elmima** [UniSharp/laravel-filemanager#438]
Whenever I tried to upload an image that needed the orientate() function , the uploaded image was not rotated, but the thumbnail was. It puzzled me as I used the same code elsewhere in my project and it worked fine. Looking at the source of the upload controller I found this:
```
try {
            if (parent::fileIsImage($file) && ! parent::imageShouldNotHaveThumb($file)) {
                Image::make($file->getRealPath())
                    ->orientate() //Apply orientation from exif data
                    ->save($new_file_path, 90);
                $this->makeThumb($new_filename);
            }
            {
                chmod($file->getRealPath(), 0644); // TODO configurable
                File::move($file->getRealPath(), $new_file_path);
            }

```
which seems to over-write the newly created image
If I change this to
```
try {
            if (parent::fileIsImage($file) && ! parent::imageShouldNotHaveThumb($file)) {
                Image::make($file->getRealPath())
                    ->orientate() //Apply orientation from exif data
                    ->save($new_file_path, 90);
                $this->makeThumb($new_filename);
            }
           else
            {
                chmod($file->getRealPath(), 0644); // TODO configurable
                File::move($file->getRealPath(), $new_file_path);
            }
```
it works

**Comment by youchenlee** [comment]
@elmima You are right.
I was very confused about that block of codes without an "else" too.
And now I tracked it back, found that it was an error due to an incorrect merge.

I will review the PRs more carefully next time.
Very appreciate your help.
Should be fixed by 2a22db5 and will be on v1.8.2 soon.
