### ISSUE TITLE
Can's seem to figure out the multiple file upload, please can anyone help me with that?

### ISSUE THREAD

**Issue by rheedwahn** [UniSharp/laravel-filemanager#439]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

If your problem still remains, please do these steps :
 * Run `php ./vendor/unisharp/laravel-filemanager/bin/debug` and paste the results here.
 * Capture screenshots of your browser console and paste them here.
 * Provide the steps to reproduce your issue, so we might solve it quicker.

**Comment by g0110280** [comment]
Option 1 : You can drag and drop files into the upload modal.
Option 2 : Click the upload modal, keep holding "shift" key and click on multiple images.
