### ISSUE TITLE
The problem with the upload or delete files on Laravel 5.2

### ISSUE THREAD

**Issue by premier213** [UniSharp/laravel-filemanager#44]
Do not upload any files deleted but you can build folder.

![2016-03-23_18-15-43](https://cloud.githubusercontent.com/assets/4321174/13987293/826978ee-f124-11e5-9665-a61f47c39c5e.jpg)
![2016-03-23_18-16-04](https://cloud.githubusercontent.com/assets/4321174/13987296/82d55a28-f124-11e5-9c09-17e608a08e72.jpg)

**Comment by g0110280** [comment]
@premier213 It seem like the csrf token has expired from your page.

**Comment by premier213** [comment]
How to Solve this Problem?

**Comment by g0110280** [comment]
https://github.com/UniSharp/laravel-filemanager/pull/36#issue-135714400
See if this helps you.

**Comment by g0110280** [comment]
I tested with TinyMCE 4 and cannot reproduce this error.
@premier213 can you show me your config/lfm.php?

**Comment by premier213** [comment]
This problem is caused by the middleware

**Comment by g0110280** [comment]
Got it.
You solved the issue by disabling VerifyCsrfToken middleware?

**Comment by premier213** [comment]
yes but need middleware for this request @g0110280

**Comment by premier213** [comment]
Apache may be my problem?
I am using wamp server

**Comment by g0110280** [comment]
I started a new 5.2 project (on OSX), but uploading/deleting works fine.
And my middlewares are set to `'middleware' => ['web','auth']` too.
Not sure if it is problem of Apache or Windows.

**Comment by g0110280** [comment]
@premier213 :
I tested 1.5.2 on Windows 10, things worked just fine.
Do you have more information about this issue?

**Comment by premier213** [comment]
by this code in `VerifyCsrfToken.php` solved.

`    public function handle($request, Closure $next)
    {
        $regex = '#' . implode('|', $this->except) . '#';

        if ($this->isReading($request) || $this->tokensMatch($request) || preg_match($regex, $request->path()))
        {
            return $this->addCookieToResponse($request, $next($request));
        }

        throw new TokenMismatchException;
    }`
