### ISSUE TITLE
Solution for update 1.8.2 with htmlspecialchars() error

### ISSUE THREAD

**Issue by nalorim** [UniSharp/laravel-filemanager#442]
when you update and get an error: htmlspecialchars() expects parameter 1 to be string

The problem is due to the url prefix in the config/lfm.php

V 1.8.1
 'prefix' => 'laravel-filemanager',

V 1.8.2
'url_prefix' => 'laravel-filemanager',

**Comment by youchenlee** [comment]
@nalorim Thank you.

Sorry for not answering this breaking change.
I will release v1.8.2.1 soon for the fix.

**Comment by youchenlee** [comment]
Fixed in d214e13
`v1.8.2.1` will be out soon.

**Comment by youchenlee** [comment]
Done: https://github.com/UniSharp/laravel-filemanager/releases/tag/v1.8.2.1
