### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by cbcto** [UniSharp/laravel-filemanager#444]
I previously had Laravel-filemanager working with ckeditor. However now when I click on 'Browse Server' I get errors from the laravel-filemanager\index.blade.php file - basically all the variables are not defined, e.g. $working_dir, $file_type, $extension_not_found

I did follow the upgrade instructions, see the debug log below.

Thanks

OS System & Version: Windows NT XPS 10.0 build 15063 (Windows 10) AMD64
Laravel Version: v5.4.22
File Manager Version: v1.8.2.1
imagick Extension: Not Install
gd Extension: Install

![img](https://user-images.githubusercontent.com/20266625/31697179-b4705668-b401-11e7-85a2-3dd8a836386c.PNG)

**Comment by youchenlee** [comment]
@cbcto looks like you didn't publish the views after upgrading laravel-filemanager.

```
php artisan vendor:publish --tag=lfm_view --force
```
Please note that this will overwrite all the current laravel-filemanager view.
