### ISSUE TITLE
Directory does not exist in live website

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#446]
Hi guys, I got an error when I upload my project live but it is working on my local machine. If I use the stand alone button, then no user's folder yet in the directory, it returns an error, But if I add the user's folder renamed it as the `id` before clicking the button then it works fine, here's the errror:

> InvalidArgumentException in Finder.php line 632:
> 
> directory does not exist.

Version of LFM: **v1.8.2.1**

I've also noticed this part in the `lfm.php`:

```
// permissions to be set when create a new folder or when it creates automatically with thumbnails
    'create_folder_mode' => 0755,

// permissions to be set on file upload.
'create_file_mode' => 0644,
```

What folder/file do I have to apply it?

Thanks 
@g0110280 
@gwleuverink

**Comment by fencermd** [comment]
Have the same problem, how did you resolved it?

**Comment by jonjie0317** [comment]
Hi @fencermd  . Try to update your LFM.

**Comment by Maximevilla** [comment]
me too

**Comment by MansoorAli6266** [comment]
i also face .
![image](https://github.com/UniSharp/laravel-filemanager/assets/157581853/bb353d4d-d2a9-40a3-ba81-7ff46c0f922d)
