### ISSUE TITLE
Animated GIF images

### ISSUE THREAD

**Issue by pompex** [UniSharp/laravel-filemanager#447]
I have just tested the package and turns out it doesn't support animated gif images. Why is that? Apparently you're loading the uploaded image into the intervention (GD) and save it like that - and since intervention doesn't support animated images - it's removing the animation. 

Mostly likely you could simply call copy on the uploaded image and disable crop/resize functionality to make it work. 

Is this known / planned to be fixed?

**Comment by g0110280** [comment]
Thanks for reporting this. This functionality was fixed before and went broken again since recent releases. We will fix this in next release.

**Comment by youchenlee** [comment]
@pompex 
Great suggestion. Thank you.
Just pushed https://github.com/UniSharp/laravel-filemanager/releases/tag/v1.8.2.2 for this fix.

Filemanager now bypasses GIF and SVG images, treat them as normal files.

**Comment by youchenlee** [comment]
BTW, cropping a GIF image will still remove the animation. This is the limitation. :)

**Comment by pompex** [comment]
@youchenlee Awesome! Thanks for the commit!

**Comment by youchenlee** [comment]
@pompex It depends on your settings in composer.json

Or simply run `composer require unisharp/laravel-filemanager:~1.8`
