### ISSUE TITLE
refreshFoldersAndItems firing too soon during upload

### ISSUE THREAD

**Issue by appdezign** [UniSharp/laravel-filemanager#452]
I have been testing with both TinyMCE and CKEditor, but the results are the same. When I am uploading a small image, the list is refreshed in the background as it should. But when I am uploading a very large image, I can see the list refreshing in the background, while the file is still uploading! The result is that, when I close the modal, the uploaded file is NOT shown in the list. I have to refresh the list by clicking on thumbnails, list, or sort to actually see the new file(s).

When I check the code that is responsible for the refreshing, I can see that 'refreshFoldersAndItems' is fired on the Dropzone 'addedfile' event:

views/index.blade.php - line 201
`this.on("addedfile", function(file) { refreshFoldersAndItems('OK'); });`

The Dropzone docs are not very clear about the 'addedfile' event, but from what I've seen, I think 'refreshFoldersAndItems' should be fired on 'success' or on 'complete'.

I have tested this extensively, and it seems to solve the problem.

**Comment by youchenlee** [comment]
Thank you @appdezign.
Will take a look soon.

**Comment by snowsem** [comment]
how much time you need to fix it? i have this problem too. After upload first image in dropzone area not update but if i upload next img in this instance previus img show...but next no...etc

**Comment by g0110280** [comment]
@appdezign Thank you for pointing out the line that causes this error, it really helps a lot. This is fixed in `v1.8.3`.
