### ISSUE TITLE
laravel-filemanager "Laravel 5.5" cannot upload png and jpg

### ISSUE THREAD

**Issue by anasmorahhib** [UniSharp/laravel-filemanager#456]
extensions like gif, svg ... gets uploaded successfully.
but the extention png and jpg me return "invalid request upload".
OS Archlinux,
php-gd installed,
 php-exif installed

**Comment by youchenlee** [comment]
Hi @anasmorahhib 
What version of laravel-filemanager do you use?
Would you please provide us your lfm.php config file and related error logs here?

**Comment by bogumilkorek** [comment]
I have the same problem. 
Laravel 5.5.19, Filemanager v1.8.2.2.
Cannot get detailed logs, just have following json response: 
```
["Invalid upload request"]
  0: "Invalid upload request"
```
when sending data to /laravel-filemanager/upload

**Comment by anasmorahhib** [comment]
problem solved
I reinstall GD

**Comment by rlrlaa123** [comment]
I'm having exactly same problem..what is GD??

**Comment by youchenlee** [comment]
@rlrlaa123 It means the php-gd extension.

**Comment by ssheduardo** [comment]
In localhost (homestead) not have the problem but production has error.
The solution is install *gd*:

```
sudo apt-get install php7.0-gd
```
In my case I uses php7.0, you change by your version of php
Next reload your server web (apache or nginx)
And ready.

---

Spanish:
En mi entorno local me funcionaba todo  al subir a producción fallaba, solo me dejaba subir gif y svg sin problemas.
La solución fue instalar gd
```
sudo apt-get install php7.0-gd
```
En mi caso tengo php7, depende de tu versión.
Luego reiniciar tu servidor web (apache o nginx) 
Y listo
