### ISSUE TITLE
This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by weeework** [UniSharp/laravel-filemanager#458]
I got some problem when I deploy my project in HTTPS server.

![screen shot 2017-10-28 at 11 33 16 am](https://user-images.githubusercontent.com/25600425/32131426-dd1f7444-bbd7-11e7-9627-b53f3bd159f3.png)

**Comment by habibix** [comment]
I have some issue like this. ssl/https successfully work on laravel project.

error message in jquery.js, url https://uxxxx.com/laravel-filemanager?type=image

`// Do send the request
// This may raise an exception which is actually
// handled in jQuery.ajax (so no try/catch here)
xhr.send( ( options.hasContent && options.data ) || null );`

route_prefix and lfm_route still loaded in http

**Comment by youchenlee** [comment]
Thank you @weeework and @habibix 

Yes, this should be configurable or auto-detected. Will schedule this to our next release.

**Comment by g0110280** [comment]
I think this is fixed in v2.0.0 alpha versions.

**Comment by turanzamanli** [comment]
It is not the bug of Laravel file manager. So it is laravel bug.

The helper url() cannot return with https.

For more details, open /vendor/laravel-filemanager/index.blade.php

the 156 and 157 th  line uses  
` var route_prefix = "{{ url('/') }}";
``    var lfm_route = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";`

Fix method:
Open AppServiceProvider and add that code.

```
class AppServiceProvider extends ServiceProvider
{
 public function boot()
 {
    \URL::forceRootUrl(\Config::get('app.url'));    
    if (str_contains(\Config::get('app.url'), 'https://')) {
        \URL::forceScheme('https');
    }
 }
```

**Comment by streamtw** [comment]
Thank you @turanzamanli !

**Comment by TranVanTri** [comment]
Thank you

**Comment by jShox** [comment]
Helper url() can return https, but it checks current request first.

Laravel checks isSecure() by request param HTTPS. Ensure that your proxy-server add this param during proxing request to php-fpm.

Laravels code:
```
    public function isSecure(): bool
    {
        if ($this->isFromTrustedProxy() && $proto = $this->getTrustedValues(self::HEADER_X_FORWARDED_PROTO)) {
            return \in_array(strtolower($proto[0]), ['https', 'on', 'ssl', '1'], true);
        }

        $https = $this->server->get('HTTPS');

        return !empty($https) && 'off' !== strtolower($https);
    }
```

If you use nginx, you can manualy add this param by
`fastcgi_param 	HTTPS ON;`
