### ISSUE TITLE
Won't crop.

### ISSUE THREAD

**Issue by ptorresic** [UniSharp/laravel-filemanager#462]
Hi,
Crop won't work.

Laravel 5.5

"unisharp/laravel-filemanager": "v1.8.2.2"

"message": "Width and height of cutout needs to be defined.",
"exception": "Intervention\\Image\\Exception\\InvalidArgumentException",

Any advice...

Thank you.

**Comment by g0110280** [comment]
Please try `php artisan vendor:publish --tag=lfm_view --force`.
