### ISSUE TITLE
Can't upload image, "Please refresh and try again

### ISSUE THREAD

**Issue by retrospectrum** [UniSharp/laravel-filemanager#467]
when I try using upload and click "Send it to server", it always show "Please refresh and try again"

![screenshot from 2017-11-10 16-39-15](https://user-images.githubusercontent.com/15890634/32652149-f47f7a40-c635-11e7-82a6-a3718df3d06a.png)

I'm still using localhost. I also already followed the installation and integration steps with CKEditor and Laravel 5.5

**Comment by jim1506** [comment]
I have this problem as well

**Comment by jim1506** [comment]
I have searched the internet and the only thing I can find is exif and mbsting, both of which are enabled on my set up. I have made certain of the folders and permissions.

**Comment by retrospectrum** [comment]
yeah, me too. it's 777, isn't it? or is there other file permission that I missed? I'm still new in web programming

**Comment by jim1506** [comment]
It is actually the middleware that is kicking up. In the middleware VerifyCsrfToken add the filemanager to the except statement so it becomes:

```
protected $except = [
      'laravel-filemanager/*'
    ];
```

and it works perfectly.

**Comment by retrospectrum** [comment]
wow, it actually works. thanks a lot

**Comment by gwleuverink** [comment]
That is weird. The csrf token should be posted along with every post request. I will try and reproduce it on a clean project. Can you post what version of CKEditor you are using? 

I discourage disabling the csrf token verification in production. Keep in mind it can be a potential security risk.

**Comment by retrospectrum** [comment]
I'm using CKEditor version 4.7.3

**Comment by jim1506** [comment]
I am using CKEditor 4.7.3 (Full) (revision dee99e2)
