### ISSUE TITLE
You can't upload files of this type.

### ISSUE THREAD

**Issue by DaxtonChen** [UniSharp/laravel-filemanager#468]
Hi~ I can't upload files except pdf. (docx,xlsx....)
Who can help me?
I use laravel-filemanager version 1.8 , TinyMCE
![2017-11-14 19-24-01](https://user-images.githubusercontent.com/32349878/32777960-3336c32a-c973-11e7-9db0-d56528a1586e.png)
![2017-11-14 19-26-11](https://user-images.githubusercontent.com/32349878/32777966-393c28aa-c973-11e7-8c38-3b8a20f2c3ff.png)

**Comment by myathtutthu** [comment]
I also meet that problem @DaxtonChen  how to u solve? kindly reply me.

**Comment by GregMtl** [comment]
config/lfm.php

'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'image/svg+xml',
        'application/pdf',
		'application/docx',
        'text/plain',
		'image/vnd.microsoft.icon',
		'image/x-icon',
		'application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/docx'

    ],

**Comment by Cyber-gedamin** [comment]
not helped. BUT I Removed from: public\vendor\laravel-filemanager\js\dropzone.min.js
This: 
dictInvalidFileType:"You can't upload files of this type.",

And now I am able to upload other type of files.

**Comment by disney1993** [comment]
> not helped. BUT I Removed from: public\vendor\laravel-filemanager\js\dropzone.min.js
> This:
> dictInvalidFileType:"You can't upload files of this type.",
> 
> And now I am able to upload other type of files.

Your tip helped to me... TY
