### ISSUE TITLE
filetools-response-error  when Upload through Drag&Drop

### ISSUE THREAD

**Issue by padre** [UniSharp/laravel-filemanager#469]
Hello, when I use the plugin https://ckeditor.com/cke4/addon/uploadimage if I drag an image to ckeditor, the image is uploaded to the server but not displayed in the editor.

Error code: filetools-response-error

When the file is uploaded successfully, a JSON response is expected, but the server response is: 

`<script type='text/javascript'>

        function getUrlParam(paramName) {
            var reParam = new RegExp('(?:[\?&]|&)' + paramName + '=([^&]+)', 'i');
            var match = window.location.search.match(reParam);
            return ( match && match.length > 1 ) ? match[1] : null;
        }

        var funcNum = getUrlParam('CKEditorFuncNum');

        var par = window.parent,
            op = window.opener,
            o = (par && par.CKEDITOR) ? par : ((op && op.CKEDITOR) ? op : false);

        if (op) window.close();
        if (o !== false) o.CKEDITOR.tools.callFunction(funcNum, '$file');
        </script>
`
Has anyone managed to integrate the plugin uploadimage? Thank you very much.

**Comment by moscoquera** [comment]
check this: https://github.com/UniSharp/laravel-filemanager/pull/474

**Comment by padre** [comment]
Thanks!
