### ISSUE TITLE
issues in laravel 5.2

### ISSUE THREAD

**Issue by kamiyar** [UniSharp/laravel-filemanager#47]
hi 
i have this problem in laravel 5.2:
uploading : 
i can't upload any file or image!
![upload](https://cloud.githubusercontent.com/assets/11064316/14011966/46ddb56e-f1c0-11e5-9d9c-e288e14361aa.PNG)
---------------------------------
i can't rename folders : 
![rename](https://cloud.githubusercontent.com/assets/11064316/14011978/56f9e616-f1c0-11e5-9bda-b84d68226171.PNG)

----------------------------------
and also, i can't delete folder:
![delete](https://cloud.githubusercontent.com/assets/11064316/14011993/6a7e343a-f1c0-11e5-9d29-7b9dbc2143c4.PNG)

thanks for your great work

**Comment by fraterblack** [comment]
I've the same problem in Laravel 5.1

**Comment by kamiyar** [comment]
hi again
ok guys,
@fraterblack , @premier213
With your permission @g0110280 
i will find the upload bug and fixed it
ok, how to fix this:
1. open vendor\unisharp\laravel-filemanager\src\controllers\UploadController.php
2. gor to : function uploadValidator()
3. chane : line 77 and 80 if(!$file) to if(empty($file))
`if (!$file) {
            throw new \Exception(Lang::get('laravel-filemanager::lfm.error-file-empty'));
        }
        if (!$file instanceof UploadedFile) {
            throw new \Exception(Lang::get('laravel-filemanager::lfm.error-instance'));
        }`
to : 
`if (empty($file)) {
            throw new \Exception(Lang::get('laravel-filemanager::lfm.error-file-empty'));
        }
        if (empty($file) instanceof UploadedFile) {
            throw new \Exception(Lang::get('laravel-filemanager::lfm.error-instance'));
        }`

i think this is help,

**Comment by g0110280** [comment]
@fraterblack, @premier213
Thanks for spotting this bug and show me the solution.
However I can't reproduce this error.
What are your PHP versions?

**Comment by kamiyar** [comment]
your welcome :)
php version : 5.6.3

**Comment by g0110280** [comment]
@kamiyar :
Fixed codes as you recommand.
Could you update to dev-master(see readme.md) and see if the problem are solved?

**Comment by kamiyar** [comment]
@g0110280 
first, thanks
updated to dev-master and republished everythinks
but i get this error
![asd](https://cloud.githubusercontent.com/assets/11064316/14059651/73869292-f365-11e5-90ac-2ce98f905ff0.PNG)

**Comment by premier213** [comment]
put 'middleware' => ['web','auth'],`

**Comment by kamiyar** [comment]
still not work!

**Comment by premier213** [comment]
agha @kamiyar this problem for persian language?

**Comment by kamiyar** [comment]
Hi :) @premier213
You don't have this problem?!

**Comment by premier213** [comment]
convert file to UTF-8 @kamiyar

**Comment by g0110280** [comment]
@kamiyar 
Did you login?

**Comment by premier213** [comment]
no @g0110280

**Comment by kamiyar** [comment]
@g0110280  yes i'm login

**Comment by kamiyar** [comment]
@g0110280 
@premier213
ok problem solved. issue is in my router.
everythinks looks good
thank you @g0110280

**Comment by g0110280** [comment]
Well, that is weird.
I just create a new Laravel 5.2 project, encountered "NotFountHttpException" like you.
Then I set middlewares as @premier213  mentioned in `config/lfm.php`.
And the problem solved after I logged in.

**Comment by g0110280** [comment]
OK @kamiyar you're welcome.
Thanks @premier213 .
