### ISSUE TITLE
[Question] ETA on roadmap for 2.0

### ISSUE THREAD

**Issue by pepijnolivier** [UniSharp/laravel-filemanager#471]
Hi,

Thanks a lot for opensourcing this repository !
I want to implement this in a real application, and would like to use features from the v2.0-dev branch. (like usage of laravel filesystems, and JSON API)

I can see there has been recent activity on the branch, so that reassures me that the repository is alive and v2.0 is coming in the near future.

However, I already want to start developing, so I'll be living on the bleeding edge.
Do you have any rough idea when V2.0 will be released as beta or stable ?

I'd like to start as soon as the JSON API is stable enough to work on :)

Thanks a lot !

**Comment by g0110280** [comment]
`v2.0.0-alpha` has just release. Haven't test on Windows. Beta version is planned to release next month.
