### ISSUE TITLE
Working Directory

### ISSUE THREAD

**Issue by gifary** [UniSharp/laravel-filemanager#472]
Hello,

Is there possible to specific folder when i open via javascript ? 
Example 
- when I open LFM in page A, the folder to open is files/shares/folderA
- when I open LFM in page B, the folder to open is files/shares/folderB

Thanks

**Comment by g0110280** [comment]
@gifary If you had published the views, you can add the following to the bottom of `resources/views/vendor/laravel-filemanager/index.blade.php` :
```
<script>
    goTo('folderA');
</script>
```
