### ISSUE TITLE
Laravel Filemanager Upload image Issue

### ISSUE THREAD

**Issue by Hredoy** [UniSharp/laravel-filemanager#475]
Hi.
I was following the installation guide carefully and upgrade unisharp filemanager.
File and folder upload is working fine, but image upload dosn't work and upload nothing!
Everything is working great but When I uploading a image it was saying  "Invalid Upload Request" . 
Notes: This site is hosted in shared hosting.
![untitled](https://user-images.githubusercontent.com/16982572/33142483-e343baf2-cfe0-11e7-8a1e-e14943c70966.png)

Please help me. How to solve it 
thnx.

**Comment by g0110280** [comment]
@Hredoy Please provide your `config/lfm.php`.

**Comment by Hredoy** [comment]
[lfm.zip](https://github.com/UniSharp/laravel-filemanager/files/1498436/lfm.zip)
Here those two file which you want ...

**Comment by Hredoy** [comment]
Hello I need that solution please tell me what i should have to do

**Comment by g0110280** [comment]
@Hredoy Can you give your folder structure? Or you can check if there is any permission issue.

**Comment by bskiefer** [comment]
Same issue.

**Comment by gwleuverink** [comment]
@Hredoy does @bskiefer's fix work for you as well?

**Comment by giigs22** [comment]
Same issue  in shared hosting.

**Comment by pranayaryal** [comment]
I had to do a `brew install php70-imagick`

**Comment by ARNolasco** [comment]
I have the same issue, but according to phpinfo() the extension php-exif in enable. There is something else that can provoke this error.  Mi project work fine in my local but in my web site (sharing-host) do not upload new photos. Thanks in advance for the help.

**Comment by g0110280** [comment]
Duplicate issue of #696 .

**Comment by faysl230** [comment]
I get the same error. It works fine in the local server but in the live server, I have got this error.

**Comment by worldtok** [comment]
I also got this error.
If you have solved it please share it with me. 
I'm using shared hosting

**Comment by Chefcury1** [comment]
how do I enable php-exif in shared hosting, tried all fixes nothing seems to solve this problem

**Comment by Chefcury1** [comment]
> Same issue in shared hosting.
> enable php-exif
> not yet upload file

How ?

**Comment by bskiefer** [comment]
https://github.com/UniSharp/laravel-filemanager/wiki/Enabling-exif-extension-for-PHP. Do you have cPanel or WHM access? EasyApache (WHM) would be the easiest, otherwise SSH into your host and install the required packages.

**Comment by faysal-web** [comment]
I think all shared hosting occur this problem. But no one gives a specific solution.

**Comment by kengketa** [comment]
I have the same problem on v2.1. Running on DO

**Comment by Catursn** [comment]
i have another problem with filemanager, i can't upload image with .webp format. Anyone know to fix this problem?
