### ISSUE TITLE
URL problem in integration with TinyMCE

### ISSUE THREAD

**Issue by DeehSlash** [UniSharp/laravel-filemanager#478]
I'm trying to insert an image in TinyMCE using Filemanager integration, but when I select an image the returned URL is: 

http://localhost/filemanager/images/test.png

When actually it should return:

http://localhost/uploads/images/test.png

Which is the public-available upload folder. Or even better, it should return without the domain as it can generate problems if I change the domain, like:

/uploads/images/test.png

**Comment by DeehSlash** [comment]
Anyone?

**Comment by g0110280** [comment]
Sorry for the late reply. I think this is fixed in `v2.0.0-alpha6`. What was the version you were using?
