### ISSUE TITLE
Can I add a watermark ? 

### ISSUE THREAD

**Issue by Hredoy** [UniSharp/laravel-filemanager#480]
I want to add watermark after uploading any image

**Comment by g0110280** [comment]
@Hredoy Please check this [post](https://github.com/UniSharp/laravel-filemanager/wiki/Putting-a-watermark-and-change-the-size-of-the-image-when-uploading-a-image) in our wiki. You can move those code into an event listener.

**Comment by Hredoy** [comment]
where i  get that file i need location

**Comment by g0110280** [comment]
The code from the wiki was in `UploadController`.

**Comment by Hredoy** [comment]
![capture](https://user-images.githubusercontent.com/16982572/33567953-0722c798-d94f-11e7-9bc4-8192d4526924.PNG)
![capture](https://user-images.githubusercontent.com/16982572/33567983-1aa38938-d94f-11e7-91f1-fa9be216464b.PNG)

when i add same code i am facing this error invalid upload request

**Comment by Hredoy** [comment]
Hello I need that solution as soon as possible.

**Comment by Hredoy** [comment]
@g0110280
Help me to add watermark.
Bro.

**Comment by gwleuverink** [comment]
Hi @Hredoy. 

You can add a watermark using a combination of the ImageWasUploaded Event and the Image facade provided by intervention image.

If you are not familiar with Laravel events I recommend you check out [the docs](https://laravel.com/docs/5.5/events) or [this video](https://laracasts.com/series/laravel-from-scratch-2017/episodes/32) first.

First you need to create an event listener within your app that listens to the ImageWasUploaded event. Check out [this page](https://unisharp.github.io/laravel-filemanager/events) in the documentation for more info. Or refer to the demo project that provides usage examples [here](https://github.com/UniSharp/laravel-filemanager-demo-events).

Next you need to add the watermark. You need to do this from within the event listener you just created. This filemanager uses the Intervention Image package. On [this  page](http://image.intervention.io/) you'll find an example on how to add a watermark.

Applying everything your event listener code should look  something like the example below. I didn't test this but it will help you on your way.

```
class HasUploadedImageListener
{
    /**
     * Handle the event.
     *
     * @param  ImageWasUploaded  $event
     * @return void
     */
    public function handle(ImageWasUploaded $event)
    {
        // Grab the uploaded file's path
        $imagePath = $event->path();

        // Open the image file
        $img = Image::make($imagePath);

        // Insert the watermark
        $img->insert('public/watermark.png');

        // Save the image
        $img->save($imagePath);
    }
}
```

**Comment by Hredoy** [comment]
how can i get current image width which is for in upload query

**Comment by g0110280** [comment]
@gwleuverink Thanks for your solution! I have add that to wiki.
@Hredoy Please check the official document of [intervention/image](https://github.com/Intervention/image).

**Comment by MFakhrani** [comment]
hi 


    private function proceedSingleUpload($file)
    {
        $new_filename = $this->getNewName($file);
        $new_file_path = parent::getCurrentPath($new_filename);

        event(new ImageIsUploading($new_file_path));
        try {
            if (parent::fileIsImage($file) && !in_array($file->getMimeType(), ['image/gif', 'image/svg+xml'])) {
                // Handle image rotation
                Image::make($file->getRealPath())
                    ->orientate() //Apply orientation from exif data
                    ->resize(840, 560)->insert('assets/watermark.png','bottom-left',10,10)->save($new_file_path);

                // Generate a thumbnail
                if (parent::imageShouldHaveThumb($file)) {
                    $this->makeThumb($new_filename);
                }
            } else {
                // Create (move) the file
                File::move($file->getRealPath(), $new_file_path);
            }
            if (config('lfm.should_change_file_mode', true)) {
                chmod($new_file_path, config('lfm.create_file_mode', 0644));
            }
        } catch (\Exception $e) {
            array_push($this->errors, parent::error('invalid'));

            Log::error($e->getMessage(), [
                'file' => $e->getFile(),
                'line' => $e->getLine(),
                'trace' => $e->getTraceAsString()
            ]);

            return false;
        }

        // TODO should be "FileWasUploaded"
        event(new ImageWasUploaded(realpath($new_file_path)));

        return $new_filename;
    }
