### ISSUE TITLE
disable auto create folder

### ISSUE THREAD

**Issue by lipxitutvl10** [UniSharp/laravel-filemanager#481]
how to disable auto create folder. i can't manager file after end of month. 
http://prntscr.com/hh2xod

how to fix one folder

**Comment by gwleuverink** [comment]
Hi @lipxitutvl10 I'm not sure I understand. Is all you need to disable the auto creation of the directory? Try to uncomment [this line](https://github.com/UniSharp/laravel-filemanager/blob/d298d448f6883de2378d009cf1b82f5838fa09b1/src/routes.php#L4)

Does that achieve what you require?

**Comment by g0110280** [comment]
This can be accomplished by setting `allow_multi_user` to `false`. Closing inactive issue.
