### ISSUE TITLE
Can't crate the config file.

### ISSUE THREAD

**Issue by exodia6666** [UniSharp/laravel-filemanager#482]
I'm following all the step given in the docs. I'm at the step when creating a config file. so when i type php artisan vendor:publish --tag=lfm_config it said it was successful but when i check in config file, i can't find lpm.php
![image](https://user-images.githubusercontent.com/10230139/33471209-cef906be-d69e-11e7-99e6-ae6876619549.png)
here's the debug and the screenshot of the creation of config files:
![image](https://user-images.githubusercontent.com/10230139/33471162-871fd48a-d69e-11e7-9f77-4d89e63b6705.png)

**Comment by g0110280** [comment]
Please check if you setup the service provider of this package in `config/app.php`.

**Comment by exodia6666** [comment]
I'm using Laravel 5.5, does it still needed?

**Comment by exodia6666** [comment]
when i typing those command it suppose give me lfm.php in root/config right? or i have to access it ini root\vendor\unisharp\laravel-filemanager\src\config\lfm.php?

**Comment by g0110280** [comment]
Please install the `v1.8.2.2` version of this package. `v1.8` doesn't contain auto package discovery scripts.

**Comment by exodia6666** [comment]
glad to know it, now it works. Thanks

**Comment by allbizznet** [comment]
I'm a newbie. I have the same problem. 
I modify composer.json with "unisharp/laravel-filemanager": "1.8.*" and have done a composer update.
But it's doesn't see the newer version. It's always the v1.8.0.
Thanks to help me
