### ISSUE TITLE
Errors uploading file on CKEditor

### ISSUE THREAD

**Issue by exodia6666** [UniSharp/laravel-filemanager#484]
Since i still have problem with using summernote with laravel-filemanager now i have to switch into ckeditor. now i got the errors when i was try to upload some images.

![image](https://user-images.githubusercontent.com/10230139/33535194-a67b6456-d8de-11e7-924d-e8c99027a789.png)

**Comment by gwleuverink** [comment]
Hi @exodia6666 

Can yo please check your browser console for errors and also the network tab and post some screenshots so we can check what is going on?

**Comment by gwleuverink** [comment]
This looks similar to #475. The solution that was given there was to enable php-exif.

**Comment by exodia6666** [comment]
ah yes this is because the Exif, when active the extension it work fine now. Thanks

**Comment by yonask** [comment]
I have the same problem.  Exif is enabled. I use PHP 7.1
