### ISSUE TITLE
Is there a possibility to have a Thumbnail for PDF DOC TXT .... on standalone button?

### ISSUE THREAD

**Issue by fencermd** [UniSharp/laravel-filemanager#485]
Is it implemented possibility to view thumbnail for FILE mode of standalone button?

**Comment by g0110280** [comment]
@fencermd do you mean displaying thumbnails inside the file manager? It is already done in `v1.8.3`.

**Comment by g0110280** [comment]
Currently we display mine type of files as thumbnails. Content preview as thumbnail is not yet supported. We will add content preview to our milestone.
