### ISSUE TITLE
Select multiple photos

### ISSUE THREAD

**Issue by LusenkoSasha** [UniSharp/laravel-filemanager#487]
Is it possible to know whether the function of selecting several photos will be implemented at once?

**Comment by g0110280** [comment]
Related to #128, this feature has been implemented in `dev-master`.

**Comment by LusenkoSasha** [comment]
@g0110280  I did not mean it. Can I select multiple photos when I add them?

**Comment by g0110280** [comment]
Yes, keep holding ctrl(win) or command(mac) and click on multiple files.

**Comment by LusenkoSasha** [comment]
no, when you click on the button to download more than one photo, and not how many to choose

**Comment by g0110280** [comment]
Please see this video : https://www.youtube.com/watch?v=MxMWEYJMcmk. The first 30 seconds shows how to select multiple files.

**Comment by LusenkoSasha** [comment]
@g0110280  You do not understand me. I click on a single button and I want to add a few photos that have already been uploaded. Add more than one photo and not how many

**Comment by g0110280** [comment]
@LusenkoSasha the feature you requested has been implemented in `v2.0.0-alpha`.

**Comment by LusenkoSasha** [comment]
How can I upgrade to version 2? @g0110280

**Comment by g0110280** [comment]
Please run `composer require unisharp/laravel-filemanager:v2.0.0-alpha`, and follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade).

**Comment by LusenkoSasha** [comment]
![image](https://user-images.githubusercontent.com/27783985/34827353-89a8d940-f6e2-11e7-917e-93237e19279a.png)
@g0110280

**Comment by tariqdev** [comment]
@g0110280 any solution?

**Comment by osdiablo** [comment]
Has the feature of multiple image selection implemented? I tried the latest version but can't seem to work it out to select multiple images? Need help.

**Comment by adriangordon1231** [comment]
I don't understand why this issue has been closes. I am not seeing where it was resolved.

**Comment by emtiazzahid** [comment]
is there any solution found yet ?
