### ISSUE TITLE
How to install v1.8.3

### ISSUE THREAD

**Issue by allbizznet** [UniSharp/laravel-filemanager#488]
I'm a newbie.
I'm running Laravel 5.5 and I want to install the 1.8.3 version in order to solve some problems.

**1) with composer**

In my composer.json file, I have "unisharp/laravel-filemanager": "^1.8"

But it's doesn't see the newer (1.8.3) version. It's always download the 1.8.0 version.

**2) I download it**

It's ok, but the command line (php artisan) in order to create config file doesn't work

I'm lost , thanks to help me

**Comment by gwleuverink** [comment]
Hi @allbizznet. Can you check your composer.lock file to see what version is locked?

**Comment by g0110280** [comment]
Another approach: 
1. Delete `"unisharp/laravel-filemanager": "^1.8"` entry from `composer.json`.
1. Run `composer require unisharp/laravel-filemanager`.
