### ISSUE TITLE
Customize functions by extending the original controllers

### ISSUE THREAD

**Issue by latr88** [UniSharp/laravel-filemanager#490]
Is there a way to modify the original functionalities? Is is possible to add or does it exist already a way to extend your controllers and then customize a function? 

I believe it would be useful for developers.

**Comment by gwleuverink** [comment]
Hi @latr88. You could overrite the standard LFM routes in your route file and point it to a custom controller. Or you can also use the events LFM provides to plug in to controller actions and add behaviour

If you want more flexibility you can also fork the project and reference your fork in the composer.json file. That way you have all the freedom you could possibly need :)
