### ISSUE TITLE
How to select file/image for use from thumbnail view

### ISSUE THREAD

**Issue by wittsparks** [UniSharp/laravel-filemanager#491]
I downloaded and installed the latest version of FileManager using the [installation instructions](https://unisharp.github.io/laravel-filemanager/installation).

Next, I copied vendor/unisharp/laravel-filemanager/src/views/demo.blade.php into my views directory and created route to it.

From the CKeditor in the demo page, click the image icon, then click browse server. The file manager comes up, showing the thumbnail view by default. I uploaded an image to it.

When I click the image, I'm shown an image preview. I see no way to select the image and use it in the ckeditor.

If I switch to list view and click the image name, the image is sent back to the ckeditor. This is the behavior I'm expecting.

The above is true for all of the editors - ckeditor, tinyMCE, and Summernote.

**Is there a way to select an image for use from the thumbnail view?**

Thank you!!

**Comment by g0110280** [comment]
Thanks for reporting this. This is a bug in thumbnail view. Will fix this soon.
