### ISSUE TITLE
Can't see the photos folder

### ISSUE THREAD

**Issue by koreanhobbit** [UniSharp/laravel-filemanager#494]
Hi...

The photos folder does not appear in the filemanager page. I noticed only files folder appears. If i turn on the shared feature the shared folder will appear alongside the files folder but no photos folder.

Thanks again

Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

If your problem still remains, please do these steps :
 * Run `php ./vendor/unisharp/laravel-filemanager/bin/debug` and paste the results here.
 * Capture screenshots of your browser console and paste them here.
 * Provide the steps to reproduce your issue, so we might solve it quicker.

**Comment by Gertiozuni** [comment]
Try this one, 

In config folder go to lfm.php and set 
`user_field' => false,`

**Comment by g0110280** [comment]
If `type` parameter equals to `image`, user will see the content in `photos` folder.
