### ISSUE TITLE
Count error on LfmHelpers.php in PHP 7.2

### ISSUE THREAD

**Issue by ilkinium** [UniSharp/laravel-filemanager#495]
Due to PHP 7.2 can not count non-countable items it shows error in  LfmHelpers.php on line 395:
count(): Parameter must be an array or an object that implements Countable

**Comment by g0110280** [comment]
Thank you for reporting this. We should fix this before next release. A quick solution will be to set value of `php_ini_overrides` as an empty array in `config/lfm.php`.

**Comment by g0110280** [comment]
Fixed in `v2.0.0-alpha`.
