### ISSUE TITLE
Adding file name suffix/prefix before file gets uploaded or renamed.

### ISSUE THREAD

**Issue by m-kiruba** [UniSharp/laravel-filemanager#496]
Currently the ImageIsRenaming event(Mostly all the events) just gives the old and new path, it does not give an ability to change it on event listener level. We would like to have the ability to change the name before it get renamed - Eg. I want to add a prefix of laraFile in all the images uploaded via lfm. As a first step I want to catch the isRenaming event and add the prefix there.

Something like...
When raising event from the controller pass a an object with path or name attributes. In event inject it as a public object, so we can change the values. (I want similar functionality as model observers Eg: In issaving event we can change the property values before it get saved to DB.)

Thanks.

**Comment by g0110280** [comment]
Sorry for the late reply. This feature can be accomplished by listening to `ImageWasUploaded.php`. You can get absolute path of the target file and rename it. See full events list [here](https://unisharp.github.io/laravel-filemanager/events).
