### ISSUE TITLE
JS events

### ISSUE THREAD

**Issue by seoperin** [UniSharp/laravel-filemanager#500]
Can i use any js events with standalone button? I need to get image path after choosing

**Comment by g0110280** [comment]
After running `php artisan vendor:publish --tag=lfm_public`, you can modify `public/vendor/laravel-filemanager/js/lfm.js` as you want.

**Comment by g0110280** [comment]
File name of `lfm.js` is changed into `stand-alone-button.js`. See document [here](https://unisharp.github.io/laravel-filemanager/integration#standalone-button).
