### ISSUE TITLE
Insert image from grid view

### ISSUE THREAD

**Issue by 3s777** [UniSharp/laravel-filemanager#501]
Sorry for my english.
In latest version of lfm, if i insert image from grid view, when i click on image it opened in full size.
In older versions after click image pasting in text. Now i can not paste image in text from grid view. I must swicth to list view and click on name of image.
How will i paste image from grid view in latest version?

Laravel 5.4
Package version: latest

**Comment by TingSyuanWang** [comment]
@3s777 Same Problem here!

**Comment by g0110280** [comment]
Please check #434. Will fix this in next release.

**Comment by 3s777** [comment]
Thanks, it's work for me.
