### ISSUE TITLE
dynamic change of url_prefix depending on localization

### ISSUE THREAD

**Issue by andreysunday** [UniSharp/laravel-filemanager#502]
Hello there! I have a multilingual site and its url has a lang prefix, so the file manager is not found. How I can change the url_prefix config when a user is changing a language (and it's changed the prefix)? Thank you!

**Comment by g0110280** [comment]
No easy way to do this. You need to copy package routes to your own route file. See [here](https://unisharp.github.io/laravel-filemanager/customization#routes).
