### ISSUE TITLE
Upgrading from "^1.7-alpha", To last version

### ISSUE THREAD

**Issue by TnCoders** [UniSharp/laravel-filemanager#503]
Hi I’m using this
 * Laravel version: 5.3
 * Package version: 1.7-alpha

I was using 1.7-alpha and i don’t know how but it stopped working after many big changes in project and i don’t know why it's not working.

The files upload PDF and image upload does not work and without any error. So i don’t know exactly what's happened. 

Can i upgrade this package to last version without break my project?

**Comment by g0110280** [comment]
Cannot be sure if it will break your project. Since `1.7-alpha` is an alpha version and as well an way-too-old version, I suggest you follow the [upgrade](https://unisharp.github.io/laravel-filemanager/upgrade) document to use the latest stable version (which is `v1.8.4` for now).

**Comment by arturmamedov** [comment]
Uhm, also the last `1.9.2` version of non alpha, @g0110280 need update requirements and README

**Comment by g0110280** [comment]
Thanks @arturmamedov , I will mark it on the document.

**Comment by g0110280** [comment]
PHP 7 limited syntax are removed from our code. Closing issue.
