### ISSUE TITLE
upload error on v2 cloud storage

### ISSUE THREAD

**Issue by michail1982** [UniSharp/laravel-filemanager#504]
i gues this line of code must be placed in filerepository because it throw ```chmod(): No such file or directory``` on cloud storage
https://github.com/UniSharp/laravel-filemanager/blob/v2.0.0-alpha/src/LfmPath.php#L277

**Comment by g0110280** [comment]
Got it. Thanks for reporting this.

**Comment by g0110280** [comment]
Fixed in a3dd20e, thank you @michail1982 .
