### ISSUE TITLE
The requested URL /laravel-filemanager was not found on this server.

### ISSUE THREAD

**Issue by shamim96** [UniSharp/laravel-filemanager#506]
I have installed this laravel filemanager.

Everything works well on my localhost. Here is a screenshot of successfully working  on my wamp localhost-
https://i.stack.imgur.com/RNtoB.png

Now After uploaded my application into the live server while I was trying to upload image, I have faced file manager showing me an error and it doesn't work. This is the error screenshot-
https://i.stack.imgur.com/NyqNv.png

Please give me a solution what should i do now.

**Comment by g0110280** [comment]
Please try running `php artisan route:clear`.

**Comment by shamim96** [comment]
I tried with php artisan route:clear and it out me "Route cache cleared!". But still same result. 
What should i do now?

**Comment by shamim96** [comment]
can i talk with you in skype for a while?

**Comment by g0110280** [comment]
@shamim96 Maybe Laravel did not find the service provider of this package (which loads the routes to file manager). Try running `composer dump-autoload -o` or `php artisan package:discover`. We can also talk on our telegram!

**Comment by shamim96** [comment]
You can go there https://tzipor.com/tz/signin and try to login with email: ranahammad@gmail.com and password: 123456 , then go this link https://tzipor.com/tz/my-account/write-new-chapter/16 and try to upload via file manager, you can view the error. 
I have tried with your last advice- https://drive.google.com/open?id=1sRrM7BC8TCO8nzPoYEa7ZWku9s3ATDGz
problem not solved. 
I did not use telegram before. I just installed telegram. Give me id or related information so i can find you there. This is a screenshot of my profile so you can also find me.  https://drive.google.com/open?id=1Hij_FuP93JZmKxtYR_xJkpQduCsI5YgV

**Comment by shamim96** [comment]
Stream Huang solved this issue very expertly. He found 2 errors in my files and i made those errors while uploading my project from localhost to live server(tzipor.com/tz). I had to correction two path while uploading to live server(tzipor.com/tz) but i did not do that. Those occurred the problem. Here i am explaining those-
1. I am using tinymce and i am integrating filemanager with that. I had to make correction to my tinymce editor file. Giving you a link of image referring to my localhost file. https://ibb.co/bZdwew
the tinyeditor file, while in localhost, `path_absolute : "/",` is the correct code. But this should be change based on my live server url. As my live server url the code should be `path_absolute : "/tz/",` https://ibb.co/c3TF6b
So we need to careful here while upload project localhost to live server

2. in config/lfm.php this code was correct while my project was in my localhost- `'base_directory' => 'public',` .https://ibb.co/jKYezw  But after upload project into live server this path should need to change based on my server link. As my live server link, this should be `'base_directory' => '../tz',` https://ibb.co/mVowew

These two correction solve my issue and my laravel filemanager run perfectly now. 
Thank you Stream Huang. I love your support.

**Comment by falecomoantonio** [comment]
Olá, eu enfrentei o mesmo problema, ai fui olha o arquivo lfm.php em config e vi que o diretório apontava para "public" enquanto no meu servidor estava para "public_html"

Então tente modificar
de:
'base_directory' => 'public',

para:
'base_directory' => 'public_html',

em /config/lfm.php

espero ter ajudado!

**Comment by rikkyps** [comment]
I found the same error with you, try to change the file on '/public/vendor/laravel-filemanager/js/lfm.js'

Change This Code (On Line 7):
`var route_prefix = (options && options.prefix) ? options.prefix : '/laravel-filemanager';`

With:
`var route_prefix = (options && options.prefix) ? options.prefix : '(your project path with no clause localhost)/laravel-filemanager';`

Example:
`var route_prefix = (options && options.prefix) ? options.prefix : '/simpleblog/public/laravel-filemanager';`

It's work for me, Thanks..

**Comment by RansomBroker** [comment]
thanks @rikkyps  it this work :D

**Comment by RansomBroker** [comment]
> Olá, eu enfrentei o mesmo problema, ai fui olha o arquivo lfm.php em config e vi que o diretório apontava para "public" enquanto no meu servidor estava para "public_html"
> 
> Então tente modificar
> de:
> 'base_directory' => 'public',
> 
> para:
> 'base_directory' => 'public_html',
> 
> em /config/lfm.php
> 
> espero ter ajudado!

this is work for me

**Comment by andes2912** [comment]
i found the samw error with u, try thix code and copy in your web.php

 Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
 \UniSharp\LaravelFilemanager\Lfm::routes();
 });

**Comment by RansomBroker** [comment]
have u install laravel file manager ?

Pada tanggal Sel, 21 Apr 2020 pukul 13.06 Andri Desmana <
notifications@github.com> menulis:

**Comment by andes2912** [comment]
yes sure

**Comment by bobbypratama97** [comment]
hi, i want to ask something. i got the same issue after changing 'base_directory' to 'storage' instead of public. I want to save the images to storage folder instead of public. Anyone knows how to fix this? 

`GET http://localhost:8000/laravel-filemanager/photos/image.jpg 404 (Not Found)`

**Comment by whiwf** [comment]
> hi, i want to ask something. i got the same issue after changing 'base_directory' to 'storage' instead of public. I want to save the images to storage folder instead of public. Anyone knows how to fix this?
> 
> `GET http://localhost:8000/laravel-filemanager/photos/image.jpg 404 (Not Found)`

I had same problem, did you fix it?

**Comment by andes2912** [comment]
> > hi, i want to ask something. i got the same issue after changing 'base_directory' to 'storage' instead of public. I want to save the images to storage folder instead of public. Anyone knows how to fix this?
> > `GET http://localhost:8000/laravel-filemanager/photos/image.jpg 404 (Not Found)`
> 
> I had same problem, did you fix it?

Try this
i found the samw error with u, try thix code and copy in your web.php

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
\UniSharp\LaravelFilemanager\Lfm::routes();
});
