### ISSUE TITLE
How to change scipts folder?

### ISSUE THREAD

**Issue by AlexMcowkin** [UniSharp/laravel-filemanager#507]
Hello

Tell me please how can I change path
to see package images from such route like: public/backeng/laravel-filemanager

?????

**Comment by AlexMcowkin** [comment]
did it. sorry. it was stupid question.
so...
I changed 'base_directory' => 'public/frontend',

but I have problem.
everytime, when I upload images I see new folder 'shares' with files.

how I can disable creating this folder?
I want that my uploaded files saved in public/frontend/images folder
not in public/frontend/images/shares folder

thx

**Comment by g0110280** [comment]
In `config/lfm.php`, set `allow_share_folder` to `false`.

**Comment by AlexMcowkin** [comment]
Thanx.

I did it. no effect =(

**Comment by g0110280** [comment]
Thanks for your question. The feature is not yet supported, but was planned in our milestones. We will implement it in the next few releases.

**Comment by heyddar** [comment]
Did you solve it ? I have the same problem

**Comment by streamtw** [comment]
Creation of "shares" folder can be disabled using [this config](https://unisharp.github.io/laravel-filemanager/config#allow_shared_folder).
