### ISSUE TITLE
class error

### ISSUE THREAD

**Issue by agrias7** [UniSharp/laravel-filemanager#51]
i got an error while installing, when i try to run php artisan vendor:publish --tag=lfm_config or php artisan vendor:publish --tag=lfm_public. It give me

[ErrorException]
  array_push() expects parameter 1 to be array, null given

but if i remove Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class, from app.php
no more error but when i try to publish it give me
Nothing to publish for tag [lfm_config].
or
Nothing to publish for tag [lfm_public].

Edit:
nvm i see the error fix and fix it by myself

**Comment by g0110280** [comment]
Got it.
Fixed with this commit : https://github.com/UniSharp/laravel-filemanager/commit/53b763dca10c6a83110e97263c41ae8305b2c9d7
Will release next version soon.

**Comment by g0110280** [comment]
New version released.
Updating to 1.5.2 will fix this issue.
