### ISSUE TITLE
standalone button file not exist 

### ISSUE THREAD

**Issue by dezarck** [UniSharp/laravel-filemanager#517]
https://github.com/UniSharp/laravel-filemanager/blob/1a4d718df210c3dbfbd480fcbc5835077f3a9a1b/src/views/demo.blade.php#L116

im trying to create standalone button for image, already try your code but still have an error like 
- uncaught ReferenceError: jQuery is not defined at lfm.js:24
-Uncaught TypeError: $(...).filemanager is not a function at create:376

if i implement this 
{!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/stand-alone-button.js')) !!}
laravel shows error with file doesnt exists and when i check in the folder there is no one files names stand-alone-button.js 

how to fix this with standalone button

**Comment by dontpanic** [comment]
Did you run `php artisan vendor:publish --tag=lfm_public` yet? That should copy the files into your public directory.

**Comment by dezarck** [comment]
yes i'm already do that laravel-filemanager already exists in public folder still got jquery is not defined in lfm.js

**Comment by dezarck** [comment]
sorry ma bad jquery just didn't actualy loaded first before script
