### ISSUE TITLE
File names with apostrophes cannot be deleted in the manager

### ISSUE THREAD

**Issue by 7immer** [UniSharp/laravel-filemanager#520]
In `list-view.blade.php` and `grid-view.blade.php` the `trash` function does not account for apostrophes `'`, for example `Jon's file.jpg`.

Code that produces the error in `list-view.blade.php`

        <a href="javascript:trash('{{ $item->name }}')">
          <i class="fa fa-trash fa-fw"></i>
        </a>

On click the error produced is This is because the apostrophe :
`Uncaught SyntaxError: missing ) after argument list`

Doing this works:

        <a href="javascript:trash({{ '"'.$item->name.'"' }})">
          <i class="fa fa-trash fa-fw"></i>
        </a>

Version 1.8

**Comment by g0110280** [comment]
Thank you @7immer .

**Comment by eugenefvdm** [comment]
@streamtw you can close this issue.
