### ISSUE TITLE
allow_share_folder in config is ignored (forced to true) when allow_multi_user is false

### ISSUE THREAD

**Issue by GrandPhoenix** [UniSharp/laravel-filemanager#523]
Hello.

I'm trying to implement Laravel-filemanager on a site where I want admins to be able to upload images and possibly other files to the server in a fixed folder structure.
But It seems like the config option allow_share_folder is ignored and forced to true if I set allow_multi_user  to false.

My "Working directory" config section looks like this:

'base_directory' => 'public',
'images_folder_name' => 'billeder-fra-balance-huset.dk',
'files_folder_name'  => 'files',
'shared_folder_name' => 'shares',
'thumb_folder_name'  => 'thumbs',

If I disable both "allow_share_folder" and "allow_multi_user" then I can only see "shared files" in the folder tree, and it is the contents of "public/billeder-fra-balance-huset.dk/shares".

I do not want to use shared folders, and I do not want to use multiuser folders.
I just want to see the folder structure of my "public" folder when I open the filemanager.

**Comment by youchenlee** [comment]
Hi @GrandPhoenix ,
Thank you for reporting this issue, that is a reasonable usage.

Setting it `shared_folder_name => ''` may do the trick.
I have not fully tested it, please let me know the result.
