### ISSUE TITLE
L 5.5 package:discover doesnt recongnizing LFM (when project is on server)

### ISSUE THREAD

**Issue by A-H-Pooladvand** [UniSharp/laravel-filemanager#526]
Hello, well actually i have two issues.
I installed LFM and everything was working great on **LOCAL** but when I moved my project on server (centos) and after composer-update I realized that package:discover is unable to discover lfm

I did every php artisan *:clear then composer dump-autoload then package:discover and nothing discovered and I tried like two days many other solutions suggested on forums,github wiki, stackoverflow and still no result
So I added service provider manually and it actually worked and routes appeared in route:list on server but i think in laravel 5.5 packages should be discover automatically. 

### Here is the main issue:
I don't know if its relevant or no but when I upload an image, it shows no error and everything looks great NETWORK console response with OK message and everything seems to be perfect but image is not uploaded and there is absolutely no error

here is the repo if you need to access anything
https://github.com/A-H-Pooladvand/Basic

I'm really exhausted please help, Thanks

**Comment by g0110280** [comment]
I think you need to run `composer self-update` on your server.
