### ISSUE TITLE
 Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class, NOT FOUND on live server but works locally. 

### ISSUE THREAD

**Issue by OshJones** [UniSharp/laravel-filemanager#529]
And provide the followings :
 * Laravel version : 5.5.33
 * Package version : 1.8

works perfectly locally on my machine, as soon as i put on live server i get this error on whole site.

![capture](https://user-images.githubusercontent.com/11396112/35739111-7f7a04ce-0828-11e8-9302-a53b5cd7375d.PNG)

any ideas would be greatly appreciated

**Comment by 1razzaghi** [comment]
any idea to fix it
this is my problem on my localhost!

**Comment by OshJones** [comment]
sorry for the late reply @1razzaghi. 

Make sure you have the aliases and providers in config/app

and then make sure you update composer on the live server.

You also need the config file for file manager by running

php artisan vendor:publish --tag=lfm_config
php artisan vendor:publish --tag=lfm_public

The missing config file was my issue.

**Comment by vandet** [comment]
Remove "unisharp/laravel-filemanager": "~1.8" and install it again
