### ISSUE TITLE
[Help] can not update any file

### ISSUE THREAD

**Issue by cona88** [UniSharp/laravel-filemanager#53]
i can not upload any file, 
![error](https://cloud.githubusercontent.com/assets/7022018/14085078/0abbe3cc-f548-11e5-8e32-4ba109e947d4.PNG)
i already install Imagick.
Thanks

**Comment by youchenlee** [comment]
@cona88 
could you please paste your HTML source here?

**Comment by g0110280** [comment]
@cona88 You are missing `jquery.form.min.js`.
Did you run `php artisan vendor:publish` after installing this package?
See [installation](https://github.com/UniSharp/laravel-filemanager/blob/master/doc/installation.md) document

**Comment by cona88** [comment]
@g0110280 jquery.form.min.js in the foder: public\vendor\laravel-filemanager\js.
@youchenlee : the code html:

<!DOCTYPE html>
<html>
<head>
    <title>Laravel</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col s12">
            <h4>Form</h4>aaaaaaaaa
        </div>
        <div class="row">
            <form class="col s12">
                <textarea name="article-ckeditor" id="article-ckeditor" cols="30" rows="30">  </textarea>
            </form>
        </div>
    </div>
</div>

<script src="{{ asset('js/jquery.js')}}"></script>
<script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

**Comment by cona88** [comment]
i fixed it.

**Comment by g0110280** [comment]
@cona88 : How did you fix this?

**Comment by ruudbwai** [comment]
same issue here, cannot upload, create or even see the test folder...console log shows - 
Current working_dir : /1 laravel-filemanager:265:3
TypeError: $(...).ajaxSubmit is not a function
When I try to upload an image. Halp :(

**Comment by CrisDev93** [comment]
same issue, how do you fixed it @cona88  ? :(

**Comment by CrisDev93** [comment]
I have to fixed it also, just change the url in script.blade.php in the ajax requests, just write a '.' before the original url for example url: './laravel-filemanager/folders' , otherwise this url will go to the root of your server link.
