### ISSUE TITLE
disable option share but create the folder

### ISSUE THREAD

**Issue by ssheduardo** [UniSharp/laravel-filemanager#533]
Hi,
When configuration the file lfm.php and disable share folder, and try upload a image, the module create the folder shared, why?

Add image

![file-manager](https://user-images.githubusercontent.com/1160138/35864503-485abe20-0b52-11e8-92b5-9eda8d7abdbc.png)

Is possible change or remove the path where save the image.

Example filemanager/photo by /photo

![image](https://user-images.githubusercontent.com/1160138/35864589-817896b4-0b52-11e8-8f41-99f99ee02d57.png)

**Comment by youchenlee** [comment]
Hi @ssheduardo 
In filemanager, all images are in `shares` folder by default, every authorized user can access it.

If `allow_multi_user` is enabled, filemanager will create user-specific folders. The `shares` folder can be turned off only when `allow_multi_user` is on.

The folder name can be modified by the config: `shared_folder_name`

**Comment by ssheduardo** [comment]
Hi @youchenlee,
I understand the problem of the folder save.
My problem is remove the path filemanager only  need the path photo, it is possible?
The path ideal is: /photos/shares/products/blabla.jpg
How remove the filemanager?

**Comment by youchenlee** [comment]
If you mean the "shares" folder, there is a trick mentioned in #523 . You may try setting `shared_folder_name` to an empty string

**Comment by g0110280** [comment]
Closing inactive issue.

**Comment by mdhosseini** [comment]
i set share older to '' but i can't open any folder after it. and folder icon change to file and work with them like files!
