### ISSUE TITLE
please add search option in V2.0.0 version.

### ISSUE THREAD

**Issue by nekooee** [UniSharp/laravel-filemanager#535]
please add search option in V2.0.0 version.

**Comment by youchenlee** [comment]
Search by filename?

We do have a plan to develop a filemanager extension that stores file metadata in MySQL. That makes it searchable.

**Comment by nekooee** [comment]
yes search by filename. 

> We do have a plan to develop a filemanager extension that stores file metadata in MySQL. That makes it searchable.

very good. I'm impatiently waiting. 
thank you. :)

**Comment by g0110280** [comment]
Duplicate of #316 .

**Comment by masumbillahbd** [comment]
how to implement search box in laravel file manager v2.0.0?
