### ISSUE TITLE
Invalid upload request

### ISSUE THREAD

**Issue by JamesDMorley** [UniSharp/laravel-filemanager#537]
* Operating system : Windows Server 2016 (IIS)
 * Laravel version : Latest(as of 09/092/18)
 * Package version :
 * Steps to reproduce your issue : Upload an image, error.
 * Screenshots of browser console :

When I upload an image, it shows up, the bar fills up and then hovering over shows "Invalid upload request." If I manually copy a picture into the location, it shows up in the manager and i can rename. I just cannot upload.
It is running via IIS and it has full permisions and is not read only.
I have double checked that the exif extension is enabled. It works fine in my developer environment with apache, just not my production with IIS

**Comment by wimurk** [comment]
Got the same error. Enable exif and it should fix the problem. But i can;t enable exif on the server. Is there another fix?

**Comment by Eiglimar** [comment]
anybody got it a solution for that?

**Comment by wimurk** [comment]
@Eiglimar enable exif. It should fix the problem

**Comment by g0110280** [comment]
I think this is solved in `v2.0.0-alpha6`. Please comment here if you have any further problem.

**Comment by faysal-web** [comment]
I also face this problem. I think all shared hosting occur this problem. But no one gives a specific solution.
