### ISSUE TITLE
File manager doesn't see images folder and doesn't create it

### ISSUE THREAD

**Issue by MetalRex101** [UniSharp/laravel-filemanager#538]
* Operating system : mac os Sierra
 * Laravel version : 5.5
 * Package version : 1.8

Is there an option to upload images to standalone "images" folder with embedded file-manager? Now all images uploading to Files folder. Even if root directory has different folders, they are not accessible from embedded file-manager. In config "images_folder_name" also has value "images"

**Comment by g0110280** [comment]
In this [line](https://github.com/UniSharp/laravel-filemanager/blob/v2.0.0-alpha6/src/views/demo.blade.php#L55), change it into `<iframe src="/laravel-filemanager?type=images"></iframe>`

**Comment by aleksandrpashkovskiy** [comment]
> <iframe src="/laravel-filemanager?type=images"></iframe>


Thank you very much. Do you can add this information to the page https://unisharp.github.io/laravel-filemanager/integration in the section "Embed file manager" ?
