### ISSUE TITLE
loadFolders is not defined

### ISSUE THREAD

**Issue by xelyos** [UniSharp/laravel-filemanager#539]
And provide the followings :
 * Operating system : Windows
 * Laravel version : 5.5.34
 * Package version :1.8.4
 * Steps to reproduce your issue : tinymce4 and open Laravel File Manager
 * Screenshots of browser console :
![screen 1](https://user-images.githubusercontent.com/35404145/36125421-9d8b8668-105c-11e8-8d85-d9caf4087829.png)
![screen 2](https://user-images.githubusercontent.com/35404145/36125427-a1d09100-105c-11e8-81d1-c874ae9b87af.png)

**Comment by g0110280** [comment]
Please upgrade to the latest version and run `php artisan vendor:publish --force`.
