### ISSUE TITLE
Little syntax error

### ISSUE THREAD

**Issue by Blum** [UniSharp/laravel-filemanager#54]
Hello and thanks for your work.
Little syntax error I've pointed on /src/views/index.blade.php : 152
`  @include('laravel-filemanager::script');`

The semicolon at the end must be removed. It seems to appear on bottom on each filemanager page. A pull-request just for that isn't necessary, is it?

**Comment by g0110280** [comment]
@Blum :
No, and thanks for spotting this.
This will be fixed withing this week. :)
