### ISSUE TITLE
Can't create directory

### ISSUE THREAD

**Issue by fbs54** [UniSharp/laravel-filemanager#541]
Hello All
on my production server I can't create folders or upload files here screenshot of my filemanager, can someone please help me.
thinks
![2018-02-14_00h02_12](https://user-images.githubusercontent.com/36426601/36179204-b7850bba-111b-11e8-80d5-39c4fddccc12.png)

**Comment by ahmedalmulki** [comment]
same problem with me

**Comment by 97morningstar** [comment]
The same, though I can see the files in my application (not the thumb for the images) but not upload them. I get a 404 response

**Comment by g0110280** [comment]
Please run `php artisan vendor:publish --force` and check [translation document](https://unisharp.github.io/laravel-filemanager/customization#translations).
