### ISSUE TITLE
Upload issue; Call to a member function getRealPath() on string

### ISSUE THREAD

**Issue by AlexFate** [UniSharp/laravel-filemanager#543]
And provide the followings :
 * Operating system : Ubuntu server 16
 * Laravel version : 5.5.*
 * Package version : 2.0.0-alpha2
 * Steps to reproduce your issue :
Hi,I update my lfm to version 2.0.0-alpha2. I know that it isn't stable. But I need multiple download files for my project. And I configurate lfm.php. Bud uploading files doesn't works. When I try to upload lfm give {object object} Error.

![36259350-513694b4-12a1-11e8-862e-93cb92d70843](https://user-images.githubusercontent.com/28627883/36264161-5f60d398-12af-11e8-8fea-ecccaece1768.jpg)

[lfm (1).txt](https://github.com/UniSharp/laravel-filemanager/files/1727599/lfm.1.txt)

**Comment by seamaan** [comment]
same porblem

**Comment by AlexFate** [comment]
more information about this problem
1.Call to a member function getRealPath() on string
![inkedunknown_li](https://user-images.githubusercontent.com/28627883/36480681-8cd7e686-1750-11e8-87b1-4cb7bfcb243a.jpg)

**Comment by ninediy** [comment]
same issue

**Comment by tonihidayt** [comment]
i have a same problem too, anyone has solved?

**Comment by g0110280** [comment]
I think this is solved in `v2.0.0-alpha6`, please comment if there is any further problem.

**Comment by Miyawvelu** [comment]
same issue
