### ISSUE TITLE
How to create custom route for different base_directory?

### ISSUE THREAD

**Issue by yekowele** [UniSharp/laravel-filemanager#545]
Hi,
I want to use `storage/app/public` as `base_directory`,  and i'm using standalone button. 

When user select any image filepath input value is,  `laravel-filemanager/multiUserFolder/image.jpg` , and i can get response from url.

Everything is alright so far.

But when i try resize image when user save a blog post, Intervention says  `Image source not readable` 
I think i must be crate custom route, but i didn't find a way create custom route.  ( Any document or example)

My input[name="filepath"] value : 
![image](https://user-images.githubusercontent.com/1898382/36338736-f20e03e6-13c7-11e8-82ce-6f15e94a6bbd.png)

My Controller : 

`\Image::make($request->input('filepath'))->fit(1920,760)->save();`

I also tried  

`\Image::make(asset($request->input('filepath')))->fit(1920,760)->save();`
or
`\Image::make(public_path($request->input('filepath')))->fit(1920,760)->save();`

All of them return me `Image source not readable` . This problem happend only when i change base_directory. 

Any suggestion?

Thanks in advance

 * Operating system : win 7
 * Laravel version : 5.4
 * Package version : 1.8

**Comment by g0110280** [comment]
I think this is solved in v2.0.0-alpha6, please comment if there is any further problem.
