### ISSUE TITLE
Getting Page Expired on upload Image

### ISSUE THREAD

**Issue by dennysutanto** [UniSharp/laravel-filemanager#551]
Hi, i failed to upload image using the latest version.
This is what i have in my composer.json
"unisharp/laravel-filemanager": "~1.8"

Below is my details
 * Operating system : Mac OS High Sierra Version 10.13.1
 * Laravel version : 5.5

When i click the "Send it to the Server" button after selecting the Image to upload, the page just stay where it is.
In my browser console, i see that the response to POST http://localhost/~denny/gradejob/laravel-filemanager/upload is the laravel "Page Expired" page.

Is it because of the _token is empty ?

Below are some screen shots of my console

The Headers
<img width="1278" alt="screen shot 2018-03-04 at 00 41 50" src="https://user-images.githubusercontent.com/2149385/36937423-b70de822-1f45-11e8-9957-7bd6e78c3b6a.png">

The Params
<img width="1280" alt="screen shot 2018-03-04 at 00 42 56" src="https://user-images.githubusercontent.com/2149385/36937425-b7416a44-1f45-11e8-84c9-286229d82b55.png">

And the Response
<img width="1280" alt="screen shot 2018-03-04 at 00 43 28" src="https://user-images.githubusercontent.com/2149385/36937426-b7709a80-1f45-11e8-8856-c75f4da07600.png">

The code in my View is

	<script src="{{ asset('vendors/ckeditor/ckeditor.js')}}"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.11/adapters/jquery.js"></script>
	<script>
		var options = {
			filebrowserImageBrowseUrl: '{{ asset("/laravel-filemanager?type=Images") }}',
			filebrowserImageUploadUrl: '{{ asset("/laravel-filemanager/upload?type=Images&_token=") }}',
			filebrowserBrowseUrl: '{{ asset("/laravel-filemanager?type=Files") }}',
			filebrowserUploadUrl: '{{ asset("/laravel-filemanager/upload?type=Files&_token=") }}',
			allowedContent: true
		};
	</script>
	<script>
		CKEDITOR.dtd.$removeEmpty['span'] = false;
		$('textarea[name="email_template"]').ckeditor(options);
	</script>

My middleware in lfm.php config is
'middlewares' => ['web', 'guest'],
I tried 
'web','auth:admin'  
'web','auth'  
before, but i get the same issue

Thanks

**Comment by yang5664** [comment]
YES, you have to remember pass CRSF_TOKEN to backend.

**Comment by dennysutanto** [comment]
how should i do that @yang5664  ?

i copy this part from the documentation, 
```
<script>
	var options = {
		filebrowserImageBrowseUrl: '{{ asset("/laravel-filemanager?type=Images") }}',
		filebrowserImageUploadUrl: '{{ asset("/laravel-filemanager/upload?type=Images&_token=") }}',
		filebrowserBrowseUrl: '{{ asset("/laravel-filemanager?type=Files") }}',
		filebrowserUploadUrl: '{{ asset("/laravel-filemanager/upload?type=Files&_token=") }}',
		allowedContent: true
	};
</script>
```

and it is working on my other project, but not in this new project, the only difference between these 2 projects is this new one has a custom guard for admin

Thanks

**Comment by yang5664** [comment]
![image](https://user-images.githubusercontent.com/5953010/36959696-60c799e2-207e-11e8-928e-5e2d8863b006.png)

```
  $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': "{{ csrf_token() }}"
      }
  });
```
if didn't work, try to comment file of "VerifyCsrfToken.php" then try again.

**Comment by dennysutanto** [comment]
I don't remember i set the ajaxSetup for my other project.
But i will try it, and will update the result soon

Thanks

**Comment by zsoltjanes** [comment]
I had the same problem. Go to your VerifyCsrfToken.php (app/Http/Middleware/VerifyCsrfToken.php) file and take a look here. I had a the following code which is not used:

```php
 protected function tokensMatch($request){
        // If request is an ajax request, then check to see if token matches token provider in
        // the header. This way, we can use CSRF protection in ajax requests also.
        $token = $request->ajax() ? $request->header('X-CSRF-Token') : $request->input('_token');
        return $request->session()->token() == $token;
}
```

**Comment by mostafamohs3n** [comment]
I just came across this and this is how I fixed it:
```
var CSRFToken = $('meta[name="csrf-token"]').attr('content');
    var CKEditorOptions = {
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token='**+CSRFToken**,
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='**+CSRFToken**
    };
```
Note that I sent the token within the URL.

**Comment by MahdiPishguy** [comment]
this solution work fine:

```php

Route::post('/attachImage', [AdminPanelController::class, 'attachImage'])
    ->name('attachImage');


protected $except = [
        '*/attachImage'
    ];
```

**Comment by ysfckr** [comment]
This solution worked perfectly for me.

```
var options = {
         filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
         filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
         filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
         filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
     };
```

**Comment by andreans24** [comment]
I experienced the same thing but the code I used was like this

<script>
    CKEDITOR.replace('body', {
        filebrowserUploadUrl: "{{ route('mypost.image').'?_token'.csrf_token() }}",
        filebrowserUploadMethod: 'form'
    });
    </script> 

what should I do?
![Uploading Screen Shot 2024-04-03 at 11.18.55 AM.png…]()
