### ISSUE TITLE
in ver 2.0, how to use multiple selection with ckeditor?

### ISSUE THREAD

**Issue by yang5664** [UniSharp/laravel-filemanager#552]
And provide the followings :
 * Operating system : MAC OS
 * Laravel version : 5.5.x
 * Package version : dev-master

I'm trying to use new function Multiple Selection with CKEditor, but when I clicked button of "confirm", always return first one or last one.

**Comment by g0110280** [comment]
Text editors like CKEditor are designed to select only on image/file each at one time. So we pass only one url to their callback as well.

**Comment by NeuroPastor** [comment]
@streamtw Hi! But how select multiple files as standalone button mode?

**Comment by streamtw** [comment]
Multiple selection can be enabled by click the "multiple selection button" in the action bar.
