### ISSUE TITLE
Image not being selected

### ISSUE THREAD

**Issue by Gertiozuni** [UniSharp/laravel-filemanager#556]
I am not able of selecting the image, when images are shown as thumbnails. When i click the image, it opens view modal, but when i switch to list view and i click the image than it is selected properly. 

Anyone has same issue ?

**Comment by salierg** [comment]
Same problem here...

**Comment by Gertiozuni** [comment]
Actually, i just deleted the file-manager folder into `resources/views/vendor` and did it. Give it a try.

**Comment by salierg** [comment]
I have no "vendor" folder in my "ressources/views".
Is it working for you know ?
