### ISSUE TITLE
Can't upload image types

### ISSUE THREAD

**Issue by alixcan** [UniSharp/laravel-filemanager#557]
Hi,

I have just tried this package, clean and successfull installation.

i can upload any files allowed in config except image types.

![screenshot_1](https://user-images.githubusercontent.com/652539/37280688-90ada652-25ff-11e8-8bcc-c2606659ccf6.png)

When i tried to upload jpg, png or any other image files it gives 
![screenshot_2](https://user-images.githubusercontent.com/652539/37280780-e629601c-25ff-11e8-87fe-5a375ac7f7e2.png)

Thanks for your attention.

Edit: is this about csrf protection? - if it is how can i upload other file types ?

 * Operating system : windows 10 | Laragon - php artisan serve
 * Laravel version : 5.6
 * Package version : 1.8

**Comment by danganh97** [comment]
the same error
