### ISSUE TITLE
How can I select multiple images after I upload them

### ISSUE THREAD

**Issue by mohammedfathi92** [UniSharp/laravel-filemanager#559]
How can I select multiple images after I upload theme by laravel-filemanager withStandalone button

**Comment by HackMort** [comment]
Same question here! Some help please

**Comment by g0110280** [comment]
@mohammedfathi92 @HackMort Waht do you mean "uploading theme"?

**Comment by mohammedfathi92** [comment]
@g0110280  I'm sorry for my bad English I meant "them = images "

**Comment by Maximevilla** [comment]
In demo.blade it is explained

**Comment by g0110280** [comment]
Implemented in `v2.0.0-alpha6`.

**Comment by ngodanghuuha** [comment]
> Implemented in `v2.0.0-alpha6`.

it's not working
