### ISSUE TITLE
Token mismatch error while uploading file

### ISSUE THREAD

**Issue by amraei** [UniSharp/laravel-filemanager#56]
When trying to upload a file, a TokenMismatchException is thrown Laravel 5.2. I checked the upload form and '_token' input has been set, but don't know why this happens.

As I have upgraded from 1.2, Is it likely that an incomplete upgrade is causing this problem? Is there a fix for this issue?

**Comment by amraei** [comment]
I found out there was a problem with my VerifyCsrfToken middleware.

**Comment by g0110280** [comment]
@amraei how did you solve this?
We might add this to FAQ.

**Comment by amraei** [comment]
I had customized VerifyCsrfToken middleware to check if the request is Ajax then read the `X-CSRF-TOKEN` header instead of `$request->input('_token')`. So I changed it to first check if `_token` has been posted and isn't null, then get the header.

```
protected function tokensMatch($request)
{
	$token = $request->input('_token');

	if(empty($token) && $request->ajax())
		$token = $request->header('X-CSRF-TOKEN');

	return $request->session()->token() == $token;
}
```

**Comment by jonjie0317** [comment]
Hi @amraei , I'm also getting this error when I'm uploading a video file that's about 20MB. It returns the 

> TokenMismatchException 

error. How did you do that? I checked my `VerifyCsrfToken` in middleware but there's no `tokensMatch()` method there. What should I do with this?

**Comment by amraei** [comment]
@jonjie0317 You have to create your own `VerifyCsrfToken` middleware in `app/Http/Middleware/VerifyCsrfToken.php`:

```
<?php namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;
use Illuminate\Support\Facades\Config;

class VerifyCsrfToken extends BaseVerifier {

	protected function tokensMatch($request)
	{
		$token = $request->get('_token');

		// If request is an ajax request, then check to see if token matches token provider in
		// the header. This way, we can use CSRF protection in ajax requests also.
		if(empty($token) && $request->ajax())
			$token = $request->header('X-CSRF-TOKEN');

		return $request->session()->token() == $token;
	}

	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \Closure  $next
	 * @return mixed
	 */
	public function handle($request, Closure $next)
	{
		return parent::handle($request, $next);
	}
}
```

Also change your verifier middleware in `app/Http/Kernel.php`:

```
protected $middlewareGroups = [
    'web' => [
        ...
        \App\Http\Middleware\VerifyCsrfToken::class,
        ....
    ]
];
```

**Comment by jonjie0317** [comment]
Where do I use the `tokensMatch()` method? because I already have the `app/Http/Middleware/VerifyCsrfToken.php` file when I installed laravel.

**Comment by amraei** [comment]
You don't need to use it, It's already used by based verifier:  
`vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php`

**Comment by jonjie0317** [comment]
@amraei Oh, do I just have to override the method?

**Comment by amraei** [comment]
@jonjie0317 Yes

**Comment by jonjie0317** [comment]
@amraei How about the functionality of the method that we override?  I'm worrying about it.

**Comment by rm116** [comment]
I have the same error with laravel 5.1 and I couldn't solve it
