### ISSUE TITLE
(1/1) ErrorException Trying to get property of non-object  in ConfigHandler.php (line 9)

### ISSUE THREAD

**Issue by s5510886103** [UniSharp/laravel-filemanager#560]
I would like to ask how this solution has been through auth, will appear the following error
![capture](https://user-images.githubusercontent.com/13843145/37509924-f81b6cf0-292b-11e8-8bb2-5437df750495.PNG)
![1](https://user-images.githubusercontent.com/13843145/37509958-1819e2d4-292c-11e8-824a-ec5348db8a9a.PNG)

**Comment by arturmamedov** [comment]
The is because maybe u use a not standard laravel auth `return auth()->user()->id;` so you nedd to edit the `'allow_multi_user' => true,` to `false`, try and let know

**Comment by g0110280** [comment]
Closing inactive issue.
