### ISSUE TITLE
How to check rename file exist in the user folder

### ISSUE THREAD

**Issue by mavinothkumar** [UniSharp/laravel-filemanager#562]
Hi,

I have renamed the file extension from png to jpg using Unisharp\Laravelfilemanager\Events\ImageWasUploaded but I can't able to identify next time whether that file name is already exist in the folder. It will just override (replace) the previous same image name. It will not show the error.

Is there any method to show error like normal way it does, like the file already exist?

**Comment by g0110280** [comment]
This package checks if the new file name exists when uploading or renaming files. There is a new feature comes in `v2.0.0-alpha6`, you can toggle whether to overwrite file with the same by setting the config `over_write_on_duplicate` to `true`.

In your event listener, you can call something `abort(400)` of any exception, and handle them with some javascript to show the error you requested.

Please let me know if your question is not solved.

**Comment by masumbillahbd** [comment]
> This package checks if the new file name exists when uploading or renaming files. There is a new feature comes in `v2.0.0-alpha6`, you can toggle whether to overwrite file with the same by setting the config `over_write_on_duplicate` to `true`.
> 
> In your event listener, you can call something `abort(400)` of any exception, and handle them with some javascript to show the error you requested.
> 
> Please let me know if your question is not solved.

sir overwrite duplicate solve. But previous file remove from my file manager
