### ISSUE TITLE
Every label is has problem for me!

### ISSUE THREAD

**Issue by reekoong** [UniSharp/laravel-filemanager#563]
![image](https://user-images.githubusercontent.com/12757006/37673143-1612a1f0-2ca2-11e8-80e1-df4362bc629c.png)

It's not problem if i use ekditor from UniSharp but,
Now I use ckeditor from https://github.com/ckeditor/ckeditor-releases

**Comment by g0110280** [comment]
@reekoong What locale are you using?

**Comment by reekoong** [comment]
@g0110280 locale is EN.

**Comment by marceloamp2** [comment]
I was having the same problem and I changed 'locale' => 'pt-br', to en and I used php artisan config: clear. Can not use another locale?

**Comment by g0110280** [comment]
Supported languages are here: https://github.com/UniSharp/laravel-filemanager/tree/master/src/lang. Make sure `locale` and `fallback_locale` settings from `app.php` match them.

**Comment by reekoong** [comment]
@g0110280 Thank you very much.  Because languages not support for th. 
I has fixed problem.
