### ISSUE TITLE
integrated google drive

### ISSUE THREAD

**Issue by olipiskandar** [UniSharp/laravel-filemanager#564]
how to connect with google drive ?

**Comment by hegzaDD** [comment]
I really like to know how to work with google cloud storage too.

**Comment by g0110280** [comment]
Please use v2.0 alpha versions. And you also need to install other packages like https://github.com/Superbalist/laravel-google-cloud-storage to integrate with Google. And the config `disk` in `config/lfm.php` should also be changed into the corresponding disk in `config/filesystems.php`.
