### ISSUE TITLE
Cloned Standalone button Uncaught TypeError: window.opener.SetUrl is not a function

### ISSUE THREAD

**Issue by harryprasath** [UniSharp/laravel-filemanager#568]
Getting this error.. on cloned stand alone button might be because of the id selector

Uncaught TypeError: window.opener.SetUrl is not a function

If the Standalone alone button can accessible from class then this issue will be cleared i think.

**Comment by g0110280** [comment]
You can achieve this by calling `$('.lfm').filemanager()`.
