### ISSUE TITLE
cannot upload images or create folder etc...exact same as #53

### ISSUE THREAD

**Issue by ruudbwai** [UniSharp/laravel-filemanager#57]
same issue here, cannot upload, create or even see the test folder...console log shows -
Current working_dir : /1 laravel-filemanager:265:3
TypeError: $(...).ajaxSubmit is not a function
When I try to upload an image. Halp :(

**Comment by g0110280** [comment]
@ruudbwai What OS are you using?
Window with XAMPP maybe?

**Comment by GregKeaney** [comment]
Yes!  I am using Windows with XAMPP and getting the exact same issue.  Any ideas?

**Comment by g0110280** [comment]
We develop this package on OSX, and the url will be like below :
![2016-06-24 12 50 33](https://cloud.githubusercontent.com/assets/7333171/16328216/77656712-3a0a-11e6-817b-90e088cc2514.png)

In Xampp, your url might contain project name between 'localhost:8000' and 'laravel-filemanager'.
This leads the error to loading published assets.

**Comment by g0110280** [comment]
@ruudbwai @GregKeaney 
Fix in 707a1fb, please update to dev-master to check if the issue still exists.

**Comment by g0110280** [comment]
We have released v1.6, please update to check if the issue still exists.
