### ISSUE TITLE
Using the standalone button

### ISSUE THREAD

**Issue by alalfakawma** [UniSharp/laravel-filemanager#570]
Can someone please guide me in using the standalone button? I feel like the examples provided are not clear enough, and also, i'm not using jQuery, just vanilla JS, when clicking the choose button it does pop up a window, but I cannot select a file, only upload it, and I need the path of that selected file to be used in my app. Thanking you in anticipation.

**Comment by alalfakawma** [comment]
I figured this on my own, thanks anyway. There was a fix needed where the images could not be selected, which is found in this issue. [https://github.com/UniSharp/laravel-filemanager/issues/434](url)

**Comment by dissovldgrl** [comment]
@alalfakawma could you perhaps post the solution here? I am experiencing the same problem and cannot seem to get it to work as per the demo. I am also not using jQuery, just vanilla JS

**Comment by alalfakawma** [comment]
> @alalfakawma could you perhaps post the solution here? I am experiencing the same problem and cannot seem to get it to work as per the demo. I am also not using jQuery, just vanilla JS

@dissolvdgrl this is really old now, i'm not very sure what the problem was anymore. And the project is long gone to a client which I was working with at that time, so I don't really have code to look back to. Sorry about that. But if you follow the issue which I have posted above #434 you may be able to figure it out yourself. I vaguely remember it but I think it was a very simple solution. Good luck! 😊
