### ISSUE TITLE
Enter folder automatically (Standalone)

### ISSUE THREAD

**Issue by alalfakawma** [UniSharp/laravel-filemanager#571]
Is there a way to add parameters to the url when using the standalone button, so it enters the folder automatically? I have prizes folder, when in the prize page and using the standalone button to upload files, I want it when clicked it automatically opens the prizes folder instead of having to navigate into it.

**Comment by g0110280** [comment]
You can try to add these lines to the bottom of `index.blade.php`:
```
<script>
  goTo('prizes');
</script>
```
