### ISSUE TITLE
Please refresh and try again.

### ISSUE THREAD

**Issue by Ham119** [UniSharp/laravel-filemanager#573]
We are using Laravel 5.6 with unisharp/laravel-ckeditor. After installing laravel filemanager 1.8, the upload tab for fileupload, always show "Please refresh and try again." after pressing upload.

![screenshot](https://user-images.githubusercontent.com/38035188/38241997-3c358450-3766-11e8-8bb9-2f319b99a0ab.jpg)

**Comment by g0110280** [comment]
I think this is fixed in the latest version. If it happens after running upgrade please let me know.
