### ISSUE TITLE
clicking on files should call `useFile` instead of `download`

### ISSUE THREAD

**Issue by jrobinsonc** [UniSharp/laravel-filemanager#574]
* Operating system : Ubuntu 16.04.3 LTS
 * Laravel version : 5.5
 * Package version : 1.8.4
 * Steps to reproduce your issue : Trying to integrate the filemanager to select an image or file and populate an input field with the name of the file that was selected.

When you click an image the function `useFile` is used and you can handle with `window.SetUrl` but when you click a file like a PDF, the`download` function is used. I would like to have the same behavior for files to be able to select and populate an input field with the selected file.

There should be a way to specify what action should be used.

File:
https://github.com/UniSharp/laravel-filemanager/blob/v1.8.4/src/views/grid-view.blade.php#L13

**Comment by tranbaolam6693** [comment]
I have the same problem, how can I get pdf url instead of 'download' ?

**Comment by ramanroy911** [comment]
is this issue solved?
