### ISSUE TITLE
Can not access url : domain.com/laravel-filemanager

### ISSUE THREAD

**Issue by huuloc4193** [UniSharp/laravel-filemanager#575]
Hello,
I had a trouble.
I installed this package and set default for laravel 5.6.
After finished. I can not access domain.com/laravel-filemanager, it's move to domain.com/home (middleware: auth).
Although laravel-filemanager url existed in route list.
Kindly help me.

Thank you

**Comment by huuloc4193** [comment]
Sorrry !! I solved this problem. Upgrade to 1.8.4 from 1.8.
And read this [https://github.com/UniSharp/laravel-filemanager/issues/516#issuecomment-357169245](url)

**Comment by jayenne** [comment]
this link 404's too ...i just love the irony :)
 ...but also have this prob and would like to read where the link went.

**Comment by jayenne** [comment]
i follow the instructions as per the docs (for summernote) and get the lfm popup window. insted of the redirect @huuloc4193 is getting I get a lovely 404... "
Sorry, the page you are looking for could not be found." page.

I havent set any routes or anything not in the docs.
I do use auth()
I have no idea how to resolve this. please help me with some pointers ;)

**Comment by vajiraHOA** [comment]
Hi @jayenne, did you have luck figuring this out? I'm on Laravel 5.6 + file manager 1.8.4 + SummerNote. Cant figure out where the 404 is being generated from...

**Comment by jayenne** [comment]
yeah. i shold have reported back.
IIRC...
The 404 was a path issue. I set the the routing in config/lfm.php:
    /*
    |--------------------------------------------------------------------------
    | Routing
    |--------------------------------------------------------------------------
    */

    // Include to pre-defined routes from package or not. Middlewares
    'use_package_routes' => true,

    // Middlewares which should be applied to all package routes.
    // For laravel 5.1 and before, remove 'web' from the array.
    'middlewares' => ['web', 'auth'],

    // The url to this package. Change it if necessary.
    'url_prefix' => 'filemanager',

Then my routes/web.php to..

Route::group(['middleware' => 'auth'], function () {
    Route::get('/filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
});

I think that was it. (tbh, once i'd done it, I went on to integrate it within my app without all thepoopup/iframe nonsence and have foggotten exactly what i did.)

let us know how you get on :)

**Comment by vajiraHOA** [comment]
Thanks a bunch @jayenne. That did  the trick!

So for future reference for anyone else, there are a few things causing this 404 error. 

1. Change in Doctrine
==============

You can fix this by following following the instructions as mentioned [here](https://github.com/UniSharp/laravel-filemanager/issues/516#issuecomment-357169245) or below:

In lfmhelpers.php line 335 replace the return with this:

`return lcfirst(str_singular(request('type') ? request('type') : '')) === 'image';`

and in vendor/unisharp/laravel-filemanager/src/views/index.blade.php line 209 replace with this:

'acceptedFiles: "{{ lcfirst(str_singular(request('type') ? request('type') : '')) == 'image' ? implode(',', config('lfm.valid_image_mimetypes')) : implode(',', config('lfm.valid_file_mimetypes')) }}",
maxFilesize: ({{ lcfirst(str_singular(request('type') ? request('type') : '')) == 'image' ? config('lfm.max_image_size') : config('lfm.max_file_size') }} / 1000)'

then 

`php artisan vendor:publish --tag=lfm_public`

this will update the views in your resources folder.

2. Path Issue
==============

You can fix this by following @jayenne 

Change line 18 in config/app.php to 

`'url_prefix' => 'filemanager',`

the add the below to your routes in routes/web.php

```
Route::group(['middleware' => 'auth'], function () {
    Route::get('/filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
});
```

you will also have to route in button creation in your javascript, if your invoking it in summernote editor as follows:

```
  var LFMButton = function(context) {
    var ui = $.summernote.ui;
    var button = ui.button({
        contents: '<i class="note-icon-picture"></i> ',
        tooltip: 'Insert image with filemanager',
        container: false,
        click: function() {

            lfm({type: 'image', prefix: '/filemanager'}, function(url, path) {
                context.invoke('insertImage', url);
            });

        }
    });
    return button.render();
  };
```

**Comment by jayenne** [comment]
Coolio.
*I actually forgot the doctrine part but it did the trick. Good spot.

On 5 Jun 2018, at 09:49, vajiraHOA <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a bunch @jayenne<https://github.com/jayenne>. That did the trick!

So for future reference for anyone else, there are a few things causing this 404 error.

  1.  Change in Doctrine
==============

You can fix this by following following the instructions as mentioned here<https://github.com/UniSharp/laravel-filemanager/issues/516#issuecomment-357169245> or below:

In lfmhelpers.php line 335 replace the return with this:

return lcfirst(str_singular(request('type') ? request('type') : '')) === 'image';

and in vendor/unisharp/laravel-filemanager/src/views/index.blade.php line 209 replace with this:

'acceptedFiles: "{{ lcfirst(str_singular(request('type') ? request('type') : '')) == 'image' ? implode(',', config('lfm.valid_image_mimetypes')) : implode(',', config('lfm.valid_file_mimetypes')) }}",
maxFilesize: ({{ lcfirst(str_singular(request('type') ? request('type') : '')) == 'image' ? config('lfm.max_image_size') : config('lfm.max_file_size') }} / 1000)'

then

php artisan vendor:publish --tag=lfm_public

this will update the views in your resources folder.

  1.  Path Issue
==============

You can fix this by following @jayenne<https://github.com/jayenne>

Change line 18 in config/app.php to

'url_prefix' => 'filemanager',

the add the below to your routes in routes/web.php

Route::group(['middleware' => 'auth'], function () {
    Route::get('/filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
});


you will also have to route in button creation in your javascript, if your invoking it in summernote editor as follows:

  var LFMButton = function(context) {
    var ui = $.summernote.ui;
    var button = ui.button({
        contents: '<i class="note-icon-picture"></i> ',
        tooltip: 'Insert image with filemanager',
        container: false,
        click: function() {

            lfm({type: 'image', prefix: '/filemanager'}, function(url, path) {
                context.invoke('insertImage', url);
            });

        }
    });
    return button.render();
  };
