### ISSUE TITLE
when will support for laravel 5.6 be added?

### ISSUE THREAD

**Issue by lscavelli** [UniSharp/laravel-filemanager#576]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system :
 * Laravel version :
 * Package version :
 * Steps to reproduce your issue :
 * Screenshots of browser console :

**Comment by huuloc4193** [comment]
Supported !! I highly recommend to install version 1.8.4.

**Comment by lscavelli** [comment]
I was referring to the development version 2.0.0alpha3. Not supported

**Comment by wimurk** [comment]
is 2.0.0alpha3 supported yet? +1

**Comment by g0110280** [comment]
`v2.0.0-alpha6` now supports laravel 5.6 and laravel 5.7 .
