### ISSUE TITLE
Unisharp shows empty directory.

### ISSUE THREAD

**Issue by aridwan** [UniSharp/laravel-filemanager#58]
when i started to integrate file-manager with laravel 5.2 i set the filebrowserImageBrowserUrl: to access routes /laravel-filemanager?type=images.
the browse button shown, but when i clicked the button, it showed empty directory.
![why](https://cloud.githubusercontent.com/assets/9368651/14270692/cd1a3efa-fb1a-11e5-8124-d96c053b8d05.JPG)
and all link above can't be clicked. (when i clicked they do nothing)

**Comment by g0110280** [comment]
@aridwan Can you show us the messages from console?

**Comment by WickedSik** [comment]
@g0110280 I found the same issue. It seems that the URL used by the filemanager is "/laravel-filemanager/jsonfiles" however, this URL does not exist! (I **assume** it's "/laravel-filemanager/jsonitems").

Also, if you guys need some help with fixing the problems of this plugin, I'd be glad to help.

**Comment by infinitencreative** [comment]
Same problem when integrating it into Laravel 5.0. The route is wrong.

**Comment by g0110280** [comment]
@aridwan @WickedSik @infinitencreative 
Fix in 707a1fb, please update to dev-master to if the issue still exists.

**Comment by g0110280** [comment]
We have released v1.6, please update to check if the issue still exists.
