### ISSUE TITLE
Multiple iframe do not store files in the same place

### ISSUE THREAD

**Issue by Maximevilla** [UniSharp/laravel-filemanager#580]
Hi,
    I am using iframe and ckeditor on different views. And they do not store files at the same place and cannot have access one from another. Even using the same user
Shall I change 
'images_folder_name' => 'photos',
    'files_folder_name'  => 'files',
to both public? in lfm.php and javascript?
Or there is better way ?
I want to save a copy of the images in my server.

 * Operating system : Debian 9
 * Laravel version : 5.6
 * Package version : latest from composer
 * Steps to reproduce your issue : The Embed file manager iframe and the ckeditor field do not store files at the same place. Even with single user...

**Comment by g0110280** [comment]
You can set both `images_folder_name` and `files_folder_name` to `files`, and they will show the same files.
