### ISSUE TITLE
GET http://localhost/laravel-filemanager?field_name=mceu_47-inp&type=Images 404 (Not Found)

### ISSUE THREAD

**Issue by vk001k** [UniSharp/laravel-filemanager#582]
Hi,
I installed laravel file manager step by step. but when I try to upload an image then it shows below error.

![image](https://user-images.githubusercontent.com/38520914/39083938-bc9c5268-458a-11e8-8fdd-6c3207058d81.png)

Can someone please help me out how to do that???

**Comment by shahbaz567zz** [comment]
Hey, have you got this issue fixed???
