### ISSUE TITLE
Object not found! Error 404 Uncaught TypeError: $(...).filemanager is not a function     at demo.blade.php:119

### ISSUE THREAD

**Issue by yelnyaface** [UniSharp/laravel-filemanager#583]
![download](https://user-images.githubusercontent.com/16500322/39182464-96fa0750-47ef-11e8-96a8-5c7523e6b5d8.png)
![download 1](https://user-images.githubusercontent.com/16500322/39182474-9bcf16d0-47ef-11e8-92a1-38cfccb6e99e.png)

nothing WORKS!!!!!!

even the so called demo doesnt work, what kind of joke is this!?

**Comment by yelnyaface** [comment]
Object not found! Error 404
localhost
Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.3

http://localhost/foodcrush/vendor/unisharp/laravel-filemanager/src/views/%7B%7B%20url(config('lfm.url_prefix'))%20%7D%7D?type=Images&CKEditor=ce&CKEditorFuncNum=0&langCode=en


GET http://localhost/laravel-filemanager 404 (Not Found)

      <div class="col-md-12">
        <h2>Embed file manager</h2>
        <iframe src="/laravel-filemanager" style="width: 100%; height: 500px; overflow: hidden; border: none;"></iframe>
      </div>


demo.blade.php:119 Uncaught TypeError: $(...).filemanager is not a function
    at demo.blade.php:119

  <script>
    {!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/stand-alone-button.js')) !!}
  </script>
  <script>
    $('#lfm').filemanager('image', {prefix: route_prefix});
    $('#lfm2').filemanager('file', {prefix: route_prefix});
  </script>








<script>
    {!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/stand-alone-button.js')) !!}
  </script>
  <script>
    $('#lfm').filemanager('image', {prefix: route_prefix});
    $('#lfm2').filemanager('file', {prefix: route_prefix});
  </script>

**Comment by g0110280** [comment]
Please upgrade to the latest version and run `php artisan vendor:publish --force`.
