### ISSUE TITLE
Package dont load 

### ISSUE THREAD

**Issue by Buxkso** [UniSharp/laravel-filemanager#584]
laravel 5.6
path: cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
     -package providers includes under route service provider
     -aliasis included
     -cache cleared
     -composer dumpautoload
     -localhost settings are right
     -i dont publish content of package

My root config file doesnt include lfm.php it is included only in package config
URL for this package included in my Editor is bad , how i could to change it?
I only have packages in vendor so how to route there

![screenshot_1](https://user-images.githubusercontent.com/37398478/39207898-7ea00d00-4801-11e8-8bac-01ad23189221.png)

**Comment by g0110280** [comment]
Please run `php artisan vendor:publish --tag=lfm_config` to get the `config/lfm.php`.
