### ISSUE TITLE
Uncaught TypeError: window.opener.SetUrl is not a function

### ISSUE THREAD

**Issue by ghost** [UniSharp/laravel-filemanager#585]
When I uploaded a file, then I will open that I click on the Image and become a error:

![bildschirmfoto 2018-05-01 um 17 08 58](https://user-images.githubusercontent.com/13014306/39478347-7be01ca2-4d62-11e8-970e-cd7f133fd545.png)

**Comment by TylerLumen** [comment]
Don't anyone can help me? 😢

**Comment by skakrecha** [comment]
had the same issue , finally managed to resolve this with a one line of code in vendor\unisharp\laravel-filemanager\public\js\script.js Line 338.
`  if (window.opener || window.tinyMCEPopup || field_name || getUrlParam('CKEditorCleanUpFuncNum') || is_ckeditor) {
    if (window.tinyMCEPopup) { // use TinyMCE > 3.0 integration method
      useTinymce3(url);
    } else if (field_name) {   // tinymce 4 and colorbox
      useTinymce4AndColorbox(url, field_name);
    } else if(is_ckeditor) {   // use CKEditor 3.0 + integration method
      useCkeditor3(url);
    } else if (is_fcke) {      // use FCKEditor 2.0 integration method
      useFckeditor2(url);
    } else {                   // standalone button or other situations
      // window.opener.SetUrl(url, file_path);
      window.open(url,"_blank");
    }`

**Comment by g0110280** [comment]
I think this is fixed in `v2.0.0-alpha6`. Please let me know if this is not fixed.

**Comment by MihoMaltesers** [comment]
I have same issue on v2.9.1
