### ISSUE TITLE
Class 'Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider' not found

### ISSUE THREAD

**Issue by taner-in-code** [UniSharp/laravel-filemanager#586]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : MacOS High Sierra 10.13.4
 * Laravel version : 5.6
 * Package version : 
 * Screenshots of browser console :
![ekran resmi 2018-05-02 11 30 47](https://user-images.githubusercontent.com/12814082/39513547-6cb5e6c6-4dfd-11e8-8225-55ecf34ef0a2.png)
![ekran resmi 2018-05-02 11 32 55](https://user-images.githubusercontent.com/12814082/39513549-6d01717c-4dfd-11e8-87e5-03ecdcf5bf3e.png)

I followed the steps, but I still get the error that the provider will not found. please help..

**Comment by michail1982** [comment]
namespace is UniSharp not Unisharp

**Comment by taner-in-code** [comment]
@michail1982 This namespace is automatically generated when the default Laravel project occurs, I do not specify it.

**Comment by michail1982** [comment]
@taner-in-code  what version did you install?
https://github.com/UniSharp/laravel-filemanager/blob/master/composer.json#L59  master
https://github.com/UniSharp/laravel-filemanager/blob/v1/composer.json#L50  branch v1

**Comment by anhducbkhn** [comment]
@michail1982 it is working for me now.
Thanks.

**Comment by teebazz** [comment]
Please how can i change it in my code

**Comment by nklatt** [comment]
This just happened to me updating an old install and the cure was to `rm -rf vendor`, change config/app.php where it was `Unisharp/Laravelfilemanager` to `UniSharp/LaravelFilemanager` (note two changes of case), and then composer install.
