### ISSUE TITLE
How configure if i using own secure middleware?

### ISSUE THREAD

**Issue by Troodi** [UniSharp/laravel-filemanager#587]
I use not auth middleware, how config for my middleware?
I delete from routes
`Config::get('lfm.middlewares')`
But i got this
![screenshot_1](https://user-images.githubusercontent.com/18666744/39515970-458933ee-4e04-11e8-8b96-c8a6cbe9c88b.png)

**Comment by michail1982** [comment]
try to  set empty an array in config

**Comment by g0110280** [comment]
Closing inactive issue.
