### ISSUE TITLE
Cut off Filenames

### ISSUE THREAD

**Issue by k4rl1** [UniSharp/laravel-filemanager#588]
Hi!

We're experiencing a problem where long file names are abbreviated with "..." at the end.  Is it possible to receive the full file names? Thanks;)

**Comment by g0110280** [comment]
@k4rl1 do you mean the path return by stand alone button?

**Comment by k4rl1** [comment]
I mean the item names (file names ) in list/thumbnail view. Long file names are abbreviated with "..." without any alt text.

**Comment by g0110280** [comment]
You can remove `text-truncate` class in `resources/views/vendor/laravel-filemanager/index.blade.php` (https://github.com/UniSharp/laravel-filemanager/blob/v2.0.0-alpha3/src/views/index.blade.php#L91).

**Comment by k4rl1** [comment]
Thanks ;)
