### ISSUE TITLE
what is a unit of "max_file_size" in lfm.php?

### ISSUE THREAD

**Issue by nekooee** [UniSharp/laravel-filemanager#590]
I could not find the file size "unit" in lfm.php. it is a byte? KB? or MB?
thank you

**Comment by SilviaCh** [comment]
at the bottom of my lfm.php file, I found the unit as MB

**Comment by nekooee** [comment]
> at the bottom of my lfm.php file, I found the unit as MB

At the bottom of the lfm.php file, the memory_limit unit is "M"(megabyte), But nothing has been said about the max_file_size unit. and max_file_size not accept character ("M") end of size!
Since it's said that the php.ini configuration rewrite, MAX_FILE_SIZE unit probably a byte.

**Comment by g0110280** [comment]
It is KB. Thanks for pointing this out @nekooee , we should add that to our document.

**Comment by adriangordon1231** [comment]
Still not mentioned in docs
