### ISSUE TITLE
certain images not uploading

### ISSUE THREAD

**Issue by colinbarstow** [UniSharp/laravel-filemanager#595]
Please check the following instructions before submitting a bug :
Latest version - check.

And provide the followings :
 * Operating system : Windows 10
 * Laravel version : 5.6
 * Package version : 1.8
 * Steps to reproduce your issue : uploading specific image files resulting in failure 
 * Screenshots of browser console : 
![image](https://user-images.githubusercontent.com/23583746/39883813-d5a0a742-547f-11e8-9e59-e65ec5e85b1e.png)

So i've got this weird problem happening right now. Images are uploading as normal but I have just compressed a huge batch of images online using http://compressimage.toolur.com/

Every single one of those images won't upload, the original images are in excess of 6MB each so they fail for different reasons. No explanation just a good old 500 (internal server error)
![image](https://user-images.githubusercontent.com/23583746/39883950-2e84b75e-5480-11e8-8838-af3c40f3578a.png)

I've attached 2 of the files that aren't working.

![cajun_blackened_chic_6euf2](https://user-images.githubusercontent.com/23583746/39883976-477628f6-5480-11e8-9089-2155ea530cbd.jpg)
![moroccanlambmeatballs](https://user-images.githubusercontent.com/23583746/39883977-478ec41a-5480-11e8-96b7-cd201fdc8bf8.jpg)

exif enabled 
gd enabled

config is the same as it's always been for me.

**Comment by colinbarstow** [comment]
Just to add to this further, if i take the original image and make it smaller in illustrator or photoshop it works. This suggests that when the image is being compressed something, somewhere is happening that GD does not like. Does anyone have any knowledge of what could be happening that would make the image "corrupt"?

**Comment by g0110280** [comment]
Sorry for the late reply. As far as I know, Intervention package has some memory issues which may cause large memory usage. All we can do is to use as less functions of it as possible.

I also tested uploading the two images you provided with `v2.0.0-alpha7`, it uploaded without error. Please let me know if you want to discuss more.
