### ISSUE TITLE
automatic open filemanager croper module after uploading image

### ISSUE THREAD

**Issue by mirabdolbaghi** [UniSharp/laravel-filemanager#600]
hi 
i want to after uploading image filemanager croper be opened an crop
or
before uploading image use js to crop image then uploading it with filemanager

**Comment by g0110280** [comment]
This can be achieved by create a event listener which listens to `ImageWasUploaded` event. See solution here: https://github.com/UniSharp/laravel-filemanager/issues/381#issuecomment-330150910.
