### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by AreYou1818Web** [UniSharp/laravel-filemanager#601]
Hello. How do I select multiple images? Could you give me an example.

**Comment by tariqdev** [comment]
@AreYou1818Web Did you find any solution?

**Comment by jayenne** [comment]
Which version are you using? ~1.8? ^2.0?

What do you want to do with the multiple images? I assume you want to upload multiple imges at once? you will need to edit the javascript option 'uploadMultiple' to 'true' within /vendor/unisharp/larqavel-filemanager/src/views/index.blade.php.

if it is to download or rename multple images etc then this isn't a current feature.

**Comment by g0110280** [comment]
Multiple files selection has been implemented in v2.0.0-alpha version.
