### ISSUE TITLE
Handling token based auth

### ISSUE THREAD

**Issue by catalinbuletin** [UniSharp/laravel-filemanager#602]
* Operating system : Mac OS
 * Laravel version : 5.6.20
 * Package version : 1.8.4
 * Steps to reproduce your issue : 

1. Create a token based auth system using the Illuminate\Auth\TokenGuard.
2. Create a middleware that checks for an api_token in the URL

I have added the middleware to the lfm.php config file. When I instantiate the editor (tinymce) i add that api_token to the url. But this is not forwarded to the other AJAX calls that are made to retrieve the folders and the items and so on. 

So, all the request that are made from the laravel file manager fail to pass that middleware that checks the api_token parameter.

Any way I can use this with a token based auth? Or am i missing something?

Thanks a lot!

**Comment by g0110280** [comment]
@catalinbuletin please check 3ae9cc6. You can pass a `token` to file manager, and it will remeber that token in every requests after.
