### ISSUE TITLE
I want to set base_directory or prefix for uploaded file or image

### ISSUE THREAD

**Issue by hai-ru** [UniSharp/laravel-filemanager#603]
I want to have prefix uploaded file to "/site/" because my framework in site folder. because my public in "../public_html/", the problem is if i set base_directory it make folder in framework but not in public.
![image](https://user-images.githubusercontent.com/24634668/40335609-c765f372-5d8e-11e8-9b5a-a64fd10f03f8.png)

**Comment by hai-ru** [comment]
I can fix it with set base_direcctory = '../site/public' . thank you

**Comment by AnimalInstinct** [comment]
I have same problem, ../../ doesnt works

**Comment by g0110280** [comment]
Duplicate of #506 .
