### ISSUE TITLE
Need reload to click ckeditor's image button

### ISSUE THREAD

**Issue by arwtyxouymz** [UniSharp/laravel-filemanager#606]
Hi, I use this plugin with [laravel-ckeditor](https://github.com/UniSharp/laravel-ckeditor).

But there is one problem.
Firstly image button of ckeditor doesn't display and it appears after reload.
So I need to reload the web browser to display image button of ckeditor.

Why this problem occurs?
I want to display image button from first.

My code is below:
```blade
<div class="form-group">
    {!! Form::label('eng_content', 'English Content') !!}
    {!! Form::textarea('eng_content', null, [
        'name' => 'eng_content',
        'id' => 'en_news',
        'class' => 'form-control',
        'placeholder' => 'Input content',
    ]) !!}
</div>

<script src="{{ asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<script>
    var options = {
        language: 'en',
        height: 600,
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
    }
    CKEDITOR.replace('en_news', options);
</script>
```

And provide the followings :
 * Operating system : **OS X 10.13.4**
 * Laravel version : **5.5.40**
 * Package version : **1.8**

**Comment by g0110280** [comment]
Sorry for the late reply. Your code looks fine. It might be the problem with CKEditor itself. Try to install the latest version of CKEditor using CDN.
