### ISSUE TITLE
Can't upload xlsx type files

### ISSUE THREAD

**Issue by Andresspak** [UniSharp/laravel-filemanager#610]
Can't seem to be able to find any xlsx type files. Saved the file as xls, then it was visible and possible to upload. Using Laravel version 5.5.40 and laravel-filemanager version 1.8.4

**Comment by gwleuverink** [comment]
In #259 someone suggested you add `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` to the `valid_file_mimetypes` array in the config file.

Does that help? The mimetype of the file could not be what you expect. Check [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types) resource for more info.
