### ISSUE TITLE
laravel 5.4 rewrite user Field function

### ISSUE THREAD

**Issue by saifuldhaka** [UniSharp/laravel-filemanager#611]
i am using laravel 5 4 and tying to rewrite user Field function.

in config\lfm.php i changes as 
`'user_field' =>  \App\Handlers\ConfigHandler::class,`

and created file as 
app\Handlers\ConfigHander.php
and 
```
<?php
namespace app\Handlers;
use Auth;

class ConfigHandler
{
    public function userField()
    {
        return auth()->user()->id;
    }
}
```

but it not working . Have any idea ?

**Comment by g0110280** [comment]
Can you paste complete code of your `app\Handlers\ConfigHander.php`?

**Comment by saifuldhaka** [comment]
<?php

namespace app\Handlers;
use Auth;

class ConfigHandler
{
    public function userField()
    {
        return auth()->user()->id;
 
    }
}

**Comment by g0110280** [comment]
Sorry for the late reply. Your code looks fine. Did you figured out this problem?

**Comment by saifuldhaka** [comment]
yes , problem solved

**Comment by iansapipi** [comment]
how can i customize when i upload the file it only for id no. 1? i can see my upload file in id no.1 when im viewing id no. 2
