### ISSUE TITLE
Should comment unit in maximum upload size

### ISSUE THREAD

**Issue by mayeenulislam** [UniSharp/laravel-filemanager#615]
https://github.com/UniSharp/laravel-filemanager/blob/8f89b2762c44abbfecefdacf3752ff21bed74f6d/src/config/lfm.php#L71

There's no comment in `max_size` section next to the value `50000`. Whether it's in bytes, or KB?

Converting it as bytes return 48.83 KB. Is that the accepted max upload file size?

Related #608, #607 

 * Package version : 1.8.0

**Comment by aabraham88** [comment]
+1 I have the same question. Is this in KB? Because the default value will be 50 MB in this case.

**Comment by aabraham88** [comment]
Well, tested out. It's in KB. It should be good if this could be commented in the config file.

**Comment by g0110280** [comment]
Commented in the config file. Thanks for the report.
