### ISSUE TITLE
Unable to load folders, it runs website in file manager popup in TinyMCE

### ISSUE THREAD

**Issue by arvind-verz** [UniSharp/laravel-filemanager#616]
![image](https://user-images.githubusercontent.com/39397649/41284444-eda221ae-6e56-11e8-8f4d-8d4aece4ef2c.png)

Integration is done step by step for demo purpose. Laravel version is 5.6.24

Solution worked!!!
When middleware is empty and set allow_multi_user to false 

OTHERWAYS

IT DOES NOT WORK FOR MULTI USER

**Comment by gwleuverink** [comment]
Thanks for reporting. Is the `var cmsURL` in the TinyMCE integration script the same as the url prefix you use for the file manager in your dashboard? It looks like it point to the wrong url.

**Comment by g0110280** [comment]
Closing inactive issue.
