### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by podlesny** [UniSharp/laravel-filemanager#618]
OS: linux
Laravel version : 5.6
package version ~1.8

Is there any ways to make pagination in your file manager? Because there are ca. 9000 images in my folder and manager cannot view this folder.

**Comment by g0110280** [comment]
It is `ItemsController`.

**Comment by BlackMetalz** [comment]
Have anyone done this? :dancer:

**Comment by taufanbasri** [comment]
Is it done?
i really need this guy.

**Comment by streamtw** [comment]
This feature is implemented in #857.
