### ISSUE TITLE
Grabbing fileinfo on upload

### ISSUE THREAD

**Issue by blorange2** [UniSharp/laravel-filemanager#619]
Is it possible with the filemanager, to grab the data about a file that was just uploaded and store it within a table?

I have seen that this can be done with photos but not files.

**Comment by g0110280** [comment]
Thanks @blorange2 . We should add new events for handling files.

**Comment by hsoheili** [comment]
@streamtw Was this feature already added?  I need to store the file information into tables so I can use more easily in other blades.

**Comment by streamtw** [comment]
This can be accomplished by create a custom event listener, which listens to `FileWasUploaded` event. See https://unisharp.github.io/laravel-filemanager/events for more detail.
