### ISSUE TITLE
htmlentities() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by WickedSik** [UniSharp/laravel-filemanager#62]
The source of this problem:

```
@foreach($dirs as $key => $dir)
        <li>
            <a class="pointer" id="folder_{{ $key }}" data-id="{{ $dir }}" onclick="clickFolder('folder_{{ $key }}', 0)">
                <i class="fa fa-folder folder-item" data-id="{{ $dir }}" id="{{ $dir }}-folder"></i> {!! $dir !!}
            </a>
        </li>
@endforeach
```

The fix isn't that difficult, actually. The reason this is happening, is because $dir contains 2 elements, with the keys `short` and `long`. While I do not exactly know which ones are needed, this was sitting in the 1.5.2 branch, and hasn't been fixed in master since.

Could it be that my version is broken or mismatched? I did check the vendor folder to see whether it was just my views, or whether it was in the package itself, and the conclusion of that is just above.

**Comment by WickedSik** [comment]
Combined with #58 this is giving me a sustaining headache. If you guys need help, I'd gladly partake

**Comment by bikedel** [comment]
so how did you fix it?

**Comment by WickedSik** [comment]
@bikedel This hasn't been fixed yet

**Comment by bikedel** [comment]
Hello
I got it working by using basename

    @foreach($dirs as $key => $dir)

        <li>
            <a class="pointer" id="folder_{{ $key }}" data-id="{{ basename($dir) }}" onclick="clickFolder('folder_{{ $key }}', 0)">
                <i class="fa fa-folder folder-item" data-id="{{ basename($dir) }}" id="{{ basename($dir) }}-folder"></i> {!! str_limit(basename($dir), $limit = 10, $end = '...') !!}
            </a>
        </li>
    @endforeach

**Comment by g0110280** [comment]
The basename() function cannot read utf-8.

**Comment by PENDOnl** [comment]
No fix yet? Keeps poppin' up in my error log.

**Comment by g0110280** [comment]
@WickedSik @bikedel @PENDOnl the codes you pasted were modified since this commit : https://github.com/UniSharp/laravel-filemanager/commit/24cf788d992cdf59e606d4ae58c4bcd96776b99d#diff-f582901cf732e05dc4419a580f79fbffR10
Please update to dev-master to check if this issue still exists.

@WickedSik #58 will be fix in v1.6 .

**Comment by g0110280** [comment]
@WickedSik @bikedel @PENDOnl 
Fix in 707a1fb, please update to dev-master to if the issue still exists.

**Comment by PENDOnl** [comment]
I can't update the project right now (heading for holidays real soon and can't have an update break the project right now). Will test as soon as I get back (in 4 weeks).

**Comment by g0110280** [comment]
Please update to v1.6 to check if the issue still exists.

**Comment by PENDOnl** [comment]
Looks like the issue is solved, error hasn't come back in the logs since updating. Thanks.
