### ISSUE TITLE
Should update document

### ISSUE THREAD

**Issue by anhducbkhn** [UniSharp/laravel-filemanager#623]
I am using Laravel 5.4 and this is my composer.json
````
"require": {
        "php": ">=5.6.4",
        "doctrine/dbal": "v2.6.2",
        "intervention/image": "^2.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "unisharp/laravel-filemanager": "~1.8"
    },
````
I was following document at https://unisharp.github.io/laravel-filemanager/installation

At step 4: when I run command ````php artisan vendor:publish --tag=lfm_config````
it show an error message: 'Class UniSharp\LaravelFilemanager\LaravelFilemanagerServiceProvider::class not found'

After googling and check the code, I found the reason is:
Namespace is 'Unisharp' not 'UniSharp'.

The document should be update

**Comment by g0110280** [comment]
Thank you @andhikamaheva , 'UniSharp' is the correct one. We will fix this in next release.

**Comment by teebazz** [comment]
please how will I correct it in my code.
Thanks

**Comment by g0110280** [comment]
The document is [here](https://github.com/UniSharp/laravel-filemanager/tree/v2.0.0-alpha6#errors-with-namespace).
