### ISSUE TITLE
Class Unisharp\Laravelfilemanager\controllers\LfmController does not exist

### ISSUE THREAD

**Issue by farbodkain** [UniSharp/laravel-filemanager#625]
* Laravel version :5.6
 * Package version :1.8
i did everything said inside installation. but when i try to load file manager give me below error:
ReflectionException
Class Unisharp\Laravelfilemanager\controllers\LfmController does not exist
inside web route i added below route:
`
    Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
`
even when i put below code inside my routes :
`
 Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });
`
give me this error:
Class 'UniSharp\LaravelFilemanager\Lfm' not found

I really appreciated if someone help me to fix this.

**Comment by Tehnik762** [comment]
I have the same problem!
I have tried to uninstall and install again - but it doesn't help

**Comment by esvills** [comment]
@Tehnik762,@farbodkain `php artisan vendor:publish --tag=lfm_view --force`

**Comment by Tehnik762** [comment]
@axyr thank you for your help, but I am still getting an error. In ny case

` Class 'UniSharp\LaravelFilemanager\Lfm' not found`

`  Class 'Unisharp\Laravelfilemanager\Lfm' not found`
![image](https://user-images.githubusercontent.com/24979712/42228662-2bc591a4-7eed-11e8-9105-1eaa260743e9.png)

**Comment by gwleuverink** [comment]
Try a composer dump-autoload

**Comment by jayenne** [comment]
I'm getting the same error and I get this at every turn.
php artisan config:cache
php artisan cache:clear
php artisan route:list
php artisan dump-autoload

everything :(

**Comment by Tehnik762** [comment]
Dump-autoload is giving me the same result:(

**Comment by PiR-B** [comment]
Based on composer.lock I have this reference for 1.8.5 which has been released 5 days ago : dc772d678b61eb4a056e470d27203ca017f82d19

If you take a look at this reference : api.github.com/repos/UniSharp/laravel-filemanager/zipball/dc772d678b61eb4a056e470d27203ca017f82d19 there is none Lfm.php file at all

**Comment by jayenne** [comment]
good spot. not sure is any other files are missing or if/when it was last there.
FYI: i just copied the current one to my ./vendor/unisharp/laravel-filemanager/src/ dir then ran 
 php artisan vendor:publish --tag=lfm_config
 php artisan vendor:publish --tag=lfm_public

and all was working. hope it helps.

*any clue on how/why Lfm.php disapeared and if the current one will introduce problems please let us know.

**Comment by AnimalInstinct** [comment]
All the routes in route:list after installation, don't do step 3 and all will be ok )

**Comment by gohari** [comment]
First of all, backup your own config/lfm.php before upgrading.
In the run commands: :

`composer update unisharp/laravel-filemanager`
`php artisan vendor:publish --tag=lfm_view --force`
`php artisan vendor:publish --tag=lfm_public --force`
`php artisan vendor:publish --tag=lfm_config --force`
`php artisan route:clear`
`php artisan config:clear`

then you have to change "Unisharp\Laravelfilemanager" to "UniSharp\LaravelFilemanager" in all of your codes :

Before :
routes/web.php
`Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');`
`Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');`

config/app.php :
`Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class,`

After :
routes/web.php
`Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\controllers\LfmController@show');`
`Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');`

config/app.php :
`UniSharp\LaravelFilemanager\LaravelFilemanagerServiceProvider::class,`

**Comment by gwleuverink** [comment]
Thanks for reporting. As @AnimalInstinct noted removing the route group from your routes file solves this.

Since middleware and route prefix can be set in configuration file you might not need to add any routes yourself.

**Comment by tenoimelda** [comment]
open config\app.php
before
Unisharp\Laravelfilemanager\

after
UniSharp\LaravelFilemanager\LaravelFilemanagerServiceProvider::class,

**Comment by galeza31** [comment]
@Tehnik762 how did you solve your problem

**Comment by hakkidilek** [comment]
I tried all things at this topic but I didnt solve **Class Unisharp\Laravelfilemanager\controllers\LfmController does not exist** problem I use laravel 5.6

**Comment by saeedvaziry** [comment]
any fixes?

**Comment by decimvs** [comment]
The problem is due to missing files. When Composer downloads the files, lfm.php and other files are missing, so you get the _Class Unisharp\Laravelfilemanager\controllers\LfmController does not exist_.
So you can fix that forcing Composer to download a specific version having all package files, so modify your composer.json file.
 Find:
 `"unisharp/laravel-filemanager": "~1.8"`

And change this line to:
`"unisharp/laravel-filemanager": "1.9.0"`

And then run:
`composer update`
Now Composer downloads all package files and your package runs correctly. 
I looked into repository and I found that inside version tags (1.9.1 and 1.9.2) these files are already missing. Maybe project developers need to add this files inside the repositories.

Note: if you try to update to 1.9.2 after you have installed 1.9.0, you get the same problem, Composer updates your local files as the same in the repository.

**Comment by VincentVanWijk** [comment]
in your routes :
Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show'); 

change 'controllers' to 'Controllers'.
same for your post route.

in vendor\unisharp\laravel-filemanager\src\Controllers 
the folder is now written with a capital C, where before it was 'controllers'

Hope this helps,
Vincent van Wijk

**Comment by akmalsulaymonov** [comment]
> in your routes :
> Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
> 
> change 'controllers' to 'Controllers'.
> same for your post route.
> 
> in vendor\unisharp\laravel-filemanager\src\Controllers
> the folder is now written with a capital C, where before it was 'controllers'
> 
> Hope this helps,
> Vincent van Wijk

Thank you very much. Made may day!

**Comment by g0110280** [comment]
For anyone encounters this error after running `composer update`:

We have changed namespace from `Unisharp` to `UniSharp`, and change the first character of every namespace into capital.

If you are updating this package and encounter any errors like `Class not found`, please remove this package entirely and reinstall again.

**Comment by ttjordan81** [comment]
Afer update...         
Change:
Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class,

To: "Notice: Uni**S**arp " and Laravel **F** ilemanager are capitilize now...
UniSharp\LaravelFilemanager\LaravelFilemanagerServiceProvider::class,

**Comment by apsaraaruna** [comment]
I had a error - `Class App\Http\Controllers\UniSharp\LaravelFilemanager\Controllers\LfmController does not exist`

and I executed these commands in order

modify your composer.json file and change this line to:

`"unisharp/laravel-filemanager": "2.2"`  to `"unisharp/laravel-filemanager": "1.9.0"`

And then run:
`composer update`

`composer update unisharp/laravel-filemanager`
`php artisan vendor:publish --tag=lfm_view --force`
`php artisan vendor:publish --tag=lfm_public --force`
`php artisan vendor:publish --tag=lfm_config --force`
`php artisan route:clear`
`php artisan config:clear`

cheers!
