### ISSUE TITLE
Image/File Browser

### ISSUE THREAD

**Issue by nasirkhan** [UniSharp/laravel-filemanager#626]
I am using the latest version of the the file manager. On one of my recent application i needed to have a feature where the users can check the images and files uploaded in the application. 

This could be the filebrowser opened as a new window while uploading. I want to add a button named `File Manager` on my application. When i will click on the button it will show the existing file manager or something similar. All the files and images will be listed there and i want to upload new image/files as well.

**Comment by g0110280** [comment]
I think you are referring stand alone button. Please see screenshots here: https://unisharp.github.io/laravel-filemanager/.

**Comment by nasirkhan** [comment]
thanks for the response. 

No, i am not referring the standalone buttons. The feature i am searching for is something like a file browser in Wordpress. I need the ability to use the File browser from the stand alone button or the CKEditor. Along with that i may want to use only the file browser, upload file and later some time select form the ckeditor or button.

When i am editing a post i am using the standalone button and it works perfectly. But sometimes i need to check all the uploaded images and files of the application. If there any way to check that? or do i have to edit any post again to open the file browser window?

**Comment by gwleuverink** [comment]
Do I understand correctly you just want to browse the files without uploading anything necessarily?

**Comment by g0110280** [comment]
This can be achieved by: 
1. Calling our api, which is `ItemsController`, and process with the json response.
2. Customizing `index.blade.php` and `script.js`, and remove any code related to file selection.

**Comment by beisong7** [comment]
you can use stand alone, or CKEditor but a quick fix is modifying the ConfigHandler.php to say [return "";] or better still set auth levels for super admin to return "" and other users to user()->username,
