### ISSUE TITLE
browse folder problem

### ISSUE THREAD

**Issue by siteincity** [UniSharp/laravel-filemanager#632]
Problem on Alpha version

storage\app\public\site - real dir
storage\app\public\site\images - my images folder
storage\app\public\site\files - my files folder

In config (lfm.php)
'allow_multi_user'   => false,
   'allow_share_folder' => false,
'disk' => 'site',
'folder_categories'  => [
        'file' => [
            'folder_name'  => 'files',
            'startup_view' => 'grid',
            'max_size'     => 50000,
            'valid_mime'   => [
                'image/jpeg',
                'image/pjpeg',
                'image/png',
                'image/gif',
                'image/svg+xml',
            ],
        ],
        'image' => [
            'folder_name'  => 'images',
            'startup_view' => 'list',
            'max_size'     => 50000,
            'valid_mime'   => [
                'image/jpeg',
                'image/pjpeg',
                'image/png',
                'image/gif',
                'image/svg+xml',
                'application/pdf',
                'text/plain',
            ],
        ],
    ],

In config (filesystems.php)
'disks' => [
        'site' => [
            'driver' => 'local',
            'root' => storage_path('app/public/site'),
            'url' => env('APP_URL').'/storage/site',
            'visibility' => 'public',
        ],
],

But package dont see my images folder. Also creates not necessary to me "shares" folder. How to make sure that he saw only the directories specified by me and did not make the shares directory

**Comment by g0110280** [comment]
1. set `allow_share_folder` to `false`.
2. Please run `php artisan storage:link`, or the images won't show up.
