### ISSUE TITLE
multiple standalone in one page

### ISSUE THREAD

**Issue by zemenik** [UniSharp/laravel-filemanager#633]
i'm trying to use standalone button for select image URL
it work fine when i use single standalone button, but after adding another button, the URL of selected image display on first button input area instead of second button input.
how to define URL input for specific button?

**Comment by zemenik** [comment]
found it !
just set same name for "data-input" and "id"

**Comment by Kokil** [comment]
@zemenik What is the solution

**Comment by g0110280** [comment]
@Kokil you can check the source code of `demo.blade.php` from [here](https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/demo.blade.php).

**Comment by Kokil** [comment]
@g0110280 i am using stable version(1.9.2) @zemenik  can you share script as well

**Comment by zemenik** [comment]
@Kokil look for lfm.js
the name has been changed in this commit [https://github.com/UniSharp/laravel-filemanager/commit/8a60d493e903ea82473a11c5fe01e2b1eba46631](url)

**Comment by Kokil** [comment]
i get issue while using multiple image upload button in a same page

**Comment by zemenik** [comment]
share your code here (just html section)

**Comment by Kokil** [comment]
<div class="form-group">
                    <label class="control-label col-lg-2">Image</label>
                    <div class="col-lg-10">
                        <a href="/file-manager?type=Images" id="feature-img-container">
                            <img src="{{ asset('images/noimage.jpg') }}"
                                 title="Choose Image"></a>
                        <input name="image" type="hidden" id="thumbnail">

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-lg-2">Image</label>
                    <div class="col-lg-10">
                        <a href="/file-manager?type=Images" id="feature-img-container">
                            <img src="{{ asset('images/noimage.jpg') }}"
                                 title="Choose Image"></a>
                        <input name="image1" type="hidden" id="thumbnail1">

                    </div>
                </div>

**Comment by zemenik** [comment]
try this :            

<div class="form-group">
                <label class="control-label col-lg-2">Image</label>
                <div class="col-lg-10">
                    <a id="lfm" data-input="thumbnail" data-preview="holder">Choose Image</a>
                    <input name="image1" type="hidden" value="{{'your image source'}}" id="thumbnail">
                     <img src="{{'your image source'}}" id="holder" class="f-image-view">

                </div>
            </div>

and in footer section :
    <script>
        {!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!};

        var route_prefix = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";

        $('#lfm').filemanager('image', {prefix: route_prefix});
    </script>


don't forget to change {{'your image source'}} with source of image

**Comment by zemenik** [comment]
try this :            

> 
                <label class="control-label col-lg-2">Image</label>
                <div class="col-lg-10">
                    <a id="lfm" data-input="thumbnail" data-preview="holder">Choose Image</a>
                    <input name="image1" type="hidden" value="{{'your image source'}}" id="thumbnail">
                     <img src="{{'your image source'}}" id="holder" class="f-image-view">

                </div>
       

and in footer section :
,,,

    <script>
        {!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/lfm.js')) !!};

        var route_prefix = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";

        $('#lfm').filemanager('image', {prefix: route_prefix});
    </script>
,,,

don't forget to change {{'your image source'}} with source of image

**Comment by Kokil** [comment]
@zemenik for single its working but i need multiple standalone buttons (not multiple images)

**Comment by zemenik** [comment]
for another standalone button just duplicate html section with different data-preview and id !
like this :
first button :

            <label class="control-label col-lg-2">First Image</label>
            <div class="col-lg-10">
                <a id="lfm" data-input="thumbnail" data-preview="holder1">Choose Image</a>
                <input name="image1" type="hidden" value="{{'your image source'}}" id="thumbnail">
                 <img src="{{'your image source'}}" id="holder1" class="f-image-view">
            </div>

Second button :

            <label class="control-label col-lg-2">Second Image</label>
            <div class="col-lg-10">
                <a id="lfm" data-input="thumbnail" data-preview="holder2">Choose Image</a>
                <input name="image2" type="hidden" value="{{'your image source'}}" id="thumbnail">
                 <img src="{{'your image source'}}" id="holder2" class="f-image-view">
            </div>

and for single image (if you want change same image input with multiple standalone buttons) you can use this :

First button :

            <label class="control-label col-lg-2">First Image</label>
            <div class="col-lg-10">
                <a id="lfm" data-input="thumbnail" data-preview="holder1">First button</a>
                <input name="image1" type="hidden" value="{{'your image source'}}" id="thumbnail">
                 <img src="{{'your image source'}}" id="holder1" class="f-image-view">
            </div>

and for second button just create another 'a' tag with same data-preview :

            <div class="col-lg-10">
                <a id="lfm" data-input="thumbnail" data-preview="holder1">Second button</a>            
             </div>
