### ISSUE TITLE
Private folder bug

### ISSUE THREAD

**Issue by wimurk** [UniSharp/laravel-filemanager#634]
After updating to the latest release using composer. The private folder shows all private folders inside the root. It isn't private anymore since every logged in user can see another users files. 

![image](https://user-images.githubusercontent.com/14072334/42442362-c53db0ec-836a-11e8-8393-2f2ecd4ce33b.png)

Update : The user root is not `/files/{user_id}` it is `/files/`

**Comment by lbodden** [comment]
If you are using the default 'user_field' config setting make sure it is set to the correct namespace.
`UniSharp\LaravelFilemanager\Handlers\ConfigHandler::class`

not
`Unisharp\Laravelfilemanager\Handlers\ConfigHandler::class`

**Comment by wimurk** [comment]
@lbodden changed `Unisharp` to `UniSharp` and it still doesn't work. I quess i'm not the only one having this problem.

**Comment by wimurk** [comment]
Edit the line `user_field` in your lfm config file. change `Unisharp` to `UniSharp`
