### ISSUE TITLE
Can I add Custom Class to the Image tag

### ISSUE THREAD

**Issue by armagedan** [UniSharp/laravel-filemanager#635]
I am using TinyMCE and I was wondering if there was a way to add custom tag before the image so I can make it responsive with browser resize. I want to be able to create a div before the image tag. As of now the image tag is inside a span which is inside a p tag.

What are my options

**Comment by g0110280** [comment]
This seem like an external problem. The callback function of TinyMCE is wrapped by `tinymce.min.js`. Perhaps you should check the documents of TinyMCE.

**Comment by armagedan** [comment]
This has been fixed. I added bootstraps responsive class tag to every image/media added.
