### ISSUE TITLE
Problem in preview

### ISSUE THREAD

**Issue by rcardoso1986** [UniSharp/laravel-filemanager#636]
Hello everyone, I'm using the v2.0.0-alpha4 version and when I select the images in the preview it returns [object Object] inside the url in the img field, if I send the form to the controller the filepath is as null.

can you help me?

Att.

Rafael Cardoso

Windows 10
Laravel 5.6
v2.0.0-alpha4

![capturar](https://user-images.githubusercontent.com/8076027/42594017-5809fed4-8524-11e8-9486-e411b2400f53.PNG)

![capturar](https://user-images.githubusercontent.com/8076027/42594052-711b7bd2-8524-11e8-825f-2fc5a9c0e1c4.PNG)

![capturar](https://user-images.githubusercontent.com/8076027/42594109-951c2fea-8524-11e8-841e-646aaf0b45c5.PNG)

**Comment by gwleuverink** [comment]
Hi @rcardoso1986 thanks for your feedback. It seems the server returns a 500 error. If you visit the network tab in chrome devtools you should be able to expand the failing request. Can you post the stacktrace here?

**Comment by rcardoso1986** [comment]
BadMethodCallException: Method App\Http\Controllers\Admin\Blog\CategoriaController::show does not exist. in file C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Controller.php on line 68
Stack trace:
  1. BadMethodCallException-&gt;() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:68
  2. Illuminate\Routing\Controller-&gt;__call() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
  3. call_user_func_array() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
  4. Illuminate\Routing\Controller-&gt;callAction() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
  5. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
  6. Illuminate\Routing\Route-&gt;runController() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
  7. Illuminate\Routing\Route-&gt;run() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php:665
  8. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
  9. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
 10. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 11. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 12. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php:43
 13. Illuminate\Auth\Middleware\Authenticate-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 14. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 15. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:67
 16. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 17. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 18. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
 19. Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 20. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 21. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
 22. Illuminate\Session\Middleware\StartSession-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 23. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 24. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
 25. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 26. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 27. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:59
 28. Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 29. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 30. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
 31. Illuminate\Pipeline\Pipeline-&gt;then() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php:667
 32. Illuminate\Routing\Router-&gt;runRouteWithinStack() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php:642
 33. Illuminate\Routing\Router-&gt;runRoute() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php:608
 34. Illuminate\Routing\Router-&gt;dispatchToRoute() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php:597
 35. Illuminate\Routing\Router-&gt;dispatch() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
 36. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
 37. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\fideloper\proxy\src\TrustProxies.php:57
 38. Fideloper\Proxy\TrustProxies-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 39. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 40. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
 41. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 42. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 43. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
 44. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 45. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 46. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
 47. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 48. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 49. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:62
 50. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
 51. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 52. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
 53. Illuminate\Pipeline\Pipeline-&gt;then() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
 54. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() C:\wamp64\www\ellotie\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
 55. Illuminate\Foundation\Http\Kernel-&gt;handle() C:\wamp64\www\ellotie\public_html\index.php:57

**Comment by rcardoso1986** [comment]
@gwleuverink 
It seems that it goes directly to the show method in this controller, I created the show method, now it does not return any errors, but how do I get this url from the image? What should I declare in the show method?

**Comment by gwleuverink** [comment]
In the trace you provided I see the show method is pointing to `App\Http\Controllers\Admin\Blog\CategoriaController::show`. In most cases it is not necessary to provide your own controllers, unless you need to modify the default behaviour in some way.

v2 and up come with their own routes you can wrap within a route group in your routes file. Check out the example below I took from the docs. Does it work if you follow that example?

_`routes/web.php`_
```
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });
```
`Lfm::routes()` adds route definitions to your project that point to the correct controllers and actions that come with the package.

**Comment by rcardoso1986** [comment]
Hello, sorry for the delay in replying, Did not work I inserted the routes in the web.php file, but still returning to the controller show method where I am, how could I make it work? with the stable version worked, but there is no support for multiple uploads and it is just the function that I need, in case the error is my excuse.

![image](https://user-images.githubusercontent.com/8076027/42740171-d4c5fbd2-8879-11e8-8337-75b6cf7e2746.png)

![image](https://user-images.githubusercontent.com/8076027/42740176-eaa53a58-8879-11e8-89cb-08c3a30b5110.png)

**Comment by rcardoso1986** [comment]
> Fixed in `v2.0.0-alpha6`.


The problem continues...

**Comment by alihesari** [comment]
@rcardoso1986 I installed this version and there is no problem. @streamtw Thank you to fix this problem.

**Comment by DonxDaniyar** [comment]
> Hello everyone, I'm using the v2.0.0-alpha4 version and when I select the images in the preview it returns [object Object] inside the url in the img field, if I send the form to the controller the filepath is as null.
> 
> can you help me?
> 
> Att.
> 
> Rafael Cardoso
> 
> Windows 10
> Laravel 5.6
> v2.0.0-alpha4
> 
> ![capturar](https://user-images.githubusercontent.com/8076027/42594017-5809fed4-8524-11e8-9486-e411b2400f53.PNG)
> 
> ![capturar](https://user-images.githubusercontent.com/8076027/42594052-711b7bd2-8524-11e8-825f-2fc5a9c0e1c4.PNG)
> 
> ![capturar](https://user-images.githubusercontent.com/8076027/42594109-951c2fea-8524-11e8-841e-646aaf0b45c5.PNG)

I had a same issue. In my case after update laravel filemanager in my view added /vendor/laravel-filemanager/lfm.js instead of /vendor/laravel-filemanager/stand-alone-button.js. I just include it and all works. Maybe it help someone
