### ISSUE TITLE
is it possible to select multiple image and show preview from Standalone button

### ISSUE THREAD

**Issue by Kokil** [UniSharp/laravel-filemanager#637]
is it possible to select multiple image and show preview from Standalone button ?

**Comment by g0110280** [comment]
Yes, this feature is in `v2.0.0-alpha4`.

**Comment by Kokil** [comment]
is v2.0.0-alpha4 documentation available ?

**Comment by claytongf** [comment]
What is the way to select multiple image and show preview in alpha version?

**Comment by g0110280** [comment]
This feature is already implemented in `v2.0.0-alpha6`, which is released today. Please upgrade to `v2.0.0-alpha6`.

**Comment by ssheduardo** [comment]
And for version 1.X ???
