### ISSUE TITLE
disable multiple selection

### ISSUE THREAD

**Issue by fixer112** [UniSharp/laravel-filemanager#638]
pls is there a way to disable multiple selection of image? I want my users to select only one image per upload.

**Comment by g0110280** [comment]
No such config for now. We will add this feature later.

**Comment by fixer112** [comment]
thanks for your reoly, i found a way to restrict multiple selection

**Comment by osmanakarr** [comment]
open vendor\unisharp\laravel-filemanager\public\js\script.js file
add code 8 row
`var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
};
`
replace this code
`
$(document).on('click', '#content a', function (e) {
  var element = $(e.target).closest('a');

  if (multi_selection_enabled) {
    selected.toggleElement(element.data('id'));
    element.find('.square').toggleClass('selected');
    toggleActions();
  } else {
    if (element.is_file) {
      use(getOneSelectedElement().url);
    } else {
      goTo(getOneSelectedElement().url);
    }
  }
});
`
to
`
$(document).on('click', '#content a', function (e) {
  var element = $(e.target).closest('a');
  if(getUrlParameter('multiple')==false){
    $('.square').removeClass('selected');
    selected = [];
  }
  if (multi_selection_enabled) {
    selected.toggleElement(element.data('id'));
    element.find('.square').toggleClass('selected');
    toggleActions();
  } else {
    if (element.is_file) {
      use(getOneSelectedElement().url);
    } else {
      goTo(getOneSelectedElement().url);
    }
  }
});
`
and add url parameter
laravel-filemanager?type=image**&multiple=false**

finish him :)

> Sorry, I do not know English very well.

**Comment by g0110280** [comment]
Multiple selection is disabled if user is using any WYSIWYG editor. The stand-alone button integration has a button which can toggle multiple selection. You can also change content of `index.blade.php` and `script.js` to remove this feature.
