### ISSUE TITLE
Event not working

### ISSUE THREAD

**Issue by fixer112** [UniSharp/laravel-filemanager#640]
i tried using imagewasuploaded event to resize image but nothing is happening, i also tried to log the path, but nothing happened, pls wat am i getting wrong?
![img_20180713_182325](https://user-images.githubusercontent.com/25584514/42705160-64df702e-86ca-11e8-9450-1055b318d976.jpg)

**Comment by g0110280** [comment]
@fixer112 did you register your event listener in `EventServiceProvider.php`?

**Comment by fixer112** [comment]
yes i did...
```
//EventServiceProvider.php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Event;
use Unisharp\Laravelfilemanager\Events\ImageWasUploaded;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        'App\Events\Event' => [
            'App\Listeners\EventListener',
        ],
        ImageWasUploaded::class => [
            'App\Listeners\UploadListener',
        ],
    ];

```
```
//UploadListener.php
<?php

namespace App\Listeners;

use UniSharp\LaravelFilemanager\Events\ImageWasUploaded;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Image;
class UploadListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  ImageWasUploaded  $event
     * @return void
     */
     public function handle(ImageWasUploaded $event)
     {
         /*$method = 'on'.class_basename($event);
         if (method_exists($this, $method)) {
             call_user_func([$this, $method], $event);
         }*/
         $path = $event->path();
         //your code, for example resizing and cropping
         $img = Image::make($path);
         $img->resize(500, 500);
         $img->save($path);
         Log::debug('image path '.$path);
     }
```

**Comment by VincentVanWijk** [comment]
Hi, I had the same problem,

Change the line : use Unisharp\Laravelfilemanager\Events\ImageWasUploaded;
to:
use UniSharp\LaravelFilemanager\Events\ImageWasUploaded;

Notice the capital 'S' in Uni/sharp and the capital 'F' in LaraelFilemanager

Hope this helps,
Vincent

**Comment by dasbit** [comment]
I had the same issue

**Comment by fixer112** [comment]
@VincentVanWijk thanks alot

**Comment by gwleuverink** [comment]
Thanks @VincentVanWijk for the fix!

**Comment by Angelo8828** [comment]
Thanks @VincentVanWijk

**Comment by Angelo8828** [comment]
Hello Sir @gwleuverink, I guess, we must re-open the issue. As of v2.0.0-alpha7 which I am currently using, the docs and the [demo here](https://github.com/UniSharp/laravel-filemanager-demo-events) are still not updated.

I can help by making a PR to update the docs but the problem that I am thinking is that is the namespace like that before especially for V1? Is it a recent change only for V2. Sorry because I just recently used this plugin.

Regards,
