### ISSUE TITLE
Route [unisharp.lfm.upload] not defined

### ISSUE THREAD

**Issue by yassersharaf** [UniSharp/laravel-filemanager#641]
Hi,

I tried to remove the package and reinstall it but getting many issues I could fix some but this still can't be fixed.

ErrorException

    Route [unisharp.lfm.upload] not defined. (View: D:\xampp\htdocs\laravel\vendor\unisharp\laravel-filemanager\src\views\index.blade.php)

In providers

    UniSharp\LaravelFilemanager\LaravelFilemanagerServiceProvider::class,
    Intervention\Image\ImageServiceProvider::class,

Routes:

    Route::group(['middleware' => 'auth'], function () {
       Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\controllers\LfmController@show');
       Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');
    });

And

    php artisan vendor:publish --tag=lfm_config
    php artisan vendor:publish --tag=lfm_public

In composer.lock

    "name": "unisharp/laravel-filemanager",
            "version": "v2.0.0-alpha4",
            "source": {
                "type": "git",
                "url": "https://github.com/UniSharp/laravel-filemanager.git",
                "reference": "65ebbf7f092f4ac3e79b06d19ee1c7799126bc17"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/UniSharp/laravel-filemanager/zipball/65ebbf7f092f4ac3e79b06d19ee1c7799126bc17",
                "reference": "65ebbf7f092f4ac3e79b06d19ee1c7799126bc17",
                "shasum": ""
            },

PHP version: 5.6

How to solve this issue?

Thanks in advance.

**Comment by yassersharaf** [comment]
Removed and installed v1.8 and it's working but couldn't solve issues with v2

**Comment by wimurk** [comment]
I have the same issue with v2. Also the publish command for views doesn't work

**Comment by VincentVanWijk** [comment]
try adding 
`\UniSharp\LaravelFilemanager\Lfm::routes();`
to your route group

**Comment by pujihartono** [comment]
if you using 

`Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');`

change to 

`Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload')->name('unisharp.lfm.upload);`


or  change 

```
Route::group(['middleware' => 'auth'], function () {
   Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\controllers\LfmController@show');
   Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');
});
```

to

```
Route::group(['middleware' => 'auth'], function () {
   \UniSharp\LaravelFilemanager\Lfm::routes();
});

```

**Comment by g0110280** [comment]
Sorry for this issue. There were some mistakes about routing in the documents, which is now fixed. As for namespace not found errors, please see the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade).

**Comment by sepisoltani** [comment]
> if you using
> 
> `Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');`
> 
> change to
> 
> `Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload')->name('unisharp.lfm.upload);`
> 
> or change
> 
> ```
> Route::group(['middleware' => 'auth'], function () {
>    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\controllers\LfmController@show');
>    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');
> });
> ```
> 
> to
> 
> ```
> Route::group(['middleware' => 'auth'], function () {
>    \UniSharp\LaravelFilemanager\Lfm::routes();
> });
> ```


dont forget to go to config/lfm.php and set use_package_routes to false to disable package's routes after your overwirde the routes in web.php
