### ISSUE TITLE
Conditionally Provide Access to Shared Folder

### ISSUE THREAD

**Issue by adriangordon1231** [UniSharp/laravel-filemanager#642]
Current setup:
allow_multi_user = true
allow_shared_folder = true

I have an application that has been utilizing both the private and shared folder features of this package, however more recently it has become necessary to restrict access to the shared folder (specifically by user role). Is there a known way to conditionally determine which users can access the shared folder?

Another acceptable workaround is if I could conditionally "hide" this folder in the actual file manager itself.

Thanks !

**Comment by rsmith87** [comment]
I'm working on this, and currently working through it to add for my use case.  You're going to have to do some customization in the LfmHelpers Trait, but it can be done.  I'm keeping the shared folder as is and creating an extra folder to use for conditional access, then adding a slug to the folder path by model id.

It would be nice to have some sort of feature to add a folder based on model to create conditionally accessed folders.  The only part of that is that it's so centric towards the particular use case.

**Comment by rsmith87** [comment]
So i've gotten this to work, and like I was saying before might be a good use case for a PR is to add ability to sort by model (Role in your case)

You'll need to add a folder in createDefaultFolder() middleware, which you'll need to pull over from the lfm vendor directory.
Also need to get the Trait LfmHelpers to your app from the vendor directory and add the conditional logic to determine the "slug" (The function getUserSlug() is a good starting point, especially if you want to integrate it into the config file) . 

public function rootFolder() will need to be modified in that file as well to find your directory based on type

Last but not least, you'll have to add a line referencing your new folder in the FolderController provided by the package.

To me this seems like a valid update to this package - maybe something like "Secondary Model for Folder"

**Comment by adriangordon1231** [comment]
@rsmith87 Hmm. I will try this and see if it works for me as well.

**Comment by g0110280** [comment]
Closing inactive issue.
