### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by liggth** [UniSharp/laravel-filemanager#645]
* Laravel version : 5.6
 * Package version : 1.9

After installation, I received an error (when I open filemanager):
`count(): Parameter must be an array or an object that implements Countable`
in 
unisharp\laravel-filemanager\src\Traits\LfmHelpers.php
Error in: 

/**
     * Overrides settings in php.ini.
     *
     * @return null
     */
    public function applyIniOverrides()
    {
        if (count(config('lfm.php_ini_overrides')) == 0) {
            return;
        }
 
        foreach (config('lfm.php_ini_overrides') as $key => $value) {
            if ($value && $value != 'false') {
                ini_set($key, $value);
            }
        }
    }

**Comment by gwleuverink** [comment]
@liggth what php version are you on?

**Comment by liggth** [comment]
php version 7.2

**Comment by gwleuverink** [comment]
Hi @liggth sorry for the late reply. I’m on vacation and will be for the next 2 weeks. 
There was a change made in php 7.2 that throws an exception if

**Comment by liggth** [comment]
How may I fix it?

**Comment by gwleuverink** [comment]
Sorry. Accidentally closed the issue. Reopened it again.

**Comment by liggth** [comment]
Where can I see this value in the configuration file?

**Comment by gwleuverink** [comment]
@liggth can you check what is in lfm.php under the php_ini_overrides key?

**Comment by liggth** [comment]
I cannot find file "lfm.php". Where is it?

**Comment by gwleuverink** [comment]
You found this file in `your-app/config/lfm.php`? If you did not find the file there you might have to publish your vendor assets first. If you already did that this might be a bug.

**Comment by liggth** [comment]
How I can publish vendor assets?

**Comment by gwleuverink** [comment]
First type `php artisan vendor:publish --tag=lfm_config` In your terminal to publish the config and then `php artisan config:clear`

**Comment by liggth** [comment]
Thank you! It worked!

**Comment by gwleuverink** [comment]
Cool glad that fixed it!

**Comment by israelnojr** [comment]
Hello I'm
![laraError](https://user-images.githubusercontent.com/12611987/55352876-d02ffe80-54b9-11e9-9cd2-90978f9c16bd.PNG)
 having the same error, but I did the above as instructed it didn't work for me
