### ISSUE TITLE
issuse version v2.0.0-alpha4. when i created new folder : error Folder name cannot be empty! 

### ISSUE THREAD

**Issue by jordankma** [UniSharp/laravel-filemanager#649]
![1](https://user-images.githubusercontent.com/15692759/43313578-aa435a68-91ba-11e8-9232-6f20ea962219.png)
![2](https://user-images.githubusercontent.com/15692759/43313581-aa7709d0-91ba-11e8-838e-4e46d488d158.png)

Please help me fix it.

**Comment by joseantoniopino** [comment]
I have the same error

**Comment by mediaverse-nl** [comment]
also the same error can someone please fix this

**Comment by sergey89d** [comment]
Is this problem fixed already?

**Comment by g0110280** [comment]
Fixed in `v2.0.0-alpha7`.

**Comment by jordankma** [comment]
> Fixed in `v2.0.0-alpha7`.

good job, thanks
