### ISSUE TITLE
How to use Events and Listeners Laravel 5.2.3

### ISSUE THREAD

**Issue by ejeanneaubc** [UniSharp/laravel-filemanager#65]
Hi all,

Can you tell me how to use Laravel listeners and events :  "When upload file, when remove file, when i move a file, etc...". In the global readme in the repository there is a doc but not compatible with current version.

Can you help me please ? 

Thank's a lot !

Best regards,

Emmanuel.

**Comment by ejeanneaubc** [comment]
Anyone can help me please ?

**Comment by ejeanneaubc** [comment]
I have add theses functionalities in the project and fixes has been merged ! 

It's resolved !

**Comment by mwallisch** [comment]
I know this is closed, but events are not working in the current master version. Any news on this?

**Comment by g0110280** [comment]
Thank you @ejeanneaubc !
