### ISSUE TITLE
Unisharp Laravel Filemanger connect to file server

### ISSUE THREAD

**Issue by smartcomparator** [UniSharp/laravel-filemanager#650]
I want to create a music website and i use laravel and unisharp filemanager package

i buy host the first is main host for running laravel and another is file server just for upload music and video that don't run any script in it. now i going to connect unisharp to file server like upload to ftp plugin wordpress

plase help me

**Comment by gwleuverink** [comment]
Hi @smartcomparator. You need v2 Alpha for this. You can configure a drive in filesystems.php. See [this document](https://laravel.com/docs/5.6/filesystem#configuration) for instructions. Then when you have configured the ftp file system you can reference that name under the `disk` key in the lfm.php config file. That should do it.

**Comment by smartcomparator** [comment]
Hi @gwleuverink ,Thanks for reply , yes i use ftp drive and solve this problem.
But now has error :" This driver does not support retrieving URLs"

**Comment by g0110280** [comment]
Thanks @smartcomparator , `ftp` driver does not support retrieving URLs. I founded it in [the source code of Laravel](https://github.com/illuminate/filesystem/blob/5.7/FilesystemAdapter.php#L395). I will try to fix this issue.

**Comment by jpcodeforit** [comment]
@streamtw .Is there any update on this issue.
