### ISSUE TITLE
Wrong file urls for uploaded files, when displaying items

### ISSUE THREAD

**Issue by llell** [UniSharp/laravel-filemanager#656]
Current url starts with 'http://localhost/...' on production, instead of real url.
Changed APP_URL in config to my url, cleared cache and so on, but still the same result, url() function in LfmItem.php returns such a type of url, so guys, i need any help or suggestions...

![234](https://user-images.githubusercontent.com/16686083/43674978-bf900b2a-97e4-11e8-8eee-ee58c21aeaec.png)

**Comment by llell** [comment]
So, i hardcoded my site url to public disk config (filesystems.php), and all is fine, but still i dont think it should be this way...

**Comment by kvinkinamoto** [comment]
You need change .env APP_URL this your site url

**Comment by g0110280** [comment]
Thanks for @kvinkinamoto 's solution.
