### ISSUE TITLE
laravel file manager upload files in laraveDirectory/files instead of public_html/files

### ISSUE THREAD

**Issue by geekamk** [UniSharp/laravel-filemanager#659]
hi,
my laravelFileManager works fine on local but when i upload project to my host its not work properly.
my host directory is this : 
   ->home/
         ->laravelfiles
         ->public_html
when i upload(write) image.jpg file, the url that laravel file manager create for me and i pass to view is correct and like this: 
domain.com/files/image.jpg
but the image upload in laravelfiles/public/files instead of public_html/files...and in my site image does not show because the upload url is wrong.
if the upload path be true everythings ok for me.

my lfm.php : 
    'base_directory' => 'public',
    'images_folder_name' => 'photos',
    'files_folder_name'  => 'files',
    'shared_folder_name' => 'shares',
    'thumb_folder_name'  => 'thumbs',

when i change base_directory to 'public_html' it goes  to laravelfiles/files/files :D 
and the final path that lfm pass me for image is domain.com/laravel-filemanager/files/image.jpg and it does not show again.

again i change it to '../public_html'  and it upload(write) the image properly in public_html/files but now i have problem to in read the picture in site because the image url it pass to view is domain.com/laravel-filemanager/files/image.jpg and it show 404.

how we should config lfm when our project directory is like that.

and my main question is how can i change upload pass off laravel file manager from laravelfiles/public to public_html/public

**Comment by g0110280** [comment]
Please take a look in #206 .

**Comment by g0110280** [comment]
Closing inactive issue.
