### ISSUE TITLE
Always perform laravel-filemanager last route action after try to web relogin 

### ISSUE THREAD

**Issue by goutamwms** [UniSharp/laravel-filemanager#661]
got an issue .
After installation opened two links in two tabs
1.http://pharmacy.local/home [ redirects after login]
2.http://pharmacy.local/laravel-filemanager

Now logged out from 1st link and tried to do some action in 2nd link . 
the system restricts the action due to not authenticate . That is ok.

Now if i try to login through 1st link , system performs the last route action from laravel-filemanager that was incomplete. But this should go to user home page .

Please check this issue ...

**Comment by g0110280** [comment]
This was because the default login mechanism of Laravel will call `redirect()->intended()`, which sends user to the last url user was at. The only solution was to overwrite this behavior in `AuthController.php`. This is an issue of Laravel framework, I'm sorry we cannot help with that.
