### ISSUE TITLE
syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ']'  in LfmPath.php line 122

### ISSUE THREAD

**Issue by Hredoy** [UniSharp/laravel-filemanager#662]
syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ']'
--
in LfmPath.php line 122

need solution using updated version

**Comment by Montazar1375** [comment]
did you solved it?!
i have the same problem here

**Comment by g0110280** [comment]
Please package version for this bug.
