### ISSUE TITLE
error facing

### ISSUE THREAD

**Issue by Hredoy** [UniSharp/laravel-filemanager#663]
Failed to load resource: net::ERR_CONNECTION_REFUSED
bootstrap.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
laravel-filemanager?field_name=mceu_48-inp&type=Images:513 Current working_dir : /1
4laravel-filemanager?field_name=mceu_48-inp&type=Images:353 Uncaught TypeError: $(...).modal is not a function
    at HTMLAnchorElement.<anonymous> (laravel-filemanager?field_name=mceu_48-inp&type=Images:353)
    at HTMLAnchorElement.dispatch (jquery.js:4665)
    at HTMLAnchorElement.r.handle (jquery.js:4333)

![untitled](https://user-images.githubusercontent.com/16982572/44046504-7cdeb4aa-9f4d-11e8-9b96-3c760dda91ce.png)

**Comment by g0110280** [comment]
Looks like `bootstrap.min.js` is missing.
