### ISSUE TITLE
i click uploads->choose file, but nothing happen

### ISSUE THREAD

**Issue by etlanda24** [UniSharp/laravel-filemanager#664]
i use laravel 5.6 on windows 10, i use the lastest version of package (1.8)
the problem is when i click uploads->choose file, nothing happens

![image](https://user-images.githubusercontent.com/28588705/44079929-b06bf0a8-9fd4-11e8-9f39-a636b5ba7d57.png)

**Comment by etlanda24** [comment]
its my bad, the problem is only about the css

**Comment by sotengboy** [comment]
Hi, i have same problem to, which css that make the button not work?

Thank You

**Comment by afshinizadi** [comment]
I had the same problem and choose button doesn't work

Error
dropzone.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Solution

Copy all content of 

> Project/vendor/unisharp/laravel-filemanager/public 

to the  

> YoutProjectPublicFolder(public_html)/vendor/laravel-filemanager/

**Comment by ngohuunhut** [comment]
> I had the same problem and choose button doesn't work
> 
> Error
> dropzone.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> 
> Solution
> 
> Copy all content of
> 
> > Project/vendor/unisharp/laravel-filemanager/public
> 
> to the
> 
> > YoutProjectPublicFolder(public_html)/vendor/laravel-filemanager/

Thank you very much
