### ISSUE TITLE
Doc's Update

### ISSUE THREAD

**Issue by duranhumes** [UniSharp/laravel-filemanager#667]
There's some capitalization that could be fixed.

Here's the original version.
``Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');``

``Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');``

Here's the working version.
``Route::get('/laravel-filemanager',` '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');``

``Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload')->name('unisharp.lfm.upload');``

And provide the followings :
 * Operating system : Elementary OS
 * Laravel version : 5.6
 * Package version : 2
 * Steps to reproduce your issue : Copy and paste the routes example from README
 * Screenshots of browser console : https://imgur.com/a/dHi13cS

**Comment by g0110280** [comment]
We fixed this issue, thanks for your info @duranhumes !
