### ISSUE TITLE
JS vendor published files are not working

### ISSUE THREAD

**Issue by sorasanin** [UniSharp/laravel-filemanager#668]
When I publish public from vendor everything works except JS files.

It still uses js files from vendor instead from public.

**I tried:**

- Run composer dumpautoload
- Clear all cache after any code changes, both in laravel and browser.

Deleting js files from public directory does nothing but when I delete them from vendor folder it says they are missing even when they are in public directory..

**Comment by g0110280** [comment]
Hello @sorasanin , you should publish views as well by running `php artisan vendor:publish --tag=lfm_view`. 

And edit [`index.blade.php`](https://github.com/UniSharp/laravel-filemanager/blob/v2.0.0-alpha5/src/views/index.blade.php#L253), use line 253 instead of line 251.
