### ISSUE TITLE
you cannot upload files of this type.

### ISSUE THREAD

**Issue by saifulislam18** [UniSharp/laravel-filemanager#669]
Hello,
can you help me?

i'm using 
laravel:5.6,
laravel-filemanager version:~1.8

i cann't upload xls or docx file.  

i'm change my lfm setting 

'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'image/svg+xml',
        'application/pdf',
        'application/docx',
        'text/plain',
        'image/vnd.microsoft.icon',
        'image/x-icon',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/docx'
    ],

i also run  cache clear command

php artisan route:clear
php artisan config:clear   

Can anybody help?

TIA

**Comment by ivanmalo** [comment]
i'm also facing the same error and my lfm.php has all the mime types I should need. I can upload .docx, but not .doc.

**Comment by saifulislam18** [comment]
for this problem i was modify my public/vendor/laravel-filemanager/js/dropzone.js file.
i removed this line 

`dictInvalidFileType: "You can't upload files of this type.",`

now it works fine for me .

**Comment by g0110280** [comment]
Issue solved, closing issue.

**Comment by developeralamin** [comment]
> Issue solved, closing issue.

How to solve this give me idea ?
