### ISSUE TITLE
data-input not working

### ISSUE THREAD

**Issue by jayked** [UniSharp/laravel-filemanager#67]
I have the following code in my template : 
```HTML
<a href="#"
      class="filemanager filemanagerImages btn btn-primary"
      data-input="testManagerField"
      data-preview="testManagerHolder">
    Choose an image
</a>
<input type="text"
	   id="testManagerField">
<img id="testManagerHolder">
```
And the following code in my javascript file
```Javascript
$('.filemanager').click(function (e)
{
    e.preventDefault();
});

$('.filemanagerFiles').filemanager('file');
$('.filemanagerImages').filemanager('image');
```
When a file is selected the preview image is successfully changed, but the input field's value is never changed. Any thoughts?

**Comment by jayked** [comment]
I have created a workaround for this problem.
In the public/vendor/laravel-filemanager/js/lfm.js I changed the following :
```javascript
  //set the value of the desired input to image url
  let target_input = $('#' + localStorage.getItem('target_input'));
  target_input.val(url);
```
Into this :
```javascript
//set the value of the desired input to image url
var target_input = $('#' + localStorage.getItem('target_input'));
target_input.attr('value', url).change();
```
There was something buggy in the .val() option.
I'm using jQuery 2.1.1.
Maybe it's worth your while to look at it?

**Comment by g0110280** [comment]
This is due to the ES6 scripts in `lfm.js`.
I have replace them them with ES5.
Testing on IE, Safari, Chrome, Firefox all works fine.
