### ISSUE TITLE
set upload limit for private folders/users

### ISSUE THREAD

**Issue by zemenik** [UniSharp/laravel-filemanager#673]
hi
is it possible to set upload limit for private folders or users with specific roles ?
i want to give access to users for uploading product images with limit in numbers or size of images.

**Comment by gwleuverink** [comment]
You could use the ImageIsUploading event to conditionally block uploading. You can find more info in the Events section of the docs.

**Comment by g0110280** [comment]
Thanks @gwleuverink , using event listeners to accomplish this is a good idea. This is also a duplicate feature request of #388 .

**Comment by cod3r0k** [comment]
Hi, Is it implemented yet? Which config parameter should we set this?
