### ISSUE TITLE
Laravel 5.7 compatibility upgrade

### ISSUE THREAD

**Issue by shsbd** [UniSharp/laravel-filemanager#675]
Hello,

Laravel 5.7 has been released. Can you please upgrade the version constraint to support Laravel 5.7?

Thank you.

And provide the followings :
 * Operating system: Windows 10
 * Laravel version: 5.7
 * Package version : v2.0.0-alpha4
 * Steps to reproduce your issue: Upgrade the compatibility to support Laravel 5.7

**Comment by phainv** [comment]
#677  is already open 😎

**Comment by g0110280** [comment]
Thank you @phainv , #677 has been merged.
