### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by AndrewSavetchuk** [UniSharp/laravel-filemanager#676]
https://github.com/UniSharp/laravel-filemanager/blob/f6e1b851f5a6c78001bff8a17d756d0941f170f4/src/config/lfm.php#L47

Change ConfigHander to ConfigHandler, and also in line above:
`// Then you can rewrite userField function in App\Handler\ConfigHander class`

**Comment by g0110280** [comment]
Fixed. I also spotted the same typo in configuration document. Thank  you @AndrewSavetchuk !
