### ISSUE TITLE
blank laravel filemanager after integration

### ISSUE THREAD

**Issue by sanketr43** [UniSharp/laravel-filemanager#68]
![filemanager](https://cloud.githubusercontent.com/assets/13629962/15267007/1213f452-19d3-11e6-8e89-6bac971d0d21.jpg)

In the above image you can see the error is showing. I am getting the blank folder of the laravel file manager. I have integrated it with TinyMCE. Please help me to solve the error.
This is the code used for tinyMCE. 

project path is  : http://localhost/laraveladmin/public/

<script>
          var editor_config = {
            path_absolute : "http://localhost/laraveladmin/public/",
            selector: ".tinymce-default",
            plugins: [
              "advlist autolink lists link image charmap print preview hr anchor pagebreak",
              "searchreplace wordcount visualblocks visualchars code fullscreen",
              "insertdatetime media nonbreaking save table contextmenu directionality",
              "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
            relative_urls: false,
            file_browser_callback : function(field_name, url, type, win) {
              var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
              var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

              var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
              if (type == 'image') {
                cmsURL = cmsURL + "&type=Images";
              } else {
                cmsURL = cmsURL + "&type=Files";
              }

              tinyMCE.activeEditor.windowManager.open({
                file : cmsURL,
                title : 'Filemanager',
                width : x * 0.8,
                height : y * 0.8,
                resizable : "yes",
                close_previous : "no"
              });
            }
          };

          tinymce.init(editor_config);
        </script>

**Comment by g0110280** [comment]
@sanketr43 thanks for showing console errors.
We fixed this in https://github.com/UniSharp/laravel-filemanager/commit/707a1fb6a32a8968a9ef02d24db89f6c03ff7fd2, please update to dev-master to if the issue still exists.

**Comment by g0110280** [comment]
Please update to v1.6 to check if the issue still exists.
