### ISSUE TITLE
[Question] Is there a way to upload files to another server?

### ISSUE THREAD

**Issue by pmirandaarias** [UniSharp/laravel-filemanager#682]
* Operating system : Centos 7
 * Laravel version : 5.6
 * Package version : 1.8

I would like to know if there is a way to upload the files to another server, not to a directory in the same server that the Laravel app.

For example, my app is in 1.2.3.4
My data base is located in another machine:  5.6.7.8
So I need to upload the files to the machine of the database, because I will execute some sql functions reading some cvs that I will upload using LFM.

**Comment by g0110280** [comment]
I think you can use `v2.0.0-alpha6` version of this package. Setting `disk` to which points to your server (you might need to see [file storage document of laravel](https://laravel.com/docs/5.7/filesystem#driver-prerequisites)). And then listen to `ImageWasUploaded` event and write something to your database using guzzle or other api.
