### ISSUE TITLE
Class 'UniSharp\LaravelFilemanager\Lfm' not found

### ISSUE THREAD

**Issue by omidsaifpanahi** [UniSharp/laravel-filemanager#683]
Hello friends

 I add this path.

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

the program will get the error

 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'UniSharp\LaravelFilemanager\Lfm' not found

 * Laravel version: 5.5
 * Package version : 1.8

**Comment by chithien175** [comment]
I'm also stuck with the same problem

**Comment by khoant88** [comment]
the same problem

**Comment by g0110280** [comment]
@omidsaifpanahi the code you pasted is for alpha version installation, I'm sorry to cause this trouble. Just remove the route group and it will work just fine. I've added some notes to prevent this from happening again.

**Comment by REZAGK1900** [comment]
HI
i have the same problem

and remove auth from bottom array

'middlewares' => ['web', 'auth']

I changed the code below

'middlewares' => ['web']

**Comment by worldtok** [comment]
If you have this same issue kindly use this route in lieu if the one they provided.
i had the same error and i hard-coded it by myself. you can simply add `\vendor` before the route they provided or simply copy this and place three.
`Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     '\vendor\UniSharp\LaravelFilemanager\Lfm::routes()';
 });`

**Comment by giliad56** [comment]
**the issue is your trying to access the route class which is not found .
try to use this** 
```
Route::group(['middleware' => 'auth'], function () {
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
    // list all lfm routes here...
});
```
**And not this:**
`Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () { '\vendor\UniSharp\LaravelFilemanager\Lfm::routes()'; });`
#

**Comment by darviscommerce** [comment]
I used this and then everything works splendid

`Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});`

**Comment by AntistressStore** [comment]
use Route::group(['prefix' => 'laravel-filemanager'], function (){ \UniSharp\LaravelFilemanager\Lfm::routes();}); 
 and href="{{ route('**unisharp.lfm.show**') }}" in you view

**Comment by rajeev-kumar9** [comment]
not working for me
