### ISSUE TITLE
$file_content variable not defined 

### ISSUE THREAD

**Issue by ddjikic** [UniSharp/laravel-filemanager#685]
* Operating system : Linux
 * Laravel version : not rly important 
 * Package version : dev master 
 * Steps to reproduce your issue : try to upload an image
 * Screenshots of browser console :   

ErrorException: Undefined variable: file_content in vendor/unisharp/laravel-filemanager/src/LfmStorageRepository.php:43

this is the content in LfmStorageRepository.php that is the issue 

   public function save($file)
    {
	    $nameint = strripos($this->path, "/");
	    $nameclean = substr($this->path, $nameint + 1);
	    $pathclean = substr_replace($this->path, "", $nameint);
	    $this->disk->putFileAs($pathclean, $file_content, $nameclean, 'public');
    }

**Comment by menkaff** [comment]
the same error in laravel 5.7

**Comment by drrasic** [comment]
same problem in Laravel 5.5, 
fixed it by using v2.0.0-alpha4

**Comment by g0110280** [comment]
Fixed in `v2.0.0-alpha5`.
