### ISSUE TITLE
ErrorException in Lfm.php line 77: array_keys() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by Sikki-Dev** [UniSharp/laravel-filemanager#689]
*When i'm trying to upload any file this error generate. Don't know why.
 * **ErrorException in Lfm.php line 77:
array_keys() expects parameter 1 to be array, null given**

 * Operating system : windows 8.1
 * Laravel version :5.3
 * Package version :1.9
 * Screenshots of browser console :
![capture](https://user-images.githubusercontent.com/37258226/45900324-e1a49980-bdf8-11e8-9052-c24181c1f525.PNG)

**Comment by g0110280** [comment]
Fixed in 3963506.
