### ISSUE TITLE
create new folder using arabic name don't display correct 

### ISSUE THREAD

**Issue by moman13** [UniSharp/laravel-filemanager#693]
I am trying to create new folder using arabic name but it display like this:
![display](https://user-images.githubusercontent.com/35956421/45931097-80540600-bf71-11e8-93ff-15b36116b9cb.PNG)
 i am using laravel 5.4 and package version v1.9.2

sorry for may english

**Comment by g0110280** [comment]
Please try `v2.0.0-alpha5`.
