### ISSUE TITLE
Dependency of Bootstrap ?

### ISSUE THREAD

**Issue by WalkingInTheDarkness** [UniSharp/laravel-filemanager#694]
Apologies, it's a question not an issue but can't see in the docs.
Does Laravel FileManager require Bootstrap /or any CSS framework/ ?

**Comment by g0110280** [comment]
If you are integrating this package with CKEditor or TinyMCE, then it does not require any framework. But if you are stand-alone button, Bootstrap is required to make the button look better like [this](https://unisharp.github.io/laravel-filemanager/#screenshots).
