### ISSUE TITLE
Disable auto close window when selected image in version 1.9 ?

### ISSUE THREAD

**Issue by minhquan3197** [UniSharp/laravel-filemanager#695]
In button i have event @click="openFileManager" and in methods i have function 
       `openFileManager () {
            window.open(`/laravel-filemanager?token=`,'newwindow', 'width=900,height=600')
            var self = this
            window.SetUrl = function (items) {
                self.form.gallery.push(items);
            }
            return false
        },`
But new window auto close when I choose one image @@ I can't ctrl + click more image, so I mean disable auto close window when selected image to push array :D Thanks

**Comment by g0110280** [comment]
In `v1.9.x`, only one image/file can be selected. Please use `v2.0.0-alpha5` if you need multiple selection.
