### ISSUE TITLE
Is it possible to add extra fields when uploading?

### ISSUE THREAD

**Issue by Tarcisiofl** [UniSharp/laravel-filemanager#699]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Windows
 * Laravel version : 5.6
 * Package version : 1.8

I need to be able to add some information to a database when upload a new file like name, revision, date ... So, is it possible to create a custom controller that extends the package and handle that?

Thank you!

**Comment by g0110280** [comment]
Hello @Tarcisiofl , please visit the [events document](https://unisharp.github.io/laravel-filemanager/events). You can achieve you requirement by listening to events like `ImageWasUploaded `, and write information you need to database in the event listener you created.

**Comment by Tarcisiofl** [comment]
Hello @g0110280 I understand that I need to listening to events; however, as I'm using it as iframe, I'm not find how to add the new fields. Do I need to change `editor_config` on `demo.blade.php`?

**Comment by g0110280** [comment]
@Tarcisiofl I think you can take a look at out [events demo project](https://github.com/UniSharp/laravel-filemanager-demo-events).
