### ISSUE TITLE
does not upload large file...

### ISSUE THREAD

**Issue by mprogrammer21** [UniSharp/laravel-filemanager#701]
I used this packege in laravel 5.5.
 Everything is right on the localhost, but after uploading to the shared host, I can't upload a file more than 3M  size.
for example, when uploading a file with 7M size, the load bar is half full and pause without any error.
I checked lfm setting and max size valeus and max file size can allow to upload on host that was 30M.
What should I do?

**Comment by g0110280** [comment]
@mprogrammer21 I will refer [this comment](https://github.com/UniSharp/laravel-filemanager/issues/592#issuecomment-387636533) in #592, please adjust the corresponding setting in your web server.

**Comment by mprogrammer21** [comment]
Thanks for answering...
Unfortunately, changing some of the settings, such as memory_limit on shared hosting, is not possible.
Is there another solution?

**Comment by g0110280** [comment]
`memory_limit` can be set in `config/lfm.php`. Please try if it works.

**Comment by mprogrammer21** [comment]
Yes, but it was not resolved by changing it...
![uni](https://user-images.githubusercontent.com/32291249/47208768-8e901900-d39b-11e8-82a8-f6e5ad8951f2.JPG)

**Comment by g0110280** [comment]
`memory_limit ` should be set to `500MB` or higher.

**Comment by makh123** [comment]
> 
> 
> `memory_limit` can be set in `config/lfm.php`. Please try if it works.



HI g0110280. I also have this problem. I did this setting but unfortunately my problem was not resolved. I searched a lot. please help me. Tanks.

**Comment by babininja** [comment]
Hi, i have this problem too

**Comment by OmarTaherSaad** [comment]
Me too!

**Comment by Lesnier** [comment]
ajax time out from dropzone

**Comment by shrestharikesh** [comment]
I have the same problem but only on my remote server. In my local server files are uploaded. 
![Screenshot (133)](https://user-images.githubusercontent.com/25215978/59974400-8728ab80-95cb-11e9-8a44-58d73447424e.png)
But in cpanel upload progress stops after some time. Is it the problem with cpanel server or execution time for upload process?
![Screenshot (134)](https://user-images.githubusercontent.com/25215978/59974435-00c09980-95cc-11e9-90cd-482899e6d00a.png)
I have my cpanel php.ini configured like this:
![Screenshot (132)](https://user-images.githubusercontent.com/25215978/59974451-1a61e100-95cc-11e9-8fcf-90ef1f4eed2f.png)

**Comment by shrestharikesh** [comment]
Updated memory_limit to 500M and now I was able to upload file size with 5MB but not with 10MB.

**Comment by shrestharikesh** [comment]
https://github.com/enyo/dropzone/issues/1561

**Comment by saberap** [comment]
Hi friends, finally I found a solution to this problem that you can't upload large files. this problem occurs because the default dropzone time out is the 30s, you can increase that manually.
First, open `resources/views/vendor/laravel-filemanager/index.blade.php`
then add timeout property to this part of js code : 
` Dropzone.options.uploadForm = {
      paramName: "upload[]", // The name that will be used to transfer the file
      uploadMultiple: false,
      parallelUploads: 5,
      timeout : 1200000,
      clickable: '#upload-button',
      dictDefaultMessage: 'Or drop file here...',
      init: function() {
        var _this = this; // For the closure
        this.on('success', function(file, response) {
          if (response == 'OK') {
            refreshFoldersAndItems('OK');
          } else {
            this.defaultOptions.error(file, response.join('\n'));
          }
      });
      },
      acceptedFiles: "{{ lcfirst(str_singular(request('type') ?: '')) == 'image' ? implode(',', config('lfm.valid_image_mimetypes')) : implode(',', config('lfm.valid_file_mimetypes')) }}",
      maxFilesize: ({{ lcfirst(str_singular(request('type') ?: '')) == 'image' ? config('lfm.max_image_size') : config('lfm.max_file_size') }} / 10)
    }`
Now you can upload files without any canceled Status.
