### ISSUE TITLE
How to debug or run tests in v.1.9.2

### ISSUE THREAD

**Issue by docmojoman** [UniSharp/laravel-filemanager#702]
I am having a problem installing into Laravel 5.6 on my local mac environment. I get an "invalid upload request" error when uploading an image. The file structure is created, but no image is uploaded.

Earlier posts referring to this same problem mention a debug script `php ./vendor/unisharp/laravel-filemanager/bin/debug`, but it doesn't exist in this version (1.9.2) of laravel-filemanager. There is a `tests` folder in the `/vendor/unisharp/laravel-filemanager/` folder.

Is there a way to do debug or run tests in this version?

**Comment by g0110280** [comment]
@docmojoman error exception logs should be in `storage/logs/laravel.log`. Please check it out. You can also check if any extension is missing from requirement section in installation document.

**Comment by docmojoman** [comment]
@g0110280 thanks!
