### ISSUE TITLE
After Uploading Image Not Display

### ISSUE THREAD

**Issue by farbodkain** [UniSharp/laravel-filemanager#703]
* Laravel version :5.6
 * Package version :1.8

everything work fine in local , but after i uploaded my laravel project on host  , lfm not working properly. my images uploaded without any problem but its not display on explorer section and i found out , this problem happen,because add lfm prefix to image url.
`/*
    |--------------------------------------------------------------------------
    | Routing
    |--------------------------------------------------------------------------
    */

    // Include to pre-defined routes from package or not. Middlewares
    'use_package_routes' => true,

    // Middlewares which should be applied to all package routes.
    // For laravel 5.1 and before, remove 'web' from the array.
    'middlewares' => ['web','auth:admin'],

    // The url to this package. Change it if necessary.
    'prefix' => 'admin/laravel-filemanager',

    /*
    |--------------------------------------------------------------------------
    | Multi-User Mode
    |--------------------------------------------------------------------------
    */

    // If true, private folders will be created for each signed-in user.
    'allow_multi_user' => true,
    // If true, share folder will be created when allow_multi_user is true.
    'allow_share_folder' => false,

    // Flexibla way to customize client folders accessibility
    // If you want to customize client folders, publish tag="lfm_handler"
    // Then you can rewrite userField function in App\Handler\ConfigHander class
    // And set 'user_field' to App\Handler\ConfigHander::class
    // Ex: The private folder of user will be named as the user id.
    'user_field' => Unisharp\Laravelfilemanager\Handlers\ConfigHandler::class,

    /*
    |--------------------------------------------------------------------------
    | Working Directory
    |--------------------------------------------------------------------------
    */

    // Which folder to store files in project, fill in 'public', 'resources', 'storage' and so on.
    // You should create routes to serve images if it is not set to public.
    'base_directory' => 'public_html',

    'images_folder_name' => 'images/news',
    'files_folder_name'  => 'files',

    'shared_folder_name' => 'shares',
    'thumb_folder_name'  => 'thumbs',`

as you can see , my images store in public_html/images/news folder but src of image in explorer is "admin/laravel-filemanager/images/news".

Really appreciated if someone give any clue to fix this.

**Comment by mprogrammer21** [comment]
Use the script like this  in your blade:
    <script>
        $('#lfm').filemanager('image', {prefix: '/admin/laravel-filemanager'});
    </script>

**Comment by g0110280** [comment]
@farbodkain there is a similar issue here: #506.
