### ISSUE TITLE
Laravel file manager

### ISSUE THREAD

**Issue by burhancelebi** [UniSharp/laravel-filemanager#704]
Laravel Problem,
Hi I am using ckeditor and file manager for uploading images. But i have trouble while uploading images. When i choose image and click upload button, it doesnt upload image. And error accurred, "Please upload an image". Can you help me to fix problem please. 

Thank you

**Comment by g0110280** [comment]
Please try if uploading images below 2MB works. If it works, please see this [wiki](https://github.com/UniSharp/laravel-filemanager/wiki/500-error-when-uploading-large-files(over-2MB)).
