### ISSUE TITLE
ImageWasUploaded Issues

### ISSUE THREAD

**Issue by Tarcisiofl** [UniSharp/laravel-filemanager#705]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

Hello guys, I was trying to save some fields information when uploaded a file to the server. Therefore, I change the `index.blade` to add my new fields. Then, I register in my `EventServiceProvider`:
```
ImageWasUploaded::class => [
            'App\Listeners\UploadListener',
        ],
```

And finally, I create my `UploadListener` class:
```
<?php

namespace App\Listeners;

use App\Revision;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class UploadListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle($event)
    {
        Revision::create([
            'path' => $event->path(),
            'revision' => $event->revision,
            'reference' => $event->reference,
            'subject' => $event->subject,
            'leaf' => $event->leaf,
            'description' => $event->description,
            'observation' => $event->observation,
            'path_revit' => $event->path_revit
        ]);
    }
}
```

However, when I try to get the form value, it is giving error: `"message": "Undefined property: UniSharp\\LaravelFilemanager\\Events\\ImageWasUploaded::$revision"`. What I need to change to make it work? 

And provide the followings :
 * Operating system : Windows 10
 * Laravel version : 5.6
 * Package version : 1.8
 * Screenshots of browser console :
 
![console](https://user-images.githubusercontent.com/1232004/47277262-9e268200-d594-11e8-8577-e847cfdd80ba.png)

**Comment by g0110280** [comment]
@Tarcisiofl could you paster the code `ImageWasUploaded.php` as well?

**Comment by Tarcisiofl** [comment]
@g0110280 I haven't change it.

```
<?php

namespace UniSharp\LaravelFilemanager\Events;

class ImageWasUploaded
{
    private $path;

    public function __construct($path)
    {
        $this->path = $path;
    }

    /**
     * @return string
     */
    public function path()
    {
        return $this->path;
    }
}
```

Do I need to change it to get the parameters? I can view them being send on the console.

**Comment by g0110280** [comment]
The `$event` instance in `public function handle($event)` only contain a method `path()`. Perhaps you should replace `$event->revision` with something like `request()->input('revision')`.

**Comment by Tarcisiofl** [comment]
Thank you, @g0110280 ! It worked using the `request()->input('revision')`.
Now, I will try to change it to only allow one upload each time and to add some validations or change the behavior to only upload if some fields are already populated.
