### ISSUE TITLE
Recursive sub folders are erroing

### ISSUE THREAD

**Issue by MrTheSoulz** [UniSharp/laravel-filemanager#708]
Steps to duplicate:
* create a disk named users (config/filesystems.php)
`'users' => [
            'driver' => 'local',
            'root' => storage_path('app/users'),
            'url' => env('APP_URL') . '/storage/users',
            'visibility' => 'public',
        ],`
* configure lfm:
`'disk' => 'users',
'allow_multi_user'   => true,
'allow_share_folder' => false,`
* make a folder named avatars
* make another folder inside avatars named TESTE

results in:
 League \ Flysystem \ FileNotFoundException
File not found at path: files/1/TESTE

 "unisharp/laravel-filemanager": "dev-master"

**Comment by g0110280** [comment]
Thanks for reporting this bug, working on it.

**Comment by g0110280** [comment]
Fixed in `v2.0.0-alpha6`.
