### ISSUE TITLE
request->file is empty 

### ISSUE THREAD

**Issue by matrianpour** [UniSharp/laravel-filemanager#711]
laravel: 5.7 , filemaneger:1.8
the image is uploaded in photo dir, but why my request->file() is empty?!
I'm new to laravel so maybe miss something.

**Comment by g0110280** [comment]
This might due to uploading file which is larger than max request size setting of your web server. Please check the wiki [here](https://github.com/UniSharp/laravel-filemanager/wiki/500-error-when-uploading-large-files(over-2MB)).
