### ISSUE TITLE
File uploading is not completed

### ISSUE THREAD

**Issue by alexeydg** [UniSharp/laravel-filemanager#714]
unisharp/laravel-filemanager  v1.9.2
laravel 5.7
os: ubunta
when i upload image the log has error:
local.ERROR: Call to undefined method Imagine\Gd\Image::orientate() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Imagine\\Gd\\Image::orientate() at /vendor/unisharp/laravel-filemanager/src/Controllers/UploadController.php:73)

**Comment by g0110280** [comment]
Hi @alexeydg , do you have `Imagick` or `GD` php extensions installed?

**Comment by alexeydg** [comment]
yes, GD

**Comment by g0110280** [comment]
The `Image` facade should call `Intervention\Image\Facades\Image` instead of `Imagine\Gd\Image`. Did you register it correctly in `config/app.php`?

**Comment by alexeydg** [comment]
'Image' => Intervention\Image\Facades\Image::class,

**Comment by alexeydg** [comment]
i find error, you was right

**Comment by alexeydg** [comment]
my app.php has second Image :
   Folklore\Image\ImageServiceProvider::class,
what me do?

**Comment by alexeydg** [comment]
conflict in facades name

**Comment by g0110280** [comment]
For now, if you need to call functions in `Folklore\Image` using facades, I suggest you register `Folklore\Image` to other alias like `FolkloreImage`, leave `Image` facade to `Intervention\Image`. 

Still, our should avoid this issue by calling `Intervention\Image` directly, without registering an `Image` facade. It will take some times but I will see what I can do. In the meantime, you can try the approach I mentioned.
