### ISSUE TITLE
Invalid Upload Request on host web

### ISSUE THREAD

**Issue by narges70** [UniSharp/laravel-filemanager#716]
my laravelFileManager works fine on local but when i upload project to my host its not work properly.
my host directory is this :
->home/
->laravelfiles
->public_html

when i upload image in filemanager makes folders but not upload image on my host.

my lfm.php :
'base_directory' => 'public_html',
'images_folder_name' => 'photos',
'files_folder_name' => 'files',
'shared_folder_name' => 'shares',
'thumb_folder_name' => 'thumbs',
<img width="776" alt="capture1" src="https://user-images.githubusercontent.com/34111380/48700183-fdd27600-ebb0-11e8-98ce-9e78f1200385.PNG">

**Comment by mortza** [comment]
Seems similar to #206

**Comment by narges70** [comment]
thank u  @mortza 
its work fine, and upload image,create image in "public_html/photos/4" on my directAdmin.
but its not show....
<img width="550" alt="capture11" src="https://user-images.githubusercontent.com/34111380/48834107-8fbdb880-ed42-11e8-9696-678d6e4ce933.PNG">

???

**Comment by mortza** [comment]
What is the output of following command
```
$ curl -I yourdomain.com/photos/4/1.jpg -k
```
I guess above path from your comment and uploaded image, replace `photos/4/1.jpg` with path of an image you think uploaded via LFM

**Comment by narges70** [comment]
Where to enter the above command in directAdmin?
can i give you directAdmin access via email and check it?

image link in upload page is "/laravel-filemanager/photos/4/thumbs/1.jpg" but in DirectAdmin is "/photos/4/thumbs/1.jpg". when delete "/laravel-filemanager" in url shows image.

**Comment by mortza** [comment]
> Where to enter the above command in directAdmin, @mortza ?

if you're using xampp on windows open `%xampp_dir%/xampp_shell.bat` and type command.

> can i give you directAdmin access via email and check it?

you can find my email on github page link in my profile but solution to the problem should submitted here for other people facing this problem.

> image link in upload page is "/laravel-filemanager/photos/4/thumbs/1.jpg" but in DirectAdmin is "/photos/4/thumbs/1.jpg". when delete "/laravel-filemanager" in url shows image.

in `/laravel-filemanager/photos/4/thumbs/1.jpg` _/laravel-filemanager_ corresponds to `lfm.url_prefix` option, it isn't path to image.

**Comment by narges70** [comment]
> hello I found solution for this problem that happen in DirectAdmin Shared host you can manually fix this problem with lfmHelpers just in getThumbUrl() and getFileUrl() method change to
> `return str_replace('laravel-filemanager/','',$this->getFileUrl($image_name, 'thumb'));`
> `return str_replace('laravel-filemanager/','' ,url($this->composeSegments('url', $is_thumb, $image_name)));`
> now you can see thumbnails...

Thank you so mush, Solved problem.

**Comment by g0110280** [comment]
Thanks @mortza and @saberap .

**Comment by ridho008** [comment]
> > hello I found solution for this problem that happen in DirectAdmin Shared host you can manually fix this problem with lfmHelpers just in getThumbUrl() and getFileUrl() method change to
> > `return str_replace('laravel-filemanager/','',$this->getFileUrl($image_name, 'thumb'));`
> > `return str_replace('laravel-filemanager/','' ,url($this->composeSegments('url', $is_thumb, $image_name)));`
> > now you can see thumbnails...
> 
> Thank you so mush, Solved problem.

where do I put the return script?
