### ISSUE TITLE
Cant remove image

### ISSUE THREAD

**Issue by sergey89d** [UniSharp/laravel-filemanager#717]
* Operating system : windows 10 x64, apache + php 7.2
 * Laravel version : 5.7.12
 * Package version : alpha5
 * Steps to reproduce your issue : uploaded image want remove
 * Screenshots of browser console : 
![2018-11-19_22-08-41](https://user-images.githubusercontent.com/21147339/48732315-f7dba400-ec47-11e8-96a7-aad1b4cca15b.png)

**Comment by sergey89d** [comment]
dont work request() or $request, but $_GET works

**Comment by g0110280** [comment]
This is fixed in `v2.0.0-alpha6`.
