### ISSUE TITLE
Image preview is not showing after closing Filemanager

### ISSUE THREAD

**Issue by claytongf** [UniSharp/laravel-filemanager#719]
* Operating system : Windows 10
 * Laravel version : 5.7
 * Package version : alpha-5
 * Steps to reproduce your issue :
After uploading an image and choose it to submit, the image is not properly loaded in <img id="holder" style="margin-top:15px;max-height:100px;">
After debugging, I realised that the src is getting [object object], like this:
`<img id="holder" style="margin-top:15px;max-height:100px;" src="[Object Object]">`

I've changed a live of lfm.js from:
`target_preview.attr('src', url).trigger('change');`
to
`target_preview.attr('src', url[0].url).trigger('change');`

And it worked. But I don't know if it is the best way to fix this issue. Is there another idea?

thanks

**Comment by mortza** [comment]
In new version to enable multi select, an array of objects returned. Take a look at [here](https://github.com/UniSharp/laravel-filemanager/blob/c5eec4360ff333d5948d6c09deb3bded31a82101/public/js/stand-alone-button.js#L23). They use `forEach` to iterate over select images and use thumbnail as their preview.

**Comment by g0110280** [comment]
This is fixed in `v2.0.0-alpha6`. Please upgrade and run `php artisan vendor:publish --tag=lfm_public --force`. The `lfm.js` has also been renamed to `stand-alone-button.js`.

**Comment by ans1** [comment]
Preview was not working with `stand-alone-button.js`.

I changed 

` <img id="holder" style="margin-top:15px;max-height:100px;">`

To this

`<div id="holder" style="margin-top:15px;max-height:100px;"></div>`

Now its working perfectly

**Comment by uwaiscode** [comment]
> Preview was not working with `stand-alone-button.js`.
> 
> I changed
> 
> ` <img id="holder" style="margin-top:15px;max-height:100px;">`
> 
> To this
> 
> `<div id="holder" style="margin-top:15px;max-height:100px;"></div>`
> 
> Now its working perfectly
it's work for me thank you
