### ISSUE TITLE
Change Folders Behavior

### ISSUE THREAD

**Issue by Tarcisiofl** [UniSharp/laravel-filemanager#720]
How can i change it to create folders for each project and not for each user?
And, I need to allow multi users to access each of these folders.

And provide the followings :
 * Operating system : Windows 10
 * Laravel version : 5.6
 * Package version : v1.8

**Comment by g0110280** [comment]
Hi @Tarcisiofl , please take a look at [this document](https://unisharp.github.io/laravel-filemanager/config#if-you-want-to-name-private-folders-other-than-columns-of-users-table-follow-these-steps), and change the content of `userField()` to something like `auth()->user()->project->name` of `session('name')`.
