### ISSUE TITLE
Working with CKEditor Images button, but not with Link button

### ISSUE THREAD

**Issue by docmojoman** [UniSharp/laravel-filemanager#722]
Laravel Framework 5.7.9
"unisharp/laravel-filemanager": "v2.0.0-alpha5"

I am using lfm with both ckeditor and as a standalone for file input fields. Lfm works great for standalone file input and within ckeditor's "Image" button _as seen below_.

![ckeditor-image](https://user-images.githubusercontent.com/3960863/49205669-b81a6800-f37d-11e8-8cbc-79ef40f4380a.png)

### Issue
I'd like to be able to link to a pdf file from within ckeditor.  When I highlight the text that I'd like to link in ckeditor and access the lfm filemanager through ckeditor's "link" button, the file manager opens, but with no files present. (see below)

![ckeditor-link](https://user-images.githubusercontent.com/3960863/49205687-c5cfed80-f37d-11e8-8f51-4850034b0f8e.png)

I'm not sure if this is a bug or not, but I cannot find anything in the documentation on how to resolve this.

**Comment by docmojoman** [comment]
Laravel Framework 5.7.9
"unisharp/laravel-filemanager": "v2.0.0-alpha5"

I am using lfm with both ckeditor and as a standalone for file input fields. Lfm works great for standalone file input and within ckeditor's "Image" button _as seen below_.

![ckeditor-image](https://user-images.githubusercontent.com/3960863/49205669-b81a6800-f37d-11e8-8cbc-79ef40f4380a.png)

### Issue
I'd like to be able to link to a pdf file from within ckeditor.  When I highlight the text that I'd like to link in ckeditor and access the lfm filemanager through ckeditor's "link" button, the file manager opens, but with no files present. (see below)

![ckeditor-link](https://user-images.githubusercontent.com/3960863/49205687-c5cfed80-f37d-11e8-8f51-4850034b0f8e.png)

I'm not sure if this is a bug or not, but I cannot find anything in the documentation on how to resolve this.

**Comment by g0110280** [comment]
Hi @docmojoman, we released `v2.0.0-alpha6` today. Can you confirm if this issue still exists in `v2.0.0-alpha6`?

**Comment by docmojoman** [comment]
> Hi @docmojoman, we released `v2.0.0-alpha6` today. Can you confirm if this issue still exists in `v2.0.0-alpha6`?

Sorry for getting back to you so late.  I just upgraded to `v2.0.0-alpha6` following [these directions](https://unisharp.github.io/laravel-filemanager/upgrade). I can confirm that this issue **still** exists.

**when accessing through ckeditor link button**
![ckeditor-link-alpha6](https://user-images.githubusercontent.com/3960863/49405868-dedff200-f721-11e8-9d67-066bf616814c.png)

**when accessing through file input field**
![ckeditor-image-alpha6](https://user-images.githubusercontent.com/3960863/49405877-e6070000-f721-11e8-81fb-409b71b8a87d.png)

The folders in the above screenshots were uploaded before I upgraded.  I tried to upload new files, and got this error...

![pdf-n-image-upload-error-alpha6](https://user-images.githubusercontent.com/3960863/49406455-a8a37200-f723-11e8-9a5f-1a590a4f1fa0.png)

**Comment by g0110280** [comment]
I thought there were some bugs with returning url of a file, but now I understand your first question. Please notice the url parameter `type`. When you open images gallery it is `Images`, and when you open links gallery it is `Files`.

If you want to see the same files in these two galleries, you need to make their `type` parameter the same([in this line, change value of `type` to `files`](https://github.com/UniSharp/laravel-filemanager/blob/v2.0.0-alpha6/src/views/demo.blade.php#L73)) when you integrate with CKEditor.

The bug with uploading files will be fixed in these two days.

**Comment by docmojoman** [comment]
Thanks, I will try this out...

**Comment by g0110280** [comment]
The failure when uploading was fix in `v2.0.0-alpha7`.
