### ISSUE TITLE
Is there any way to add a search box to the list of files?  I want the searchbox to find files with keywords on the index page

### ISSUE THREAD

**Issue by asifzahandeep** [UniSharp/laravel-filemanager#728]
![screenshot](https://user-images.githubusercontent.com/7421587/49355259-01a5e280-f6f1-11e8-94ca-a76d78b9ade5.png)

this is my view and i would like to have a search box to filter my files

**Comment by g0110280** [comment]
Yes. In `script.js`, you can add additional functions to accomplish search function with your custom javascript.

**Comment by redzwanlatif** [comment]
#995 Search function added
