### ISSUE TITLE
DigitalOcean [S3 Driver] 

### ISSUE THREAD

**Issue by ScottyRobinson** [UniSharp/laravel-filemanager#731]
Hi! Currently using the latest Alpha build (7v) and when using the S3 driver which is connected to Digital Oceans Spaces it doesn't upload files correctly. 

 I have the driver setup fine as I can upload files manually but when using File Manager it doesn't save in the right location.

For instance; I create a folder in /uploads (which I've put as root folder LFM). Say I call it test the path should be /uploads/test/<file name>. 

When saving that file through LFM it saves it like: 
`uploadshttps/<space endpoint>/uploads/test/<file name> `

Any ideas?

**Comment by g0110280** [comment]
Hi @ScottyRobinson , what is the correct path you were expecting?
