### ISSUE TITLE
FatalThrowableError-Call to undefined function Illuminate\Filesystem\finfo_file()

### ISSUE THREAD

**Issue by nekooee** [UniSharp/laravel-filemanager#732]
* Operating system : CentOs
 * Laravel version : v5.4.36
 * Package version : 1.7

when I open photos or files that uploded by filemanager get this error:

FatalThrowableError
Call to undefined function Illuminate\Filesystem\finfo_file()

screen shot:
![error photo](https://user-images.githubusercontent.com/6003803/49685748-841e1000-fafe-11e8-85fb-a468309b5a65.png)

**Comment by streamtw** [comment]
`fileinfo` extension has been added to the requirements list. Please check if it is missing.
