### ISSUE TITLE
Images uploaded size limited to 450x450px (+Unisharp/laravel-filemanager)

### ISSUE THREAD

**Issue by arianabedi71** [UniSharp/laravel-filemanager#734]
What Im working on:

- Laravel 5.3 (Xampp/Apache on windows server 2012)
- Web app is based on jeroennoten/Laravel-AdminLTE
- Images are uploaded by dragging into jeroennoten/laravel-ckeditor (as part of AdminLTE)
- Image uploade is done by Unisharp/laravel-filemanager (Stock composer installation as per guide).
- Set up is done correct with uploads through CKeditor, symlink etc.

When I drag/paste an image that is more than 450 pixel in either height or width, it "loads" it in the editor as the actual image but then resizes it with aspect ratio locked to 450 pixels in which ever was the largest side.

I tried to upload using the image icon in CKeditor, upload a file, then when I press send to server I see it sent to server as the same 450px rule.

I've raised the php.ini limits to 20M and removed file size validation from filemanager configs. I do not see any configs on this in CKeditor (but then again all my config files are un-indented so its hard search).

Is this something imageuplaoder could cause?
Any direction to even approach this would be appreciated.
Any info on my dev site you'd like to know I will provide.

My webapp is done and everyone is happy except this critical lack of feature (since people will have to uploade high res-ish images all the time :) )

Images below on how I arrive at the limit of 450px in the web app:

1. Uploaded a 3,000 by 1,000 (300kb) image:
<img width="1159" alt="screen shot 2018-12-23 at 10 24 01 am" src="https://user-images.githubusercontent.com/45975292/50382324-ff55f900-069c-11e9-8459-d31ddf1e0389.png">

2. The forced resize image right after upload:
<img width="447" alt="screen shot 2018-12-23 at 10 24 26 am" src="https://user-images.githubusercontent.com/45975292/50382323-ff55f900-069c-11e9-9504-55ff4423b2f0.png">

EDIT: I uploaded the images in the wrong order

**Comment by streamtw** [comment]
Hello @arianabedi71 , I cannot reproduce the problem you encountered. Here are my steps
1. Create a new Laravel 5.7 app
1. Install this package
1. Login and go to `laravel-filemanager/demo` page

Can you see if this condition can be reproduced in the demo page?
