### ISSUE TITLE
Link image with "url_prefix" can't display, only display with "base_directory"

### ISSUE THREAD

**Issue by ducnhsmcorp** [UniSharp/laravel-filemanager#736]
I use laravel-filemanager with the server and have a problem as follows,
The image after upload is not displayed with the "url_prefix" link but only the test with the "base_directory" link,
Link does not display "http: //pro.okara.local/filemanager/photos/shares/tintuc/28072016/5799c59c52170.jpg"
The link displays "http: //pro.okara.local/uploads/photos/shares/tintuc/28072016/5799c59c52170.jpg"

Above the local, both threads display the correct image

**Comment by streamtw** [comment]
Please try `v2.0.0`, and remember to run `php artisan storage:link` and set `APP_URL` in `.env`.
