### ISSUE TITLE
folder not open

### ISSUE THREAD

**Issue by mdhosseini** [UniSharp/laravel-filemanager#737]
Please check the following instructions before submitting a bug :
 * folder in file manager have file icon and not open. if i click on folder then folder url was be select and not open folder!
 * folder not open!
please help me...
images:
[image1](https://imgur.com/q4zipj7)
[image2](https://imgur.com/griTCDS)
[image3](https://imgur.com/xQfZost)

And provide the followings :
 * Operating system : 10
 * Laravel version : 5.7
 * Package version : 2.0.0.7
 * Steps to reproduce your issue :
 * Screenshots of browser console :

**Comment by streamtw** [comment]
`v2.0.0` has been released yesterday, please upgrade the version. Let me know if it is still not solved in `v2.0.0`.
