### ISSUE TITLE
Error file moving file: mb_detect_encoding() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by owaisahmed5300** [UniSharp/laravel-filemanager#739]
hi, i am using windows.

it's show error only in windows while moving files please check:
(E_WARNING): "mb_detect_encoding() expects parameter 1 to be string, array given"

**Comment by owaisahmed5300** [comment]
solved by edit overwrite  "translateFromUtf8" function  Lfm.php

    /**
     * Translate file name to make it compatible on Windows.
     *
     * @param  string  $input  Any string.
     * @return string
     */
    public function translateFromUtf8($input)
    {
        $rInput = [];

        if ($this->isRunningOnWindows()) {
        // $input = iconv('UTF-8', mb_detect_encoding($input), $input);
            
            if (is_array($input)) {
                foreach ($input as $k => $i) {
                    $rInput[] = iconv('UTF-8', mb_detect_encoding($i), $i);
                }
            } else {
                $rInput = $input;
            }
        } else {
            $rInput = $input;
        }

        return $rInput;
        // return $input;
    }

**Comment by sorasanin** [comment]
Did you overwrite vendor method or what did you do?

**Comment by erfanhemmati** [comment]
@owaisahmed5300 Thanks for your help 😊

**Comment by raulcano** [comment]
I am experiencing the same error on Windows. Can someone explain how to fix that , please?

**Comment by Spryer** [comment]
u need to go to vendor\unisharp\laravel-filemanager\src\Lfm.php to row 190 and replace the code with the code above from @owaisahmed5300

**Comment by Spryer** [comment]
also if u can't download a file because of this error: Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header() in RevalidateBackHistory.php
then u need just to edit ur handle function of  RevalidateBackHistory.php file. 
here is the link regarding this error on stackoverflow: [https://stackoverflow.com/questions/47429829/call-to-undefined-method-symfony-component-httpfoundation-binaryfileresponsehe](url)

**Comment by webservice96** [comment]
> solved by edit overwrite "translateFromUtf8" function Lfm.php
> 
> ```
> /**
>  * Translate file name to make it compatible on Windows.
>  *
>  * @param  string  $input  Any string.
>  * @return string
>  */
> public function translateFromUtf8($input)
> {
>     $rInput = [];
> 
>     if ($this->isRunningOnWindows()) {
>     // $input = iconv('UTF-8', mb_detect_encoding($input), $input);
>         
>         if (is_array($input)) {
>             foreach ($input as $k => $i) {
>                 $rInput[] = iconv('UTF-8', mb_detect_encoding($i), $i);
>             }
>         } else {
>             $rInput = $input;
>         }
>     } else {
>         $rInput = $input;
>     }
> 
>     return $rInput;
>     // return $input;
> }
> ```

Unbelievable. My Problem solved. Thank you so much.

**Comment by Maxime-LP5** [comment]
Hi, reopening because I had the same issue with 2.9.0

The same fix is working but editing vendor files isn't an acceptable solution for the long term, should I submit a PR?

**Comment by streamtw** [comment]
Hi @Maxime-LP5 , any PR is welcome!
