### ISSUE TITLE
Upload FIle and show it in the forntend

### ISSUE THREAD

**Issue by blpraveen** [UniSharp/laravel-filemanager#747]
I am using unisharp File manager it is uploading and storing the photo. But to show the image on the frontend it is using http://localhost/storage/photos/1/someimage.png instead of a http://localhost/{project}/public/storage/photos/1/someimage.png

**Comment by mortza** [comment]
try running following command in Laravel project folder:
```
php artisan storage:link
```
Read [here](https://laravel.com/docs/5.7/filesystem#file-urls) for how create link to files in Laravel.

**Comment by blpraveen** [comment]
I changed the APP_URL to localhost/project/public it is now working correctly
