### ISSUE TITLE
How to upload video file?

### ISSUE THREAD

**Issue by farissyf30** [UniSharp/laravel-filemanager#749]
How to upload video file? 

this is my source

![screenshot_1](https://user-images.githubusercontent.com/42666064/51783257-18553c80-216a-11e9-964f-5faea3f77752.png)

In config
![screenshot_2](https://user-images.githubusercontent.com/42666064/51783262-25722b80-216a-11e9-8a85-7363a56151c5.png)

error 
![screenshot_4](https://user-images.githubusercontent.com/42666064/51783284-58b4ba80-216a-11e9-9d39-5c91293e1f21.png)

**Comment by Illusionist3886** [comment]
I found the issue. You can solve it by simply editing "upload_max_filesize=M"

**Comment by j33tmane** [comment]
need to clear cache and config
```
php artisan config:clear
php artisan cache:clear
```

**Comment by alzahraabeauty179** [comment]
I have the same problem!
