### ISSUE TITLE
Relative path (without domain) does not work in v2.0

### ISSUE THREAD

**Issue by andreaschrist27** [UniSharp/laravel-filemanager#756]
relative path (without domain) doesn't work.

**Comment by iammackinnon** [comment]
I have the same problem.  The boolean configuration variable  "relative_paths" does not appear to be used in LFM 2.0 source code anywhere (at least not when I grepped)

**Comment by iammackinnon** [comment]
@andreaschrist27  Please update the subject as well, since it does not describe the problem at all.  Something like "Relative path (without domain) does not work in v2.0"  Will make it easier to identify for the devs and possibly increase the chances of them handling it, or at least responding.

**Comment by audetcameron** [comment]
Having trouble going between staging and production because the domain url is being written into the database as src path,  relative_path doesn't appear to be working.

**Comment by Younesi** [comment]
Yes, All paths are full, we need relative

**Comment by streamtw** [comment]
Sorry for late reply. Example code for getting relative urls, and explanations about why the full urls are returned can be found in #1233 .
