### ISSUE TITLE
[Question] Folders name

### ISSUE THREAD

**Issue by joaoCrulhas** [UniSharp/laravel-filemanager#757]
I have a question about LFM. 
It's possible to change the folders name, for example, (Files to My Files), the same idea to the Shared folder, I didn't find anything in the documentation to change their names.
Thanks for your attention.
Edit: Is it possible to change the folders orders? 
For example, first show the "Shared folders" and after "Files" for example

**Comment by kingster996** [comment]
If you check the docs for how to edit the language files, you can change the folder name of "Files" to whatever you want in the lfm.php file in your language folder where it says 'title-user' => 'Files'

**Comment by streamtw** [comment]
This can also be done by running `php artisan vendor:publish --tag=lfm_view`, and then edit files in  `resources/views/vendor/laravel-filemanager/`.
