### ISSUE TITLE
Can not working when has public in path

### ISSUE THREAD

**Issue by tmbnh1** [UniSharp/laravel-filemanager#76]
Hello, Your module is not working for laravel has public in path. Please have a look for this. Thanks!

**Comment by g0110280** [comment]
#77

**Comment by g0110280** [comment]
#77

**Comment by g0110280** [comment]
@tmbnh1 
Fix in https://github.com/UniSharp/laravel-filemanager/commit/707a1fb6a32a8968a9ef02d24db89f6c03ff7fd2, please update to dev-master to if the issue still exists.
