### ISSUE TITLE
can't create folder on hosting server, but it can on localhost

### ISSUE THREAD

**Issue by rikopramayudi** [UniSharp/laravel-filemanager#764]
hallo
i can' create folder on server, but on local it can.
this is my folder tree
```
-public_html
       | upload -> symlink to system/public/upload
-system
     | -public
            | -upload
                   | - shares
                          | - tesfolder
                          | - vve.jpg

```
it show all image like vve.jpg but i can't open tesfolder and create new folder, it say folder name cannot be empty.

![screenshot from 2019-02-25 19-28-49](https://user-images.githubusercontent.com/22573815/53335328-213a5900-3936-11e9-8bdf-9cca259171ae.png)

pls help.

**Comment by rikopramayudi** [comment]
it's done.. my htaccess setup is error.. 
pls close this issue

**Comment by Askancy** [comment]
how did you upload it in public/ pload and not in storage?

**Comment by dogukanoksuz** [comment]
i've experiencing this issue too.

**Comment by trieuconcrete** [comment]
> it's done.. my htaccess setup is error..
> pls close this issue
Hi @rikopramayudi 

Could You share my . htaccess setup to resolve?
