### ISSUE TITLE
need to laravel 5.8 support

### ISSUE THREAD

**Issue by mdhosseini** [UniSharp/laravel-filemanager#765]
Laravel 5.8 has been realased and need to laravel 5.8 support

**Comment by mdhosseini** [comment]
please help me
i need install lfm on laravel 5.8 and it's not install and have error.
check it and help me

**Comment by SHSharkar** [comment]
@mdhosseini,

I am also hoping someone from the contributor/ admins will update the version tag for **Laravel 5.8** support. I have to manually update the repository which takes time for individual projects.

**Comment by arxeiss** [comment]
@SHSharkar You were able to force Composer to install Laravel 5.8 with LFM? I'm trying to do this few hours and can't find anything how to do this.

Thank you

**Comment by ujackson** [comment]
composer require unisharp/laravel-filemanager
Works on Laravel 5.8

**Comment by arxeiss** [comment]
@ujackson you are right! I guess all of use talking about version 2.0 alpha version.

**Comment by mdhosseini** [comment]
composer require unisharp/laravel-filemanager
this command install version 1.9 but i need to dev-master version or 2.00.alpha.7 or newer
please check it
thanks

**Comment by Dimimo** [comment]
The composer.json should be adapted. Everywhere you see `"5.4.* || 5.5.* || 5.6.* || 5.7.*",` should become `"5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.*",`

**Comment by arxeiss** [comment]
Here is pull request https://github.com/UniSharp/laravel-filemanager/pull/772 by @rsmalc

Now it enought to change composer.json like this (add repositories and require `dev-master`): 

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/rsmalc/laravel-filemanager"
    }
],
"require": {
    "unisharp/laravel-filemanager": "dev-master",
    ...
}
```

**Comment by mdhosseini** [comment]
when laravel 5.8 support add?

**Comment by mdhosseini** [comment]
If the update is not coming soon, I'll have another idea or change my filemanager

**Comment by vasyok28** [comment]
laravel 5.8 support add?

**Comment by mdhosseini** [comment]
> laravel 5.8 support add?

hi still not support laravel 5.8 and we are waiting for change.
i use another filemanager and wait for this filemanager update

**Comment by EnesErtugrul** [comment]
I hope you can find some time to update this repository @streamtw 
It's not possible to install this package (latest alpha version) on a fresh Laravel 5.8 installation. Any help appreciated 😉

**Comment by streamtw** [comment]
I'm sorry for the late reply. `v2.0.0-alpha8` has been released today. Please upgrade to this version.
