### ISSUE TITLE
style doesn't load properly in laravel 5.7

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [UniSharp/laravel-filemanager#766]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : windows 8.1
 * Laravel version : 5.7
 * Package version : 1.8
 * Steps to reproduce your issue : after full config
 * Screenshots of browser console :
![screenshot 139](https://user-images.githubusercontent.com/44982504/53486108-177f3580-3a9d-11e9-943e-5fc16cd9ab7b.png)

**Comment by streamtw** [comment]
Please try running `php artisan vendor:publish --tag=lfm_public`.
