### ISSUE TITLE
Multiple Guards Configuration

### ISSUE THREAD

**Issue by jariesdev** [UniSharp/laravel-filemanager#767]
Im building a multi users site which I separated with different authentication Guards. I Want to use this package on both of them but by reading the documentation there is no Guard mention.

I have dealer guard (which is default ) and admin guard for admin. both need to login to access the portal. 

How can I setup this?

possible like this?
photos/dealer/{dealer_id}/sub_folder/image1.jpg
photos/admin/{admin_id}/sub_folder/image1.jpg

**Comment by streamtw** [comment]
This can be accomplished by implementing custom logic in `userField()`. See: https://unisharp.github.io/laravel-filemanager/config#multi-user-mode
