### ISSUE TITLE
folder.png thumbnail is not loaded

### ISSUE THREAD

**Issue by nepnepz** [UniSharp/laravel-filemanager#770]
Hi

sorry
I changed my laravel structure, I put the index.php file from the public folder to the root folder

so if I want to call a file or image from a public folder I will use the code

`asset ('/public/images/images.png')`

in the vendor directory **\vendor\unisharp\laravel-filemanager\src\Traits\LfmHelpers.php**

I found the code to call the file folder.png

`$thumb_url = asset('vendor/laravel-filemanager/img/folder.png');`

I have to add / public to 

`$thumb_url = asset('public/vendor/laravel-filemanager/img/folder.png');`

the question is can I set it from config / lfm.php ? or replace it with an icon?

![Annotation 2019-03-16 111300](https://user-images.githubusercontent.com/12314602/54470562-8f0ecd80-47dc-11e9-85dd-cd2a60d7a1e7.png)

**Comment by hpr895** [comment]
Hi.

in "/your-path/laravel-filemanager/js/script.js"

on 452 line:
`
          if (item.thumb_url) {
            if (item.thumb_url.slice(-14) == 'img/folder.png') {
              item.thumb_url = '/_admin/vendor/laravel-filemanager/img/folder.png';
              var image = $('<div>').css('background-image', 'url("' + item.thumb_url + '?timestamp=' + item.time + '")');
            } else {
              var image = $('<div>').css('background-image', 'url("' + item.thumb_url + '?timestamp=' + item.time + '")');
            }
          } else ...

`
