### ISSUE TITLE
The published views are ignored!

### ISSUE THREAD

**Issue by TamkeenLMS** [UniSharp/laravel-filemanager#773]
I have published the views using the command:
```php
php artisan vendor:publish --tag=lfm_view --force
```
But the package still used the original views in `\vendor\unisharp\laravel-filemanager\src\views\`. How can I force use the published templates?

Thanks.

 * Operating system : Windows
 * Laravel version : 5.5
 * Package version :  1.8
 * Steps to reproduce your issue : The installation steps.
 * Screenshots of browser console : na

**Comment by kabircse** [comment]
clear cache, config and views. It may solve your problem.

**Comment by TamkeenLMS** [comment]
Done that, and even removed the library and installed it again, but nothing changes! 

Your help is very appreciated here.

**Comment by TamkeenLMS** [comment]
As it turned out, the library publishes the view files into /resources/views/vendor/..., but if the views directory is configured (in config/view.php) to be somewhere else, the library attempts to load the view files from the path in the config/view.php.
