### ISSUE TITLE
No way to specify resize dimensions

### ISSUE THREAD

**Issue by stuartcusackie** [UniSharp/laravel-filemanager#776]
* Operating system : Windows
 * Laravel version : 5.7
 * Package version : 1.92

I don't see a way to specify resize dimensions. All images are resized to 600px by 600px.

Is this a bug or intentional, or am I completely missing something?

![image](https://user-images.githubusercontent.com/20210934/55278980-1561fe00-530b-11e9-97ca-8be22c2e2762.png)

**Comment by streamtw** [comment]
There are input fields for width and height in `v2.*` versions.
