### ISSUE TITLE
Stand-alone-button: customizing retured path (v2.0.0-alpha7)

### ISSUE THREAD

**Issue by ESEEG** [UniSharp/laravel-filemanager#782]
Hi guys,
is there any opportunity to customize the returned path when using the standalone button?
At the moment the full path will be returned into my inputfield, eg:
_https://subdomain.domain.tld/public/img/mv/filemgr/home/03.jpg_
Let's say the rootdirectory for that user is _/filemgr_. Is it possible to adjust the returned value so I only receive _**home/03.jpg**_ or _**/home/03.jpg**_

Laravel 5.7
Filemanager: v2.0.0-alpha7

**Comment by streamtw** [comment]
Sorry for late reply. Example code for getting relative urls, and explanations about why the full urls are returned can be found in https://github.com/UniSharp/laravel-filemanager/issues/1233 .
