### ISSUE TITLE
Upload folder duplicated in error logs

### ISSUE THREAD

**Issue by tugamars** [UniSharp/laravel-filemanager#783]
* Operating system : Linux
 * Laravel version : 5.6
 * Package version : 1.8
 * Steps to reproduce your issue :
 * Screenshots of browser console : https://i.imgur.com/UInSa0M.png

Error: "Can't write image data to path (/home/user/laravel_folder/../public_html/web/files/images/public_html/web/files/images/image.jpg"

Somehow it is adding twice the upload folder. The error is that i cant upload files/images with error: "invalid upload request"

**Comment by streamtw** [comment]
This looks like a duplicate issue of #696 .
