### ISSUE TITLE
Laravel 5.8 File upload to FTP server Not working

### ISSUE THREAD

**Issue by codetestmg** [UniSharp/laravel-filemanager#784]
First of all ,thanks for this great library.
I have installed ` "unisharp/laravel-filemanager": "v2.0.0-alpha8" in laravel 5.8 and it works very well.
But when i change it to FTP credential i got following error

> RuntimeException
This driver does not support retrieving URLs

Please provide me any solution to fix this issue

I saw there is fix for s3 bucket in  v2.0.0-alpha2

`

**Comment by streamtw** [comment]
This exception is thrown by Laravel File System, which does not support retrieving URLs when you are using FTP driver. You will need to implement routing to your FTP server yourself. Please send a pull request if you have any progress.
