### ISSUE TITLE
mfb.css

### ISSUE THREAD

**Issue by ruslan-gennadievich** [UniSharp/laravel-filemanager#785]
Hello
in commit b3ce89c0d5d3d87dfd61f16081b53ccdd73c1c74 you removed mfb.css
but after install 2.0 version, mfb.css and jquery.form.min.js the required
Maybe you have some links to this files at other location. Check please

**Comment by streamtw** [comment]
`mfb.css` is removed because it was integrated in `lfm.css`. Please upgrade to the latest alpha version and run `php artisan vendor:publish --tag=lfm_public --force`.
