### ISSUE TITLE
Minimum PHP-Version

### ISSUE THREAD

**Issue by mroedel** [UniSharp/laravel-filemanager#79]
Is it possible to set the minimum PHP-Version down to 5.4.0?

I'm bound to use PHP 5.4.24 and tested the package with this version without any issues.

**Comment by youchenlee** [comment]
@mroedel Thanks for suggestion.

Yes it seems not using any of the php5.5 features in the code. Except the document uses the new  `::class` class name resolution. We will modify the doc, and bind it to php5.4.

Thanks!

**Comment by g0110280** [comment]
Implemented https://github.com/UniSharp/laravel-filemanager/commit/8db0457780a41ae5465469b31b0011bc90c05b74.
