### ISSUE TITLE
Wrap through text the image

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#791]
Hi. I'm trying to research how I can implement this feature. I want to wrap an image through text like the ms word's feature. Any idea for this? Please see my screenshot below.

Screenshot:
<img src="https://i.imgur.com/HxHOfh6.png">
<br><br>

Thanks.

**Comment by streamtw** [comment]
I think you might need to look for WYSIWYG editors which support this feature. The output of this package is image url only.
