### ISSUE TITLE
Problem with images thumb (and image itself) displaying after upload

### ISSUE THREAD

**Issue by sergmsr** [UniSharp/laravel-filemanager#793]
version installed: unisharp/laravel-filemanager          dev-master 5635aaa 
env: windows 8 64 bit
address: localhost:8000
integrated with ckeditor  4.6.2

after uploading file I'm getting urls like this:
<div style="background-image: url("localhost:8000/storage/photos/1/thumbs/150_0.jpg?timestamp=1558423450");"></div>

which leads to broken images, as there is no protocol specified.

is there any way to avoid adding domain (and port) to address and use relative paths instead?

http://localhost/laravel-filemanager/jsonitems?working_dir=&type=Images&sort_type=alphabetic&_=1558424310756
returns same:
10:38:31.392 XHRGEThttp://localhost/laravel-filemanager/jsonitems?working_dir=&type=Images&sort_type=alphabetic&_=1558424310756
[HTTP/1.1 200 OK 146ms]

{"items":[{"name":"150_0.jpg","url":"localhost\/storage\/photos\/1\/150_0.jpg","time":1558423450,"icon":"fa-image","is_file":true,"is_image":true,"thumb_url":"localhost\/storage\/photos\/1\/thumbs\/150_0.jpg"}],"display":"list","working_dir":"\/1"}

**Comment by streamtw** [comment]
Sorry for late reply. Example code for getting relative urls, and explanations about why the full urls are returned can be found in https://github.com/UniSharp/laravel-filemanager/issues/1233 .
