### ISSUE TITLE
Too many words are missing in the Vietnamese language

### ISSUE THREAD

**Issue by xuandung38** [UniSharp/laravel-filemanager#804]
I'm a Vietnamese developer, I'm already using laravel-filemanager for my projects, everything is normal until I switch to the Vietnamese. 
So I found the original English language file and translated it out to Vietnamese the most complete and meaningful 
This is the file that I translated
[vi.zip](https://github.com/UniSharp/laravel-filemanager/files/3346726/vi.zip)

**Comment by streamtw** [comment]
Thanks for the effort @xuandung38 ! 

Would you like to send a pull request of your changes here?

**Comment by xuandung38** [comment]
of course

**Comment by xuandung38** [comment]
Please check my pull request

**Comment by xuandung38** [comment]
Everythings was done

**Comment by streamtw** [comment]
Thanks again @xuandung38 !
