### ISSUE TITLE
Laravel 5.8, filemanager redirects to /login page

### ISSUE THREAD

**Issue by idezigns** [UniSharp/laravel-filemanager#812]
When i click on laravel-manager, instead of showing me the file manager, it redirects to the main login page. 

I want to point out I have separate guards for admin and users, using two different tables to handle normal users and admin users..

I tried using 'middlewares' => ['admin']

and 'middlewares' => ['users','admin'] just to see if it would come up, but they all redirect to the login page.

       'guards' => [
        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],

        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],

**Comment by idezigns** [comment]
Nevermind, I somehow was using version 2, with v1 instructions, everything works now.

**Comment by omarname** [comment]
Hi, How did you manage to solve this issue, cause filemanager redirects to login page.
