### ISSUE TITLE
v2.0.0-alpha8 doc needed

### ISSUE THREAD

**Issue by nasirkhan** [UniSharp/laravel-filemanager#818]
`v2.0.0-alpha8` installation works but it is very different than the `v1`. Could not use this version. Can you please add at least a minimal doc to test the `v2`?

**Comment by streamtw** [comment]
This is why we haven't release v2.0 yet. I will try to add some documents and maybe there will a stable release in the middle of September.

**Comment by hannanstd** [comment]
hi
i want to use this package. can you tell it will be release these days? and will be compatible with version 6 of laraval?

**Comment by lloricode** [comment]
> This is why we haven't release v2.0 yet. I will try to add some documents and maybe there will a stable release in the middle of September.

today is the last day of September :)

**Comment by hannanstd** [comment]
hi
will we be waiting or no?

**Comment by chojnicki** [comment]
This package seems to be abandoned by author. That's sad :(

**Comment by streamtw** [comment]
`v2.0.0` stable version has been released yesterday. We will start to fill the missing documents in these days. Sorry for the long waiting.
