### ISSUE TITLE
Requirements for laravel-filemanager?

### ISSUE THREAD

**Issue by LaravelExcel** [UniSharp/laravel-filemanager#828]
Hi 

I am using laravel 4.2 and Php 5.6.25
i just want to ask if this is compatible for laravel 4.2? 

Thanks

**Comment by mohamedsabil83** [comment]
No, It's for L5.4+ but you must keep upgrading your projects to the latest version for security purpose and to take advantages of all new features.
Also, PHP5.6 is deprecated you need to move on to at least PHP7.1

**Comment by xuandung38** [comment]
You should upgrade laravel!

**Comment by streamtw** [comment]
@LaravelExcel the tag `v1.9.2` supports Laravel 4.2 .
