### ISSUE TITLE
The requested URL /laravel-filemanager was not found on this server.

### ISSUE THREAD

**Issue by soheilyou** [UniSharp/laravel-filemanager#83]
I've done all steps to install it , but when I want to use it i face this error :

Not Found

The requested URL /laravel-filemanager was not found on this server.

Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80

![untitled](https://cloud.githubusercontent.com/assets/12086397/16272748/3e014b64-38b4-11e6-8cb0-f77176dd8035.png)

I am using laravel 5.1 on wamp server

**Comment by g0110280** [comment]
@soheilyou 
Fix in https://github.com/UniSharp/laravel-filemanager/commit/707a1fb6a32a8968a9ef02d24db89f6c03ff7fd2, please update to dev-master to if the issue still exists.

**Comment by andhikamaheva** [comment]
@soheilyou  Make sure, the file manager URI not in other prefix like dashboard.
If your file manager will be open in dashboard (e.g dashboard/laravel-filemanager) you should costumzie the file manager route [.](https://github.com/UniSharp/laravel-filemanager/blob/master/doc/customization.md)

**Comment by w0rd-driven** [comment]
Thanks for this. In my case my laravel project is in a subdirectory and all of the internals are looking at /vendor not /subdirectory/vendor. It looks like this was the case here when I looked at the screenshot but it wasn't clear from the initial report.

Updating to dev-master and using the prefix setting is the easier choice, with the alternative being to change all of those views.

**Comment by g0110280** [comment]
v1.6 has released.
For any one encountered this issue, please update to v1.6.

**Comment by mfaatz** [comment]
This is still happening in v1.6 and dev-master.  Fresh clean laravel 5.2 install, follow instructions, when I try to insert an image in the editor (TinyMCE), I get "The requested URL /laravel-filemanager was not found on this server."

artisan route:list does show the route so I'm not sure why it's not getting hit.
