### ISSUE TITLE
Can't see files and create subfolder in AWS EC2

### ISSUE THREAD

**Issue by tobyrgb** [UniSharp/laravel-filemanager#84]
I create a laravel project in localhost, and use this package well.
But when I upload my code to AWS server, it can't work.
I reconfirm the path that had some photos in the share folder.

<img width="437" alt="2016-06-23 6 01 30" src="https://cloud.githubusercontent.com/assets/5463590/16299802/bf27e242-396e-11e6-8648-e175655a77eb.png">
Then nothing but [Shares] folder.
<img width="499" alt="2016-06-23 5 57 02" src="https://cloud.githubusercontent.com/assets/5463590/16299794/abc0d9f2-396e-11e6-8be9-f424e328d9bd.png">

And when I create subfolder, it told me I didn't key the folder name.

<img width="615" alt="2016-06-23 6 20 33" src="https://cloud.githubusercontent.com/assets/5463590/16299890/511996dc-396f-11e6-9b83-f90755bb274d.png">
<img width="613" alt="2016-06-23 6 20 42" src="https://cloud.githubusercontent.com/assets/5463590/16299892/541e355e-396f-11e6-8f8f-942763923a58.png">

` The following is my lfm.php

    'rename_file'           => true,

    // If rename_file set to false and this set to true, then filter filename characters which are not alphanumeric.
    'alphanumeric_filename' => true,

    'use_package_routes'    => true,

    // For laravel 5.2, please set to ['web', 'auth']
    'middlewares'           => ['web'],

    // Allow multi_user mode or not.
    // If true, laravel-filemanager create private folders for each signed-in user.
    'allow_multi_user'      => false,

    // The database field to identify a user.
    // When set to 'id', the private folder will be named as the user id.
    // NOTE: make sure to use an unique field.
    'user_field'            => 'id',

    'shared_folder_name'    => 'shares',
    'thumb_folder_name'     => 'thumbs',

    'images_dir'            => 'public/photos/',
    'images_url'            => '/photos/',

    'files_dir'             => 'public/files/',
    'files_url'             => '/files/',

    // available since v1.3.0
    'valid_image_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif'
    ],

    // available since v1.3.0
    // only when '/laravel-filemanager?type=Files'
    'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'application/pdf',
        'text/plain',
    ],

    // file extensions array, only for showing file information, it won't affect the upload process.
    'file_type_array'         => [
        'pdf'  => 'Adobe Acrobat',
        'docx' => 'Microsoft Word',
        'docx' => 'Microsoft Word',
        'xls'  => 'Microsoft Excel',
        'xls'  => 'Microsoft Excel',
        'zip'  => 'Archive',
        'gif'  => 'GIF Image',
        'jpg'  => 'JPEG Image',
        'jpeg' => 'JPEG Image',
        'png'  => 'PNG Image',
        'ppt'  => 'Microsoft PowerPoint',
        'pptx' => 'Microsoft PowerPoint',
    ],

    // file extensions array, only for showing icons, it won't affect the upload process.
    'file_icon_array'         => [
        'pdf'  => 'fa-file-pdf-o',
        'docx' => 'fa-file-word-o',
        'docx' => 'fa-file-word-o',
        'xls'  => 'fa-file-excel-o',
        'xls'  => 'fa-file-excel-o',
        'zip'  => 'fa-file-archive-o',
        'gif'  => 'fa-file-image-o',
        'jpg'  => 'fa-file-image-o',
        'jpeg' => 'fa-file-image-o',
        'png'  => 'fa-file-image-o',
        'ppt'  => 'fa-file-powerpoint-o',
        'pptx' => 'fa-file-powerpoint-o',
    ],
`

**Comment by g0110280** [comment]
That is wired.
Is shared folder writable?
Can you show me console errors and laravel log messages?

**Comment by tobyrgb** [comment]
There is no console err or laravel log.
I can upload image, but I can't see that in the web form.
When I connect through FTP or SSH, I can see the file I just upload.
I found something when I modified FolderController.php as follows:


    public function getAddfolder()
    {
        $folder_name = Input::get('name');
        return 'folder name is :' . $folder_name;

        $path = parent::getPath('directory') . $folder_name;

        if (!File::exists($path)) {
            File::makeDirectory($path, $mode = 0777, true, true);
            return 'OK';
        } else if (empty($folder_name)) {
            return Lang::get('laravel-filemanager::lfm.error-folder-name');
        } else {
            return Lang::get('laravel-filemanager::lfm.error-folder-exist');
        }
    }

and then I type the url "http://mysite/laravel-filemanager/newfolder?name=test_folder"
<img width="565" alt="2016-06-28 6 18 17" src="https://cloud.githubusercontent.com/assets/5463590/16412046/cb78c98e-3d5c-11e6-90d9-116c235902cc.png">

Input::get('name') is empty?!

**Comment by tobyrgb** [comment]
The problem is： 
http://stackoverflow.com/questions/31925992/unable-to-retrieve-get-parameters-using-laravel

Thanks for your help.
