### ISSUE TITLE
Delete file with Directory Traversal vulnerability

### ISSUE THREAD

**Issue by MatisAct** [UniSharp/laravel-filemanager#845]
- You can delete files on the system.if you were to go to:
#### https://domain.com/laravel-filemanager/delete?working_dir=%2F146&type=&items=../../robots.txt
- if you replace robots.txt with files on the system.It was actually deleted . You can essentially break out of the application and affect the actual server
- the vulnerability in src/Controllers/DeleteController.php.

**Comment by streamtw** [comment]
Fixed in `v2.2.0`, thanks for reporting this.
