### ISSUE TITLE
ERR_ABORTED 404 (Not Found) (laravel 6 and heroku)

### ISSUE THREAD

**Issue by TranManhThang96** [UniSharp/laravel-filemanager#847]
I got an error "ERR_ABORTED 404 (Not Found)" when I uploaded the source code laravel 6 to heroku. In the local run normally. I have tried everything on the internet but still haven't solved it. Please help me?
![filemanger](https://user-images.githubusercontent.com/32483289/67613848-85226380-f7dc-11e9-9025-ee3a6b2d0b5a.PNG)
![filemanger2](https://user-images.githubusercontent.com/32483289/67613851-8ce20800-f7dc-11e9-8b79-39e10fb7dbd1.PNG)

**Comment by StApostol** [comment]
Looks like it wasn’t done `php artisan vendor:publish --tag=lfm_public`

**Comment by streamtw** [comment]
Please try to publish public assets as @StApostol stated.
