### ISSUE TITLE
How does the Vanilla Javascript standalone button work?

### ISSUE THREAD

**Issue by dissolvdgrl** [UniSharp/laravel-filemanager#864]
The documentation isn't very clear or I am stupid, but I can't seem to get the standalone button to work and I don't want to use jQuery just for this one button in my application.

I use it like the documentation and the file manager pops up on page load, but I want it to trigger on button click only. Do I need to write additional code in the callback function? 

The input field's value also doesn't update, what must I do to get this working? Sorry for stupid question, I am new to programming :(

My code:
```
<input type="file" id="feature-image" name="feature-image" placeholder="Upload a featured image" value="{{ old('feature-image') }}" required  data-input="thumbnail" data-preview="holder" >
// Standalone - feature image
        let featImg = document.getElementById('feature-image');
        
        let lfm = function(options, cb) {
            let route_prefix = (options && options.prefix) ? options.prefix : '/laravel-filemanager';

            window.open(route_prefix + '?type=' + options.type || 'file', 'FileManager', 'width=900,height=600');
            window.SetUrl = cb;
        }

        featImg.addEventListener('click', lfm({type: 'image', prefix: '/laravel-filemanager'}, function(url, path) {}));
```

**Comment by streamtw** [comment]
Hello @dissolvdgrl , I will try to add vanilla javascript standalone button on `demo.blade.php`. Thanks for the report. I didn't notice that it was missing in the demo page. I will leave another comment when I am done.

**Comment by streamtw** [comment]
@dissolvdgrl I have updated the documents: https://unisharp.github.io/laravel-filemanager/integration#javascript-integration. You can also check the same code from `demo.blade.php`: https://github.com/UniSharp/laravel-filemanager/blob/master/src/views/demo.blade.php. Please let me know if your problems are solved.

**Comment by dissolvdgrl** [comment]
@streamtw thank you!! I will test it today. I appreciate the assistance :)

**Comment by dissolvdgrl** [comment]
Works great! Thanks for the docs update.

I used `<input type="file">`, it opened the default file browser, so I just included an event parameter to the event listener function to prevent the default action as per below:

 button.addEventListener('click', function (event) {
                event.preventDefault();
                // rest of code as per documentation
};
