### ISSUE TITLE
Image preview gives invalid path

### ISSUE THREAD

**Issue by sujith2014** [UniSharp/laravel-filemanager#871]
* Operating system : debian
 * Laravel version : Laravel Framework 5.8.35

 * Package version " unisharp/laravel-filemanager": "^2.0",
:
 * Steps to reproduce your issue :
 * Screenshots of browser console :
 https://ibb.co/cx2MZn6
https://ibb.co/hBzn6Dt

**Comment by HalfBottleOfMind** [comment]
Check your APP_URL in .env. If you use 'php artisan serve' make sure that APP_URL has :8000 port.
