### ISSUE TITLE
How to use on shared hosting?

### ISSUE THREAD

**Issue by dissolvdgrl** [UniSharp/laravel-filemanager#887]
* Operating system : Windows 10
 * Laravel version : 5.8
 * Package version : 2.0
 * Steps to reproduce your issue : Upload application to shared hosting, cannot upload files to public_html

I am stuck working with shared hosting unfortunately. I can't create a symlink between public and storage, because I do not have SSH access. Is there any way I can specify that Laravel File Manager must upload to `https://subdomain.maindomain.com/images` ? It keeps creating a public folder in the root, which is not what I want, I'd like it to go to the `public_html` folder.

I have my app files on the server root and the contents of public in `public_html/subdomain/` 

Thanks in advance, I will try to convince my manager that VPS using Forge is better for our websites :)

**Comment by dissolvdgrl** [comment]
Fixed it by referencing the absolute path in my filesystems.php file.

**Comment by mrmmg** [comment]
@dissolvdgrl Hi, how do you deal with this problem, can you explain to me? my problem is the same as yours

**Comment by dissolvdgrl** [comment]
@mrmmg my previous comment states how I fixed it, but I have since stopped using this package and switched to Laravel Voyager instead for my backend admin.
