### ISSUE TITLE
Does V2.0 is compatible with laravel 6 and 7 ?

### ISSUE THREAD

**Issue by Saad047** [UniSharp/laravel-filemanager#891]
First of all i would like to thank you all people who have been working and creating such wonderful packages and plugins. I have used and really enjoyed this package in laravel 5.8. Now want to use with Laravel 6 ? Is it compatible with laravel 6 ?
Thanks

**Comment by TaffoVelikoff** [comment]
I had a problem with 7, but it worked well on 6.

**Comment by filippodicostanzo** [comment]
Doesn't work on v7 of Laravel

**Comment by francesco-taioli** [comment]
Any news on laravel v7?

**Comment by huylong** [comment]
I will show you how to install on  laravel v7
```composer require unisharp/laravel-filemanager:"v1.9.2"```
After install helpers
```composer require laravel/helpers
```

**Comment by streamtw** [comment]
Fixed in `v2.2.0`. Now we support Laravel `6.*`, `7.*`, `8.*`. Thanks for reporting this.
