### ISSUE TITLE
Laravel 7.x Not Support

### ISSUE THREAD

**Issue by hmoradian** [UniSharp/laravel-filemanager#899]
Why you not change composer.json for support Laravel v7 and up?

**Comment by filippodicostanzo** [comment]
you can add this in your composer.json and run composer update

`"repositories": [{
        "type": "git",
        "url": "https://github.com/neopheus/laravel-filemanager.git"
    }],`

**Comment by hmoradian** [comment]
Thanks, But "neopheus/laravel-filemanager" repository does not support laravel 7.2

**Comment by filippodicostanzo** [comment]
> Thanks, But "neopheus/laravel-filemanager" repository does not support laravel 7.2

Are u sure?

Check this https://github.com/UniSharp/laravel-filemanager/pull/898/commits/bbea8b23f652cbe8c6004e8c1e48992fa267992b

**Comment by hmoradian** [comment]
Yes, I am sure!
I just tried again, it made errors for laravel 7.2
The code of this file also shows:
```
    "illuminate/config": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
    "illuminate/filesystem": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
    "illuminate/support": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
    "illuminate/http": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
    "illuminate/container": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0"
```

**Comment by huylong** [comment]
> Yes, I am sure!
> I just tried again, it made errors for laravel 7.2
> The code of this file also shows:
> 
> ```
>     "illuminate/config": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
>     "illuminate/filesystem": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
>     "illuminate/support": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
>     "illuminate/http": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
>     "illuminate/container": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0"
> ```
> 
> This Lines must be changes to:
> 
> ```
>     "illuminate/config": ">=5.4",
>     "illuminate/filesystem": ">=5.4",
>     "illuminate/support": ">=5.4",
>     "illuminate/http": ">=5.4",
>     "illuminate/container": ">=5.4"
> ```
> 
> or remove this lines and add simply this line only:
> 
> ```
>     "laravel/framework": ">=5.4"
> ```

How to install it on laravel 7.2

**Comment by hmoradian** [comment]
> > Yes, I am sure!
> > I just tried again, it made errors for laravel 7.2
> > The code of this file also shows:
> > ```
> >     "illuminate/config": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> >     "illuminate/filesystem": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> >     "illuminate/support": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> >     "illuminate/http": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> >     "illuminate/container": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0"
> > ```
> > 
> > 
> > This Lines must be changes to:
> > ```
> >     "illuminate/config": ">=5.4",
> >     "illuminate/filesystem": ">=5.4",
> >     "illuminate/support": ">=5.4",
> >     "illuminate/http": ">=5.4",
> >     "illuminate/container": ">=5.4"
> > ```
> > 
> > 
> > or remove this lines and add simply this line only:
> > ```
> >     "laravel/framework": ">=5.4"
> > ```
> 
> How to install it on laravel 7.2

This will work in all versions of laravel equal or up to 5.4, Including 7.2 and up

**Comment by huylong** [comment]
> > > Yes, I am sure!
> > > I just tried again, it made errors for laravel 7.2
> > > The code of this file also shows:
> > > ```
> > >     "illuminate/config": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> > >     "illuminate/filesystem": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> > >     "illuminate/support": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> > >     "illuminate/http": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0",
> > >     "illuminate/container": "5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* || ^6.0 || ^7.0 || ^7.1 || ^8.0"
> > > ```
> > > 
> > > 
> > > This Lines must be changes to:
> > > ```
> > >     "illuminate/config": ">=5.4",
> > >     "illuminate/filesystem": ">=5.4",
> > >     "illuminate/support": ">=5.4",
> > >     "illuminate/http": ">=5.4",
> > >     "illuminate/container": ">=5.4"
> > > ```
> > > 
> > > 
> > > or remove this lines and add simply this line only:
> > > ```
> > >     "laravel/framework": ">=5.4"
> > > ```
> > 
> > 
> > How to install it on laravel 7.2
> 
> This will work in all versions of laravel equal or up to 5.4, Including 7.2 and up:
> 
> ```
> composer require/update unisharp/laravel-filemanager
> ```
It not working https://github.com/UniSharp/laravel-filemanager/issues/904

**Comment by hmoradian** [comment]
> It not working #904

😕

**Comment by francesco-taioli** [comment]
> > It not working #904
> 
> confused

do you find the solution?

**Comment by hmoradian** [comment]
Yes, install this forked package:
composer require hmoradian/laravel-filemanager for laravel up to version 7.3

**Comment by hmoradian** [comment]
I'm waiting for confirm my pull request:
https://github.com/UniSharp/laravel-filemanager/pull/900

**Comment by hmoradian** [comment]
> do you find the solution?

I'm waiting for confirm my pull request:
[Support Laravel 7.3](https://github.com/UniSharp/laravel-filemanager/pull/900)

**Comment by hdvinhhoang** [comment]
The package doesn't still support for laravel 7 :(

**Comment by hmoradian** [comment]
> The package doesn't still support for laravel 7 :(

Of course for now (2020-04-03) :-)
