### ISSUE TITLE
Deleteing files

### ISSUE THREAD

**Issue by nadj** [UniSharp/laravel-filemanager#90]
Hi, I have a problem when I want to rename or delete a file (not an image) I receive an error like this one: /home/virtual/sitename/code/public/data/images/1/documents/zavrsni-rad-hu.zip not found!

It tries to remove the file from the images folder, but my file is in files folder.

**Comment by g0110280** [comment]
@nadj We can't reproduce this issue.
Can you post your screenshots here?

**Comment by nadj** [comment]
Here you go

![screenshot-homestead app 2016-08-05 07-59-36](https://cloud.githubusercontent.com/assets/6311444/17427709/e8a6d5ac-5ae2-11e6-9d14-d1691787e6f9.png)

![screenshot-homestead app 2016-08-05 08-01-04](https://cloud.githubusercontent.com/assets/6311444/17427708/e89156f0-5ae2-11e6-8a92-6045792951d7.png)

And this happens:

`ErrorException in Filesystem.php line 174:
rename(/home/vagrant/site/code/public/data/images/1/56deb520435e5.xls,/home/vagrant/site/code/public/data/images/1/test.xls): No such file or directory`

In the config file I have this setup:
`'images_dir'         => 'public/data/images/',
    'images_url'         => '/data/images/',`

    `'files_dir'          => 'public/data/files/',
    'files_url'          => '/data/files/',`

It's getting the images path while it should use the file path.

**Comment by nadj** [comment]
This is resolved, I used an old version 1.3.0-alpha, after the update the issue is gone.
