### ISSUE TITLE
Full Path

### ISSUE THREAD

**Issue by utsavDave97** [UniSharp/laravel-filemanager#905]
I am on the latest version.

Right now the images are being uploaded as following: 

`<img src="/storage/attachments_images/1/5e771bcdaf6b2.jpg" alt="" width="200" height="200" />`

Could you please let me know how to upload images with 

`<img src="https://domain.com/storage/attachments_images/1/5e771bcdaf6b2.jpg" alt="" width="200" height="200" />`

I also looked at your different issues and it seems that I have to edit **script.blade.php** or **lfm.js** bt I cannot find those files.

Thank you.

**Comment by mohamedsabil83** [comment]
Do you set your domain in `.env` file? **APP_URL=https://domain.com**

**Comment by utsavDave97** [comment]
> Do you set your domain in `.env` file? **APP_URL=https://domain.com**

did that..still not working

**Comment by mikebronner** [comment]
We also need a way to configure domains for multi-tenant apps, root-relative file paths would be great to have.

**Comment by shc6669** [comment]
is it anyone can find this solutions with tinymce full url path?

**Comment by havanan** [comment]
solutions ???

**Comment by kukukk** [comment]
I have the same problem. Have you found a solution?

**Comment by austyuzhaninov** [comment]
Still problem. Its possible to select by config setting to choose full path or relative?

**Comment by streamtw** [comment]
Sorry for late reply.

Full urls are returned by default.

However, if you need relative urls, example code for getting relative urls, and explanations about why the full urls are returned can be found in https://github.com/UniSharp/laravel-filemanager/issues/1233 .
