### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by rifqirosidin** [UniSharp/laravel-filemanager#915]
Hi i am using laravel 5.8.34. I have an installation problem

 Problem 1
    - Conclusion: don't install browner12/helpers v3.1.0
    - Conclusion: remove laravel/framework v5.8.34
    - Installation request for browner12/helpers ^3.0 -> satisfiable by browner12/helpers[v3.0.0, v3.1.0].
    - Conclusion: don't install laravel/framework v5.8.34
    - browner12/helpers v3.0.0 requires illuminate/contracts ^6.0 -> satisfiable by illuminate/contracts[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.
0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2,
v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].

**Comment by Zinc-Kun** [comment]
how you fix that? i can't installed browner12
