### ISSUE TITLE
GoTo last opened folder 

### ISSUE THREAD

**Issue by postwirt** [UniSharp/laravel-filemanager#917]
Hi,
**GoTo last opened folder** 
Is there an option the iframe automaticly will open the folder the user used last time?

**Examlpe**
User upload a file in the folder /public/nature
Next time the user open the filemanager the link go to /public/nature

Thanks in advance

**Comment by streamtw** [comment]
There is no such options for now. Any PR is welcome!

**Comment by postwirt** [comment]
I have solved this task as follows, maybe it helps somebody:

In the file script.js (function done() after "$('#working_dir').val(working_dir);") I saved the last used folder into an cookie like:

`function setCookie(key, value, expiry) {
            var expires = new Date();
            expires.setTime(expires.getTime() + (expiry * 24 * 60 * 60 * 1000));
            document.cookie = key + '=' + value + ';expires=' + expires.toUTCString();
        }
        //delete cookie
        function eraseCookie(key) {
            var keyValue = getCookie(key);
            setCookie(key, keyValue, '-1');
        }
        //set Cookie
        setCookie('filemanager_folder',working_dir,'30');`

And in the file index.blade.php I get the cookie and goTo the folder (if set) like:
`  <script>
        function getCookie(key) {
            var keyValue = document.cookie.match('(^|;) ?' + key + '=([^;]*)(;|$)');
            return keyValue ? keyValue[2] : null;
        }
        var cookie_folder = getCookie('filemanager_folder');
        if(cookie_folder){
            goTo(cookie_folder);
        }
    </script>`
