### ISSUE TITLE
How to change shared directory for image to "public/photos/shared" to public/my_image" ?

### ISSUE THREAD

**Issue by misomba** [UniSharp/laravel-filemanager#918]
Hi.
Im pretty new to laravel and stuck with the problem below: 

* Operating system : Windows 10 Xampp
 * Laravel version : 5.8
 * LFM Package version : 2.0  
 * Steps to reproduce your issue :
As default, shared directly is set as "public'/photos/shared".
But I want to use "public/common_images" for shared images.

Also, is it possible to open "public/common_images" when browsing?
Thank you in advance!!!

**Comment by flaviopc** [comment]
see #933
