### ISSUE TITLE
Laravel 5.0

### ISSUE THREAD

**Issue by sudinem** [UniSharp/laravel-filemanager#92]
The package is not working with laravel 5.0. 

I get the following error:
Trait 'Illuminate\Foundation\Bus\DispatchesJobs' not found

In laravel 5.0, DispatchesJobs class is named as DispatchesCommands. How to fix this issue ?

**Comment by sudinem** [comment]
Please reply guys..I've been waiting for the response too long

**Comment by g0110280** [comment]
The fastest way to solve this is to fork this package, and remove line 3, 5 and 9 in `src/controllers/Controller.php`.
See this [link](https://github.com/UniSharp/laravel-filemanager/blob/master/src/controllers/Controller.php#L9).
