### ISSUE TITLE
Undefined variable: helper unisharp

### ISSUE THREAD

**Issue by Keweb** [UniSharp/laravel-filemanager#922]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Mac
 * Laravel version : 5.8
 * Package version : "unisharp/laravel-filemanager": "^2.0",
 * Steps to reproduce your issue : I have followed the steps in the documentation that is available. but when I implement it in my view the error is: Undefined variable: helper
 * Screenshots of browser console :
![Untitled](https://user-images.githubusercontent.com/18476093/79865205-5ee92380-840d-11ea-977e-bc55fd5291b2.png)

**Comment by mafftor** [comment]
Can you send the code of `views/admin/product/add.blade.php` as well?
Try to find the line with helper variable

**Comment by streamtw** [comment]
Closed due to lack of detail and inactivity.
