### ISSUE TITLE
lfm.js not working version v2.0.1 please fix

### ISSUE THREAD

**Issue by huylong** [UniSharp/laravel-filemanager#926]
```
(function( $ ){

  $.fn.filemanager = function(type, options) {
    type = type || 'file';

    this.on('click', function(e) {
      var route_prefix = (options && options.prefix) ? options.prefix : '/filemanager';
      localStorage.setItem('target_input', $(this).data('input'));
      localStorage.setItem('target_preview', $(this).data('preview'));
      window.open(route_prefix + '?type=' + type, 'FileManager', 'width=1024, height=600, top=0, left=1024');
      window.SetUrl = function (url, file_path) {
          //set the value of the desired input to image url
          var target_input = $('#' + localStorage.getItem('target_input'));
          target_input.val(file_path).trigger('change');

          //set or change the preview image src
          var target_preview = $('#' + localStorage.getItem('target_preview'));
          target_preview.attr('src', url).trigger('change');
          console.log(file_path);
          console.log(url);
      };
      return false;
    });
  }

})(jQuery);

````

var route_prefix = "url-to-filemanager";
lfm('lfm', 'image', {prefix: route_prefix});
lfm('lfm2', 'file', {prefix: route_prefix});

**Comment by huylong** [comment]
var url is object

**Comment by mafftor** [comment]
You shouldn't set
```js
var route_prefix = "url-to-filemanager"; // http://localhost/filemanager
```

try to set
```js
var route_prefix = "prefix"; // /filemanager
```
What does your browser's compose say? And what object inside url variable?

**Comment by huylong** [comment]
> You shouldn't set
> 
> ```js
> var route_prefix = "url-to-filemanager"; // http://localhost/filemanager
> ```
> 
> try to set
> 
> ```js
> var route_prefix = "prefix"; // /filemanager
> ```
> 
> What does your browser's console say? And what object inside url variable?

Its structure seems to be wrong
 console.log(file_path);
```underfined```
 console.log(url); 
```ojbect```

**Comment by mafftor** [comment]
> > You shouldn't set
> > ```js
> > var route_prefix = "url-to-filemanager"; // http://localhost/filemanager
> > ```
> > 
> > 
> > try to set
> > ```js
> > var route_prefix = "prefix"; // /filemanager
> > ```
> > 
> > 
> > What does your browser's console say? And what object inside url variable?
> 
> Its structure seems to be wrong
> console.log(file_path);
> `underfined`
> console.log(url);
> `ojbect`

First of all the function of ` window.opener.SetUrl()` returns only 1 parameter - it's list of items
That's why your `file_path` variable is `undefined`

Your script looks incorrect. Try to replace your script with this script of [stand-alone-button.js](https://github.com/UniSharp/laravel-filemanager/blob/master/public/js/stand-alone-button.js)

If it doesn't help you then your package must be updated to the latest release or dev/master

**Comment by huylong** [comment]
Thank you
