### ISSUE TITLE
Forbidden You don't have permission to access /filemanager/ on this server.

### ISSUE THREAD

**Issue by lizeshakya** [UniSharp/laravel-filemanager#927]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : CentOS
 * Laravel version : 7.7.1
 * Package version : dev-master
 * Steps to reproduce your issue :

1. composer require unisharp/laravel-filemanager:dev-master
2. php artisan vendor:publish --tag=lfm_config
3. php artisan vendor:publish --tag=lfm_public
4. php artisan storage:link

5. Copied the demo.blade.php to resources/views/test.blade.php
6. Added Lfm Routes in web.php

```
Route::group(['prefix' => 'filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
```

7. Added a testing route

```
Route::get('test', function () {
    return view('test');
});

```
8. Visited the url /test

9. Error displayed in embedded file manager and http://photo.local/filemanager/?type=image

 * Screenshots of browser console :

![Embeded Error](https://user-images.githubusercontent.com/20186159/80279217-c1973380-871b-11ea-93b9-a405a2ef52d3.png)
![Embed File Manager](https://user-images.githubusercontent.com/20186159/80279220-c2c86080-871b-11ea-8e33-45dc5ac67e25.png)

**Comment by mafftor** [comment]
If you declare the routes by yourselves you must set `use_package_routes` to false in `lfm.php` config.
And check if you have folder with name filemanager in your project, sometimes it can cause the problems like this.
Last opinion is your server was configured incorrectly

**Comment by lizeshakya** [comment]
@mafftor  
Removing the route also redirects the same issue. There is a folder inside the public directory. 
public > filemanager > config > .htaccess, config.php
I am working on locally, is there might be any other issue?

**Comment by mafftor** [comment]
For what did you create public > filemanager folder?
Try to rename it or delete and it should help you!
I guess that when you trying get access to http://localhost/filemanager/ your webserver thought that you're trying to get access to the folder but it's not allowed and throws you an error.
I've got the same issue if I want to create public > admin folder and have the same time admin route :(

**Comment by lizeshakya** [comment]
Thank you so much. Removing the folder public > filemanager helped me.
