### ISSUE TITLE
change base_directory not working!

### ISSUE THREAD

**Issue by K1-Aria** [UniSharp/laravel-filemanager#933]
how should i change upload directory from 'storage' to 'public' folder??

the base_directory option not working

**Comment by mafftor** [comment]
Do you want to set up: 
`http://localhost/public/image.jpg` instead of `http://localhost/storage/public/image.jpg` ?

**Comment by K1-Aria** [comment]
yes
exactly

my folder is now like this : http://localhost/storage/app/public/photos/image.jpg

**Comment by mafftor** [comment]
**Step 1:** Create your own disk in `config/filemanager.php`
```php
    'testDisk' => [
        'driver' => 'local',
        'root' => public_path('test_disk'),
        'visibility' => 'public',
    ],
```

**Step 2:** register your own disk in `config/lfm.php`

Find:
```php
'disk' => 'public',
```
Replace:
```php
'disk' => 'testDisk',
```

And now you will have path like this: `http://localhost/public/test_disk/photos/image.jpg`

**Comment by K1-Aria** [comment]
thank you very much my friend
its working

i worked with 1.8 version before and that was different with 2.0
its nice
thank you again

**Comment by mafftor** [comment]
@K1-Aria Welcome :) I wrote you an email, check 👍

**Comment by haykokalipsis** [comment]
> **Step 1:** Create your own disk in `config/filesystems.php`
> Find - `'disks' => [` and add:
> 
> ```
>     'testDisk' => [
>         'driver' => 'local',
>         'root' => public_path('test_disk'),
>         'visibility' => 'public',
>     ],
> ```
> 
> **Step 2:** register your own disk in `config/lfm.php`
> 
> Find:
> 
> ```
> 'disk' => 'public',
> ```
> 
> Replace:
> 
> ```
> 'disk' => 'testDisk',
> ```
> 
> And now you will have path like this: `http://localhost/public/test_disk/photos/image.jpg`

In my experience it worked partially. Files were being uploaded correctly, but when looking up in file manager window, images were broken, and in console i was able to see that image urls were still in storage, although images themselves were in public folder. So i had to edit new disk and add url key to it, like this

```
'public_unisharp' => [
    'driver' => 'local',
    'root' => public_path('/unisharp'),
    'visibility' => 'public',
    'url' => env('APP_URL').'/unisharp',
    // 'url' => public_path('/unisharp'), // js console error: Not allowed to load local resource
], 
```
