### ISSUE TITLE
Cannot change public directory path

### ISSUE THREAD

**Issue by KrystianZareba** [UniSharp/laravel-filemanager#940]
I have two folders on server in main path: private - there are my application files, and web - this is my public path, i modified files `index.php` and `server.php`

My public drive is:
`
'public' => [
            'driver' => 'local',
            'root' =>  public_path('upload'),
            'url' => env('APP_URL').'/upload',
            'visibility' => 'public',
],
`

and i added to `AppServiceProvider` register function this:
`
 $this->app->bind('path.public', function () {
           return base_path().'/../web';
  });
`

but when i create new folder on file manager then manager creates a public folder in my private and subfolder upload

How can I setup this? I wan ../web to be "public" folder for filemanager

**Comment by mafftor** [comment]
try to change `shared_folder_name` or `folder_categories.image.folder_name`
or your mentioned disk `public.root`

You can set `shared_folder_name` => `web`
and `folder_categories.image.folder_name` => `'private folder name (parent folder of web)'`
don't forget to change the root of your disk `'root' => public_path('upload')`

**Comment by KrystianZareba** [comment]
Private is not parent of web, web is another folder on server. When i changed shared_folder_name to web this create something like that: `/private/public/upload/files/web` (Filezilla)

I want this: `/web/upload`

**Comment by mafftor** [comment]
this is your real hierarchy `/private/public/upload/files/web`
How do you want to get `/web/upload` ? maybe `/private/public/upload/files/web/upload`

**Comment by KrystianZareba** [comment]
I have file `index.php` in `web` i want to upload files to subfolder of `web` named `upload`
I don't have all laravel files in parent of web but in subfolder of parent, named `private`. When i makes folder in manager it's not creating in `web` but this creates new folder named `public` in `private`. This is my problem.

When i call function `public_path()` this returns `/provider1/www/clients/client1/web1/private/../web`

**Comment by mafftor** [comment]
go to config `lfm.php` and change `folder_name` to `/path/to/your/folder/web` and `shared_folder_name` => `'upload'`

**Comment by KrystianZareba** [comment]
Okey, i was added this to index.php:

`
$app->bind('path.public', function() {
    return __DIR__;
});
`

and it's works.
