### ISSUE TITLE
File download attack

### ISSUE THREAD

**Issue by sanvu88** [UniSharp/laravel-filemanager#944]
This file manager is good, but it has a dangerous bug: you can easily attack the server by dowloading files.

Ex:  /laravel-filemanager/download?working_dir=%2F&type=&file=../../../../.env

**Comment by mafftor** [comment]
Wow! I've tested, it is really big fail...
Good job @sanvu88

**Comment by mafftor** [comment]
Fixed @sanvu88 
https://github.com/mafftor/laravel-file-manager/commit/ca56205e452bb19252941a277ebd93ddc4229686

**Comment by streamtw** [comment]
Fixed in `v2.2.0`, thanks for reporting this.
