### ISSUE TITLE
routes issue

### ISSUE THREAD

**Issue by farshid-ahmadian** [UniSharp/laravel-filemanager#946]
hi,
thank you for your nice package.

when i Create route group to wrap package routes.

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['auth', 'admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

all the file manager routes duplicated and middleware not work

Laravel Framework v6.13.1
unisharp/laravel-filemanager v2.1.0 

thank for your guidance.❤

**Comment by mafftor** [comment]
go to `config/lfm.php` and set `use_package_routes` to `false` to disable package's routes

**Comment by farshidahmadianpin** [comment]
thank you 💙💙
l have new problem!
i change use_package_routes to false and my route is like that. 
Route::group(['middleware' => ['auth','admin', 'verified']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
i use TinyMCE4 my file manager popup return to 404 error

**Comment by farshidahmadianpin** [comment]
thank i fix this.
in:  var editor_config
            var cmsURL = `editor_config.path_absolute` + 'filemanager?field_name=' + field_name;
i change cmsURL
:D :)
