### ISSUE TITLE
Don't have validate each file!

### ISSUE THREAD

**Issue by devNajjary** [UniSharp/laravel-filemanager#950]
hi
Not any way for file validation.
For example for a image:
-Max Dimension
-Min Dimension
-.....
In addition, the CONFIG must be dynamic for each request.Maybe I want  max file size to be 2 MB in one place and 8 MB in another.

**Comment by streamtw** [comment]
This can be done using event listeners. Examples can be found here: https://unisharp.github.io/laravel-filemanager/events.
