### ISSUE TITLE
 how to change userField at runtime

### ISSUE THREAD

**Issue by guillebalmacedaonline** [UniSharp/laravel-filemanager#954]
Hello, I need change de userfield at runtime. I have one frontend with id. I need set with this id in folder name.
 Any idea?

Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Windows 10 Home
 * Laravel version : 5.7.29
 * Package version : v2.1.0
 * Steps to reproduce your issue :
 * Screenshots of browser console :

**Comment by guillebalmacedaonline** [comment]
Momently I used the constructor in the Handler, by this way:

`<?php

namespace App\Handlers;

class LfmConfigHandler extends \UniSharp\LaravelFilemanager\Handlers\ConfigHandler
{

    public $user_data = "default";

    public function __construct() {
      $this->user_data = (session('retiro_id') != null) ? session('retiro_id') : 'default';
    }
    public function userField()
    {
        return $this->user_data;
    }
}`

I have resolved this comments.

**Comment by fbc** [comment]
Could we just do?:
```
public function userField()
{
    return session('project_id');
}
```
