### ISSUE TITLE
TinyMCE 5 support?

### ISSUE THREAD

**Issue by mrmmg** [UniSharp/laravel-filemanager#958]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Windows 10
 * Laravel version : ^7.0
 * Package version : ^2.1
 * Steps to reproduce your issue : -
 * Screenshots of browser console : -

Hi, i found this #759 and it's not working... any solution?

**Comment by jdatpdm** [comment]
Not battle tested. 

But try adding a file_picker_callback function like this:
`file_picker_callback: function (callback, value, meta) {
        let x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
        let y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

        let type = 'image' === meta.filetype ? 'Images' : 'Files',
            url  = '/laravel-filemanager?editor=tinymce5&type=' + type;

        tinymce.activeEditor.windowManager.openUrl({
            url : url,
            title : 'Filemanager',
            width : x * 0.8,
            height : y * 0.8,
            onMessage: (api, message) => {
                callback(message.content);
            }
        });
    }`

**Comment by mrmmg** [comment]
thanks. it's worked
