### ISSUE TITLE
Independent use does not work at all

### ISSUE THREAD

**Issue by c1t1zen** [UniSharp/laravel-filemanager#96]
hello
i did try to use filemanager fo input use for upload image

**Comment by c1t1zen** [comment]
![unisharp](https://cloud.githubusercontent.com/assets/385714/16710857/8992a47c-463f-11e6-98d3-675cf4bcb48b.jpg)

**Comment by youchenlee** [comment]
Hi @c1t1zen ,
Thanks for the feedback, would you mind pasting the html and js here?

**Comment by c1t1zen** [comment]
step 1 : route
=========
`Route::group(['prefix' => 'laravel-filemanager' , 'middleware' => 'web' ], function()
{

 
	Route::get('/', function () {
	    return view('vendor.laravel-filemanager.myindex');
	});


});`

step 2: html and js (myindex.blade.php)
==============
` 
<!DOCTYPE html>
<html>
<head>
	<title></title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">	
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>

	
</head>
<body>
<textarea id="my-editor" name="content" class="form-control"></textarea>
  <div class="input-group">
      <span class="input-group-btn">
        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
          <i class="fa fa-picture-o"></i> Choose
        </a>
      </span>
      <input id="thumbnail" class="form-control" type="text" name="filepath">
    </div>
    <img id="holder" style="margin-top:15px;max-height:100px;">

  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="/vendor/laravel-filemanager/js/lfm.js"></script>  
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.3.0/bootbox.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  <script src="/vendor/laravel-filemanager/js/cropper.min.js"></script>
  <script src="/vendor/laravel-filemanager/js/jquery.form.min.js"></script>
  @include('laravel-filemanager::script');
<script>
$(document).ready(function () {
  $('#lfm').filemanager('image');
});

  CKEDITOR.replace( 'my-editor', {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
  });
</script>  
</body>
</html>
 `

**Comment by c1t1zen** [comment]
my route
========
`Route::group(['prefix' => 'laravel-filemanager' , 'middleware' => 'web' ], function()
{
	Route::get('/', function () {
	    return view('vendor.laravel-filemanager.myindex');
	});
});`

my blade file
===========
[myindex.blade.txt](https://github.com/UniSharp/laravel-filemanager/files/364682/myindex.blade.txt)

**Comment by g0110280** [comment]
https://github.com/UniSharp/laravel-filemanager/blob/master/doc/integration.md#independent-use

**Comment by g0110280** [comment]
1. Create a button, input, and image preview holder if you are going to choose images.

    Specify the id to the input and image preview by `data-input` and `data-preview`.

    ```html
        <div class="input-group">
          <span class="input-group-btn">
            <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
              <i class="fa fa-picture-o"></i> Choose
            </a>
          </span>
          <input id="thumbnail" class="form-control" type="text" name="filepath">
        </div>
        <img id="holder" style="margin-top:15px;max-height:100px;">
    ``` 

1. Import lfm.js(run `php artisan vendor:publish` if you need).

    ```javascript
        <script src="/vendor/laravel-filemanager/js/lfm.js"></script>
    ```

1. Init filemanager with type. (requires jQuery)

    ```javascript
        $('#lfm').filemanager('image');
    ```
