### ISSUE TITLE
Why numeric folder generate automatically ?

### ISSUE THREAD

**Issue by shankhadevpadam** [UniSharp/laravel-filemanager#973]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Ubuntu 18.04
 * Laravel version : 7.24
 * Package version :2.1
 * Steps to reproduce your issue :
 * Screenshots of browser console :

Why automatically generating numeric "1" folder inside photos folder.

**Comment by mafftor** [comment]
Because your user ID is 1
disable this setting if you want in `config/lfm.php` `allow_private_folder`

**Comment by shankhadevpadam** [comment]
> Because your user ID is 1
> disable this setting if you want in `config/lfm.php` `allow_private_folder`

Thanks.
