### ISSUE TITLE
View not found in subdomain

### ISSUE THREAD

**Issue by JayedHasan232** [UniSharp/laravel-filemanager#974]
I have to work with sub-domains. It's working with the root domain, but not working with sub-domains.
Please help me to fix the problem.

Here is the Error:
**InvalidArgumentException
View [blog.laravel-filemanager.index] not found.**

**Comment by mafftor** [comment]
Disable package routes in config, and create your own routes by copying from Service provider of package

**Comment by ghifar1** [comment]
> Disable package routes in config, and create your own routes by copying from Service provider of package

can u give me an example?

**Comment by streamtw** [comment]
Is this issue solved? I will close this since this is an inactive issue. If this is still an issue to you, feel free to reopen this issue and provide us we more information to help us trouble shoot you issue.
