### ISSUE TITLE
Rename laravel-filemanager to filemanager

### ISSUE THREAD

**Issue by bashet** [UniSharp/laravel-filemanager#98]
Hi,

I am sorry if I annoyed you by asking this question!

What is the quickest way to change the file manager url removing the "laravel-". I just didn't want to let my user to know that, this application was built with laravel!

Many thanks for giving us such wonderful file manager system.

**Comment by Rohos** [comment]
@bashet hi, just change prefix var on your config laravel-filemanager/src/config/lfm.php

**Comment by bashet** [comment]
@Rohos thanks for your advise. There is no prefix in config. However, prefix is hardcoded in routes file (vendor/unisharp/laravel-filemanager/src/routes.php)

I have tried to change all the possible things (such as rename the folder and change the prefix in router). Nothing is seems working for me!

**Comment by Rohos** [comment]
@bashet in current version add prefix. You can add this (https://github.com/UniSharp/laravel-filemanager/blob/master/src/routes.php) in you route, in your config set 'use_package_routes'    => false and don't forget change url in views

**Comment by bashet** [comment]
@Rohos thanks for the update.
According to your advise, I have added the master branch to my project although I believe "master" branch is not a stable release! 

I am encountering the problem with generating file url. Such as when I upload a file, the url should be as http://localhost:8000/photos/1/578bf9c48eb6b.png" but I am missing the '/' bwteen the photos and user_id. Means I am getting the url as http://localhost:8000/photos1/578bf9c48eb6b.png"

**Comment by g0110280** [comment]
@bashet For now you can use 1.5.2, since we haven't release 1.6, which fixes asset and api issues on windows.
We might add tests (especially for urls) to this package before the next release.
But it will take sometimes to accomplish

**Comment by g0110280** [comment]
Route prefix can now be set in `lfm.php`, closing issue now.

**Comment by AkAgio** [comment]
I found it, You must change the prefix also in /vendor/unisharp/laravel-filemanager/src/traits/LfmHelpers.php. Search line 70 $prefix = 'laravel-filemanager/' . $prefix;

**Comment by nekooee** [comment]
after change prefix in config/lfm.php you must change $prefix too in :
vendor\unisharp\laravel-filemanager\src\traits\LfmHelpers.php
change it:
`      if ($type === 'url' && $base_directory !== 'public') {
            $prefix = 'laravel-filemanager/' . $prefix;
        }`
to :
`      if ($type === 'url' && $base_directory !== 'public') {
            $prefix = 'filemanager/' . $prefix;
        }
`

**Comment by nekooee** [comment]
must change prefix in lfm.js too:
public/vendor/laravel-filemanager/js/lfm.js :
`      var route_prefix = (options && options.prefix) ? options.prefix : '/laravel-filemanager';`

**Comment by g0110280** [comment]
Thanks @AkAgio & @nekooee . Hard coded prefix was replaced in `v1.7.7`. As for `lfm.js`, maybe we should not put the prefix in it.
