### ISSUE TITLE
Laravel File Manager + IIS Server

### ISSUE THREAD

**Issue by rhellow** [UniSharp/laravel-filemanager#986]
Hello! I'm a student, new to Laravel & I would like to seek assistance from you as soon as possible!
I'm currently using Laravel v7/8. I need to build a file management system with Windows IIS Server and not any other cloud. Could you provide me some guidance/documentations on that. I can't even run composer require unisharp/laravel-filemanager.

**Comment by streamtw** [comment]
Please check if requirements are met and try following the installation document https://unisharp.github.io/laravel-filemanager/installation. Please feel free to comment here for any obstacles you encountered.

**Comment by rhellow** [comment]
It works thank you. Is there a way for me to tie to file manager to a specific id from my db

**Comment by streamtw** [comment]
Database integration can be done using event listeners. Examples can be found here: https://unisharp.github.io/laravel-filemanager/events.
