### ISSUE TITLE
unisharp invalid upload request 

### ISSUE THREAD

**Issue by alirezajavanmardi** [UniSharp/laravel-filemanager#989]
hey guys . Im new to docker,at first,i create a ubuntu image, then config nginx,mysql,php-fpm on it. Then i pasted my laravel project files there from windows. Unisharp works fine on windows but when i try to upload photo on linux , it tells me : invalid upload link . But the point is , the unisharp upload the photo to the server but not the way it should . In network tab (inspect element) the response is 200 and the photos are uploaded to storage/app/public/5/image_name.jpg . I can change the address when i want to read it , but when the user upload the photo he/she gets an error and should reload the window to see the photo.
btw , i gave 777 to all the dir of the project .
I would be really happy if you guys help me . Thanks.

this is an image of error 

![64946210-ff290980-d87a-11e9-8539-674ef6c9982e](https://user-images.githubusercontent.com/47011266/93182931-93a89f00-f74f-11ea-8034-8ea9e5fb147d.png)

**Comment by JDsWebService** [comment]
Also having this issue as well. Works on my dev server but not production.

**Comment by JDsWebService** [comment]
@alirezajavanmardi 
For anyone that is having this issue... You can solve this by making sure your re-change your permissions on your folders.

```
read -p 'Site: ' site &&
sudo chown -R :www-data /var/www/$site &&
sudo chmod -R 777 /var/www/$site/storage &&
sudo chmod -R 777 /var/www/$site/bootstrap/cache
```

Solved
